### ISSUE TITLE
[Feature Request] Flask Slots

### ISSUE THREAD

**Issue by shoolayce** [Openarl/PathOfBuilding#10]
Flasks have a large impact on builds, having a way to preview their effects, both defensive (eg. basalt, Taste of Hate, Ruby,) and offensive (eg. Vinktar's, Aztiri's,) would be extremely helpful. Being able to see the impact of flask effectiveness modifiers could also be very useful. Potentially this could work similarly to auras, in that they can be checked as active or inactive.

This is merely showing interest for such a feature, and in no way should be seen as a demand. No hard feelings if the feature never makes it in. Again, thanks for the amazing planner tool.

**Comment by Openarl** [comment]
Flask support is a planned feature; it's quite a lot of work to implement though so I'm not sure when I'll get it in. Thanks for the feedback!

**Comment by lokilin** [comment]
Realy need this feature, as I try pathfinder now, it is hard to compare to other ascendancy.
Thanks you work!

**Comment by Openarl** [comment]
Flask support will be added in the next update, which should be out in the next day or two if everything goes as planned. This is one issue I'm very, very glad to finally be able to close!
