### ISSUE TITLE
Any kind of support for Dual Strike?

### ISSUE THREAD

**Issue by ransagy** [Openarl/PathOfBuilding#100]
While i noticed that the skill isn't supported in the app, Beyond a mention in the changelogs that Dual Wielding only uses the main hand, I could not find what is the particular issue with it or why it is not supported.

Sorry if i missed something obvious. I'm aware this might be complicated to implement, Just wondering what the reason is and if anything can be done/help to get it done.

Thanks!

**Comment by Openarl** [comment]
The program doesn't handle dual wielding attacks properly yet; as you said it only uses the main hand. This isn't a big issue for most skills, as true dual wielding isn't used nearly as often as two-handed or "southpaw" setups. Dual Strike on the other hand always attacks with both weapons, so without proper dual wielding support the program can't possibly calculate the correct DPS for that skill.

Unfortunately proper dual wielding support isn't easy to do. Consider that the game client's DPS estimates are unreliable when dual wielding, and Path of Building does even more detailed calculations than the game client. It'll take a fair amount of reworking of the calculation code to make it happen.

**Comment by ransagy** [comment]
Thank you for the detailed reply.
Is there a stopgap measure that can be done to make the calculation show the shakey estimate the game shows? I saw that the app still shows some measure of DPS for the skill group with Dual Strike, maybe due to the supports or auras.

Either way, yeah, probably not a priority to change this seeing as it effects one skill, more or less.

**Comment by Openarl** [comment]
Even getting that far is difficult; the program needs to run hit damage calculations on both weapons, which requires a bit of work as it's not designed to do that at the moment. The DPS from the skill group would be for the default attack, which is used if there's no usable active skills in the group.

**Comment by ransagy** [comment]
That makes sense. I'll close this for now, hopefully there will be more interest in doing this in the future. Thanks!

**Comment by zocke1r** [comment]
It would be great if the program could indicate that behaviour as right now
it is quite misleading
