### ISSUE TITLE
Frostbreath ornate mace dual wield calculation

### ISSUE THREAD

**Issue by orctest** [Openarl/PathOfBuilding#1002]
Frost breath when dual wielded with another item is not calculating damage correctly to chilled targets

the damage should work like this

weapon 1 damage/hit chance/ crit is calculated , weapon 2 damage/hitcrit is calculated , they are then averaged for the dual strike attack- now since it is all in one attack some funky stuff happens and the local modifier of " attacks with this weapon against chilled targets deal double damage" applies to the entire averaged dmg of weapon 1 and weapon 2

right now it PoB is calculating each weapon seperately  as an "attack" in the calculation

thanks!

**Comment by kungurov-a-v** [comment]
You can find answer here: https://www.pathofexile.com/forum/view-thread/13701/filter-account-type/staff/page/3#p13247263

**Comment by Openarl** [comment]
This is indeed working as intended; the damage calculation of the two weapons is 100% independent, and local damage modifiers to one weapon can never affect the other.
