### ISSUE TITLE
Elemental Equilibrium option for player debuff are "Of Balance"

### ISSUE THREAD

**Issue by skimbre** [Openarl/PathOfBuilding#1004]
The Elemental Equilibrium option in configuration/map modifiers and player debuff arent working, it says  "Of Balance" i dont know if its an issue or something else.

Please look into it and thank you for the great program

**Comment by Asymat** [comment]
It works. "Of Balance" is the name of suffix map mod.

I think you get confused about Map Modifiers vs Effective DPS.

**Comment by Openarl** [comment]
The option is applying EE, but it isn't causing the EE-related options to appear in the Configuration tab, which makes it a little useless. I'll fix that in the next update.
