### ISSUE TITLE
New Calculations for Blade Vortex

### ISSUE THREAD

**Issue by DanielGrobelny** [Openarl/PathOfBuilding#101]
Hey there,

I am trying to build a new fire-based BV char and noticed that the new way BV works seems to be not implemented yet.

I tried to find some information on the new more multiplier, but couldn't find anything. E.g. if it double dips on ignite (the wording for flameblast is "more **spell** damage for each stage" for blade vortex it's "more **damage** for each blade".

600% more damage on an ignite / poison with 20 blades up and the new way BV hits seems quite OP to me, so not really sure if it works this way.

Anyway, it would be cool to have the new way BV hits implemented into the planner in a similar fashion Flameblast or Blade Flurry are implemented.

**Comment by DanielGrobelny** [comment]
When I see something like [this](https://vid.me/6DtK) I am not so sure anymore tbh...

**Comment by Openarl** [comment]
The new Blade Vortex is a bit tricky to handle. I can add an option to select the blade count, but it'll only affect the average damage calculation; it won't calculate the actual DPS since I can't currently decouple the hit rate from the spell's cast time.

**Comment by DanielGrobelny** [comment]
Average hit would be absolutely enough for me.

FYI:
The "more" mutliplier actually does double dip atm, but this will be fixed with 2.5.1
https://www.pathofexile.com/forum/view-thread/1800735/page/2#p14013050

**Comment by Openarl** [comment]
Ok, I'll see what I can do. I won't bother handling the double dipping, since it's going to be fixed soon.

**Comment by Openarl** [comment]
Regarding my statement about not being able to decouple hit rate, I'm a filthy liar. I managed to get a hit rate override working, so you'll see true DPS numbers for Blade Vortex now. Enjoy!

**Comment by DanielGrobelny** [comment]
I am dancing shirtless on my desk out of pure enjoyment while writing this message.
Colleagues are looking at me weirdly, probably because there is no actual music playing. I will stop now. Thanks.

**Comment by Openarl** [comment]
You're welcome ;). That update is live now.
