### ISSUE TITLE
Combat Focus illeminating two elements, does not change DPS, even t hough it should when heavy focused into one element.

### ISSUE THREAD

**Issue by Schmidter** [Openarl/PathOfBuilding#1011]
The calculations towards Elemental Hit using Combat Focus jewels is not correct. It should be much higher when you only use the one element you focus on, but it still calculate it otherwise I think.

**Comment by Openarl** [comment]
The changes to the various gems haven't been made yet, as I need the patch data; so the Combat Focus jewels won't work until Elemental Hit itself is updated.

**Comment by Schmidter** [comment]
Oh yeah of course. Sorry my bad.
