### ISSUE TITLE
Melee Avoid Chance error with Blind?

### ISSUE THREAD

**Issue by YouDontGitMe** [Openarl/PathOfBuilding#1016]
Hello,

I don't believe the total defenses for Melee Avoid Chance are being calculated correctly when "target is blind" is checked.

With Blind
https://i.imgur.com/EW02weS.png
https://i.imgur.com/jd9H9EM.png

Shouldn't the chance for evasion to fail be 0.39 in this scenario, not .71?  If I toggle "enemy is blinded", this value doesn't change for Melee avoid chance and it should.

Thanks and great work!

-Nicholas

**Comment by Openarl** [comment]
You've set the calculation mode in the Calcs tab to "Buffed"; this disables all combat and enemy-related modifiers and options, including Blind. You'll see that your Evade chance in the sidebar is much higher, as that takes everything into account regardless of the Calcs tab mode.

**Comment by YouDontGitMe** [comment]
Wow, you are quick with those responses.  Thanks for teaching me a lesson about calculation mode!
