### ISSUE TITLE
Energy Shield Pool Wrong Calculation

### ISSUE THREAD

**Issue by QbleD3** [Openarl/PathOfBuilding#102]
Path of Buiding v1.2.36 shows 14843 ES pool whereas in game i have 10311 ES (both with Discipline Aura level 19).
The character's tree and items have been imported through the "Import/Export Build" function.
Screenshot available below.

_Thank you for your work._

![pob wrong es pool calculation](https://cloud.githubusercontent.com/assets/24281359/21181395/fd8ead96-c1fd-11e6-8c45-82e71f07b027.png)

**Comment by zocke1r** [comment]
Is all your armor in game q20?

**Comment by Openarl** [comment]
All skills (including auras) are initially enabled when imported. In your case, that includes Vaal Discipline. You can see which skills are enabled in the View Skill Details section at the top of the Calcs tab.

**Comment by QbleD3** [comment]
@zocke1r yes all my items are 20Q ingame.
Good catch @Openarl, the difference was coming from Vaal Discipline.
Maybe Vaal skills should be disabled by default ? I'm sure many energy shield users might be thrown off because of Vaal Discipline. I've been trying to figure this out for a week now until i finally came to post here.

Thanks guy.
