### ISSUE TITLE
Hierophant's Pursuit of Faith causing error message with new "# of Enemies Killed Recently" counter

### ISSUE THREAD

**Issue by Quotae** [Openarl/PathOfBuilding#1023]
When hovering over the "Total Increased" part of the Calcs page, and more than 0 enemies in either "# of Enemies Killed Recently" or "# of Enemies Killed by Totems Recently", the following error message pops up: https://i.imgur.com/EXIXi3d.png

I've tested on multiple builds, even a blank one, and the error happens every time just by taking Pursuit of Faith and adding an enemy to one those counters. That said, here's the build I first encountered it on: https://pastebin.com/j139i1XG

**Comment by Openarl** [comment]
Oops; fixed in the next update.
