### ISSUE TITLE
Calcs page - Total Increased % lua crash

### ISSUE THREAD

**Issue by ekuland** [Openarl/PathOfBuilding#1026]
Imported a build to check out and am experiencing a constant lua error any time I highlight Skill Hit Damage - Total Increased for any skill in this build.

Error Screenshot - https://i.imgur.com/3GDW5nA.png

https://pastebin.com/BJDV3kVP

Latest Version

**Comment by Openarl** [comment]
Yep; that's already been reported and fixed for the next update.
