### ISSUE TITLE
Omeyocan's "onslaught on low mana" does not work (gives onslaught always)

### ISSUE THREAD

**Issue by Xebtria** [Openarl/PathOfBuilding#1027]
Those new incursion boots give onslaught while not on low mana.
they show up in my build as a DPS upgrade: https://i.imgur.com/2FzIsyu.png
(for comparison, the Kiara flask (which also gives onslaught) gives the exact same dps increase: https://i.imgur.com/NZNeNK9.png)

but I am on low mana, as I only have 15% mana unreserved: https://i.imgur.com/3lYgwOk.png

so the boots should not give onslaught in PoB, but they seem they do. dps also increases on equip, it's not just a tooltip error or an issue with the new sort by dps display.

edit: same issue with "Dance of the Offered".

**Comment by Openarl** [comment]
Fixed by #1013.
