### ISSUE TITLE
[Bug] Righteous Fire does not show more damage with Pain Attunement

### ISSUE THREAD

**Issue by Ruarl** [Openarl/PathOfBuilding#1029]
When you select the Pain Attunement node, the DoT DPS of Righteous Fire does not change even if "Are you always on Low Life?' is checked in the Configuration tab.

**Comment by relinu** [comment]
Spell damage ( 30% more stell damage from pain attunement)  does not effect rf degen effect. So no this not a bug ^^

**Comment by Openarl** [comment]
That is correct; RF does not deal Spell Damage and therefore cannot be affected by Pain Attunement.
