### ISSUE TITLE
[Feature Request] Essence of Delirium weapon calculation

### ISSUE THREAD

**Issue by Keawen** [Openarl/PathOfBuilding#103]
Hi ! 

First of all, big thanks for great tool ! really have been enjoying this tool. Would like to know if there is already calculations for delirium weapons on tool somewhere or could you add one for it when you have time and energy :) ?

**Comment by Openarl** [comment]
Not yet. I was putting it off since I didn't think essences would be staying. I need to find the time to work on it; I'm not sure how easy it will be to support.

**Comment by disastranagant** [comment]
Wouldn't you just handle it like bleed and show it separately since it's a non-stacking dot?

**Comment by Openarl** [comment]
Yeah, more or less. Now that 1.3.0 is out I should be able to spare the time to implement it. We'll see.

**Comment by Openarl** [comment]
The next update will add support for Decay.
