### ISSUE TITLE
Blade vortex can still go up to 20 stacks (max is 10 as of 3.3)

### ISSUE THREAD

**Issue by sockington** [Openarl/PathOfBuilding#1030]
Blade vortex can still be set at 20 stacks when the max is now 10 as of 3.3.

**Comment by relinu** [comment]
I think none of the skills is up to date yet (Trap Support still has cooldown and Barrage only 3 additional projectiles instead of 4)

**Comment by Openarl** [comment]
Skills have not been updated; I'm working on that now. Please be patient.
