### ISSUE TITLE
Game Version says "3.2 (War for the Atlas)"

### ISSUE THREAD

**Issue by SineSwiper** [Openarl/PathOfBuilding#1036]
The tree looks like it has the changes, but the Configuration entry still shows it as 3.2:

![image](https://user-images.githubusercontent.com/1041375/40881586-489efdb4-6698-11e8-883b-693135dfa8b7.png)

Proof of version:

![image](https://user-images.githubusercontent.com/1041375/40881589-60db5bde-6698-11e8-979d-f77253de8710.png)

**Comment by Openarl** [comment]
Fixed in the next update.
