### ISSUE TITLE
Error when swapping to item with "Aspect of the X" mod

### ISSUE THREAD

**Issue by Henbun** [Openarl/PathOfBuilding#1037]
![path of building_2018-06-03_07-31-20](https://user-images.githubusercontent.com/35263495/40883551-25cf2878-6700-11e8-9e4d-8cfc46d8d49c.png)
When trying to swap to another item (in my case a shield) with Aspect of the Spider PoB gives me the previous error.

The error goes away when the aspect is removed from the item.

**Comment by Openarl** [comment]
Fixed in the next update.
