### ISSUE TITLE
Should/can we get Proxy config?

### ISSUE THREAD

**Issue by LyskOnGithub** [Openarl/PathOfBuilding#104]
I sometimes, only during my lunch break ofc, like to fiddle around with builds while in the office network.
Via browser I can reach pathofexile.com and the api as well. From within PoB I get the "Error retrieving character list, try again (Couldn't connect to the server)" message upon trying to import from an existing and publicly listed account.

There are programs like Proxifier and ForceIPBind that can be used to have the process use a different Network Card, so I can bypass this issue through using my phones Wifi Hotspot for PoB.

Maybe though, PoB could implement proxy settings or use the global ones? I don't even know if the proxy is the problem. The process is being run by an account that has internet access and all, so it's a guess...

**Comment by Openarl** [comment]
Hmm. Adding proxy settings shouldn't be too difficult. I need a place to put them though; there's no global options screen yet, and I'll need to add one for this.

**Comment by pokemane** [comment]
Hey I'd like to +1 this.  I know the issue was updated a while ago and you've got more pressing issues, just want to make sure it doesn't rot.

**Comment by Openarl** [comment]
I've finally found the time to work on this; it will be coming in the next update.
