### ISSUE TITLE
Equipping Blood of Corruption causes script errors.

### ISSUE THREAD

**Issue by Kapps** [Openarl/PathOfBuilding#1041]
Not a huge deal since it doesn't really need to be equipped in PoB, but equipping Blood of Corruption causes script errors. I took a screenshot of the errors at https://imgur.com/a/RNzmR1c. Unequipping it makes the errors go away. This is a regression in one of the versions for 3.3.

Steps to reproduce:
- Start with a new build
- Add Blood of Corruption to the build (no errors yet)
- Equip Blood of Corruption (errors should occur)

**Comment by Openarl** [comment]
That's already fixed for the next update.
