### ISSUE TITLE
Slavedriver's hand not counting attack and cast speed nodes

### ISSUE THREAD

**Issue by BrokenGlassFactory** [Openarl/PathOfBuilding#1042]
Frenzy charges, Trickster passives, and other sources of both attack and cast speed are not modifying trap throwing time with Slavedriver's Hand equipped.

**Comment by barbieqfreak** [comment]
I'll add on this: specifically it's not adding cast speed from onslaught and frenzy charges. Cast speed on passive nodes are working for me

**Comment by Openarl** [comment]
Fixed in the next update.
