### ISSUE TITLE
Occultist Malediction not applying correctly per enemy killed

### ISSUE THREAD

**Issue by salixa** [Openarl/PathOfBuilding#1047]
Malediction's extra chaos damage per enemy killed does not work properly using the new "# of Enemies Killed Recently" configuration option. Currently the chaos damage only applies once, even if the setting is set to a higher number.

**Comment by Openarl** [comment]
Malediction's buff does not stack; you only gain the added Chaos damage for the highest number of Curses on an Enemy you Killed in the past 4 seconds; so that is working as intended.
