### ISSUE TITLE
Arctic Armor not applying physical or fire damage damage taken values.

### ISSUE THREAD

**Issue by Teonlight** [Openarl/PathOfBuilding#1048]
Toggling Arctic Armor on and off does not reflect in the damage taken of the "Calcs" page.

For Comparison Storm Barrier does apply but not Arctic Armor.

![arctic armor issue](https://user-images.githubusercontent.com/10212447/40991048-308e0144-68b8-11e8-9855-a94863aa3783.PNG)

**Comment by Openarl** [comment]
I suspect you haven't enabled the "Are you always Stationary?" option in the Configuration tab, as the skill appears to be functioning as intended.

**Comment by Teonlight** [comment]
You are right. It was not enabled. Thanks!
