### ISSUE TITLE
[Feature Request] Hide Jewel Tooltip when holding i.e. Alt Key

### ISSUE THREAD

**Issue by LyskOnGithub** [Openarl/PathOfBuilding#105]
The tooltip sometimes makes it hard to see which Passives are inside the bounds of a Jewel's radius. To have it hidden OnKeyDown and reappear OnKeyUp of a set or configurable Key would be a QoL improvement.

**Comment by LyskOnGithub** [comment]
Additional Info for people with the same problem: To "see behind the Tooltip", my workaround currently is to move the view of the tree so that the jewel is too close to the right edge of the window so the Tooltip get's rendered left of the cursor.

**Comment by Openarl** [comment]
The tooltip is actually supposed to hide when Shift is held down, but it looks like I broke that at some point. I'll fix that in the next update, and add a note about it in the jewel tooltip.
