### ISSUE TITLE
Summon Stone Golem regen is incorrect

### ISSUE THREAD

**Issue by landrew831** [Openarl/PathOfBuilding#1054]
I have a level 19 Summon Stone Golem enabled but it will only increase my life regeneration by 40, when in game it raises life regen by around 200 (golem effect jewel and elementalist bonus). Nothing major, but would be nice to fix.

**Comment by Openarl** [comment]
Could you give me your build? The regen numbers for Stone Golem look correct; they're exported from the game data files, so they wouldn't be wrong anyway. I should note that the buff effect from Liege of the Primordial isn't supported by PoB yet, so the number reported by PoB will be a little lower than in-game.

**Comment by landrew831** [comment]
https://pastebin.com/vW9SM6nV

**Comment by landrew831** [comment]
Ok I see the issue. The stone golems from the clayshapers were already enabled, so by enabling my higher one, it just raised it by the difference. I also didn't know LotP wasn't accounted for in PoB. Thanks. Issue closed.
