### ISSUE TITLE
Raise Zombie's Slam ability should always hit

### ISSUE THREAD

**Issue by telaak** [Openarl/PathOfBuilding#1058]
Both Necromantic Aegis + Lycosidae and Added accuracy increase Slam's tooltip DPS, which should always hit as per 3.2 changelog https://www.pathofexile.com/forum/view-thread/2093500

- The Slam skill used by Raised Zombies can no longer be evaded.

**Comment by Openarl** [comment]
This was previously the case, but it seems that one of the changes in 1.4.92 broke certain skill-specific modifiers, primarily those relating to skills used by minions; that include the one that causes the Slam skill to ignore evasion. I've fixed that in the next update.
