### ISSUE TITLE
Crashes when opening in second monitor.

### ISSUE THREAD

**Issue by richorton** [Openarl/PathOfBuilding#1059]
Opening Path of Building after the window has been moved onto a second monitor causes a crash - "Path of Building has stopped responding".

The only way to recover from this is to:

1. End the Path of Building process through task manager.
2. Disable/turn off the second monitor through Windows/Nvidia Control Panel.
3. Open Path of Building again (with only one monitor active).
4. Re-enable the second monitor and move the Path of Building back window back onto the second monitor.

However, if you fail to remember to move Path of Building back onto the first monitor before shutting down the machine, on the next boot & time you open Path of Building the bug will occur again and you will need to repeat steps 1-4.

Feel free to get in touch if there's anything I can do to assist further (i'm not sure if there are any crash logs etc. that I can send).

Thanks,

**Comment by Openarl** [comment]
Duplicates #336; unfortunately I still haven't worked out why this occurs on certain systems; the only known common factor is Nvidia graphics.
