### ISSUE TITLE
Blade flurry DPS calculation

### ISSUE THREAD

**Issue by dmitriy-kiriyenko** [Openarl/PathOfBuilding#106]
Hello.

In-game tooltip for damage blade flurry per use, full-buffed (unflasked) is like 3200. This tool displays me 3933 average hit. Where's the truth?

Build export code is: https://gist.github.com/dmitriy-kiriyenko/7effe464224e53c9be8b58f269b11e4d

**Comment by dein0s** [comment]
With all your profile and settings it's only 3272.3 avg hit, so where's the truth?
![imported_stats](http://i.imgur.com/GeEXWVP.png)

**Comment by dmitriy-kiriyenko** [comment]
Mmm. Sorry then. I'll check more.
