### ISSUE TITLE
Needs more documentation

### ISSUE THREAD

**Issue by fireundubh** [Openarl/PathOfBuilding#1062]
Lua version? Lua dependencies? Recommended Lua binaries? Environment variables? There's virtually no information about how to get a Lua environment ready for installing and running Path of Building.

**Comment by Openarl** [comment]
That's because none of that is at all necessary; just download [one of the installers](https://github.com/Openarl/PathOfBuilding/releases).

**Comment by fireundubh** [comment]
Quite a curt response, but if you have a local installation of Lua and Lua Rocks, Path of Building can't run because there's no `xml` module.

The xml module then can't be installed via Lua Rocks because `luafilesystem` fails to compile for one of four reasons: cannot find `cl`, cannot find `errno.h`, cannot find `vcruntime.h`, or some weird byte reading error.

I nuked Lua and Lua Rocks last night when I gave up trying to get this to work. After reading your response, I started up Path of Building to get the call stack, but it finally loaded up.

**Comment by Openarl** [comment]
Path of Building does not require, nor will interact with, any installation of Lua on your system, as it is entirely self-contained. 

You should have provided more details in your opening comment however, as Lua Rocks is a partial exception to that: it sets the LUA_PATH and LUA_CPATH environment variables to non-standard values, which prevents PoB's own Lua version from finding the program's libraries. To fix it, you need to add "!\lua\?.lua" to LUA_PATH, and "!\?.dll" to LUA_CPATH.
