### ISSUE TITLE
Cold Snap's DoT component improperly affected by Elemental Equilibrium

### ISSUE THREAD

**Issue by SeventhSolar** [Openarl/PathOfBuilding#1063]
Activating EE and checking "Enemy hit by Lightning Damage" will properly affect the hit component of Cold Snap, but the DoT component will always only have the modifier "Condition: Hit by cold damage" as listed in the calc tab, and all damage calculations are in this way affected.

**Comment by Openarl** [comment]
For skills with both Hit and Dot components, the Hit damage by default will override the EE settings for the DoT; to prevent this, you need to enable the "Ignore Skill Hit Damage" option.
