### ISSUE TITLE
100% Reduced Arctic Armor Mana Reservation with The Perfect Form

### ISSUE THREAD

**Issue by avgjoe** [Openarl/PathOfBuilding#107]
When using The Perfect Form Body Armor, http://pathofexile.gamepedia.com/The_Perfect_Form The application still calculates the Arctic Armor reservation.

![mana reserve](https://cloud.githubusercontent.com/assets/20477/21283677/410bce8a-c3cc-11e6-9dcc-a058a3685eac.png)

![perfect form](https://cloud.githubusercontent.com/assets/20477/21283680/464f6bea-c3cc-11e6-9418-80d80f04526d.png)

**Comment by dein0s** [comment]
Red color - affix/modificator aint supported yet.

**Comment by Openarl** [comment]
In theory that modifier should have been recognised, but it seems the modifier parser had difficulty reading that one. It's fixed in the next update.
