### ISSUE TITLE
Activating "Dying Sun Ruby Flask" shows DPS loss instead of gain

### ISSUE THREAD

**Issue by asanomura** [Openarl/PathOfBuilding#1078]
On a deadeye molten strike build and having the flask active on pob gives me a negative effect instead of a positive effect
![dying sun activated](https://user-images.githubusercontent.com/37965854/41506331-91709988-71d0-11e8-8680-2667ee3860a3.PNG)
![dying sun deactivated](https://user-images.githubusercontent.com/37965854/41506332-91878f80-71d0-11e8-875b-010b9e3f2a93.PNG)

**Comment by Openarl** [comment]
I'll need your build to diagnose this.

**Comment by asanomura** [comment]
Here's the pastebin:
https://pastebin.com/zMhdJTxt

**Comment by Openarl** [comment]
Ah, The Wise Oak strikes again. 62% of your damage is Lightning, and only 14% Fire, and activating Dying Sun causes Fire to supplant Lightning as your highest Resistance.
