### ISSUE TITLE
ES -> Armour conversion doesn't work for Energy Shield on Shield node

### ISSUE THREAD

**Issue by at-kevinlau** [Openarl/PathOfBuilding#108]
Per the title, using an [Energised Armour](http://pathofexile.gamepedia.com/Energised_Armour) jewel doesn't correctly convert this particular node into armour. Here's a screenshot showing that it does convert in game, resulting in 12.6k armour:
![es_from_energised](https://cloud.githubusercontent.com/assets/3458285/21287210/171e757e-c41b-11e6-9315-85d4d266c1fe.png)

In the editor, the armour value remains at 11.6k whether or not the node is allocated:
![es_from_energised_pob](https://cloud.githubusercontent.com/assets/3458285/21287249/36155212-c41c-11e6-83b6-dd6e5a52885f.png)

Using version 1.2.26.

**Comment by Openarl** [comment]
Ah conversion jewels, the bane of my existence :P. It'll be fixed in the next update.
