### ISSUE TITLE
Vaal Righteous Fire does not allow you to select Righteous Fire in active skill selection

### ISSUE THREAD

**Issue by wafflesncyanide** [Openarl/PathOfBuilding#1087]
When you use Vaal RF in your main link, you can no longer see the stats of RF by selecting the VRF links and using the second dropdown to select Righteous Fire (as you can with Arc/Vaal Arc)

**Comment by Openarl** [comment]
Did you enable Righteous Fire using the option under the gem selector? Aura/buff skills are enabled/disabled separately from the gems themselves.

**Comment by wafflesncyanide** [comment]
Oh, that was it, My bad, i guess it doesnt automatically do that with Vaal RF.  Thank you so much sir i love your application :)
