### ISSUE TITLE
DPS calculation not accounting for Fate of the Vaal Elemental Conversion

### ISSUE THREAD

**Issue by wheelsfire** [Openarl/PathOfBuilding#1089]
DPS doesn't appear to be reflecting the change accurately when i turn elemental damage with attacks on and off. 
In theory, i should be 100% elemental, so a level 20 EDWAS gem should be a pure and obivous 49% more change. Also the Scaling doesn't seem right with Fate of the Vaal either. In my PoB (which i will attach) it goes from 9434 to 11143.4 (with conc turned off) that is definately less than 49% more.

https://pastebin.com/Bzr95fRJ

**Comment by Openarl** [comment]
As per #803, the program isn't currently able to simulate random added/converted damage.
