### ISSUE TITLE
Rapid Decay not calculated on 100% ignite BFlurry

### ISSUE THREAD

**Issue by harrybow** [Openarl/PathOfBuilding#109]
`eNrFWl1z2koSfY5-xRRV2bIrASSBhPDiewtjMCTG2IDtOC-pQRqBbEmDNZIB37r_fXtGEgbxYXKT3c2DA1JPq6f79Okzsmt_zj0XvZCAOdQ_zSkFOYeIb1LL8cenudthK2_k_vxDql3jcNKzzyLH5Xf-kD7UGtg1GXz4UOv40yhEPvbIaY49Oa77Y4qDMIf8yBuRAJzmijvssBk6L-RK2O239xxm_hhFtt2lFskhFgYiwGar1WwMO3fNnY_wdzgfEHg29ZFJXRdPGbFOczZ2Gfh24OOArx0QF4wOsm874Tn28JgcZH1OD_M6mBJiHWTZCJyDA21MsG-Sw9MwXEzJIMQhO2jJmXtozNfUYdQ_yLQz9p3wsJC7AJSmbYPNYfHWQ4DSKArJYeaXjn1gHNjHBxk2fRKMF4OJQ9zD8lYPPBoFh_l-wbyvD7LtE-aw8OAcnxMbeCLJWq2YskFNUARyyQtxT3NVLYdMFzN2JTry3gnNSQ5hZhLfarxdb7rEI36IXR4AenHIjHc5lL173esPc8jDjj-g5hMJLwIaTXkToxH2LSfsksB0XMLYae6K-iS9fEUDD7vr1xpBRNJLImYB7pjBxEfk4hG34ASIRy7fcwhrgGxcGgKwqbVASe5FRHVBXmIpj4g7-lC7IF66eRWoVHDQNbDhaa604ZfTFLS4yZsGWwS13CgIFjn0HEEmwsVpTo6rseF1p5-6ZRELtZyAoISOfsFZC7OQBAgaBJtP7Fc89fHUsdA5MfEv7S4mLhRSlPDBT_hK0PvmrOObAcGAbHQWBT4Mk9-QsXuCp9A0SzjvdFkrCtgcgL1DgbYbEv6Yj79_vqk2CTB0NLVRnU1-xdEg8jzITsuFK-iCQpL-297e0px8Egw1DAhBsfKIXcUprfEvcQy3_Uvx4cMkDKfspFiczWaFKSggapM50E3BpF5xCvQFLvKixfMhOC3W4d9Zvduo9-Z37f7N7dBusXu71__6Y3558eWi__rcqffdy9cmNjud5-qcDNuV-7b1rUw77S7169_HZWNxaej356PWxKvrt67RxBe3zK_7qpW_b3g_6rZRVVRtod_i0nQ--U5a5W-9wYwYvS9faZPN-_Obb4P5zePoQZ-My7d6af7ypep7Jczas87Dt_7ENZ-9l1BfPFzowcOXsylrek-4d9U3fjTn1PAweQwq5qP9GLyWKmGn3bkutXtW8Bg8lCqNSmVgh3dP4_7lzZUyrkY3d-ZQvW2at53e1fNXKn9r1x96WuviJv_0NGq2nLrjmC9X16T9_Xv4EHwNbs9-fDm7M3H4aLnGWd22R7a56D4Oddm5mLU8Q9VvTk9FAYpJBaBscVFqRV41_uGKwqjm9_jF9Iuo6R3MDcQIDszJIASlhwVxISZEFHql1Hs4zeVLZa1Q0nW5XK5qOswRNqGzNsFhF09TkHHTyxiCevztG4DR0AqyoWklVa9WtWo8Qjoh8RINDJ_EbEz6s49BkS1O0K3vPEdE6uNXGvAeCicEDcC3H07QIPKR1HUs3xlPQiRmgNTzCWrDvAJeGsxoYEl98hwBnzMkIkK68RkpSgnBDuMP52QuKcZH5Cz5rG6aUYDNBerjEHhNgqHA0JGu5SvaMSfPI0WR80pJPkbXkwVzzCVPSYosrzpaJ0bk2GhBo38BxbF_v5CEgy2EgfB84sHjCIz10F1AyCaFE8UCKR_5lrt47niRh7h0QrMJ8bmbZPlydfbZXdDeJBsgwmOgQxYun82XOoQJzIBk6GMgOxTwn8ABBS1WK2pKBrxG68VStxaryU8KM_wEZYtGsC-exEwZFF36dKTKPJ2QyI_8fzF1YxHFx5R0pGj8sqodr-5rZTZLR8JAkdcMGjB1kRD-kvYRmZmRJz1A6kxImuPbrmOGKJrGMciJAUNAisukgnWA-NlAJBEw4zyBhUWRT0NkEbhG5mGA04AMKAEXU5nK70-vkjL3ewXYY1HaXaLS1hJ1fDaFTFpQDixClWCXHhwn0BcyIy70m-VE7AQNQAa6UsebQrKcEC7IUsdGZQTEwecKQxjKUXddCqwE3hwfxSs_o_sUqF_5eMZwHSxh4nBN9Fnc4FhEigQIB89wC7rMhiYHVDBoAN9iW3b0AtvAfshzInZX3rq74YSPNNByUIqBSQMfwACiYgwrE1a4i_2coGuISi2oBfntUgNUJDTiJpVkuukESEHO6wYHUFXLK7JxLGWwgmLJBZbVgibHaIUPxx-lRBWiKSjEgdjuCVLgVrZRVOCrsh7TlaYt2aqzk61uGawdUaBHeLQltDeTjlQt6bX1ZskS2FE1DjLbU1t3Jf2VVONE-ftT2q1JM1-4dAT22YXdyA0dwBIJ3harf2eZ4P3Fn47KYoW2gzsa2OcdOlqybEyPALUsIzaoD1TLsZu6SVKRoUjR0vC8j8gWsn5JJNR3FzEVJB5nDuQ-nDgMJXKWlyFhn0OaeI9F-V0L7V0L_V2Lym4y0ba2G-hayKgLSbmJ4Kj2iu5hy5L4sdEy1bxSkbICH_qDj9SywJ6RV9XdjWQUoJA7uqe00T0KdI-uQbeEME5Eo4LvVWTDoHCX6I8HfSaSNVDEFuW8zu9X8tW1u_ya8Af9tgLPXXoAItKXEW3MKUVevSiGWrwlAyXKvY_H3NkAeNwJ-dTiRPs_GzW_A6XbEKZvRdj5AlsRg6llk8AHUNTna0qPf91AWpkLtq1Qq0CFY6JTZRlqLB9_3np1Jwi17Qg8UgrlkkAO5_gN5VkFwakZMZVXdEHlCeI2H72GKxiTXT4r-W73LGlQOGa-LenZdrwCEC2CWhdS8QYSpZSSXGMCGIKboNr4hA5Bw6HyHk0rqaCxsq8VYo26FnRGnIrHoHOYW-IlGfWXLJsuXQb__5ROlXUs9uv9ptSgQRBNRdj8GBIg6TzAY8q_Co0gan2CKiqvL8wJsRLKgxz3Ba4bZUlRVzvbxBEjSLz05WkFP20njIss2AFOKNkhHd9M1IS-yU8JrVRWASEKtaP4pcoBs55HDXoxMpORuID7cPwaTgDgE3jOAVrN2NravYDGRyKQatgMHNsxyVujb1FrwPPb1NpwRtfV2pbOL6tavlwRQkXTQLrJ_6jHS0bc4-XyZo9XtpwuS_K-0-UV3V7gbcGun37eb2tV3jJZVlSbKu8Rg6L7_VWdpvyMedb72qDc73nTtBG5rhh2cY3SY2xKRukx9oITDkYtAMTrglcyiI_dINOSvKSHvOUJ7_fMum3sUd15NBlij1f-OnCYByAw4xMynMTGEQDvnMJdQYyf0RVAGERtFmYgdD4dGcvDL_wP8mvltembEmbSemqTrHJEQ5bIK_mMBhMKiXkTqSkdLyRljTOy_RQL3VjjMohnBY77A9rrdf3QvivGXx0Le8qmyFvrdjWG8CZRSlXitalUHy0YS-RIyj_8C9tyVIQxXVBivVcpVI7zRyVZKQimLpVLhT2KV9upeDkXaQkXAZMlxw2xY5DDShY1mgacpCYCBOYH56YjEBF5tfTOqdDIK-pultF-8mSV3L8mPglBAUB8nCmyR7h17kreRQrIpW-QUJe6IcgFYAEmBHD8zovPz9-jGlbgMYBjdPJr8STNCpjC3Y4YbMWskXiLglS9ompvdqVNO975q67UHSbqm0ny6rSYvjutQaJtZ7zx63vQFTERxjzIcmhEqUuwn7ym3fyFP0eVw4lHtH-iBX92WcLJK8viXx3tWQcVS999vv802FbTt2CEAjJ-fmdfxZ4OfxrhWxKAe_sLiIr2bhKSlwc_ERjv_n1h1YppmWvF7N-S_AfHHb-W`

**Comment by Openarl** [comment]
Not a bug. Blade Flurry cannot be supported by Rapid Decay, since it lacks the Duration tag.
![untitled](https://cloud.githubusercontent.com/assets/19189971/21301454/4e02faee-c5f9-11e6-81b6-91dc9ba4e84e.png)
