### ISSUE TITLE
Item editor allows adding impossible modifiers

### ISSUE THREAD

**Issue by fireundubh** [Openarl/PathOfBuilding#1090]
If an item already has a modifier, that modifier should not appear in the add modifier dropdown.

**Comment by Openarl** [comment]
It's impossible to reliably determine if an item already has a given modifier, so the program won't prevent you from doing this.

In general, the program doesn't stop you from doing something impossible if the user can be expected to know that it isn't possible.

**Comment by fireundubh** [comment]
How is it impossible to reliably determine that?

I think it can be done for most modifiers, excluding some edge cases.

**Comment by Openarl** [comment]
Yes, there are edge case, which means it can't work reliably, and something like this needs to be reliable to be useful.

**Comment by fireundubh** [comment]
Edge cases shouldn't stop you from implementing exclusion rules for most of the modifiers; otherwise, you might as well kill the item editor entirely since it doesn't handle unique modifiers at all.

**Comment by Openarl** [comment]
My point is that exclusion rules won't help in most cases; you wouldn't add Fire Resistance to an item that already has it even if the program allows you to. Where they would actually be useful is in instances where it isn't obvious if that modifier can be added or not, but that's precisely when those edge cases stop the rules from working correctly.
