### ISSUE TITLE
Vaal Impurity of Ice lowering DPS

### ISSUE THREAD

**Issue by Guffinn** [Openarl/PathOfBuilding#1091]
Yo everyone, the new Vaal Impurity of Ice lowers my DPS in PoB.
Weirdly enough, since I play a Cold Conversion Build and deal most of my Damage as Cold. So my Hits ignoring the enemies (set to Shaper) Cold Res should be a significant boost in DPS. At least that would make sense to me.

PoB for Reference, toggle it on and off to test: [4kk without, 3.7kk with Impurity](https://pastebin.com/ZXmnnzb3)

Hope I don't waste your time, really appreciate the work that you put into this awesome tool :)

**Comment by Openarl** [comment]
That's working as intended. Vaal Impurities work like Inevitable Judgement in that they cause your damage to ignore everything that affects the effective resistance of the enemy; including innate resistances, debuffs (curses, Frost Bomb), and penetration. Even against The Shaper, Frost Bomb + penetration are reducing the enemy's effective resistance below 0, so ignoring that will reduce your DPS.
