### ISSUE TITLE
Doryani's Catalyst missing some attributes ranges

### ISSUE THREAD

**Issue by Eirika** [Openarl/PathOfBuilding#1092]
Hi, I can't find any reference to this problem in other issues so here is the problem :

![image](https://user-images.githubusercontent.com/5630256/41811659-0b51c388-7714-11e8-9777-5b3d4b98efe7.png)

When adding Doryani's Catalyst into my build, I can only customize the range of "**Adds (65-85) to (100-160) Physical Damage**" but not any of the others attributes, despite the "**{range:0.5}**" param in the edit mode.

Am I doing something wrong or is there a real problem with this item ?
Thx for your help ! :)

**Comment by Openarl** [comment]
You need to select one of the other attributes from the dropdown to change its range; they aren't all displayed at once.
