### ISSUE TITLE
Adds cold and fire damage from boot enchantment does not apply to spells but lightning damage does

### ISSUE THREAD

**Issue by f0lie** [Openarl/PathOfBuilding#1094]
I was messing around with lab enchantments for boots. "Adds lightning damage" enchant would apply added lightning to my spell, Vaal Arc. However, "Adds fire damage" or "Adds cold damage" wouldn't apply to my spell. I confirmed this from the calc tab looking at both Vaal Arc and Lightning Spire Trap.

From my understanding, "adds etc damage" enchant is suppose to apply to both attacks and spells. Even if it didn't apply to spells, it doesn't make a lot of sense for only lightning to add damage to spells while the other two doesn't.

**Comment by Openarl** [comment]
Are you sure you've enabled the corresponding options for the Cold and Fire versions? The Lightning version applies automatically as the program assumes you haven't Killed Recently, but the Cold and Fire versions require you to enable the "been Hit Recently" and "Killed Recently" options respectively.

**Comment by f0lie** [comment]
I didn't realize that fire and cold damage were actually two different conditions! I figured they would be the same for consistency but PoE is not the game for that.

Thanks for the fast response and awesome project!
