### ISSUE TITLE
Wrong resistance shown?

### ISSUE THREAD

**Issue by Exportforce** [Openarl/PathOfBuilding#1097]
Build: https://pastebin.com/T2NVCG9d
Character: https://www.pathofexile.com/account/view-profile/GreenEyes1993/characters - GreenEyes_S

Ingame it shows clearly 75%+ Cold Resistance
https://puu.sh/AMbsK.png

In Path of Building only 61%

**Comment by Openarl** [comment]
Do you have the bandit option set? It cannot be imported, unlike the rest of your character's data. Selecting Alira gives the correct resistances, so I suspect that's what you have.

**Comment by Exportforce** [comment]
Ah right, that's it.
Thanks!
