### ISSUE TITLE
Vaal Blight Allows Stacking Spreading Rot Hinder Debuff

### ISSUE THREAD

**Issue by qikink** [Openarl/PathOfBuilding#1101]
With Spreading Rot jewels socketed, and an already active Blight skill, adding Vaal Blight applies the 25% increased damage taken (per jewel) again. This can be verified by checking the math, as well as mousing over the Effective DPS Mod line, in the chaos column. The context hover will show 2 lines of "50% Increased Damage Taken" with the source given as "Jewel Socket"
![image](https://user-images.githubusercontent.com/2025166/42131095-7a841356-7cae-11e8-84af-e4700cd2aae6.png)

**Comment by Wires77** [comment]
Just discovered this as well.  Here's a build that exemplifies the issue:  https://pastebin.com/3DwqUPx5

**Comment by DaneelTrevize** [comment]
A related issue is that the Vaal Blight gem does not have a checkbox for enabling (non-Vaal) Blight or not, in the socket groups UI. I intended only to use the Vaal version of the skill, but noticed the threshold jewel bonus was applied with the Vaal Blight gem row enabled but skill disabled. And, as already reported, it applies the bonus twice if you also enable the only toggleable skill from the gem row.

**Comment by Openarl** [comment]
This was accidentally fixed in 1.4.110.
