### ISSUE TITLE
Negative fire resistance breaks negative physical damage reduction

### ISSUE THREAD

**Issue by iamyourleader** [Openarl/PathOfBuilding#1103]
I am making the build to defy the idea that "all builds can do something" and I found that when I go below -252% fire resistance it breaks my -70357% physical damage reduction and instantly sets it to 90%. I am not sure why this happens other than I think it could be a possible underflow error? If you would be able to fix that would be nice but otherwise it is fine, ty.

**Comment by iamyourleader** [comment]
build is https://pastebin.com/KFbkCGQY if you wanted to look at something with it

**Comment by Openarl** [comment]
It's not an underflow; you've actually managed to give yourself negative armour... I presume the game wouldn't allow that to occur, so I will fix that in the next update.
