### ISSUE TITLE
Support for special characters in account names

### ISSUE THREAD

**Issue by cirf** [Openarl/PathOfBuilding#111]
the import does not work currently with some account names. For example: /account/view-profile/äxa/. I am not able to put an "ä" into the account name field instead there is an "?" apearing.

**Comment by dein0s** [comment]
Check here https://github.com/Openarl/PathOfBuilding/issues/55
TL;DR Not an easy task, on todo list, no eta, you can use url encoding atm.

**Comment by cirf** [comment]
OK, then it is a duplicate
URL Encode does the trick for me

**Comment by Openarl** [comment]
Indeed. If I ever get around to adding some documentation for the program, I'll make sure to add a note about that URL encoding trick, since it'd be useful for many people.
