### ISSUE TITLE
Malediction of Occultist doesn't seem to be functioning properly

### ISSUE THREAD

**Issue by WreckerOfDays** [Openarl/PathOfBuilding#1110]
I love PoB. I use it more than POE itself!

I just wanted to report that the Malediction node in Occultist doesn't seem to function properly. I don't see many aspects of the node calculating in a way that makes sense to me...whether it's the taking 10% extra damage, extra damage per curse, or seeing the added chaos damage on my skill. 

Sorry if this post isn't correct and it is working as intended. But I've scoured everything and can't seem to make it function correctly.

Thanks again for the amazing program!

**Comment by TechTrooper** [comment]
Any update on this?

For example my Soulrend does 410k dps and choosing Malediction in Occultist Ascendancy definitely doesn't include the 10% extra damage.

**Comment by Openarl** [comment]
As far as I can tell, all parts of that node are working correctly. Could you give me your build?

**Comment by TechTrooper** [comment]
> 
> 
> As far as I can tell, all parts of that node are working correctly. Could you give me your build?

Here it is. Maybe it's some setting causing it, but I can't figure it out. Hopefully you can :)
https://pastebin.com/d2NSDpgY

Seems that neither Soulrend Hit/DoT DPS is receiving the Malediction bonus.

**Comment by Openarl** [comment]
The Malediction bonus is applying correctly. However, since it is additive with other sources of "x% increased Damage Taken", it may not actually give a 10% increase; in your case, you have 90% increased Chaos Damage Taken from Wither, and 15% increased Damage Taken from Aspect of the Spider, so Malediction will give much less than 10%.

**Comment by TechTrooper** [comment]
Heh, this game is sometimes too complicated. I was 99% sure that "enemies take increased damage" is same as extra damage.

Well, thanks for the help !

**Comment by Openarl** [comment]
You're welcome!

I'll go ahead and close this, since I'm quite sure everything is working.

**Comment by WreckerOfDays** [comment]
Hey Openarl,

Congrats on being an employee of GGG!

I originally posted this last July because Malediction wasn't adding DPS to
my skills in the Calcs screen...namely Vortex. Here's my build:
https://pastebin.com/7MpdN3ga (I know a lot has changed since then). The
original issues has been fixes for a while. Before, Malediction wouldn't
show up in any "hover" menu. Now it does.

One thing it still doesn't does is ignore the DoT damage when highlighting
a specific curse's checkmark in the Skills screen. If you use the pastebin
above, Highlighting either Enfeelble or Temporal Chains' check mark only
considers Vortex's Hit, not it's Dot. As far as I understand it, the DoT
should be considered.

Thanks again for such a great program. I spend so much time in it.

(Did you make the Mobile version?)

**Comment by WreckerOfDays** [comment]
Hey Openarl,

Congrats on being an employee of GGG!

I originally posted this last July because Malediction wasn't adding DPS to my skills in the Calcs screen...namely Vortex. Here's my build: https://pastebin.com/7MpdN3ga (I know a lot has changed since then). The original issues has been fixes for a while. Before, Malediction wouldn't show up in any "hover" menu. Now it does. 

One thing it still doesn't does is ignore the DoT damage when highlighting a specific curse's checkmark in the Skills screen. If you use the pastebin above, Highlighting either Enfeelble or Temporal Chains' check mark only considers Vortex's Hit, not it's Dot. As far as I understand it, the DoT should be considered.

Thanks again for such a great program. I spend so much time in it.

(Did you make the Mobile version?)

**Comment by WreckerOfDays** [comment]
I didn't realize my email would show up on on a closed post. Sorry for the double post.
