### ISSUE TITLE
Ignite DPS not affected by Dyadian Dawn

### ISSUE THREAD

**Issue by petterannerwall** [Openarl/PathOfBuilding#1137]
Hey!

Seems like the ignite duration and therefor DPS is not affected by equiping the Dyadian Dawn belt. 

![pob dyadian dawn](https://user-images.githubusercontent.com/5909669/44173542-8a682680-a0e0-11e8-800f-1b040ef19fa2.png)

According to the [wiki](https://pathofexile.gamepedia.com/Dyadian_Dawn) the total amount of ignited damage should remain the same and the duration should be 35% shorter. That should mean that the new duration should be ~5,87 sec and thus the new DPS 697553,1 but that dosen't show when equiping the belt as you can see above.

**Comment by Blaatschaap** [comment]
This is not a bug. Please read the belt again. only enemies ignited by an attack!

**Comment by petterannerwall** [comment]
My fault!
