### ISSUE TITLE
Flask support needed

### ISSUE THREAD

**Issue by rhazor** [Openarl/PathOfBuilding#114]
THere is this trashcan streamer with 2k viewers on Twitch named etup and he was babyraging he cant add his nice flasks like taste of hate and vinktars.

Just add them as custom item slots and tread like rare items with rolls, etc.

**Comment by Openarl** [comment]
Duplicates #10 
It's been on the TODO list since before the program was even released, but it's not that simple to add them as there's quite a few details to work out (like how to handle flask effectiveness).
