### ISSUE TITLE
Spiritual Aid + Minion Damage Support

### ISSUE THREAD

**Issue by Thorinori** [Openarl/PathOfBuilding#1141]
Currently you do not gain damage from Minion Damage Support while having the Spiritual Aid node, which should allow minion damage increases to effect you., while Minion Speed Support and Spiritual Command DO work together.

Version 1.4.97

**Comment by Openarl** [comment]
That's working as intended. Minion Damage Support provides "X% **more** Minion Damage", not "X% **increased** Minion Damage", and so Spiritual Aid doesn't apply to it. On the other hand, Minion Speed Support is "increased", so it will work with Spiritual Command.

**Comment by Thorinori** [comment]
Ahhh ok, thanks! I forgot that it was a more multiplier.
