### ISSUE TITLE
[Typo] Dendrobate stat line typo

### ISSUE THREAD

**Issue by Bobblybook** [Openarl/PathOfBuilding#1150]
```
x% increased Damage with Poison if you have at least 300 Dexterity
y% increased Poison Duration at least 150 Intelligence
```

Second line should read: _y% increased Poison Duration **if you have** at least 150 Intelligence_

Nothing much else to say.. low priority fix

**Comment by Openarl** [comment]
Fun fact: That's actually how that stat was originally written in-game... But it was fixed, I just didn't get around to changing it. I'll do that now, since it's easy.
