### ISSUE TITLE
Smite missing melee phys scaling

### ISSUE THREAD

**Issue by oskar94** [Openarl/PathOfBuilding#1159]
Was trying to test out smite skill and it currently is not scaled by any "x% increased Melee Physical Damage" nodes and neither does the "Melee Physical Damage" support gem. 
I would expect this to actually work ingame since it has the Melee tag. 

https://pastebin.com/xCNdLd1v
As you can see neither the support gem or the Marauder starting passives changes the damage output of the skill.

**Comment by Openarl** [comment]
Yup, already fixed for the next update.
