### ISSUE TITLE
Withering Touch doesn't apply stacks of Wither

### ISSUE THREAD

**Issue by sherlockmatt** [Openarl/PathOfBuilding#1160]
**Steps to reproduce:**
Equip a Normal melee weapon, add the skill Spectral Throw, add Withering Touch support to it.

**Expected result:**
Calcs tab shows Wither in the "Curses and Debuffs" field

**Actual result:**
Calcs tab does not show Wither in the "Curses and Debuffs" field

Note: When you add the Wither skill itself, you can choose the number of stacks, after which "Wither (X stacks)" is present in the "Curses and Debuffs" field.

**Comment by Openarl** [comment]
It doesn't show up by default; there's an option in the Configuration tab under Skill Options to set the stack count when you have a skill with Withering Touch in your build. This is necessary as the stack count can't be set in the same way that it can be for Wither, since it is a support gem.
