### ISSUE TITLE
[Request] Add a horizontal scrollbar to calcs page

### ISSUE THREAD

**Issue by PathoDP** [Openarl/PathOfBuilding#1164]
The items page has one, sadly the calc page doesn't.

**Comment by PathoDP** [comment]
1080x1920
Vertical monitor as a side monitor.

**Comment by Openarl** [comment]
Well, the program's UI really isn't designed for vertical monitors! The lowest horizontal resolution I've accommodated so far is 1280; anywhere below that causes issues in a few places, not only the Calcs tab. It is something I want to address eventually, but very few users run anything that low, so it hasn't been a priority at all unfortunately.

**Comment by PathoDP** [comment]
Understandable, keep up the amazing work!
