### ISSUE TITLE
New Minion Nodes causes error messages.

### ISSUE THREAD

**Issue by ufail0r** [Openarl/PathOfBuilding#1166]
Just updated to version 1.4.103 for the current Delve League.
Although upon trying to check my Summoner Build, this error message popped up.
Checks out it was repeatedly caused by the new Minion Clusters containing "Sacrifice" and "Spiritual Command".
![poberror](https://user-images.githubusercontent.com/42879401/44937751-20f04500-ad7b-11e8-8cfb-062d79488b98.png)

This error could be reproduced 95% of the time by hovering over the nodes. My Summoner Build is unusable/unable to load because of this error message

**Comment by southernwestern** [comment]
I'm having the same issue after updating to the latest build of PoB and attempting to load my build using these nodes.

**Comment by ayan4m1** [comment]
I am having the same issue after updating to 1.4.103.

**Comment by KillaSeven** [comment]
Same error after updating.

**Comment by Openarl** [comment]
Fixed in the next update.
