### ISSUE TITLE
Error after updating to 1.4.103

### ISSUE THREAD

**Issue by philconow** [Openarl/PathOfBuilding#1168]
Error: 

In 'OnFrame': Modules/CalcOffence-3_0.lua:184: attempt to index global 'mod' (a nil value) 
stack traceback: 
Modules/CalcOffence-3_0.lua:184: in function <Modules/CalcOffence-3_0.lua:128> Modules/CalcPerform.lua:934: in function 'perform' 
Modules/Calcs.lua:121: in function 'buildOutput' 
Classes/CalcsTab.lua:402: in function <Classes/CalcsTab.lua:384> 
Modules/Build.lua:551: in function 'CallMode' 
Modules/Main.lua:298: in function <Modules/Main.lua:289> 
[C]: in function 'PCall' 
C:\ProgramData\Path of Building\launch.lua:99: in function <C:\ProgramData\Path of Buildinglaunch.lua:96> 

Press Enter/Escape to Dismiss, or F5 to restart the application.

**Comment by philippeop** [comment]
I have this when hovering above the new Spiritual Command node that gives:
Minions deal 15% increased damage
Minions have 4% increased Attack Speed
Minions have 4% increased Cast Speed
Increases and reduction to Minion Attack Speed also affect you
20% increased Minion Accuracy Rating

**Comment by Zoltorion** [comment]
For me I updated from 1.4.102 to current and got this and now when I restart it gives me this error whenever I try to open one of my builds.  Creating new build doesn't cause it until I hover Spiritual Command node like philippeop said.

**Comment by Openarl** [comment]
Fixed in the next update.
