### ISSUE TITLE
Configuration can't choose WHILE IGNITED 

### ISSUE THREAD

**Issue by zodiacpf** [Openarl/PathOfBuilding#117]
Very useful software! 
I use "Eye of Innocence Citrine Amulet" & "Mokou's Embrace Ruby Ring" to be ignited to get 70% increase fire damage and 20% attack speed. So, wanna to have a option in WHEN IN COMBAT configuration like "while been ignited".
TYVM

**Comment by Openarl** [comment]
Easy enough. It'll be in the next update.

**Comment by zodiacpf** [comment]
Nice~
