### ISSUE TITLE
Can we get rid of the Infinite Skill Tree Canvas?

### ISSUE THREAD

**Issue by dsnvwlmnt** [Openarl/PathOfBuilding#1172]
Is it really necessary to have an infinite canvas for the skill tree? Because the coordinates are saved every time you close a build, you can find yourself in a situation where the tree can never be found.

I use PoB on a computer (1920x1080) and a laptop (1366x768), sharing the same Settings.xml and /Builds folder.

The resolutions are different, so an issue has arisen: on the laptop, looking at the skill tree canvas, i can't find the skill tree. Even if i zoom out to the maximum, the skill tree is not visible. So, i drag the canvas in all directions for a while. Still can't find it.

**Comment by moocowpong1** [comment]
I have the same issue - I misclicked and managed to drag the tree offscreen, and now I can't find it again!

**Comment by Openarl** [comment]
Sure!

**Comment by Openarl** [comment]
Sure!
