### ISSUE TITLE
Unnatural Instinct + Might of the Meek interaction

### ISSUE THREAD

**Issue by Asymat** [Openarl/PathOfBuilding#1176]
Actually doesn't work in PoB (small passives grants normal value -- not boosted by Might of the Meek). I don't know if working in PoE but it _should_ be from wording.

**Comment by Guffinn** [comment]
Yep, just noticed this as well. It works in PoE, but PoB doesnt take the Meek-Modified Values of the Minor Nodes into Account when granting their Boni through Unnatural Instinct.

**Comment by Openarl** [comment]
Fixed in the next update.

**Comment by tirrorex** [comment]
@Openarl was there a regression?
I have v 1.4.121 and putting the jewel into the socket doesn't grant any passive bonuses.

**Comment by Sarkestorm** [comment]
This is not working once again...
Also I added militant faith for the 3 jewel scion combo... 
While Unnatural instinct and militant faith seems to work... Adding might the meek doesent do anything.
