### ISSUE TITLE
Spiritual Aid/Command's Minion-to-Self buffs not factored in calculations

### ISSUE THREAD

**Issue by SineSwiper** [Openarl/PathOfBuilding#1178]
Both of these (new) passive tree nodes have "Increases and Reductions to Minion Attack Speed/Damage also affect you".  However, the calculations aren't factored properly for DPS.  Minion damage additions appear in "MH Total Increased" for All Types, but the percentage isn't used.  They don't appear in the Physical section at all.

**Comment by Openarl** [comment]
If it's in the All Types column, then it **is** being used; the damage calculations combine both the modifiers in the All Types column and the ones in the specific damage type columns.

You can provide me with your build if you'd like me to double check, but I don't think there's anything wrong.

**Comment by SineSwiper** [comment]
Ahhh, you're right.  It's included in the "Inc/Red" multiplier for Physical hit damage.  This was a bit confusing since All Types seemed like a rollup, at least for "MH Hit Damage".
