### ISSUE TITLE
Need some clarification (further useful for faq/wiki?)

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#12]
Can you, please, explain how does exactly 'Mode' switcher works on 'Calcs' tab?
I can see some difference in values under 'attack area' while switching unbuffed/with buffs/effective dps. But what exactly happens, which buffs are counted and so on?

And what happens (should happen) if I manually turn on/off buffs/conditions/other stuff in that column? How does it interact with 'Mode' switcher?

**Comment by Openarl** [comment]
The mode selection really needs a description somewhere; I've been getting a lot of queries about it so I'll get to it soon.
In the mean time, here's the basics:
Unbuffed: Auras and buff skills (e.g Golems, Righteous Fire, Blood Rage) will apply, as will anything under the Conditions header. This is your tooltip DPS out of combat.
Buffed: Anything under the Buffs header will also apply (charges, onslaught, etc). This is your tooltip DPS in combat.
Effective DPS: Curses enemy resistances, penetration, and anything under the Effective DPS header will also apply. This is an estimate of your true DPS.

**Comment by dein0s** [comment]
According to 'Unbuffed' state: will it apply only 'Active' checked skills from 'Skills' tab or all possible skills from there?
According to 'Buffed' and 'Effective DPS' states: I need manually activate buffs/conditions for them and if current state is 'Unbuffed' - they wouldn't count, right?

As for example: I have 'Rampart' wheel on the tree (duelist area). To apply it damage buffs I have to turn on 'Buffed' or 'Effective DPS' state and turn on 'Fortify' in related column. Am I right here?

**Comment by Openarl** [comment]
Skills that aren't set as Active in the skills tab will never have any effect; they won't apply in any mode or reserve life or mana. Any Active skills that provide buffs or auras will apply in all modes; curses will only apply in Effective. I know it's confusing that buff skills apply in Unbuffed mode; as I said I really need to clarify the mode selection.

Regarding Rampart, that's 100% correct! Fortify is counted as a combat buff, and so only applies in Buffed or Effective. The exception to this is Fortitude in Champion, which will make fortify active in all modes since you'll always have it on.

**Comment by dein0s** [comment]
Great, thanks for the explanation. Also it's very cool that I can finally see the damage of each part for multiparted skills (like EQ) without any spreadsheet math :D

And the last thing here, related to my previous example - it looks like there's no any difference if I turn on/off 'Fortify' in 'Effective DPS'/'Buffed' state. Is smth wrong here or I just still don't understand the whole mechanic? Though that's not a champion.
![Fortify OFF](http://i.imgur.com/kb89YHh.png)
![Fortify ON](http://i.imgur.com/VBhzbVi.png)

**Comment by Openarl** [comment]
Oh, you have the Fortify support on your Earthquake? In that case, fortify will be enabled automatically in when in Buffed mode, no need to tell the program that you have it.

**Comment by dein0s** [comment]
Blah, thanks. Because that switcher confused me :)

**Comment by Openarl** [comment]
The mode dropdown has had an explanatory tooltip since 1.2.0, so I'll close this.
