### ISSUE TITLE
Support for elreon mod on rings

### ISSUE THREAD

**Issue by fakeaccount1234** [Openarl/PathOfBuilding#120]
Any chance of this being implemented?

**Comment by Openarl** [comment]
It is supported, but it's not currently included in the ring or amulet templates. You can add it to an ring/amulet manually if you need to though; just click the "Edit..." button when viewing the item, then add the -mana cost modifier somewhere. If you want to be able to select the range, you can write it like this:
-(4 to 8) to Mana Cost of Skills

**Comment by fakeaccount1234** [comment]
Thanks for the quick reply!
