### ISSUE TITLE
Geofri's Legacy Great Crown is L62, not L53

### ISSUE THREAD

**Issue by TheRealRequnix** [Openarl/PathOfBuilding#1204]
Easy error - Geofri's Legacy Great Crown is L62, not L53 (which it currently shows in PoB).

**Comment by Wires77** [comment]
I see that in my version already.  Can you make sure your PoB is up-to-date?  Perhaps you're looking at Geofri's Crest by mistake?

**Comment by Openarl** [comment]
Are you looking at an imported version? Imported items that have sockets will sometimes show a level requirement that is lower than expected; unfortunately there's nothing I can do about it, as it's a limitation of the game's character API.

**Comment by TheRealRequnix** [comment]
Ahh that must be it. Sorry to take your time - keep up the excellent work on PoB, and thanks a ton for reviewing this!
