### ISSUE TITLE
Bug: Abyss jewel in weapon crushes PoB

### ISSUE THREAD

**Issue by timofeyeva** [Openarl/PathOfBuilding#1221]
### Abyss jewel in sceptre crushes PoB.

Error:
In download callback: Classes/lmpoilTab.lua:712: attempt to index a nil value 
stack traceback:
Classes/lmportTab.lua:712: in function 'Importltem'
Classes/lmportTab.lua:722: in function 'ImportSocketedltems'
Classes/lmportTab.lua:646: in function 'Importltem'
Classes/lmportTab.lua:486: in function 'ImportltemsAndSkills'
Classes/lmportTab.lua:417: in function <Classes/lmportTab.lua:407>
[C]: In function 'PCall'
...sers\%username\Desktop\PathOfBuildincj-1.4.99\Launch.lua:203: in function <...sers\%username\Desktop\PathOfBuilding-1.4.99\Launch.lua:195>
Press Enter/Escape to Dismiss, or F5 to restart the application.

**Comment by Openarl** [comment]
Fixed in the next update.
