### ISSUE TITLE
Bug: Lightning resistance not being factored correctly

### ISSUE THREAD

**Issue by Slivenius** [Openarl/PathOfBuilding#1222]
To reproduce: https://pastebin.com/SS9KzVqB

I was playing around with elemental equilibrium and noticed that when "Hit with Lightning damage" was ticked there was no real change in damage, I adjusted the lightning resistance modifier as well and there was no change. The calcs tab shows a flat 1x effective dps mod for lightning damage only - other damage types seem fine.

**Comment by Openarl** [comment]
You have Vaal Impurity of Lightning active, which causes your Lightning Damage to ignore enemy Resistances.
