### ISSUE TITLE
Zealot's Oath and Mana Reservation calc

### ISSUE THREAD

**Issue by pohky** [Openarl/PathOfBuilding#123]
i importet my character and noticed 2 things (account is TouhouNerd and character is HardgoreAlice in case for testing)
the Zealot's Oath passive node gives +72 flat Energie Shield Regen in the stats calculation
and i'm using the Prism Guardian shield , Blood Magic and the 50% less mana reserve node behind it in the passive tree, Alpha's Howl helmet and grab all the reduced reservation nodes aswell for the 38% reduced
now in the calculation when socketing auras into the shield the reservation gets rounded up (so Grace 50% becomes 8% when it should be 7% or Purity of Ice 35% becomes 6% but should be 5%)

**Comment by Openarl** [comment]
The flat regen from ZO is from your Stone Golem.

The issue with the rounding on the reservation calculations is something I'm looking into.

**Comment by Openarl** [comment]
The reservation calculations should be fixed in the next update. Let me know if there are still inconsistencies.
