### ISSUE TITLE
Temporal Chains impact on DPS with poison builds

### ISSUE THREAD

**Issue by ExilMage** [Openarl/PathOfBuilding#1246]
**Description:**
In PoB Curse Temporal Chains has negativ effect on any poison damage.

POE Page says: 
>Increasing poison duration with the Temporal Chains curse results in a longer-lasting poison that deals damage at the same rate.

**Steps to reproduce:**
1. Create new build.
1. Add spell Bladefall with Poison Support Gem.
1. Add Temporal Chains.

**Expected result:**
* DPS should increase if Tempral Chains is active because there can be more poison stacks.

**Actual result:**
* DPS is lower with Tempral Chains.

**Notes:**
Looking at the calculation i see, that the operation ist wrong.  It says: 

Poison Duration: 1.43s
2.00s (base duration)
/ 1,40 (debuff expires slower/faster)
= 1.43s

Shouldn't it be 2.00s * 1.40 = 2.80s ?

**Comment by Openarl** [comment]
Fixed in the next update.
