### ISSUE TITLE
[Yriel's Fostering] Rallying Cry Buffer :POB Error

### ISSUE THREAD

**Issue by lucifering** [Openarl/PathOfBuilding#1247]
Yriel's Fostering

[Config]Tab
"Enable Summoned Ursa's Rallying Cry:" Checked

[Skills]Tab
Add Skill [Cyclone]

[Calcs] Tab:
select [Cyclone]

Error  CalcPerform.lua 763:attempt to index field "minion"(a nil value)

**Comment by Openarl** [comment]
Fixed in the next update.
