### ISSUE TITLE
Variable Initialization Errors?

### ISSUE THREAD

**Issue by Lothrik** [Openarl/PathOfBuilding#1248]
~~Reproduction Steps:~~
~~1: Import PoB from https://pastebin.com/n46YKL57~~
~~2: Open Skills Tab~~
~~3: Attempt to add any support gem to Summon Lightning Golem~~

~~After Step 3, the following errors will appear:~~
~~http://puu.sh/BScl5/551bdf4b21.png~~
~~http://puu.sh/BScll/0c167004df.png~~

~~This is caused by the following configuration option:~~
~~http://puu.sh/BSclt/8bdecaf899.png~~

~~.. coupled with the "Summon Lightning Golem" skill being uninitialized. Selecting it as your Main Skill will (..sometimes) prevent the error, but only for that session.~~

(This appears to be fixed, probably as of 1.4.115)

----

There also seems to be some sort of error with how Gem Quality is handled in the Calcs tab. ~~Attack Speed Quality bonuses are frequently attributed to completely nonsensical sources, like Whirling Blades somehow giving Spectral Throw 10% attack speed, or Ancestral Call giving Leap Slam 10% attack speed: http://puu.sh/BScsX/e0cb89b974.png~~ (Partially fixed, error still exists in other areas of the calcs tab)

I tried to get a screenshot of the Whirling Blades 10% attack speed thing.. but just switching builds turned it into Ancestral Call: http://puu.sh/BScv4/3669f3bfbf.png

Edit: https://pastebin.com/4CUUPv3s (Swap between Molten Strike and Leap Slam in the Calcs tab and look at the attack speed bonuses, it gets "stuck" and attributes the 10% quality bonus to the wrong support gem).

**Comment by Lothrik** [comment]
1.4.115 (Fixed an issue where modifiers from skills sometimes had the wrong source in the Calcs tab) fixed some of the Calc tab issues, but not all of them.

Area of Effect modifiers in particular have the same issue (ie: 10% aoe quality bonus being attributed to Volatile Dead on an Infernal Blow build). I'll update this if I notice any others.

**Comment by Lothrik** [comment]
Duration modifiers have the same problem. Lightning Warp is showing Bone Offering as a source of 10% reduced Duration. The build doesn't have Bone Offering at all (and even if it did, that's not something Bone Offering does).

http://puu.sh/Cdw2t/b32408e67e.png

**Comment by Openarl** [comment]
The next update will finally banish this bug to the dark beyond.
