### ISSUE TITLE
Ignite DPS + Concentrated Effect

### ISSUE THREAD

**Issue by AmenRa666** [Openarl/PathOfBuilding#125]
Hi, it seems that _**Concentrated Effect**_ double dip _**ignite dps**_.

**Without Concentrated Effect**
Avarage hit: 15856.2
Ignite DPS: 6456.1

**With Concentrated Effect**
Avarage hit: 25245.7
Ignite DPS: 15989.9

**Comment by Openarl** [comment]
Yes, that's how it's supposed to work. Area damage affects ignite if it is applied by an area skill; I've confirmed this myself.

**Comment by AmenRa666** [comment]
Oh, i didn't know that, great! :)

**Comment by ImaginaryDevelopment** [comment]
This appears broken now, FlameBlast with concentrated effect only gives Average hit, no Ignite DPS.
