### ISSUE TITLE
Staff not considered as two-handed melee weapon ?

### ISSUE THREAD

**Issue by binbinhfr** [Openarl/PathOfBuilding#1260]
Hi,
I have a profile with a staff installed, and a jewel with something like "+% crit multiplier with two-handed melee weapon". PoB does not seem to take this property into account (i tried deleting and re-adding this mod, and nothing changed).
But when I check the web, it seems that staves are considered as TH melee weapon :
https://pathofexile.gamepedia.com/Two-handed_melee_weapon

Is it a bug, or am I wrong somewhere ?

Tx for this great tool.

**Comment by Wires77** [comment]
That mod is not considered if you're casting spells, only if you're using the weapon to attack.

**Comment by binbinhfr** [comment]
oh ok, sorry. Not obvious. Thanks for your help. My bad.

**Comment by DaneelTrevize** [comment]
You should be able to close this issue yourself.
