### ISSUE TITLE
Blasphemy's reservation isn't being calculated properly in this build.

### ISSUE THREAD

**Issue by calmchaos** [Openarl/PathOfBuilding#127]
In the following build, a single blasphemy (Temporal Chains) is being used without Enlighten, any reservation nodes, nor any decreased affixes, but it is being affected by two Essence Worm rings. It _should_ come out 63% reserved (35% * 1.8), but it instead shows 89% reserved.

After testing, I found that the issue stems from Blasphemy in some way, probably from a weird interaction this build creates. 

In the build below, I tested this by putting a Vitality (also 35%) in place of Blasphemy, and the mana reserved came out to 63% like it should. Replacing Blasphemy again returned the incorrect value of 89%. 
Then I removed all things that affect reservation and solely used Blasphemy. For some reason, Blasphemy is showing that it reserves 49% at base instead of 35%.

In a separate build that uses two curses with Blasphemy (Assassin's Mark and Poacher's Mark), Blasphemy's reservation is beingly correctly calculated to 70%.

I don't know how or why this particular build is creating the bug, so I've dropped the build code below.

BUILD:
`eNrtW1tT47gSfl7_ClWq5hRTMwm-xInDgT0VAgwMl2GSwAz7MqU4SqLBl2DZCWFr__tpSTa52bEzsLtTew4PxrFbrVar-1N3S97_z6ProAkJGPW9g5JWUUuIeLbfp97woHTTPSlbpf_8quxf43D0aXAYUYe_-VX5Zb-FHZvBzS_7Z944CpGHXXJQYvfUcb6NcRCWkBe5PRIA09JuBp2kmFNWUyhdyuxvvWgwuPT7pIRYGAjRjk9Ojlvds9vjTObYDumEXK10kQjTIfDa95DtOw4eM9I_KHnUKSEKNx3evkMcIClAfUrDI-ziISlAe-QX4dgZE9IvQNcKaEEBWyPs2aTo0LuzMemEOGQFGhw6xWS99inzvQKEZ0OPhkVEvQTDOB4MgKKInM0QDKcXhaQI8QUdFJIAe7gA2bFHguGsM6LEKaKpZuD6UVCE7wRzry1A2SaMsrCgTo_IABAg1tP-buLn-8L5kUMmxAE3UgEobAczdiVcrjPCfX9aQpjZxOu35i-6AbXvWchdcELJlDsxzPHl9ad2t4RcTL2Ob9-T8EPgR2MOAKiHvT4NL0lgU4cwdlA6DzANZ17y5soPXAwSXPkeSZ61gogkj4TUwowlOolb5OAep-DghnsOH3MIbQBOHD88KH0heAwa0aRETQEcoh3HC87ll_0PxE3GrqtrbDjugNfawGpEAwcQCh06uA9KRA8RdkB-0Wx3O14nmCsOgeli0OHLWPlBSAezFB77u2Kk2-pKL64rAcfXsCSI-c3WHA1H3ExeMEq4gvxdPyTuayi-Bf9gKl9BaafEcUmYojLuedvJdouxg47AT-kY7IwsCLf1MM88OyAYEAAdRQHmoPAirXWJO_YDkA5WG-q9zF7Be9h4RNzXsNhDvz9DMaq-3MGPGePwiI4All6mr1uf9hGsIXQcOS_Xfsv3wgAgnc8mgSgpsl_Mso3HlHOz8exFfK4poDnJY7EJG47Bsqap4LCtMXxw_AmH5VfwxGZvxhg392D2E9nB3Kmb8B_5AySDpL_GuLb3TT98ndngIuLhT6m9V8bZV1-d2jxe0V5nFhwMScnstYTSX0Wo1NVyXa74TgS73YAQJDNIyUMuE_v8h-z8pn0hbn4ZheGY7e3uTqfTyhjSZH9AHiF0rdi-uzuGOBhYlEUIVA6B6W4T_g6bd63m4ZPth_dPo7rhhk8tVR14fvOx9t03PL0WjPXhgx1MP_SCuzrt1qvDo3r0LfA7jYfvh1fhqXr8qXNycqp_Dy-C0devowfz481XdzQLr7VeeXqnWeXbi9HnjxM_8DXv2wfn2-e7W-eCHX2dObP60Z191TWm7cnZuRP2Ledj9_z6wZ6Mjif3s77mTdz7k8AytJOJal3dspausdrnj1_urAs2ZKT8yXlsaviu_FS_OdYffZeeDS6O2habVKPfrLsH9ah5P_x8Z1vnZ99q-PTz6elYjxzz67XxRf1Nd8-brDyJbu--htdV_dvssHt90nd64-lQv76z8IfZF61z4UzOpz5tHH0xP7iPl0x1H69vrbbjDD6Wu4PPp-W-eti76U_ub0_N1nm7_TTTZ83Ho6vRYX1ssvZN8-BATNBuPEMwrXLS9nf5rPKbK4gQRXbAHyY_xJzfQo6CGMGBPeqEATfOJ9937w5KZlWr1FWzCqsUG_nTU4LDSzxObI0TXUhLtOSvrwelsm4YRqVWV-u6zErOIC6NSyZwhybgKtgDU9dl8tWQZt0WHrSHbjz6EBGlOyIIsI1FLneIIxzcKycUciy4HQ5JoNxKLnvoOiBIr-gVdf6oFQUB8UIlJr0ezRi1efgo6hV7SGuU6zWFlxHEYxgxvSdIFgv2UL2iqm-UOPtAY4AcSB19rw_tKrqqtMlDRAPCkBg4Mo33yLRgeXh8jzTdQGfQb019g-gz-MHS2xPLZVp3yjsNhX7MC2BXpoXQ6gT6QODpTNmpqpykpr5d5Cpjfjki5d2OLmiq6lv-D2SAl3TIAzbl91jfe9ofVfMN70Owli25iick4B1COxDJZwnP53b6H4a6Rbs7iDeXniBZA2Ho2CMuJUxYKSTEbezBy4BfIYivmNIajGRZyKRIqmW73JqyzcpKNatD6vn_gkyO_ZuhcxraI-Khc48OiNJxcDQc8RVG_n6Jge2YjXKtwVWjNayyrllvM61tp1HRq5yyUWnADGfYXXXN7mrme2Rpsd1pdWF31S3szliijWcKYsQAdalLlGa_z2AYarkmDEvT1bLGrWtlqIlxmsvGmdHngim-29EkYxMawv8MYS8jJ-RLGCh5wR6hsckb6YUbv9ux5DBkA2mesjwkJPsEVgBLFYcaHNsrDIMb7Ow98gAXe7PEfBEOyDOJggGR4vdNaE84V_A7AvEOWI2qIl5TE5PJxGS-kvFvoDBzKWq5FPV0F5MCLLkV_CeKrPQhWepDMulXTqNeQBlq0cB24Cd40YA-Eran_C5626vUzT92pA0Y-pL1LLFLyNWY2Kzl03LW7yR5XReI6OJH6kZuLnmjsUTOJ28uQMLSWKLh1dA1GtnrOqpfUo_XIAWud6LBskaeW1dVieNN24bA2Z6BlnnIu0Znmilwv8rLkiYvwHvB4rPoWj5MYQG6Cwpg6XGH2UBsmBn-lm599dj89GwDrelaw9TkRc91mnqu1-T5TJ7HLPlL5vtGzntN3TAGS61aySUej6ZtoK8aDVVPLjH9Bo1CnGZoz5eY3sgTuJqNEHouQrRGkEwroqIHaAmJCf674EGrmlvhg6b9IEBkO_v_oBOblmnUkkv1p_FiazsnzHbqyiJ1tVHAxxt6zdLjSz3Xx5edOs0HzVwflAVByKmAZcB3nFCHOvfJ4x1NL2u17ITjb3JXsNttvNV66Wouo2AIgjkJRMDrAbBYpmXIvt5MhrjwH8ReTJ42tWnETWpvpRcXaKLLJjr0Mnfo9XYpEBTP2PIkSHokduNfGppAegIZFdjgPx72kpU5H8by1tZqPosfR7pKrVozqlpyKRa-WH9eeFMU64oGJNkEeTrTNiltKUiK6etbxlSblpcFai3hn6fVeSV3Hf-NXPwXOxBKxw9sEkB2Kn_-lbCu_j2grsUiGssVi0tY9lzihTHs_T9cW7U2Yzvr_dNiNe2lGVd6QqVumVC9XgK2DHBpzlxLrWQezwgvLcA0zyIHK5-82SNquhGvtayUCnVVeS631YT1Yojk5ifDFF19gwLSj2xwhCW_Wi4SSgF4p6KijwZ-5PWVFvY8P0Q9gjph5PGaWJEFMm2cWvo444MHX_zAVW48RkLE98hWB2lYyilmSItrLco7Pb0C04SwJa6_JI_4L-4oJJgQdOVLuFiupfJHCUk_Q_x6CuYeEidUWsEMXNBB4se7nZpattQNkLcGwuo21SlTy0fTObDU4mhOnBJZRfHqCuI7AiHnoe-UhiMkz0WxfMTshAHxhuHonx3l_VxgmZ6JWttl5pugdF6Mg8urBXt6sR0e6CkVMKTJnwS-i_jhOuopLb4_EKKPZEqc1Y0dM21jp437NGJ76AIHw6V9i4V9hLlnZDjbfMNixxA7eAUaJWcmGOI7C20OyvzgBJMGPSDAAEnhxD5EFzTHBoCMciMOj8fOjN8sM_3RjGU5NEiFbC0F9KSal3Segmmpuefq9tJm6oWcOodyIZXOoVzNoPMYL22ZbiQV5zMzSOupprEM8HH4W8TylptwMQby8AyAWxCK4z1LyUCb2CNp6ZtHEOBxsbFeUo8UpuQ7IoVoV2svcgECR2GbtbRY0djQaEPBC01H1OEdEvEhCMKwnOHBYHsOI_-ZQXrmtGxdMGuJ2IUEyGm-1nv2qh1Hipmrdvw-u8ATE6QnSjHJcg6WYQPLWHsd-N_5SX6HFKNf29neTC6Ov6UzrqbZFEfpuZo3T0d6YS2NeTbHFXGXirKbSTcfB1htWy2wnw8JQCAlYOuzrxfe119tmURkmU0W-91UH_nhIO2lUVnFqi0EUo3X2UPcELVZC_mmqv9lNTn9py7a5VbpcstyRetweYrS8xSlb8gXFgNyI84X9Dy96WZO-UTP05uepzc9T296nt6MPAs0ctOsXBfPs0AjT5OGuRb8dhw_-eIyOVVP4d3ZHBIWSebfWCVEjXUiESSjmlbVGnM6Tcvkps-prHWi-HB5QmGkUSx8GpLQ6ZlyQapqbpYrGYBlVDcTygrVnKaWyUs31CJ9VjVdbGMkhGoWoVGr5QmXHAh_pskg0TeSJB89JSTVFP0TZ4GgHn9ymJyT3W_53oAO177v5efHKM8Gxbm0Fg9pSP_Ma7JRCfV83yHYOygNsMNIysfBESMnEMo9zVoi0mcLTcRZ3t2c7iCOoy7t45D0C_TGP1x-_vZuu44gb38iXoE-npud0hASGEjbndk2zURvnRGvAva3bic_192-3SWGGHSrZvxcIulvMUAi5GOHPmNbi5eca9y6ofgeWnyWUbxhM2w5PiMCdrfusBUFbDs5DwnJNZX93cT39ndXv_3_L5f-jGQ=`

**Comment by calmchaos** [comment]
Oh!
The Increased Duration support was increasing the mana cost. I was under the impression that supporting a curse with Blasphemy stops invalid supports from affecting the active at all. Or is that a bug after all?

**Comment by calmchaos** [comment]
...accidentally hit the close button. My bad.

**Comment by Openarl** [comment]
Blasphemy does not prevent such supports from applying to the linked curse. The program's behaviour in this case matches that of the game, so there's no bug here.
