### ISSUE TITLE
Frostbite Quality bug

### ISSUE THREAD

**Issue by Draesy** [Openarl/PathOfBuilding#1275]
Frostbite "Freezes on Cursed enemies have % increased Duration" reduce duration instead.
![default](https://user-images.githubusercontent.com/27978318/49303685-67208600-f4db-11e8-9826-8d4439273f35.png)

**Comment by LocasMaxis** [comment]
Still happening as of latest patch

**Comment by Openarl** [comment]
Fixed in the next update.
