### ISSUE TITLE
Commander of Darkness not benefitting from aura effect

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#128]
"increased effect of Non-Curse Auras you Cast" increases the effect of the bonus granted by Commander of Darkness, since CoD modifies the aura to grant that stat. This is rounded down of course. So 35% aura effect would mean each aura grants 13% increased damage and 6% increased attack/cast speed.

Unwavering Faith does this too but its not DPS related.

**Comment by Openarl** [comment]
Hmm. That's going to be tricky to fix. I took a bit of a shortcut when implementing those passives, which avoided having to tinker with the aura code, but it didn't allow for aura effectiveness to apply (which I didn't realise was necessary). I'd have to completely rework them to fix it.

**Comment by Openarl** [comment]
I've managed to come up with a reasonably elegant solution to this. It'll be in the next update.
