### ISSUE TITLE
"Total More" Calc is wrong for arc+chain setup

### ISSUE THREAD

**Issue by ArnaudDesaulty** [Openarl/PathOfBuilding#1284]
### BUG

When using Arc spell with Chain support, the "total more" value is not the sum of the tooltip individual "more"

### PICTURE

![image](https://user-images.githubusercontent.com/22226633/49512996-ddccd300-f88f-11e8-9257-7ea4a4cf4417.png)
![image](https://user-images.githubusercontent.com/22226633/49513219-8da24080-f890-11e8-8992-034f6ba22a32.png)

On these pictures, we can see that the bug is affecting the skill hit damage (*2,1 more instead of *2,36)

**Comment by Openarl** [comment]
How are you arriving at x2.36? "More" multipliers are combined multiplicatively; 0.9 x 1.44 x 0.69 x 2.35 = 2.101464.

**Comment by ArnaudDesaulty** [comment]
😓 This explains that... My bad, I was mistaken on how more modifiers are working.

Thanks for the answer !
