### ISSUE TITLE
(Vaal) Storm Call quality modifier labeled incorrectly in Calcs

### ISSUE THREAD

**Issue by Patchumz** [Openarl/PathOfBuilding#1285]
Storm Call/Vaal Storm Call's quality effect (Increased Area of Effect, under Area of Effect Mod in Calcs) is labeled as Rain of Arrows instead of Storm Call/Vaal Storm Call. Very minor, but it's there.

![image](https://user-images.githubusercontent.com/1404291/49530964-21164a00-f86e-11e8-9348-dc4188c90707.png)

**Comment by Lothrik** [comment]
See also #1248 -- this happens in several different places.

**Comment by Openarl** [comment]
Fixed in the next update.
