### ISSUE TITLE
Ruby, Saphhire, and Topaz flasks still grant max res

### ISSUE THREAD

**Issue by Jackalope-Gaming** [Openarl/PathOfBuilding#1291]
The patch notes specifically mention the elemental flasks (and Divination Distillate) no longer grant max res and instead grant reduced damage taken of their respective elements.  Will this be addressed in a newer version that adds more 3.5 stuff such as skills and items?

**Comment by decayedCell** [comment]
Obviously it will, there are no 3.5 changes yet so this fix will be expected whenever it's getting updated for 3.5.

**Comment by Openarl** [comment]
The next update will apply these changes.
