### ISSUE TITLE
Crafting resistance mod's aren't calculated

### ISSUE THREAD

**Issue by GZer** [Openarl/PathOfBuilding#1307]
When using crafted mods in Betrayal League the resistances gained, specifically the ones with Chaos Resistance, are not counting towards the total.

https://pastebin.com/Avpjcfe0

**Comment by Skyl3lazer** [comment]
Confirmed for me as well https://pastebin.com/1bvb5RdX

**Comment by Kryai** [comment]
Same issue. Here's an item example that does not count the +15% Fire/Chaos Res:

Rarity: Rare
Miracle Sole
Stealth Boots
--------
Quality: +20% (augmented)
Evasion Rating: 347 (augmented)
--------
Requirements:
Level: 70
Str: 155
Dex: 117
Int: 68
--------
Sockets: G-R-G-R 
--------
Item Level: 82
--------
80% chance to Avoid being Stunned if you've Killed Recently
--------
+55 to Dexterity
+35 to Evasion Rating
16% increased Evasion Rating
+24 to maximum Life
+43% to Fire Resistance
30% increased Movement Speed
9% increased Stun and Block Recovery
+15% to Fire and Chaos Resistances

**Comment by GZer** [comment]
Fixed, TY!
