### ISSUE TITLE
Poison DPS contribution to total does not correctly account for accuracy

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#131]
While looking at the difference between a Vagan dagger and a normal one on a poison build I noticed an otherwise identical Vagan dagger hardly increases the total DPS over a normal dagger.

Here is the stat differences when evaluating equipping the Vagan dagger:

![image](https://cloud.githubusercontent.com/assets/510805/21758218/11e46294-d5ff-11e6-9701-754e3690d1db.png)

You can see the vagan dagger increases my chance to hit from 77% to 100% and my hit DPS by 29.9% (as expected), but it only increases total DPS by 4.1%. I couldn't figure out exactly what the issue is, the total DPS without the vagan dagger seems too high to be correctly accounting for accuracy but too low to not be accounting for it all.

You can find the export string for the build [here](http://pastebin.com/GcFQWWYn). I named the two daggers "Chaos Dagger" and "Chaos Vagan Dagger".

**Comment by Openarl** [comment]
Indeed. That's easily fixed though; it'll be done for the next update.
