### ISSUE TITLE
Double strike uses both weapon to calculate damage

### ISSUE THREAD

**Issue by zys5945** [Openarl/PathOfBuilding#1313]
From [poe wiki](https://pathofexile.gamepedia.com/Double_Strike) it says

> Dual Wielding: This skill will only attack with the main hand weapon while dual wielding.

Which should mean that only the MH weapon damage is used for calculation, however currently POB uses both MH and OH to calculate damage.

**Comment by Openarl** [comment]
The wiki is out of date; 3.5 removed the concept of main-hand-only skills, so all skills that work with one-handed weapons will use both weapons when dual wielding, which includes Double Strike.
