### ISSUE TITLE
Crit chance calculation does not account for evasion

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#132]
> If an incoming critical strike succeeds its hit roll, a second independent hit roll is performed to determine if the critical is evaded or not. If this roll succeeds, a critical strike is scored. If it fails, the attack still hits, but only for regular damage.

http://pathofexile.gamepedia.com/Evasion

This mechanic doesn't seem to be accounted for. I suppose it should only be accounted for in Effective DPS mode since its necessary to ignore it if you want to produce in-game tooltip DPS-like values.

**Comment by Openarl** [comment]
It's something I plan to fix at some point. The fact that the in-game tooltip doesn't do this is a bit of an pain though; anything that causes the sidebar stats to differ from the in-game tooltip is a potential source of confusion, but I don't really have a choice in this case. So it will indeed be Effective DPS only. I also need to find out how it interacts with the lucky crit chance calculation; I'm sure it'd occur afterwards, but I need to be 100% certain.

**Comment by Openarl** [comment]
This is fixed in the next update.
