### ISSUE TITLE
"Copy Tree" is "Rename Tree"

### ISSUE THREAD

**Issue by SwitchBL8** [Openarl/PathOfBuilding#1328]
Selecting a tree in Manage Trees and pressing the "Copy" button brings up the Rename dialog. Basically, Rename and Copy do the same thing. 

Version 1.4.121.

**Comment by BrennanBarni** [comment]
They do bring up the same dialog, but they don't have the same functionality. Rename changes the name of a build, while Copy asks you what you'd like to name your copy, rather than simply copying it as "yourbuildname(1)". The result is a new copy of the selected build under the designated name.

**Comment by SwitchBL8** [comment]
I did not work like that in version 121. It does work properly now (version 127).
