### ISSUE TITLE
Vaal Blight seemingly not recognized as AoE.

### ISSUE THREAD

**Issue by dck-k** [Openarl/PathOfBuilding#1338]
It has no radius displayed, nor does it show any damage increase for taking inc AoE damage nodes such as blast radius, or being supported by conc effect.

**Comment by qikink** [comment]
With the AoE re-work several patches ago, aoe damage only affects (to paraphrase GGG's words) damage that a monster can "move out of" - like fire trap, caustic arrow DoT, or Vortex. Blight (Vaal or not) is a DoT that will continue to affect the enemy after they leave the zone, and therefore is *not* buffed by increases to area damage.

**Comment by Openarl** [comment]
qikink is correct; Blight does not deal Area Damage over Time, and therefore does not benefit from Area Damage modifiers.

**Comment by Openarl** [comment]
Because I don't know what the radius is. I can check when I get into the office on Monday, though.
