### ISSUE TITLE
[BUG] On import characters list goes up and text is missing if list is too long

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#134]
Can't provide you with exact boundary values. Just faced it when tried to import one of Zizaran's characters.
![list](http://i.imgur.com/AfI3qg7.png)

**Comment by Openarl** [comment]
Yep, that's the dropdown code freaking out when it's unable to fit all the entries on the screen at once. I'll need to add a scrollbar; I'd have done it earlier but I didn't think any of the dropdowns could get enough entries. But then along comes Ziz with 87 characters on his account...

**Comment by Openarl** [comment]
Right, that's fixed in the next update. *Shakes fist at Ziz*
