### ISSUE TITLE
[Bug] Aura in disabled socket group is active when it is selected as main skill

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#1346]
Not sure if this is a bug, but certainly not the behavior I expected.

If you disable the socket group that an aura is in, that disables the aura (its reservations and effects). However, if you select that auras as the main skill in the left pane the aura is then active.

https://pastebin.com/W0cp9eUa

**Comment by Openarl** [comment]
That's intended; selecting a socket group as your main skill will temporarily enable it (otherwise you'd have no main socket group).

**Comment by aggixx** [comment]
Ok, fair enough.
