### ISSUE TITLE
Exception when trying adding affix to a flask

### ISSUE THREAD

**Issue by MatthewClair** [Openarl/PathOfBuilding#1348]
Repo:

1. Create new build
2. Go to Items and click "Craft Item..."
3. Select Flask: Utility and select any base
4. Click Add Modifier
5. Hover over the Source drop down. It will sometimes crash here.
6. Click Source and move down to the Custom option and it will crash

Here is the full error: https://i.imgur.com/HzuUBTx.png

**Comment by Exportforce** [comment]
Seems to the related to #1347

**Comment by Openarl** [comment]
Fixed in the next update.
