### ISSUE TITLE
Deadeye ricochet works incorrectly

### ISSUE THREAD

**Issue by crabovan** [Openarl/PathOfBuilding#1349]
Instead of giving +10% more damage per chain it got calculated with 0 chains in configuration and adding additional chains remove those +10% per chain. (for example, we have spell/attack with +5 chains, initial more damage modifier must be 0%, and getting +10% more damage per each additional chain. Instead, it got +50% more damage without any chains in configuration, and adding more chains reduce added more damage by 10%).

**Comment by Openarl** [comment]
Ricochet states "10% more Damage for each **remaining** Chain", so this is working as intended.
