### ISSUE TITLE
Ice Spear's second form does not take the increased crit chance into account

### ISSUE THREAD

**Issue by Sentenryu** [Openarl/PathOfBuilding#135]
When changing the combobox in both the side panel and the calcs tab to "Second Form" with an Ice Spear setup, only the pierce chance is updated. The crit modifier does appear, but not as "Inc. Crit Chance" and does nothing.  

Here's the first form:  
![image](https://cloud.githubusercontent.com/assets/1932074/21844498/006a44e2-d7d6-11e6-8674-1e32b94cebfd.png)
  
and the second form:  
![image](https://cloud.githubusercontent.com/assets/1932074/21844572/475c9120-d7d6-11e6-86d7-fbaf538b5f68.png)

**Comment by Openarl** [comment]
Oops. The modifier had the wrong type, so it wasn't working correctly. That's fixed in the next update.
