### ISSUE TITLE
Winterweave "Are you affected by chill" removed with new update

### ISSUE THREAD

**Issue by Schmidter** [Openarl/PathOfBuilding#1352]
Still being counted though as On on my old build that had it On. But I can't change it On/Off.   

Another issue. Playing Elementalist with 20% shock effect the very least. The Increased Shock effect nodes and nicreased effect of non-damaging effects are not counted towards DPS either.

**Comment by Exportforce** [comment]
As far as I understand PoB always assumes 50% shock, no matter what if you check the "is the enemy shocked". #1351 that is why I requested this.

**Comment by Openarl** [comment]
This should be fixed now.
