### ISSUE TITLE
Can't open summoner builds using Tukohama's Vanguards since update

### ISSUE THREAD

**Issue by Rising-Soul** [Openarl/PathOfBuilding#1355]
I get these error messages:

https://imgur.com/vEE87qI

To test, I imported a new build without spectres, added a Wicker Man (no problem), then as soon as I added a Tukohama's Vanguard, I get the errors.

(Couldn't get github file uploader to work either, sorry)

**Comment by Openarl** [comment]
Fixed in the next update.
