### ISSUE TITLE
[Unique] Cinderswallow Urn missing mods support

### ISSUE THREAD

**Issue by TechTrooper** [Openarl/PathOfBuilding#1363]
Hello,

Please add support for the new unique Cinderswallow Flask.
`Enemies Ignited by you during Flask Effect take 10% increased Damage`
"Is the enemy Ignited?" configuration enabled should result in enemy "take 10% increased Damage"

![pob](https://user-images.githubusercontent.com/3955313/50654431-7ccf1280-0f95-11e9-99fa-1aa45c698f85.PNG)

**Comment by Dorky106** [comment]
Well really the recover amounts should be added as well.

**Comment by Exportforce** [comment]
> Well really the recover amounts should be added as well.

Those mods are not recovery like "xHP per second" but they are instantly per killed enemy, so there is no way in counting them into regeneration or something.

**Comment by TechTrooper** [comment]
Seems to be implemented now.

![image](https://user-images.githubusercontent.com/3955313/53914940-73caf200-4067-11e9-900f-693b3773533d.png)
