### ISSUE TITLE
Sorting equipment by DPS causes the box to freeze

### ISSUE THREAD

**Issue by Teonlight** [Openarl/PathOfBuilding#1364]
![image](https://user-images.githubusercontent.com/10212447/50657730-f5fe4380-0f5c-11e9-83c9-c72bc3a85a56.png)
![image](https://user-images.githubusercontent.com/10212447/50657747-ff87ab80-0f5c-11e9-98f5-2291283f1391.png)
![image](https://user-images.githubusercontent.com/10212447/50657760-09111380-0f5d-11e9-8a09-8aafc607567b.png)

Sorting unique equipment by DPS causes the box to freeze when selecting Any type, Armour, and Body Armour types. All other types resolve and present the list.

**Comment by woodwa68** [comment]
Same here. Here's my setup for debugging purposes: https://pastebin.com/p9mhQNny

**Comment by mari0ndrew** [comment]
experiencing the same issue after the last update

**Comment by Openarl** [comment]
Fixed in the next update.
