### ISSUE TITLE
Support gems no longer affect the base mana cost of skills

### ISSUE THREAD

**Issue by moxaj** [Openarl/PathOfBuilding#1365]
It seems one of the recent updates (1.4.124?) broke the mana cost calculation - whatever support gems you add to a skill, the displayed mana cost (in both the left panel and the calc panel) isn't updated.

**Comment by stania** [comment]
maybe it doesn't adjust mana reservation when some aura is linked with lv3 enlighten

**Comment by Openarl** [comment]
Fixed in the latest update.
