### ISSUE TITLE
Mousing over Gruthkul's Pelt Causing Error

### ISSUE THREAD

**Issue by Sinxar** [Openarl/PathOfBuilding#1366]
This is occurring when mousing over Gruthkul's Pelt in the "Items" tab.

![image](https://user-images.githubusercontent.com/3210315/50673432-9ed38f80-0fab-11e9-8fc5-63f0c95a7581.png)

may be related to this new one (Sorting equipment by DPS causes the box to freeze) https://github.com/Openarl/PathOfBuilding/issues/1364
I think this may be related because if I try to sort by DPS on body armor it freezes. However some other groups will sort just fine.

**Comment by OursRonchon** [comment]
Same here, and encountering #1364 as well.

**Comment by Openarl** [comment]
Fixed in the next update.
