### ISSUE TITLE
Temp Chains Duration Calc is Wrong

### ISSUE THREAD

**Issue by Retik** [Openarl/PathOfBuilding#137]
Temp Chains duration modifier should (duration/(1-.4)) instead of (duration/.4). Also, the 0.4 needs to account for increased curse effect. So with the max 40% increase on the passive tree, that's 56% slower. So the numbers would be (duration/(1-0.56)).

**Comment by Openarl** [comment]
What you're describing is exactly how it's currently implemented.

With no increased curse effect:
![dur1](https://cloud.githubusercontent.com/assets/19189971/21951807/f1e05d50-da58-11e6-836b-3db071e89622.png)
With 40% increased curse effect:
![dur2](https://cloud.githubusercontent.com/assets/19189971/21951806/f1dd4cf0-da58-11e6-854d-276c92f40cfe.png)
