### ISSUE TITLE
1.4.127 Empower Change?

### ISSUE THREAD

**Issue by Lothrik** [Openarl/PathOfBuilding#1376]
This commit: https://github.com/Openarl/PathOfBuilding/commit/5e3acb48c1ceaac6ed3d8fe991d71c3de2eb5364#diff-a5602aa3f371a6a04da4db4990839284

Nerfed empower from +120% more at level 7 to +90.5%, but the change isn't documented in the patch notes, was this intended? Losing an entire Empower level worth of damage is rather surprising, and if this actually reflects in-game behavior it significantly impacts support gem decisions.

**Comment by Openarl** [comment]
Fixed in the next update.
