### ISSUE TITLE
[BUG] Power Charge on Veiled mods

### ISSUE THREAD

**Issue by Bloodzy** [Openarl/PathOfBuilding#1383]
The new veiled mod: +1 Power Charge is not being factored in for damage calculations. I tried on both amulet and ring and neither are working at the moment.

**Comment by Exportforce** [comment]
The Mod is "minimum charges" meaning if you have that mod, you just always have at least 1 charge per equip with that mod. So if you have charges, you check that in "configuration". You do not get max charges with them.

**Comment by Bloodzy** [comment]
> The Mod is "minimum charges" meaning if you have that mod, you just always have at least 1 charge per equip with that mod. So if you have charges, you check that in "configuration". You do not get max charges with them.

My lord. That is an awful mod then. Thank you for the clarification! Closed
