### ISSUE TITLE
LifeOnHit(Claw)  not calculated as Life Gain Rate.

### ISSUE THREAD

**Issue by lucifering** [Openarl/PathOfBuilding#1397]
"+46 Life gained for each Enemy hit by Attacks"
not calculated as Life Gain Rate.

[https://imgur.com/a/AOMzrd0](https://imgur.com/a/AOMzrd0)

Skill:
`Molten Strike 20/0 `

Item:
Kaom's Sign
and

> Rarity: RARE
New Item
Eye Gouger
Crafted: true
Prefix: None
Prefix: None
Prefix: None
Suffix: None
Suffix: None
Suffix: {range:1}LocalIncreasedAttackSpeed8
Quality: 20
Sockets: G-G-G
LevelReq: 64
Implicits: 1
+46 Life gained for each Enemy hit by Attacks
27% increased Attack Speed

**Comment by Openarl** [comment]
Fixed in the next update.
