### ISSUE TITLE
Poison 'Total More' section not displaying all sources

### ISSUE THREAD

**Issue by Retik** [Openarl/PathOfBuilding#141]
For some reason my 'Total More' for Poison is showing 148% but when I mouse over it, the components only sum up to 110%. I can't tell where the extra 38% is coming from, or if there even is 38% coming from somewhere.

![poisonmoretooltip](https://cloud.githubusercontent.com/assets/4002618/21960945/7c0eb7a4-dab0-11e6-8825-ba2e3a431ba0.PNG)

**Comment by Retik** [comment]
Here's an export of the build.
[http://pastebin.com/eRbTzG2C](http://pastebin.com/eRbTzG2C)

**Comment by Openarl** [comment]
You seem to be misunderstanding how More modifiers are combined. They are multiplied together, not added; so: 
1.12 x 1.59 x 1.39 = 2.475
Which rounds to 2.48, which is 148% more damage.

**Comment by Retik** [comment]
Hmm sorry for being mistaken, I thought more multipliers were added with each other and that number multiplied with all the increased damage values.

**Comment by Openarl** [comment]
All good. Everyone has to learn that at some point!
