### ISSUE TITLE
Level 20 Barrage has wrong damage multiplier

### ISSUE THREAD

**Issue by melink14** [Openarl/PathOfBuilding#1416]
In POB, level 20 barrage has damage multiplier of 48% but in game and on wiki it is listed as 47.6%.

This is important because POE rounds down so it's means the damage at level 20 barrage is wrong. It also means that POB shows leveling Barrage to 21 has no effect even though that's when Barrage's damage multiplier should hit 48%.

Thanks!

**Comment by Openarl** [comment]
Actually, it is also 47.6% in PoB, but it is currently rounded to 48% when displayed in the gem tooltip; I'll fix the inconsistency in the next update.

**Comment by melink14** [comment]
Hmm, in that case, I'm surprised because POB shows no DPS change when leveling the gem to 21 even though it should be effective 1% increase in damage multiplier as far as I can tell.

Glad to hear about tooltip!

**Comment by Openarl** [comment]
I tried changing the gem level in a simple Barrage setup and did see a DPS change from 20 to 21; what is your build?

**Comment by melink14** [comment]
https://pastebin.com/jZcq7w1B barrage six link.

I thought it was the rounding issue since DPS changes from 19 -> 20 and then 22 -> 23.

Though perhaps something about the build is making damage multiplier not do anything and change is just from damage effectiveness?

**Comment by Openarl** [comment]
The change is indeed from damage effectiveness alone, and that's working as intended; you don't actually have any damage on your weapon for the base damage multiplier to apply to.

**Comment by melink14** [comment]
Right, I was thinking it was just no physical damage but was misreading. Thanks for point it out. Super useful as always.
