### ISSUE TITLE
Attack mods with #-# range are a bit incorrect

### ISSUE THREAD

**Issue by master2080** [Openarl/PathOfBuilding#142]
What I mean is there is no way to make a 6-10 physical damage to attacks into a 4-10 or a 6-15.
It's a minor inconvenience, but makes it harder to do some stuff.

**Comment by Openarl** [comment]
That's a side effect of the way mod ranges are handled, since both min and max are scaled together. I wouldn't have thought it'd ever be a problem though; what exactly is made harder by this?

**Comment by master2080** [comment]
Just copying items from, say, poe.trade to the program with the exact values.
But it's a minor issue, nothing really important or big(I just edit the values to what I need)

**Comment by Openarl** [comment]
Ah. Well, I find that importing from poe.trade is much easier if you use the "Create custom..." option; you can copy the item stats line by line, or you can copy the whole block and reformat it like this:
![import poe trade](https://cloud.githubusercontent.com/assets/19189971/22006701/06f9b8aa-dcb9-11e6-88bb-4e30cef9cbf0.png)
