### ISSUE TITLE
How to debug POB?

### ISSUE THREAD

**Issue by lurumdare** [Openarl/PathOfBuilding#1420]
Hi!

How debug this tool on VS, Jetbrains IDEA (lua plugin) etc ?

**Comment by jaspergould** [comment]
Solved.

Intellij IDEA + EmmyLua [screen](https://image.prntscr.com/image/1jR2ewdJS0SkkEXfRVDN2A.png)

**Comment by thomassjogren** [comment]
@jaspergould Please close the issue if it is resolved. Helps keep maintainers somewhat sane. 😄

**Comment by jaspergould** [comment]
@thomassjogren im need another method for debug
