### ISSUE TITLE
Missing "increased" damage on sheet but included in calculations?

### ISSUE THREAD

**Issue by shrewdlogarithm** [Openarl/PathOfBuilding#1422]
I've attached a pic of a Gladiator build I was looking at recently

![onehandmissing](https://user-images.githubusercontent.com/40507378/52922102-2421c200-3316-11e9-9332-608e887947d6.jpg)

It shows the MH/OH "increased" damage as 450% but in the calculation, the multiplier is 5.82 (582%) 

This confused me for a while - eventually I found the "missing" damage and it seems it's "weapon specific" tree nodes!?

e.g. on this character there is an Ascendancy "One Handed Speed and Damage" which adds 15% increased damage when using One-Handers - that's included in the 582% but not the 450% 

Not actually sure this is a bug or if I'm not looking in the right place for that damage???

Thx

**Comment by lucifering** [comment]
all types:32%.

(1+450%+32%)=5.82

**Comment by shrewdlogarithm** [comment]
Aha - I must be blind - thanks for the quick reply

Next time I'll look harder before spending an hour stripping the character down to bits ;0
