### ISSUE TITLE
Inevitable Judgement calculation

### ISSUE THREAD

**Issue by myrahz** [Openarl/PathOfBuilding#143]
First I would like to say thanks to you for this amazing tool. I had plans to develop something similiar but I never found the strength to do it. I was doing basically the same thing by using a Spreadsheet, it took me a while to understand how the game rounds certain stuff in order to be 100% accurate. I have a couple of suggestions that I will post in here.

**The issue:**
It is probably a known Issue but I couldn't find it anywhere.

Inevitable Judgement is not being correctly calculated, both crit and non-crit bonuses.

**Comment by Openarl** [comment]
I haven't had time to add support for Inevitable Judgement yet. It's a fairly high priority but there's a fair bit of work involved due to the number of changes I'll have to make to the calculation code.

**Comment by Openarl** [comment]
The next update will add complete support for Inevitable Judgement.
