### ISSUE TITLE
[Bug] Error when trying to add a custom mod to abyss jewels

### ISSUE THREAD

**Issue by TheJustikar** [Openarl/PathOfBuilding#1432]
Error message when trying to add a custom mod to an abyss (ghastly) jewel. Specificly when trying to click into the text box to type in the mod.

![image](https://user-images.githubusercontent.com/20945299/53740650-f485c480-3e94-11e9-82c3-0984f97e6e42.png)

**Comment by Openarl** [comment]
Fixed in the next update.
