### ISSUE TITLE
[Bug] Swapping a bow acts as if you replaced the quiver too

### ISSUE THREAD

**Issue by joris-s-k** [Openarl/PathOfBuilding#1447]
The new feature where two handed weapons calculate your resulting stats for replacing both weapons also applies to bows and quivers. As a result you can get situations like this:

The quiver
![grafik](https://user-images.githubusercontent.com/19972862/53921526-0b810e00-4071-11e9-8118-0b36df43c9cb.png)

Swapping in an identical bow
![grafik](https://user-images.githubusercontent.com/19972862/53921566-29e70980-4071-11e9-8e8f-4e19dd53c83b.png)

**Comment by McFrugal** [comment]
This happens for one-handed weapons and shields as well.

**Comment by SparkusK** [comment]
Can confirm it's happening for me too, with a wand and shield.

**Comment by romanalexander** [comment]
Seems like quick compare specifically is broken. Has the same issue with dual wielding wands.

**Comment by Openarl** [comment]
Fixed in the next update.
