### ISSUE TITLE
unsupported file type?

### ISSUE THREAD

**Issue by Rypteq** [Openarl/PathOfBuilding#1455]
i downloaded the new POB, and it keeps giving me all these warnings about being unable to support PNG photos, any reason why im getting this error?
![screenshot_34](https://user-images.githubusercontent.com/48307120/53933282-98c16400-406b-11e9-993f-22c09c55a90d.png)

**Comment by TanMitties** [comment]
I'm having the same issue, looking for an answer.

**Comment by Rypteq** [comment]
I downloaded the .exe version and installed it instead of downloading the zip file and it worked fine
