### ISSUE TITLE
[1.4.131] Lethal assault / resourcefulness wrong

### ISSUE THREAD

**Issue by Xetaxheb** [Openarl/PathOfBuilding#1461]
POB: https://gyazo.com/689270bc75df28365da300e8b246980b

In-game: https://gyazo.com/a0f39ef5dd90bcfb0cfab6b764f2f9ae

**Comment by Openarl** [comment]
That area of the passive tree changed after I updated the tree in PoB; the next update will contain the latest version of the tree.
