### ISSUE TITLE
Wand calculations wrong

### ISSUE THREAD

**Issue by DonTheGreatOne** [Openarl/PathOfBuilding#1466]
When I compare wands on the following build the comparison numbers are always the same no matter what wands I am comparing.
https://pastebin.com/baUEZ2u7

**Comment by Openarl** [comment]
Fixed in the next update.

**Comment by DonTheGreatOne** [comment]
Thanks
-- 
Don Hart
Hart Woodcrafts
Hand Crafted Pens, Pencils, Key Chains and Kaleidoscopes.
http://www.hartwoodcrafts.com
