### ISSUE TITLE
Wrong weapon craft comparation

### ISSUE THREAD

**Issue by EiGHD** [Openarl/PathOfBuilding#1470]
If I craft a Scepter and compare with which weapon I'm using doesn't matter the values, even same stats or same weapon will show less damage. I don't know if it is happening for other weapons aswell.

**Comment by SparkusK** [comment]
Same is happening here. I suspect it's related to issue 1447 (https://github.com/Openarl/PathOfBuilding/issues/1447)

I think PoB is trying to compare the values between your current weapon set (including both weapon and shield), and the weapon set that only includes the weapon.

Apparently there's been an update that added some weird comparison functionality between two-handers and one-handers, but I suspect it's broken normal comparisons in the meantime.

Pure speculation though. I'd love to have it fixed nonetheless

**Comment by Openarl** [comment]
Fixed in the next update.
