### ISSUE TITLE
[Bug] Bane damange calculation <PATCHED>

### ISSUE THREAD

**Issue by Ydoum** [Openarl/PathOfBuilding#1472]
Correct me if I'm wrong please, I am no genius. Bane deals 47% more DoT damage per applied linked curse at lvl 20.

Let's say I have the following setup for Bane:
Bane-Enfeeble-Temporal Chains-Despair - PoB shows 61k DoT DPS

Now Let's say I add in Vixen's Entrapment gloves (curses applied when bane is used) and the following setup:
Bane-Efficacy-Controlled Destruction-Void Manipulation - PoB shows 75k DoT DPS

How is this calculated? The linked gems in this setup do not and simply can't exceed the 47% more damage per applied linked curse from Bane.

Could you please explain or take a look into it?

**Comment by Ydoum** [comment]
Just did some testing on packs of the same mob types.

Bane definitely deals more damage when linked with curses, so PoB needs an update to remedy this bug.

**Comment by Exportforce** [comment]
The Skill description clearly states that the bonus damage is only being calculatedfor curses applied by bane itself.

**Comment by Ydoum** [comment]
@Exportforce indeed, and with this in mind the total damage calculation for Bane should be higher when curse gems are linked with it, than with non-curse gems (as per my example). PoB currently shows it the other way around.

**Comment by Ydoum** [comment]
Daamge calcualtions: 44% more from controlled destruction, 44% more from efficacy, 39% more from void manipulation.
Total: 127% more chaos damage
+ despair applied via gloves

Bane with curses: 47% more from X curse, 47% more from Y curse, 47% more from Z curse
Total: 141% more chaos damage
+ despair added automatically via Bane


And somehow the former setup with non-curse gems appears to deal more damage as per PoB info, but testing I have done shows that the latter is more effective and deals much higher DoT.

**Comment by BrokenRose** [comment]
Have you accounted for the Despair damage multiplier? Because when you cast Bane with Controlled Destruction, Efficacy, and Void Manipulation, you still apply the Despair curse, which is a huge damage boost in and of itself.

**Comment by Ydoum** [comment]
It's not really "me" accounting for the despair damage multi. Despair is automatically applied via Bane - that's what Bane does. The curse applies the multiplier just as if the curse was self-cast or cast from the unique gloves.

As I said, I have done some actual in-game testing and Bane with linked curses = higher DoT (PoB says it deals much less damage with this setup).

**Comment by Ydoum** [comment]
SOLVED with the most recent patch. Good job!
