### ISSUE TITLE
Importing fractured items excludes fractured mods

### ISSUE THREAD

**Issue by melink14** [Openarl/PathOfBuilding#1475]
All other mods import correctly but the fractured mods are simply missing after import.

**Comment by melink14** [comment]
1.4.133 claimed that synthesis items could be imported but after update I still see fractured mods not included when I import.

**Comment by melink14** [comment]
Ah it looks like the patch was only for Synthesized items not synthesis items generically.

**Comment by Openarl** [comment]
Fixed in the next update.
