### ISSUE TITLE
Essence of Delirium Decay dps not scaling with spelldmg when linked to Soulrend or Essence drain

### ISSUE THREAD

**Issue by Ogrinn** [Openarl/PathOfBuilding#1483]
Decay should be scaling with spell damage when applied with soulrend or essence drain which allows spell damage modifiers to apply to their damage over time.

**Comment by Openarl** [comment]
That is incorrect; "Modifiers to Spell Damage apply to this Skill's Damage Over Time effect" only applies to DoTs that are part of the actual skill, not to any other DoTs that it applies, such as Decay and Ailments.
