### ISSUE TITLE
My friend has 2x the dot damage with same skill tree and items.

### ISSUE THREAD

**Issue by m2tuu** [Openarl/PathOfBuilding#1489]
I copied my friend items and skill tree is pretty much the same he has over 700k dot i have 300k dot with items i copied from him on pob... how is it possible ? Same skilltree and same items but more than 2x less dot dps.

**Comment by Wires77** [comment]
Did you make the same checkmarks in the configuration?  You should probably just copy his PoB link and make the changes you need from there.

**Comment by m2tuu** [comment]
both of the pobs are open on my computer with same configurations , pretty much same skilltree with small changes:/ copied his items and nah he has 2x more dmg than i do

**Comment by m2tuu** [comment]
both of the pobs are open on my computer with same configurations , pretty
much same skilltree with small changes:/ copied his items and nah he has 2x
more dmg than i do

**Comment by niuage** [comment]
99.9% chance this is a user error. There's an option you forgot to check/select or something.

Are both PoBs set to be against guardians/shaper for instance?

As Wires77 suggested, just start from his, and then make the changes you want.

**Comment by m2tuu** [comment]
No i did not activate anything nor did i change any configs
before i tried that

**Comment by niuage** [comment]
Ok, what about you just share both PoBs and we can try to look at what's different?

**Comment by m2tuu** [comment]
https://pastebin.com/DHhqP0jL mine without his items.. and his https://pastebin.com/yeWmwz01

**Comment by niuage** [comment]
First thing I noticed is that he has Vaal righteous fire enabled. Removing that already takes it down to 496k. I could keep looking, but you can see that there are definitely sizeable differences ;)

Why not start from his PoB and change a couple points and pieces?

**Comment by m2tuu** [comment]
Hmm, thx mate i did not notice that :D its not still the same but i can see now where the difference comes, u have no idea how long ive searched for an answer:D

**Comment by niuage** [comment]
You're welcome. You can close the issue if you're satisfied.
