### ISSUE TITLE
adjusting vaal righteous fire gem level does not reflect in righteous fire damage

### ISSUE THREAD

**Issue by Shrunn** [Openarl/PathOfBuilding#1492]
When the righteous fire skill is obtained via a vaal righteous fire gem, the righteous fire damage calculation is fixed and does not change when you adjust the level of the VRF gem. The VRF damage does change when the gem level is changed.

**Comment by Openarl** [comment]
That is working as intended. Righteous Fire's damage does not change as it levels up; only the Spell Damage bonus does (and that doesn't affect RF's Damage over Time).

**Comment by Shrunn** [comment]
You are of course correct, but I got confused because the damage of VRF changes as I change the gem level. In addition, I can see now that the calculated damage of VRF can't be right, as it is 5 times as much as RF, should only be about a third higher I think.  Maybe should be a separate issue,
