### ISSUE TITLE
New mods for watcher's eye is missing

### ISSUE THREAD

**Issue by Hapseleg** [Openarl/PathOfBuilding#1493]
Hi there, the new mods on watcher's eye for Malevolence and Zealotry are missing (it works if you do it manually for those I have tried)

Malevolence 
- (20–30)% increased Skill Effect Duration while affected by Malevolence
- +(18–22)% to Non-Ailment Chaos Damage over Time Multiplier while affected by Malevolence
- +(18–22)% to Cold Damage over Time Multiplier while affected by Malevolence
- (15–20)% increased Recovery rate of Life and Energy Shield while affected by Malevolence
- Unaffected by Poison while affected by Malevolence
- Unaffected by Bleeding while affected by Malevolence
- Damaging Ailments you inflict deal Damage (10–15)% faster while affected by Malevolence

Zealotry 
- Critical Strikes Penetrate (8–10)% of Enemy Elemental Resistances while affected by Zealotry
- (10–15)% increased Cast Speed while affected by Zealotry
- Effects of Consecrated Ground you create while affected by Zealotry Linger for 2 seconds
- Consecrated Ground you create while affected by Zealotry causes enemies to take (8–10)% increased Damage
- Gain Arcane Surge for 4 seconds when you create Consecrated Ground while affected by Zealotry
- 180% increased Maximum total Recovery per second from Energy Shield Leech while affected by Zealotry
- (100–120)% increased Critical Strike Chance against Enemies on Consecrated Ground while affected by Zealotry

**Comment by Wires77** [comment]
It's not just these auras unfortunately. #935 is a PR for all of the missing mods.  I can probably add these to that branch

**Comment by Hapseleg** [comment]
Ah, I see, I will close this issue then.
