### ISSUE TITLE
storm brand cast and hit rate

### ISSUE THREAD

**Issue by sadicutz** [Openarl/PathOfBuilding#1500]
Hi,

Build : Storm brand 

I`m not sure if this is an issue or it`s supposed to be this way, however
According to POB, when I assign a "faster casting" passive node to the hero, the followings are increased
Cast rate ( correct )
Hit rate ( why is this correct ? )
This affects the damage by a lot, increasing my damage in POB a lot, which is not correct?

In game however, assigning a faster casting node, does affect only the casting time, NOT the hit rate or better said the activation time, which should be equal to the hit rate per second.

Looking forward for your reply on this.
Thanks

**Comment by Openarl** [comment]
That is working as intended; as stated on the Storm Brand gem: "Increases and Reductions to Cast Speed also apply to this Skill's Activation frequency".

**Comment by sadicutz** [comment]
So there is a bug in the game? 
The increases in faster casting do not affect the activation frequency.
Just to be sure, is this correct?

**Comment by sadicutz** [comment]
Thanks, clarified that, was assigning to few cast speed, and didn`t see any different in game.
Thanks for the quick reply :)
