### ISSUE TITLE
[Feature Request] Consecrated Ground + Zealot's Oath

### ISSUE THREAD

**Issue by DarKWinGTM** [Openarl/PathOfBuilding#151]
[Feature Request] Consecrated Ground + Zealot's Oath

- Not show and calculate 4% HP/ES[Zealot's Oath] Regenerate 

http://pathofexile.gamepedia.com/Zealot%27s_Oath
http://pathofexile.gamepedia.com/Ground_effect#ConsecratedGround

**Comment by Openarl** [comment]
Easily done. It'll be in the next update. Not sure why I didn't add that when I added support for "while on Concecrated Ground" modifiers...
