### ISSUE TITLE
[1.4.135] Despair Curse doesn't affect Chaos dmg

### ISSUE THREAD

**Issue by TechTrooper** [Openarl/PathOfBuilding#1513]
Curse effects seem to be completely ignored. 
Comparing e.g. Soulrend & Essence Drain DPS. Adding Despair curse to PoB doesn't change DPS in any way.

I've tried standalone despair, with blasphemy, with Bane and Witchfire Brew potion.

AFAIK these should affect Soulrend DPS:
Cursed enemies have -(20-29)% to Chaos Resistance
Cursed enemies take (15-25)% increased Damage from Damage Over Time effects

**Comment by TechTrooper** [comment]
nvm. toggling gems used with attack spells seemed to have fixed the calculation issue.

**Comment by Ruddplays** [comment]
Im having the same issue and I didnt understand your solution

**Comment by MalteMagnussen** [comment]
> nvm. toggling gems used with attack spells seemed to have fixed the calculation issue.

Elaborate. How did you fix the issue?

**Comment by TechTrooper** [comment]
> 
> 
> Im having the same issue and I didnt understand your solution

This was almost 9 months ago, so I can't remember specifics, but I'd guess I turned Soulrend support gems off/on. 

If you feel like you encountered similar bug, then maybe open a new issue.
