### ISSUE TITLE
[Feature Request] Ground Effect + Steppan Eard Sorcerer Boots

### ISSUE THREAD

**Issue by DarKWinGTM** [Openarl/PathOfBuilding#152]
[Feature Request] Ground Effect + Steppan Eard Sorcerer Boots

- Not calculate "Steppan Eard Sorcerer Boots effect" on Ground Effect

http://pathofexile.gamepedia.com/index.php?title=Consecrated_ground&redirect=no
http://pathofexile.gamepedia.com/Steppan_Eard

**Comment by Openarl** [comment]
I've added these for the next update.

I was hesitant about adding 3 options to the Configuration tab that would only work for this one item, but I've made a change now that prevents such options from showing up if they won't have any effect.
