### ISSUE TITLE
Import support for console accounts 

### ISSUE THREAD

**Issue by FilixDark** [Openarl/PathOfBuilding#1526]
Hi,

since ggg finalized the console connection to their website, we are now finally able to browse our characters. But the url is different for PSN/XBOX accounts.

Looks like this for PSN:

https://www.pathofexile.com/account/sony/view-profile/Filix80/characters.

Maybe you could add an option to insert the url instead of just the account name for the import. So it should work (if the api is the same) for all linked accounts.

The console communities, would be really happy, if this would work. The tool is awesome and we could really use this feature.

Cheers

**Comment by Openarl** [comment]
I will be releasing an update shortly with import functionality for consoles.
