### ISSUE TITLE
Patch 1.4.136 dps dropped from 7mil to 4,6mil...

### ISSUE THREAD

**Issue by SwedishGT40** [Openarl/PathOfBuilding#1532]
My listed dps on wave of conviction on a CwC chain just balldropped with latest patch.
Can anyone explain what happened??

Pastebin for reference
https://pastebin.com/MGrbZy6P

**Comment by SwedishGT40** [comment]
Oh, castspeed for wave is now 2.4ish insted of the locked 2.86 as it should be for a lvl 20 cwc.
Something is wrong here with cwc, i think it is missing in the calcs

**Comment by jRam84** [comment]
Something is definitely wrong with Cast While Channeling. The CwC Winter Orb/Ice Spear build I'm using also went down after the patch.

**Comment by Openarl** [comment]
Sorry about that; it'll be fixed in the next update (which I'll be putting out once I get home).
