### ISSUE TITLE
Shouldn't Vaal Discipline Have Discipline Enabled By Default?

### ISSUE THREAD

**Issue by dsnvwlmnt** [Openarl/PathOfBuilding#1536]
Fresh import, other aura is on by default but not Discipline.

![image](https://user-images.githubusercontent.com/14173022/56390883-fc4dbe00-61e1-11e9-9d77-b7b85276eb50.png)

**Comment by dsnvwlmnt** [comment]
lol was about to create this issue, forgot I already posted about it.

**Comment by arne-z** [comment]
This behavior is consistent with all other auras and skills that have a Vaal Version. E.g. adding Vaal Righteous Fire to your build will enable Vaal RF but not RF. If you want to have both enabled you can do that with one click.

I do not believe this needs changing.

**Comment by dsnvwlmnt** [comment]
Hmm well that makes sense for most Vaal skills, but certainly not for Vaal Discipline. No one uses Vaal Discipline and not Discipline.

In any case, given there are a whopping 526 issues, it seems this program doesn't have enough developers for the amount of work required, so I don't imagine minor stuff like this will ever be dealt with.
