### ISSUE TITLE
[Bug] Point Blank more not accounted for

### ISSUE THREAD

**Issue by Sairony** [Openarl/PathOfBuilding#154]
Doesn't seem to work for neither the keystone nor the gem. Using Barrage, Slower Proj, Pierce, Faster Attacks, Physical Projectile Attack Damage & Point Blank in a link & have Enemy is at Close Range  checked in configuration.

**Comment by Sairony** [comment]
Physical Projectile Attack Damage more modifier isn't accounted for either it seems.

**Comment by Openarl** [comment]
Duplicates #73 
It's not a bug as such, but a lack of support for that keystone.
