### ISSUE TITLE
"Added Cold Damage" is called "Ice Bite" in the "Calcs" window.

### ISSUE THREAD

**Issue by Hillgrove** [Openarl/PathOfBuilding#1549]
The skill gem "Added Cold Damage" is erroneously called "Ice Bite" in the "Calcs" / "Cold: Added Min/Max" window.

Should be easy enough to see for one self by adding a skill and support it with both "Added Cold Damage" and "Ice Bite". 2 x "Ice Bite" is showing.

**Comment by Bradders1504** [comment]
Hi, I am unable to replicate in 1.4.137.

**Comment by Hillgrove** [comment]
That is odd... and I can't replicate it again now.. I guess it must have been a ghost in the machine or something :)
