### ISSUE TITLE
Wrong Resistance Calculation

### ISSUE THREAD

**Issue by hochl** [Openarl/PathOfBuilding#1550]
My current char has the following resists in-game:

123
109
82

all capped to 75%. POB says the resists are:

75 + 33 = 108
75 + 19 = 94
67 + 0 = 67

Not sure what is going on, until now POB has not miscalculated those. I'm running version 1.4.137 of POB:

Character export:

eNrdXGtz2ziW_dz6FSxXzdZMeW0TIAiCWWem_I6m7diRnKQ7W1tdIAhKbFOkQlJ2lKn573MBihIpkTLldmZrt7vKkch78Ti4j3NBUMd_-zaJjEeZZmESv91Dh-aeIWOR-GE8erv38f7ygO397a-94zuej2-D01kYqTt_7f10rD8bkXyU0ds9B-8ZOU9HMv9UNmX9Bk15PPbD_H2STjhIvU9iWV6rf7uRqQgjmWXlZRHxLHvPJ_Lt3r2cTCOe7hk8EzL2z1Z3-vHXWZiFeQI3JzyMh4l4kPlVmsym0P-e8RjKp5vEV5I3d7eD-7K3s3Qmy-HAVH46vov4XKbDnOdGBn_e7p0AInwk34U5tMKjGTRBLdc6dC0bY3vvaKvWOZ_A310Uh1Mp_aUCPmR_WBBGXpclhyZtE75L5UUQSJGHj_IsBXzGPBarCVjssHXkLxC_mUV5OI1Cma5UDpm7ZSZrHSDTbBO-T3Iend8NVxDZru0eWo5jIsverpWs1rq1_c9hPr5LwiyJd-7khsf8LMlWnZDWXob5ChrEWsUG8mtN0mpd4HP5rYIe3dJgVRKcukWwH6-mYWG0pb2qJG5ft-swqBiQYzpbHEC8UdL9WKymZONtDX-MU5nJ9LHiDdu6qKvcQWSSlUmg7ZMYyJGMV92gQ9um2-SvpRTjK4hdA57L5-1PGVFlKAhvxUlJV3HCbFu7DTBh2-qmsY4S3uoGayDRQ7JNekeILmKZjubDcSijSvSz3a1IVZVqiNlduqnPp9PIdp3UI1dZdYWZvd1DFvLVqbTblIykBAVfrsVZ9noad2nyu8ov0W5qJ-kkmaXPT0HPuRDuNOW78TwLBcR8nakH0p_B2JIuS1imyZvkUU7A4nWSBY6xcsrD9nh4GgFBWU9m20hBFDWptI7uJM-5eDhP_JHsqqI72UnjMkwBsSysZDKnPd8nyjs6Cl-Ho3EeA71c06Cttg5jTrI16QPaYei3wNTO-HTlT9bzM1jXQW7Hiawrmh2m01nnLnkCybHi3tlu0jd8lepbp3-Zyvj7vHP7NfFOHVzE_ixVlte5j3WNzW6Oj3Rxoj71J9MkzQ2oGfITIZJZnL_j2fjtnmdxRCnmlDi-yxjjHrNslwtGseNgizk-RViYEEuU6kDyaALonRVfVcdc5DIt2hII2L3PKPU5srgNLZmME4YtgRwubM90TdVYYS7HZzwSmZ5ZP57OciPWpcwkzMRv3iwIVL2yBzNNdQF2cXl5cXbf_3SxAKOqkj2EUfRbPJt4ikkX_66AHkod0gyRRBGfZtJ_uxfwKIO2Q_g4VLpDCOMi7yQPJHxR1XSRVlS60yh0hdJFUtUNXQe6CGSdYbifT6Uyr6yTymnUdcxFndBJtD-Kw7wjtlLweSfJJcXoJH0DBlhkt244QK5JQ2-Wy27imuB3GodiuF0Eazyv04gLMtGp7QXd6iK7SD-d1k670D1_kN3X5FwGEsw5WwS2Mnoca9PNDF8GHOrpKzn5MONRmM_f7sVhtFe5fl3s0OirGcRCuJSdzqF8fbuXp7PFBohuTe-hnGh6o7_rviDPqaDnqTbU1hD3IjVKrWpkUaKKYsmnMAe0t96A0lXN_3QMnZZbRcgpm7mKEo9HqGxsJCd9NWmZc5_n_Kifw0iP1HCPdGvw6XPK83FdHS8R-1oCYMLAlIJqraaxHLcKoIozlvePXnWU72TKI_82uB_PYl_F5h3G26LbMPJC0kgCo5QtTKoYxv-lVQXSIL9DurubaVx2QKtRswGrUs4oBF8XqHcymsj8x8M0zJN0cgrMx98Jo7ME-FKYD8ORigCtEOnWjaL5V3KH2XRaxJtL4EyKziqWvsPIFw1sajetsBYylBSs86vP4MT3pb-k9eUG7-5z2dZOw6y0uLGUN6oc7BVnByaSp5CBpH8ugXmWxfDu09vaUMP8VvJGVeGHBDL87whkSZafJhNvxyC2ptUYwEDG0EKvvfinUNFMx3Iyf8mCbyg3jH0l82MSlDF8UoXyj17c8_AxjKV6GCV3jGONmg1AFXJGP319Dx_OJpMkvhqDFd3GP8O4XrLYrY00pRMta9xBLZbzbGLAZ63x2hO7iPQ2HI_uII5AjQF07oWxa3tLDVNcKhh1jR8Tvf5NVl7yz76QL-KtFb2tnLUvXt_IL-GfMHhRHFtTbYrAC4mGQdOXwz2Qv88eQVkZzn0C93cafKt2w_irskYh_LqGCiN-VNt3P9pCl2zoXu1l3qfKK3bArF29AbQV8xpOw1QaWvyVLGBptqrRk9i_gdj_cmLZ2kjDrJSsATzfUNJbOCX9f8cpX3F-_VikkmfSP4F_boNi6-wl89vaUMP8lvKGUlCxdKHyuu58mvhzo3z-9qN9Wm3vqudxkOweYpllO-F4kmU8y8I4u-Hpw7ZiaiH3H5BQs__KDC3-vwwa_gPFRgQzO-fZbvthG1pNqU7JGFpo02vsP5LsYIkjvcWw2wrrvYtCe1udoRo2FmKbAyd_qP5PBY_lcJa-sOzfVG8yUC1lFGKvuyWpN4GULcIId989WlNsDrorsdf2qSTvSiv-ABMrCpZlwr9KIkWnNA6QJiGDLLvtCl9FbTXXimU09fdcPbUiJJsDLIUqG0yF0Cv7whWknVymi2N8cnW0I3uJazzfWgMaCyWj1DKqaq_rOedSJPPdqfmmWlPBr4SqZPwV-YmGZvdxLxrY1G4Y_hJ9LZi1-X0G2VCoM7gg9MZ5MwC2aXwKM_mfxjCMHoyWuuGHlB0tgP44L7-IhdoBUfsE6pmOvEr5o3x28-RzkuoiOR9LQ2us-XlfzAFF8G9VlYQbzG_xST8mvE-lNHiBi24bLR74wZcCn4-Da_3hp3GeT7M3R0dPT0-HU56Pk0B-A4c6FMnkaKqY06M80MM4yKHRoxP47_Tk4-nJ6emvo99u-u7f3f7j7fTrB9o_Ye8_ZWfuOfL638ypOJ08PT1Mok-_XI37N1l8fk5mX-6e3pH4HvFfv16wm_vT6_ds9Fvsf_o4u3n_lQzT9Obyw0M0mD_-_RuXX9yb_OrTdRR___23NHU_fvYD9mUSR7fvr34PzyZPP3--jcb51S-_DtJHRvH1Be4_DsYksuYXQzQ___6r-3D58eIUvR-Ky_4gCpPrkDwFJw90NpmdhunF98CMn-Lr797l-cPIm58I-eHLF_6z-eldzNPHftD3R-7j7-PzvmnfzqMvB4-zh7l4q8E7KtE7Ls6eZwWUi29GnPhSmYHjUrCXMC8cd3GyZVPMwg61OshhRhy7ixxFLu3SL6UW6SJHCOs0PuSyLu0RyhjuIEcRQW4HOZsg7HSZB6Kd5mHbyO2yboQ5lHVaDwd3WTfLclmX-VJsdRkeNR2rW7fUQl2mi3AnM6WIdTIrTNyGbiGKrVwKvhQB6_hIRTT14T0kHX3vv61D-j9G5fmlsXovxDgwTiVEyhjIwmUaytiP5nBtOLw8upZ8NAO2nfM0h3ykQjHcOYGEpXYQIGD3tgXEIElnkyP1gslBPgY24h9hC9yNEjXEcmg6-n4CGSOTPBXjYZ6qPPY9SSa_qvzuHmKGbYYdYqukMU6e3gGvueHTZbpRoosDHGYhoU4qnYdQ8af6WEiZPJTgL2_3DixoFIYBCwQ2uTiheKwJwiILqM9Dmes0NcvkEChI7BebzPpy0XFx2AxE9TkUxIpcOuCQbeZvjMHJ4KJ3rmZtDPik9zNPZ6ExFHIKiaGntfSY3xi201scS3ljYLO3WFBo4OC0p0UG8itI0V5_Mo1CEap7qIfpn4xwucux2mYvdqp6Nq7eXn842jvx_cywjDwxqLl5F7GqcnFg1tDn0Hr_ECkPcun_8x9gRCP5xjy0_6kb-zM-oH9RDf7ZsQ4c5y8brap7-iBtpg33JvEHqgVDtwMrd2gX53nKk6-asa1BbNUh_vi-_-HjRe9GGS-wgXLP4ipM_Uj2wEwe52DZUd77GIdfwYz754CwDHwqmG9Jh9EACxE4CLvUx0xiYbqEUE5cR0hm2dS3sOmblmdSUyLLRb4Da1VdOsuurBCrL9C-hfSUYbnjUT7u7WO79l2jpi8h2yjPWlewKmDPesisLsaEfwsnMxhAGMjePnL-pETV8VujOGKlTvX1sF1VuYx49qAVVN0PRDCdA-i5bAO5wYwv-Agc_5SnXu8iHimy5RufIYhUgUWeHZh2YNnEJg6TlJnCcsHbAzPwTOJZQgZMIFMwxERAfNuVgKklqMWJGXDk14AlZOUTFZc4PTg1qk5BzDWnqFm9trZmm67d0iuBHIUkdgswq3eIumGzbQa9j5FeiIIIG-VOnVrs8EEaq5e5Vv6DyFYHbV4b3LQ2aid3OjfuJH8ApCK4lxlnYSoiWTN8JMDKvQDoBJEmJGMP2YxQF5mW9LGHuGljwqQnA9ODnIQRIx5ckbbnuDZQEFaPWW5zzIIFUv9X45ZbXSIToAKMlXkLMUu5mENwVIdRevs2Vpfr9o1dDas6kl61732LNNr9ElxS85niEKRRnIJsQdZqQFYfezPUSdm8dwvhdcPkHQwmbUnbIgiAc0yKmekCWo7LmTClkB62aeBYFMFlz7UggAaCYWY7gUVN7NUgpWYnk7etNZNvt2vL2W7yGnAXbRrfvsKvCXeVdBpw38dFeBlBeQk9Qdo3JBdjBfxkbozD3PDmy3i2XKSVczl0e7ZoWjBSX7Cbk6v-We_dbDJRbQCQaf69zLaqSnzHHxNRXTuLS5_bvots7tqWRK7gLvOQJ7BnYl96xHYgZlHmEoYczB3TdxAn0rUczyEQuGprh1Hb2tV8Adlra2duzeFFXNJJenONlGusdNcjTnG8W6_EVhTtOorvbwc3J9fAWsIgf0oSaDeaeVXUGHIxQIEdXyIBwd5lSAGCkJQW87CQtgoyHofwTzhYeGAjDzHPodxkJnhEPXs2gjY4uDoY1HFSKTBV7x8Vzgw2NcxnsXEPnBLYXqtP0yYTOZ15XqQfVgJCeRiE0KY6Tr1Ik8pUgF7W5mwSi_o2phwYA8VQnVgmUANuQaRkMPHAkZZrOjTwCfWFoODtjAlbBpaPsED1wElrllJxa7MeJu3KlE8m6pWMMnkDCUNWLcHXs7rShFksL_KpyjyK7ytvzaM5dDSZxTAC7eLq0KfUDzrPxmojyp-plyoWaEj90Kw3kBO1f7QpnMSKHrfA7zSE1OW-Vq-yrVUDGzvchlDJHeojSD3A1GwLMhWQM9fByMaCSc6Bt2MHBYg5EiFgZ8whDvikizboWbNbXq05Jl5zzGWMuk_D0QjKoo3NJuNpDAlhnszAwYpD5uBqxdZTpg_xqESnAD6X33KpEICo6jRkOFK9pgwRrjVH3-Wg9hWXaQjDzcvAmrzgbCwnoFYy5g-zEEJzGD2qCrD0gzOYp8rMldWhHnKo8B1MBJWMUxv-MFf4wCcgv9mIUiY8Fti2QIhgF0pbbjPXgoqeepQKUlsd5Da7AkJ1V1BstnSFxdtMyur8nnlItKkvyfOiUllkEP1qB-jwrHDwJstuhsxtguxOplOZw4Cb0VqPGpDsOXU8SRhlPhZUuNLC0vGodKniXFJwzwaGTDwmA88GE7cwF5bneS431-sM0oyUVQfKqrHfAqplHPh3eT0ym8A7eYSiR6alvb3jUZQ8ad4LtGGJIZTts1iM14zOd8F4JBAtxn1IIYFDIMEQV5gMQ3FNbAi1hJgOhiTOiOU6vuO4jBBmm5ibPltDkjVDSXAdS4BtYWrW0uhKlzdyDimWryfdGsL6DSgF6TZkl0LbEW2qyCByJhPjbJbmwLl6ZxzKDvBnWO0RfOBV-ASB-EmgCpMSq4wtHAkp2iYWUB1sOi6Gf32Tc-FZtgeM1ZKCEZvDX64rgzrvR-0kdYP6W_Y69acKmn6cAyMJR1JTR2RXA2Cdqu8zdyNiDmSgXsgD9oqaqmb91vUiEMi0wjb38S5BEzVVWiep6sX3YbWGMU8hh-UzffZ8fY-BMYSxBwHQBnqEPBeWHYiQcHxVLPiMSs_hrunbQJqoaXrAmohjMrBcIYkfQFysQU6rZkrWGGStitSs6HxWHLFURqXIUggJdt9y6nsRDLUWWyumWUEJuRv9qHigX7xehZgWLEkDlouDvpDkVFzo3T8lB8M8iSFerXl_ADmHAJGywUIhvUA5SsDfLSvwmI9c4AAuMQPimz51KHMCE1OIpKbLbNsPPEhPdUJQxRKvYbmPrFXe1dGubipZhZDj6jZBdbdm38KbCb0lX-8j2o54xXBRIx1oAdtuCr9DKXMVVtsCr_o1oNhfQ55LJC3P55ZFgI_RIIBSycI-mKyA_ISgPDIx8HzpgR07YPLgCYIJiCMYBQwH9U1OiK_LwGFvibuUbuG9CwrbnNOGY2WL28JtIbE91tIGWz2N1AKpo1Bi3BvySZhLYxiF06kKMNUdFkDJJ64PZYLgGGiPxFD6c45tqCYZOLxLaYCQMF1bBNxEHncQ_MUC9ITD1rYDnFbuOoD6qC0kmKUF1qOss-nv6NAtNwVBSJ3LBshhSkamd7t7yhsqNYYGRB9K1vvkgTKYXhlUW6lqPT6Vvwex2EtuWYLGugEKUuMqUb-d1TsL1XvfEOQns7UtrsCxHAqhNwhcaVPAOCABGJJ0fOx71Ap8x-eBJwLJEHFswi1CCQPeJUxqOwyCQ81iq2aK13ZdgKNXA6oOFyumj9Dzm-96QRBp3PhYBhPSsCdm2Q0BxqxtwCzeI2gD2G0AGJjdBAYvjKs5JLb7ZMq_b4RiDs7OgYzZQFpt1-aBCWaOA-Q43PM9AkZMPGE5yEeBgwPqgh_AMlA74BwomVu3b1IjsngdXtQeGfdd3LSBWNvsUq-4LaxswToWbysvtxups1sGXMVjy91YgBrQwygpf32gPHdRPrYrf6OjIrJ6g7QUQptCRTirPE5kmzKFO1SacdraqfZltglVnoXSNpnKY-nlL7RsTq18K6MU3SK5ErI2hWrnRpf9tqJVeajqtsO-NjayKam8oDZT0jQ0ffxuKUJbmqki3zCo8iXZUgY39ARUs9JIKbF4YLnlYWX12U4HE-1mo42LqBA1Trx5lqnSqHiK3XCAYX1WO6q0uUSbyezYfJs3dXOnzrigLpPcdMVnwevUboP7NpjjjsBtd_pmH9xt8K3Bonu06BQuOo21KxovUmuJTp3C02Z82nEMRWDY1ZHbHQ69pLtnlJotFL1sTdBzU2uM8Y3r9gJXb8sPndvHXaDayC3Pmwl6PnQ3JKSjRUbSp5F0yaB_1imJg3C08SNNnjqQpEnvWPr3iX7Es2d4SRJJHi8O7yx-2WXRwPHR-m_t_gt-4dTQ

**Comment by Bradders1504** [comment]
I'm unable to import the code. https://gyazo.com/9fb8952053335f78790c06907ba1f2e0 

Can you share a pastbin link please?

**Comment by lucifering** [comment]
lose 15% resists .

[[The Bandit Lord Alira]] reward? +15% to all Elemental Resistances

**Comment by hochl** [comment]
> lose 15% resists .
> 
> [[The Bandit Lord Alira]] reward? +15% to all Elemental Resistances

Man I could have seen that, yes I took Alira, I usually just take the skill points so I didn't think about it anymore (it's been 2 weeks since I killed her at flashback start).
