### ISSUE TITLE
[Feature Request] Life Leeched per second / Leech rate per second

### ISSUE THREAD

**Issue by DarKWinGTM** [Openarl/PathOfBuilding#156]
[Feature Request] Life Leeched per second / Leech rate per second

**- Leech rate per hit from attack/spell skill**
```
Example : 
Leech rate per hit from attack/spell skill
=
Averge Hit (DisCharge) = 1000 x 0.02 ( 2% Life Leech from Warlord's Mark)
```
= 20 Life Leech per hit

**- Leech rate per second from attack/spell skill**
```
Example : 
Leech rate per hit from attack/spell skill
=
Leech rate per hit from attack/spell skill = 20 x 4/s Attack/Spell Cast
```
= 80 Leech rate per second

**- Maximum leech recovery rate**
```
Example : 
Maximum leech recovery rate
=
Maximum life 1000 x 0.20(20%) 
```
= 200 Maximum leech recovery rate per second

# **This caculator it not correct 100 %**

http://pathofexile.gamepedia.com/Leech

![image](https://cloud.githubusercontent.com/assets/8704185/22361495/e848f4da-e48c-11e6-83e1-31469d7c2987.png)

**Comment by Openarl** [comment]
The next update will add full support for leech (and life/mana/es on hit too).

**Comment by DarKWinGTM** [comment]
awww. god awswome feature ever seen
