### ISSUE TITLE
1.4.141 Spell Block chance on Unique Items not working

### ISSUE THREAD

**Issue by Synol** [Openarl/PathOfBuilding#1562]
None of the Uniques that have + to spell block chance are adding any spell block chance.

![image](https://user-images.githubusercontent.com/31122638/59000511-2ae52e00-884e-11e9-9e16-b047db907710.png)

My block chance is not maxed and this should be giving +6% Spell Block chance over the Anvil. As you can see it is simply adding none. All other uniques are the same.

**Comment by MatthewClair** [comment]
Do you have Versatile Combatant from Gladiator?  If you do, additional spell block doesn't do anything since your spell block is always equal to your attack block.
