### ISSUE TITLE
Overwhelm base critical strike chance

### ISSUE THREAD

**Issue by nxPublic** [Openarl/PathOfBuilding#1571]
Wording is "Base critical strike chance for weapons is 8%", meaning the critical strike support should not have effect on that value, neither should any other source of base critical strike chance.

**Comment by a-ton** [comment]
Mark from GGG confirmed that it works by replacing your weapon's base critical strike chance with the 8% value. So, that support gem and any other added source of base critical strike chance works. 

https://www.reddit.com/r/pathofexile/comments/bvtutb/what_does_base_critical_strike_chance_actually/epsk2xg/
