### ISSUE TITLE
Disciple of the Unyielding not adding +1 Endurance Charges

### ISSUE THREAD

**Issue by aalukacsko** [Openarl/PathOfBuilding#1575]
On the 'Calcs' screen, I'm not getting credit for the +1 endurance charges on this node. It is unclear if the charge is included in the damage/etc. calculations due to other features on this node.

**Comment by skiskow** [comment]
Disciple of the Unyielding's node reads, "+1 minimum endurance charge", not "+1 maximum endurance charge". If you were thinking it was + max this is not an issue.

**Comment by aalukacsko** [comment]
Thanks - I clearly read that wrong with all the theory-crafting!
