### ISSUE TITLE
Life regen is not calculated

### ISSUE THREAD

**Issue by thang241190** [Openarl/PathOfBuilding#1590]
It happens in this patch, in 3.6 it was totally perfect.
![image](https://user-images.githubusercontent.com/21122587/59230929-c298a280-8be7-11e9-8b6b-bca7967fcc37.png)

**Comment by Exportforce** [comment]
You probably have something like Blood Rage running, that drains your life
and maybe you have vaal pact that disables normal life regen completely

Am Di., 11. Juni 2019 um 00:29 Uhr schrieb Nguyen Hoang Thang <
notifications@github.com>:

**Comment by thang241190** [comment]
My bad, i was so noob, thank you very much
