### ISSUE TITLE
[Feature Request] Add support of 'Wither' gem

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#16]
Is it hard to implement support of 'Wither' gem or just no one asked for this yet?
Couldn't find any info on forum/reddit.

**Comment by Openarl** [comment]
Wither is indeed a tricky one. I have no support for stacking debuffs at the moment; I have no idea how I'll support it. I'll try to get around to it some day.

**Comment by dein0s** [comment]
Hmm, maybe under 'For Effective DPS' section? Just an idea here.
Like with 'Charges' above it - yes/no selector and manual stack count with limit (if it exists, either add some pseudo-limit for effects such as Poison). By default at max stack value.

**Comment by tuffff** [comment]
So, Wither now added as a supported skill. Thanks for that! Awesome tool you built.

But when I add Wither as enabled Skill, Chaos Damage gets the "7% increased Chaos Damage Taken", but it does not stack.

I would expect the Debuff to stack to Skill Duration (based on the 2s duration here, not the 0.5s) × Casts per Second, max 20 Stacks.

**Comment by Openarl** [comment]
Currently the program doesn't automatically calculate the stack count for Wither, so to set it, you must select Wither as the main skill in the sidebar, then select one of the options from the skill part list.

It's not ideal, but calculating the stack count automatically is more difficult than you'd think: the program only calculates the skill stats (damage, cast time, duration etc) for the main skill, but in order for Wither to affect other skills it'd need to calculate the stats for both the main skill AND Wither, and it's not designed to do that at the moment.

**Comment by tuffff** [comment]
Ah, thanks for the explanation, didn't see the option at first because I didn't select it as main spell.
