### ISSUE TITLE
[Feature Request] Support : Intuitive Leap Viridian Jewel On passive Tree

### ISSUE THREAD

**Issue by DarKWinGTM** [Openarl/PathOfBuilding#161]
[Feature Request] Support : Intuitive Leap Viridian Jewel On passive Tree

![image](https://cloud.githubusercontent.com/assets/8704185/22453130/18903d72-e7af-11e6-87cc-92d1cb063ab6.png)
![image](https://cloud.githubusercontent.com/assets/8704185/22453142/3b4425fe-e7af-11e6-9b11-2f4de866e278.png)

**Comment by Openarl** [comment]
Duplicates #51
