### ISSUE TITLE
Cannot use Chinese in lua

### ISSUE THREAD

**Issue by noobdawn** [Openarl/PathOfBuilding#163]
I want to make a version for chinese player, but no matter i use UTF-8\UTF-8 No Bom or ANSI, the simplified Chinese text will dispear.

**Comment by Openarl** [comment]
As explained in #55, the text renderer used by the program doesn't support Unicode at the moment. Unfortunately it's not an easy thing to fix, but it's definitely on my radar.

**Comment by noobdawn** [comment]
It seems that the SimpleGraphic.dll made by C++, so sorry about that because I am a new one in C#/Unity/Lua :D, hope to see more programs

**Comment by noobdawn** [comment]
if u replace the text render, pls let me no
