### ISSUE TITLE
[Bug] Blade Flurry more doesn't double dip

### ISSUE THREAD

**Issue by Sairony** [Openarl/PathOfBuilding#164]
Or at least it doesn't seem like it unless I've missed something. Setting Skill Part to 6 instead of 1 updates MH Total More correctly, but Poison & Bleed Total More doesn't seem to change.

**Comment by Openarl** [comment]
Working as intended. "More" multipliers that are attached to the skill never double dip, as they only apply to the damage dealt by the skill itself, and not any secondary effects like poison.
