### ISSUE TITLE
"x% increased Effect of Fortify on you" doesn't work

### ISSUE THREAD

**Issue by molt3nrock** [Openarl/PathOfBuilding#1641]
I have level 20 fortify support gem which increases melee damage by 34%.
If I edit jewel manually `20% increased Effect of Fortify on you` then it should be `34 + 6.8 = 40.8%`  right? I don't know about the roundings.  but the calculiation on the `MH Total More` stays the same.

so anyway it's amazing tool for playing . I really enjoying it.  thanks for hardwork.

**Comment by lucifering** [comment]
"increased Effect of Fortify " not  "increased Effect of fortify support".


Fortify is a buff that grants the player 20% reduced damage taken from hits for 4 seconds.

https://pathofexile.gamepedia.com/Fortify

**Comment by molt3nrock** [comment]
@lucifering thanks for clarification. :thumbsup:
So there's nothing wrong with the fortify calculation.  Closing the issue.
