### ISSUE TITLE
Slave Drivers

### ISSUE THREAD

**Issue by COPhoenix** [Openarl/PathOfBuilding#1644]
Dear creater of Path of Buiding. 

I couldn't write this  as a Pull Request, and I'm not sure it's an issue, but here goes:

As I'm trying to find out my DPS on my necromancer, I cannot find the Slave Driver unit under "Manage Spectres". As I am using the Slave Driver unit, it's impossible right now to figure out the DPS. 
Could you please add this unit? 

Thanks in advance.

**Comment by Openarl** [comment]
They will be added in the next update.
