### ISSUE TITLE
Hello, I am very interested in how you make equipment price forecasts. Can you have an interest to talk about it?

### ISSUE THREAD

**Issue by youboyTizzyT** [Openarl/PathOfBuilding#1646]
I am currently researching the price forecast. The POE data source is obtained from this website https://www.pathofexile.com/api/public-stash-tabs. At present, some machine learning models are used to price. Regression prediction.
The first question, can you tell me what method you are using to predict the price of rare equipment, but also machine learning? Tell me if there are other troubles.
Second question, can you share your prediction method? I am very happy to share this knowledge with you.

**Comment by Polatrite** [comment]
Is this relevant to Path of Building? I don't see any price prediction in POB.

**Comment by Openarl** [comment]
Polatrite is correct, PoB doesn't do anything of this nature, nor have I ever looked into it.
