### ISSUE TITLE
Unique Amulet Missing - Tavukai Coral Amulet

### ISSUE THREAD

**Issue by BlastedAmerican** [Openarl/PathOfBuilding#1648]
**Issue:**
The unique item Tavukai Coral Amulet is missing from the dropdown options for unique items. 

A link to the item on the the poe Wiki:
https://pathofexile.gamepedia.com/Tavukai

**Reproduction steps:**
Open path of building.
Click on the items tab. 
In the Unique search field, enter Tavukai.

The application will respond with no items found. 

**Suspected Cause:**
I suspect this is because no data is present for the item in the amulet.lua file under the data path.

**Comment by Openarl** [comment]
This will be added in the next update.
