### ISSUE TITLE
[Feature Request] Saving on updating program

### ISSUE THREAD

**Issue by vegeto079** [Openarl/PathOfBuilding#165]
Right now when you do an update, any changes since the last save are not kept.
A warning message like "Any unsaved changes will be lost. Would you like to update?" on pressing update would work.
Or if you want more integration it could be "would you like to save" which could save the current profile on pressing 'yes'. This could be more complicated in the scenario of not having a profile saved for the currently open sheet since it would have to ask for a profile name too. I think the warning would suffice.

**Comment by Openarl** [comment]
Good point. I wouldn't think it'd cause problems very often, but it's easily fixed as I can invoke the same dialog that normally appears when closing/exiting with unsaved changes. It'll be in the next update, as usual.
