### ISSUE TITLE
Combustion not recognised in ignite chances

### ISSUE THREAD

**Issue by Nimyron** [Openarl/PathOfBuilding#1652]
When using combustion, the ignite chances in the "calc" section is marked as "Armageddon Brand"
![Combustion](https://user-images.githubusercontent.com/45174799/64080207-e6a0e700-ccf1-11e9-9721-f6f82a3e88d0.png)
![Ignite_chances](https://user-images.githubusercontent.com/45174799/64080208-e6a0e700-ccf1-11e9-9ca7-9f4e7ef16e06.png)

**Comment by hateborne** [comment]
Are you using the most recent version of the tool? I show 1.4.151 and it functions normally.

<img width="519" alt="Screen Shot 2019-09-09 at 1 22 07 PM" src="https://user-images.githubusercontent.com/4691451/64552336-098c5600-d305-11e9-9e1f-6258086983e6.png">
<img width="898" alt="Screen Shot 2019-09-09 at 1 22 35 PM" src="https://user-images.githubusercontent.com/4691451/64552337-0abd8300-d305-11e9-9060-a12558e0697b.png">

**Comment by Nimyron** [comment]
Yep issue solved in the latest version indeed, I close the issue then
