### ISSUE TITLE
Mana reservation bug with Hierophant's "Sanctuary of Thought" node

### ISSUE THREAD

**Issue by Polatrite** [Openarl/PathOfBuilding#1655]
Build 1.4.149, Windows 10 x64.

I was testing a Hierophant build and noticed that, even though I had tons of auras equipped, I still had plenty of unreserved mana available. I believe that the "50% less Mana Cost of Skills" is applying to auras as well.

![image](https://user-images.githubusercontent.com/1864992/64302989-cb74e800-cf3a-11e9-803c-b62e49f6e0ea.png)
![image](https://user-images.githubusercontent.com/1864992/64302995-d29bf600-cf3a-11e9-960d-9c091a6da4de.png)

POB link here for testing: https://pastebin.com/kgdvZMqh

**Comment by Openarl** [comment]
This is now fixed.
