### ISSUE TITLE
[Feature request] Add bonus per points to node to bonus panel

### ISSUE THREAD

**Issue by Asymat** [Openarl/PathOfBuilding#166]
Giving the bonus of a particular node and all the nodes leading to it is VERY helpful (I even discover today you can determine your pathing when holding SHIFT).

In the bonus of all nodes leading to it, please add [in brackets for example] the bonus PER points to allocate = divide full bonus per points to node.

It should be really easy to add so let's hope it is for next patch and thanks for your hard work!

Example (new stats in **bold**):
 
_Allocating this node will give you:_
+1291 Average Hit (+1.4%)
+1291 Total DPS (+1.4%)
+6533 Ignite DPS (+3.0%)
_Allocating this node and all nodes leading to it will give you:_
+3874.6 Average Hit (+4.3%) **[+0.6% per points to node]**
+3874.6 Total DPS (+4.3%) **[+0.6% per points to node]**
+19890 Ignite DPS (+9.3%) **[+1.3% per points to node]**
...
...
7 points to node

**Comment by Openarl** [comment]
Good suggestion. I'm flat out working on the next major update, but I'll see if I can find the time to put this in.

**Comment by Openarl** [comment]
This will be in the next update.

**Comment by Asymat** [comment]
@Openarl white I'm amazed to see how quick you pushed this live, I think a majority of users are using percentages to compare rather than flat stats.

Up to you to show only percentage or both but dude we need percentage. :)

**Comment by Openarl** [comment]
Hmm. I did contemplate adding the percentage too, but I didn't think it was really necessary: if you're comparing two sets of nodes, whether the per-point stat is absolute or relative shouldn't make a difference, as you're just looking for the higher value. I'll give it some more thought though, since you've asked.

**Comment by Asymat** [comment]
While it does work for absolute DPS, how do you compare +0.4 cast rate to +456 damage?
