### ISSUE TITLE
ntdll.dll causing crash on startup

### ISSUE THREAD

**Issue by mangekyou80** [Openarl/PathOfBuilding#1662]
PoB crashes on startup with the new build, the last thing I see in the launcher before it snapping shut is WGL extensions not supported. 

I did some checking and it seems like this could be caused by hard coding the location of ntdll.dll

Microsoft in all their wisdom uses windows/System32 for 64 bit apps and windows/SysWOW64 for 32bit apps. 

I have already tried restarting, reinstalling video drivers, uninstalling and then reinstalling PoB, and uninstalling and running the stand alone version. The result is always the same. Crash on startup with identical entries in the windows application event viewer:

General:
Faulting application name: Path of Building.exe, version: 0.0.0.0, time stamp: 0x58a9a3a1
Faulting module name: ntdll.dll, version: 10.0.18362.1, time stamp: 0x9bbcb4a9
Exception code: 0xc0000005
Fault offset: 0x0003ada5
Faulting process id: 0x2b00
Faulting application start time: 0x01d56582013ba02e
Faulting application path: C:\Program Files (x86)\Path of Building\Path of Building.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: cb0766e9-c627-4cdd-8b4a-91da0a9d09cb
Faulting package full name: 
Faulting package-relative application ID: 

Details XML (friendly view wouldn't copy pasta):
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-09-07T13:42:04.075746000Z" /> 
  <EventRecordID>3959</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-KGIONFC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Path of Building.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>58a9a3a1</Data> 
  <Data>ntdll.dll</Data> 
  <Data>10.0.18362.1</Data> 
  <Data>9bbcb4a9</Data> 
  <Data>c0000005</Data> 
  <Data>0003ada5</Data> 
  <Data>2b00</Data> 
  <Data>01d56582013ba02e</Data> 
  <Data>C:\Program Files (x86)\Path of Building\Path of Building.exe</Data> 
  <Data>C:\Windows\SYSTEM32\ntdll.dll</Data> 
  <Data>cb0766e9-c627-4cdd-8b4a-91da0a9d09cb</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by mangekyou80** [comment]
actually, there are 2 error messages for each run (sorry haven't had my coffee this morning)

Faulting application name: Path of Building.exe, version: 0.0.0.0, time stamp: 0x58a9a3a1
Faulting module name: nvoglv32.dll, version: 26.21.14.3615, time stamp: 0x5d620327
Exception code: 0xc0000005
Fault offset: 0x00eac2bb
Faulting process id: 0xb40
Faulting application start time: 0x01d56581dd51c95e
Faulting application path: C:\Users\andre\Desktop\PoB\Path of Building.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_9f1b2c8a203d6fe0\nvoglv32.dll
Report Id: 0b39dc0d-b1f3-43e0-b397-617226291377
Faulting package full name: 
Faulting package-relative application ID:

**Comment by hateborne** [comment]
> actually, there are 2 error messages for each run (sorry haven't had my coffee this morning)
> ...
> Faulting module path: C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_9f1b2c8a203d6fe0\nvoglv32.dll
> ...

This is could be related to an nVidia device's drivers. You mentioned uninstalling and reinstalling drivers, but did you try the somewhat aggressive method? Uninstall software via Add/Remove Programs equivalent first. Open Device Manager, expand Displays, right click and 'Uninstall Drivers' on the video card there. Finally, find and delete "C:\nVidia" and any nVidia folders in "C:\Program Files" and "C:\Program Files (x86)". Reboot.

Once all that is done, download and install the latest nVidia drivers. In the install process, be sure to click/use "Custom Install" to utilize the "Install Fresh" option (or equivalent), which will make bloody sure everything is clean and new.

If that fails, the only thing left is to disable any custom Windows themes and default to the 'factory default' Windows theme to see if that resolves.

If even that fails, time to just burn the machine, the house, and most of the city down. </3

**Comment by mangekyou80** [comment]
clean install did it, thanks!
