### ISSUE TITLE
New gems for Blight League don't appear

### ISSUE THREAD

**Issue by AAkhilleus** [Openarl/PathOfBuilding#1663]
Current version for PoB: 1.4.149
OS: Windows 10 Pro 64b

Problem: new gems for Blight League are not recognized/supported in PoB, it shows this error message: "Unrecognized gem name 'Venom Gyre'"

**Comment by Exportforce** [comment]
Gems are not yet supported. Wait until openarl implements them

Am So., 8. Sept. 2019 um 14:00 Uhr schrieb Ουιλιαμ Αρκευα <
notifications@github.com>:
