### ISSUE TITLE
Lua error when overing Blink Arrow's Skill Cooldown

### ISSUE THREAD

**Issue by KurzedMetal** [Openarl/PathOfBuilding#1668]
Using this build: https://pastebin.com/hii4M6Fb

When I hover Blink Arrow's Skill Cooldown:
![image](https://user-images.githubusercontent.com/1426680/64505690-22681d80-d2ab-11e9-8d42-6eeb42249cd7.png)

I get this error:
![image](https://user-images.githubusercontent.com/1426680/64505614-d5844700-d2aa-11e9-9c09-7cfb6eefb3e9.png)

**Comment by Openarl** [comment]
Fixed in the next update.
