### ISSUE TITLE
EE not applied to non-hit skills

### ISSUE THREAD

**Issue by kohelfs** [Openarl/PathOfBuilding#167]
As the title says, EE effect is currently not being applied to skills that don't hit, such as Righteous Fire and Scorching Ray. Clicking on "enemy was hit by x damage" doesn't chance anything and no conditional modifier is shown in the effective DPS tooltip (however, other changes to enemy resistance, such as flammability or elemental weakness are working perfectly).

I'm using version 1.2.36, but I didn't notice any documented changes to this issue.

**Comment by Openarl** [comment]
Looks like the hit-by-x conditions were being incorrectly reset for skills that don't hit. It'll be fixed in the next update; it's a major update though so it might not be released for a few days as there's a lot of work being done.
