### ISSUE TITLE
Incorrect Tempered Flesh value

### ISSUE THREAD

**Issue by GloomyC** [Openarl/PathOfBuilding#1679]
In PoB Tempered Flesh gives 5% Crit Multi per 10 str when in game it gives 7%
Same thing with Transcendent Flesh
![Path_of_Building_DeJkQeOBbk](https://user-images.githubusercontent.com/23178468/64696288-52c3dd80-d49e-11e9-88c7-cde969246e4b.png)

**Comment by Openarl** [comment]
Fixed in the next update.
