### ISSUE TITLE
Feeding Frenzy buff doesn't affect non-linked minions

### ISSUE THREAD

**Issue by serenewaffles** [Openarl/PathOfBuilding#1681]
When you have Feeding Frenzy, you get the following:
10% more Minion Damage
15% increased Minion Movement Speed
15% increased Minion Attack and Cast Speed

These buffs are not reflected on other minions when the configuration option to enable Feeding Frenzy is checked. I cannot tell if they are reflected on the linked minion (the direct damage buff to linked minions is calculated)

**Comment by Openarl** [comment]
Fixed in the next update.
