### ISSUE TITLE
Unnatural Strength +2 gem levels not applying to support gems.

### ISSUE THREAD

**Issue by jfinnecy** [Openarl/PathOfBuilding#1685]
It can be tough to see because toggling Unnatural Strength (Necro ascendency that gives +2 levels to all minion gems) does change the DPS, but you can repro in the UI thus:

1. Add minion damage level 20 gem to build.
2. Check calculations, under MH total more, 49% more damage is shown from "Minion Damage" gem.
3. Toggle the Unnatural Strength node.
4. Check again, MH total more still shows only 49% more damage from "Minion Damage" but should in fact be 51% (easily verified by upping the gem level to 22 manually).

**Comment by Openarl** [comment]
That is working as intended; global gem level modifiers do not apply to support gems.
