### ISSUE TITLE
[Feature Request] Add an ability to copy skill chains

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#17]
For testing puproses it's sometimes needed to have almost the same skill chains but with 1 or 2 changed gems in setup.
It would be so much QoL if we can just copy (button?) the existing skill chain so we don't need everytime to replace gem, switch 'Calcs' tab, then back to 'Skills' and so on.

**Comment by Openarl** [comment]
That's a good suggestion! It would also allow skills to be copied from one build to another. I'll see what I can do.

**Comment by Openarl** [comment]
Ok, it'll be in the next update.

**Comment by dein0s** [comment]
I know that you've already went to sleep, but anyway :)
Nice to have this done, but still can we also get buttons for this? Right now it's not quite obvious and there is a lot of unused space on skills tab for this.
Like this (just some duplicated some strings, fck paint :D)
![Buttonz](http://i.imgur.com/eGVD85U.png)

**Comment by dein0s** [comment]
So, @Openarl is this possible to add buttons like above?

**Comment by Openarl** [comment]
Sure, I'll pop that in the next update.
