### ISSUE TITLE
[BUG] witchfirebrew + vulnerability

### ISSUE THREAD

**Issue by AntiDog** [Openarl/PathOfBuilding#171]
The curse is applied 2x in DPS calculation.

![image](https://cloud.githubusercontent.com/assets/13760683/23081505/6bf8a6b2-f555-11e6-80c0-b657df291dfa.png)

**Comment by Openarl** [comment]
You've got another Vulnerability curse active; the program doesn't currently check for duplicate curses so both are applying.

**Comment by Openarl** [comment]
The next update overhauls the buff/debuff handling code, which fixes this issue.
