### ISSUE TITLE
[Feature request] Load up (rare) items you've created for previous characters

### ISSUE THREAD

**Issue by JYshadow** [Openarl/PathOfBuilding#172]
Hi, first of all, thank you for making this awesome program!
But, just a small request: it would be nice if I could load up already created rare items from other builds I've made with the program. So basically saving templates I've created myself (mostly rare items).

Btw, are you considering supporting Fireburst from Essence of Hysteria on weapon?
Thanks you!

**Comment by Openarl** [comment]
You can copy and paste items between builds; but I do plan to eventually add a shared item list, or at least a way of importing items directly from another build.

**Comment by JYshadow** [comment]
Ah, right, didn't realize I could do that. Thanks!
And about the Fireburst Essence; I'm using Fireball as placeholder, which is almost the same, so it's fine for now

**Comment by Openarl** [comment]
Support for Fire Burst is coming in the next update; otherwise this duplicates #47, so I'll close this now.
