### ISSUE TITLE
Ichimonji buff modifier not working

### ISSUE THREAD

**Issue by SharodX** [Openarl/PathOfBuilding#173]
Buff effect modifier not recognized

![image](https://cloud.githubusercontent.com/assets/25855057/23087176/d583c434-f57a-11e6-9ef2-1052b75b200e.png)

**Comment by Openarl** [comment]
I haven't had time to add support for that modifier yet. I'll see if I can get it working in the next update,

**Comment by Openarl** [comment]
This will be supported in the next update. The increased buff effect _should_ be applying to everything correctly, but do let me know if there's any discrepancies.
