### ISSUE TITLE
Quality on items

### ISSUE THREAD

**Issue by JYshadow** [Openarl/PathOfBuilding#175]
Hi, appreciated that you keep supporting the program, keep it up. 
However, the latest patch with the quality changes messed some things up for me. I've made a ton of builds and a few of those items have lost their 20% quality (and a few of them didn't), which means I have to manually add them back again for each item I've made, which takes a lot of time. Could you make an button that just adds 20% quality on all items? Because the values are now all a little bit off and inconsistant, which makes comparing builds a bit harder now.

**Comment by Openarl** [comment]
Oops, didn't realise that change could affect existing builds like that; it's specifically items that were added before that update, but not by importing from a character, which are affected.

The next update will fix this; any items affected should have their quality re-added automatically.
