### ISSUE TITLE
Witchfire brew

### ISSUE THREAD

**Issue by Qompas** [Openarl/PathOfBuilding#177]
Brew's aura doesnt affected by less curse effect on bosses. I know that curse aura affected by neither player's flask nor curse effect, but i don't think that is true for less curse effect on monsters in general. Also this curse doesn't count towards Malediction buff.

**Comment by Qompas** [comment]
i have screenshots for that
![image](https://cloud.githubusercontent.com/assets/25932577/23172904/d7e2846a-f870-11e6-9cc0-13e6cfdce41b.png)
![image](https://cloud.githubusercontent.com/assets/25932577/23172827/93df8394-f870-11e6-9b4c-828cce928acb.png)
![image](https://cloud.githubusercontent.com/assets/25932577/23172927/eda09a26-f870-11e6-84da-47fc93667e28.png)

**Comment by Openarl** [comment]
Oops. I had to handle Witchfire Brew's Vulnerability separately from normal curse skills; looks like I forgot to add a few things to that code. It'll be fixed in the next update.
