### ISSUE TITLE
Resolute Technique throws up an error

### ISSUE THREAD

**Issue by DoctorBacca** [Openarl/PathOfBuilding#1770]
Whenever I hover over "Resolute Technique" it will throw up this error:  https://imgur.com/a/GHExxxW
Its the only node that causes this error and it doesnt matter what my other settings are. If I allocate a point into it it causes the error to pop up when i hover over any othe node in the tree, every single time.

**Comment by ppoelzl** [comment]
Can you post your build? It's not possible to reproduce otherwise.

**Comment by DoctorBacca** [comment]
The error comes up even without a build but this is what i had when i had first discovered it.

https://imgur.com/a/KLvlc7p

As for the version, I cant find a link for the current version and the update check constantly fails to find another version

**Comment by ppoelzl** [comment]
It seems like somethong is wrong with your installation.
I would suggest to uninstall PoB, download version 1.4.147 and update from there.

**Comment by DoctorBacca** [comment]
it took a few attemtps but it eventually found the update and the problem went away thanks
