### ISSUE TITLE
[Bug] Pierce chance on items not applying

### ISSUE THREAD

**Issue by didii** [Openarl/PathOfBuilding#178]
Small bug: extra pierce chance on gear does not appear on the Calcs tab as shown in [these pictures](http://imgur.com/a/x0Opu).
Here is the [build code](http://pastebin.com/8kgKV3Gn) (I added some more pierce on the items).

**Comment by Openarl** [comment]
That's working as intended.  
The implicit of Penetrating Arrow Quiver is "10% chance of **Arrows** Piercing"; Spark is a spell, it doesn't fire arrows so that stat shouldn't apply to it. "10% chance of **Projectiles** Piercing", on the other hand, will.
