### ISSUE TITLE
Mysticism Wheel not working

### ISSUE THREAD

**Issue by smsanta** [Openarl/PathOfBuilding#1784]
Hello i was building some dual whield wand and adding a layer of defence with block, and i found that the Mysticism Wheel Notable and small nodes are not working at all. 
Hope u can fix it

**Comment by ppoelzl** [comment]
Can you provide a build to test with?

**Comment by smsanta** [comment]
Hello, was preparing some screenshots and i noticed i have set up the wrong set of weapons, and that's why block doesnt inpact in the stats. i have just checked and it is working just fine. Sorry but still thanks to attend that request. I will close this. and thanks!
