### ISSUE TITLE
[Feature] Elemental Equilibrium: Possibility to check "Enemy is allways hit by <Elemental Type> damage

### ISSUE THREAD

**Issue by Asymat** [Openarl/PathOfBuilding#179]
Consider this example:

Orb of storm + Flameblast: To calculate dps of ignite I have to check "Enemy was hit by Fire damage" and put "-75% Fire resistance to monster". Because if not, PoB will consider that Enemy is hit by Fire damage _after_ the Flameblast hit while in fact it is rehit by Orb of storm.

So, let's add another 3 checkbox with "Enemy is allways hit by <Elemental Type> damage" (that would for instance autocheck/lock "Enemy was hit by <Elemental Type> damage").

Thanks again for your hard work. This tool is amazing!

**Comment by Openarl** [comment]
The next update will add an option to ignore the hit damage of the main skill, so that the options you set don't get overridden after the hit damage calculation.
