### ISSUE TITLE
[Feature Request] Import not only tree, but the whole public character profile

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#18]
Don't know is it in your todo-list or not, but it would be great if we could just import all character related info from public profile (like gear, gems, jewels)
Something similar to [Atlas of Build tool](https://www.pathofexile.com/forum/view-thread/1715993), but inside PoB.
I realise that such scratching of web page and parsing data could be an ass pain, but still.
Just in case you'll have some free time :)

**Comment by Openarl** [comment]
Oh it's on the TODO list, but as you guessed it's a bit of a pain. Free time is largely being consumed by the new league though; but I'd like to get it done soon as I know it'd be very useful.

**Comment by Openarl** [comment]
This will be in the next update, which should be out in the next day.

**Comment by dein0s** [comment]
Wow, sounds great!
