### ISSUE TITLE
Suggestion - separate ele/chaos resist from "is enemy a boss"

### ISSUE THREAD

**Issue by Sectoidfodder** [Openarl/PathOfBuilding#182]
Shaper and guardians are rather popular bosses with 40/25 resistances instead of 30/15.  Other bosses also have varying resistances (off the top of my head, Doedre has much higher than normal fire res).  Might as well leave enemy resistances to the appropriate boxes instead of having to check "is a boss" for the curse effect, then adding 10 in each resistance box to get the right numbers.

**Comment by Openarl** [comment]
The last update (1.3.7) added a second "boss mode" option for the Shaper and Guardians which sets the resistances to 40/25, as well as applying the higher curse effect reduction and bleed/ignite/poison duration reduction that those bosses all possess.

**Comment by Sectoidfodder** [comment]
I just got the
