### ISSUE TITLE
[bug] Deadly Infusion crit chance not working

### ISSUE THREAD

**Issue by Aleteh** [Openarl/PathOfBuilding#183]

**Comment by Openarl** [comment]
It seems to be working fine for me. Are you sure you have power charges enabled?

**Comment by AmenRa666** [comment]
I have PC enabled and there are some bugs with Deadly Infusion, melee crit and mace crit.
Try to rebuild this tree:
`
https://www.pathofexile.com/passive-skill-tree/AAAABAYBAFuvDdFZ8_cytfJvJ49ghXvjhClPtDh3404qo4qYbyPTZlSbtYTFFfY9PhPM4XNKiwSzIzZRR4w2I_a-p0V8Ynno1hm0GjiE2ZeXY_0qOJBVa7dwUm87MjJjQyT9rKpd8qZXTePyRREvZU3sONmGjX0NjQ-rN9Q1kv6PhX3Grrc-vTbx_vAfkn2J0zqzTZLaue4OmjuxQk_zwzqpbha_5CIXsDB8_gpqkysK_MWHdu0_wBr_3sT2IuomlTrYvG965oNfYGUABnIPJy-Cm0d-JIvlz1MQPC3YvWHi3CPnVJpqTP_79ezLcqkQklVLBbV4DSoLaf6DzHGFRtc64aIA5RmNv0p9Adw=
`
look crit chance change with every point spent.

**Comment by Openarl** [comment]
What do you mean by "crit chance change with every point"? I've imported that tree and I don't see anything odd happening. I'll need the complete build; go to the Import/Export tab and generate a code in the second section, then post it here (or via pastebin).

**Comment by AmenRa666** [comment]
I mean any "crit chance" point.
Here we go: 
`
eNrtW1tz2sgSfg6_YoqqPeXUBlsaCUn44E0BvuEYBwN2bL9QgxhARhfQBYy38t9P68JFIFkTOzmb3Y0fsNB83TPT0_N190iUPz4ZOppR29Es8yjP73N5RE3V6mvm8Ch_0zktKPmPf-TKTeKOPg-qnqb7LX_k3pVrRFcduHhXrpsTz0UmMehR3hlrut6dENvNI9MzetQGpfmDFBxRXW1GrwLcy3hDc9RuzxsMGlaf5pHj2sEAT05PT2qd-u1JahdmivI2hb4tE6mWrpOJQ_tH-QHRHdCtwWXbl21THUBM-HPNPSYGGVIm9LHFprU9obTPhKzZGvNAayNiqpTdDJ3FhLZd4jpMIlWddcxNS3MskwlaH5qay2hbqpIFE7IBLnUyGACGbWYVF5yu57mUDX6pDdhG3CAmYQKemNQeLtojjepsFq7YhuXZbLpnxGcAJmyLOprjMtv4mA6AUSKrlQ-WvFEOyATpdEb1o3wJeEfVieNcBXu3PSJ9a55HxFGp2a-tGyqOA9eamUczjc59MgDvaDQ_tzp5ZBDNbFvqmLpntuVN_L2OesTsa26D2qqmU8cBBbpmk-X9K8s2CPR-ZZl0ea9me3R5KxhxsAlCpgsukU56PsInStLT_Rm7IBP2XwkYLcD5_ftS78pn1FjOE8M8A2JqAkUGI9xS4nMX7HsVbGfpLjVRG7xuDA1Tj-iauzjKc6Hld9SmKqr0YVqwRkRHFVX1bKIu3qLuCyUTWPATnRrUdEFpxHxvGyHto0ttOHJN4PXvoLFuqjYl4I7Ip0ZNhWGGhnR2tZYPgvUKvHO12OWOTSkKA1SoMlzNsv8lHMtN6zK4eDdy3YlzeHAwn8_3JxAorQF9AnfbVy3jYOK764wWgkUvuKD0oAJ_1cp9tXLqzY77pw9KV124g4vZhVgaju5mj6Oa3nSPR4LIiVNLnN73Fs3Og97uufed09PBfak5ajbEu6tP2rz9XH9-aLXEOa53SWHC3Sr3pmnxI4M7e9RO8AO9u-9y088X1Vsi9-c3hiI3Hi8erxedkv1p0lemD3cd2ly0WiezhxvB-XxlnD3ecVeP1wX7qnTNj2dSc3QnnNm2Wph1ek_dWWUwNvEF9zx97jxcEo-Kn41H7-l63H2eP08nvRHpFmv1O-e4qnSHk-l44XzqNr6c9z2uO6_aXcHp4LpnGXrHvp-dlaSidTW4P7upVM1682JRqBlcv3BRn-nPfOO6WRPuZ1_ONaHWNG8vJtNOsyuX6POlOh1fj_Xby2rvVjxuW5dkIB0_n5-dtlxVEkm9UmwZVzNuUqr050fBIh0sV6kcUoMTLln0DZnAIHXwH7kkgTtBkDH8b0t324EJWJYEBhxWRLnIgpP4ksTSryQJIgtOKCklln75ksKiT5QUBTPNQ8Ys8y2KPJYZcBInC0z6inyJZd1ERZYUln55hc3OvKSw-AFMl8lfJCwwuZ8gCTwLThSZhifxIs_kLmIpoVtgy_WWgi8hMZYPfOb0L64syJX8Nv_m8kvAq7cQu5FDia2OgJWP8h_z6NmyjHtY0H2Ow1ypJGEsyyK4gDOy5ueUuA0yWWUWPvYyDAJC-O3uKF8QJW5f4OEPXFbmpTB412HMUZUCV2hGbI2YbiDn5ydRhG7BbXdxiG5MberRXNX2XM_5D4Q557_okpI-ak-g3hjr1M61NNfzg4lKJ0DmOWgdevQQdSCTgGiYuw07OERNmyK8L-xz27ekzVs1z7Z9sRadeppNHRRMC2HlAyryfsQK_tcBUTcmuqZqrnOIcO7PaB6H_Fee-w1pq2C3HZTXSPxB-MpLL2JxTFVztHCCuLmtif-Av0LAdhBfRK6FcBGdwtAjGCJDyIIcF4UpO_RiUkOjTi6Q2FMKvPDel9rDUkHg36f3IoR9YB8sxnqAG5CKE3XsoAm1Ec_5dqLm0B3lhNgMNoRye3yxgLn3m82hEhQUWbk9gSuI8fatxAGFdVPg-JB3togJY7H9T9gR-8XQn4rLrZGKUDIRpWVW4nvs2nX9Jhx3V_hPc2GSj86pblA3d-JS20_0qp49hAzWzYHTDbQn6hzm_gw6OtyXi1_3OFgHHLdGoGYT9HuAUoLlSm4tlYJGgzxphmcgv-JZQrgAgIP20KetAQrpAjpraKZfM0Ay5-TaUNTHBhiKihwX9hxlrDBZF1LDOKhYDDCr9U9qhM1DdV0b-jXIVhcKWAAQgZ-ERQ1JBdUsKFayQOsMNg0pFCN1I2I5m6hkl5Ajn8DpXrOECNkQMRWS5b1hu5zeRYkXIUNZfmS5eszRU9t5LgvAZwFwFkBI32xCwmZr-S5Ys2zYYcHl73uY85dT4HZ3ws7OCz1Azto0shAD-McDW94mxwDhsQAKzwXiSF4OxxVV9zt7KCRl2MghJ4NAcYeSN_h2VxAXl5IiXCWzdIIUXknB-IKdxSAlL4VkEN-uFRMl_Q7iLLcd89Bcc0corGhBULXJAPjp66aG7agRMSEDdNvqLCLxtUyVGBAHiB4Bd9iuz6wxOaAVdURsP5ruKFgak-eX1sTgbiEb7VoyhZtZaPeYPsEIYed8IynzUgAguo7WB24_MW9vD_635ejXrrZGx31TjqcbsKRRMpIOiuUsmzCpFMP5pAH9gn2pTdzICek3Rlh_QvHts5lRvQDb2NEvwbb3cLK_BzZdC53pVg9s-prkLCtaCBntbw2f0qvD6w-Pp_syXyryePnxvcNrOiDLpnyWUXnphaSEw6Kw-ojwWVbks8yIs9ISnGU3nGU3nGU3nGU3nGU3nOWNOMsdcZYlcZYlhSxLCplbNsuSQpYlBTE9AxTTy62qZblOrqMBraMzoKYZcPvrSq2QjBXuhTpLSU8Zeb8DIZ5ENKxZEHqiMPGaIP6PKI3eXhfxmVV9Ut3zF_J4nLiTfLqY5NOGp1MX_vUgp4y--JVNISprVj6SUtIoby5pijxLSbNKXldVB5b-YfUKfpkqdhFppV0CMtmooRU3gUAbup6Uv72xmPrpaw8B_2tqD15gKT5-UFUhKN-Q0sdNERktRaTh6a420TUa3zK8zFbFyGxVjPxyFfOrBvk5zvQSIz4nC_zq4-01SHKJkWXEXzXIv7IGSUrHpIR0rEp1N3cONcUCBZeQigVP2oQiUzaW-VSGLdkKyFxKKktekQukn3ie6sQZB4P0jy2hcrEXYD6XZstE0WhT5m9f6mROuhYc7DrIf8q6FawDvE37nrqD9pwk7LZuGrwMifpeGNx_1kCWeFb14-JaYon314ax_8PZWTySJTGXnH44AtmZfx4SnY4Qz3ShonTe-Cj6tSck67pDWj3l4r6tauS5laTCXjWuH6pJ7EXjqtLEystFYwLV7R6WJz8u-K6P11NqrV_P1n-yxPwtjJWc5f5NCaytW8tfiIQ8tX6xbQnegEQvO2-8_cbvgsIjszWkmKoHv6jHf6VgEyLsQoJz5zVCTFHCv6wEsso1QNoFhC8TrSE4end_-TZduWaZA22485MbyDNOgSueF1HikUc9y9IpMZev7h0kiTStObV3JYJXuqPfDETdlQ-2f4f0P4Fusrs=
`
Try to add or remove PCs, you sould see no changes to crit chance, same with Disemboweling cluster and Deadly Infusion.

**Comment by Openarl** [comment]
Ah ok, now I can see the issue!

Path of Building factors in accuracy when calculating crit chance, by simulating the crit confirmation roll. This occurs after your "true" crit chance is calculated, so if your crit chance is over the 95% cap, then your effective crit chance will be lower. In your case, the effective cap is 95% x 90% (your hit chance), which is 85.5%. You can see all this in the crit chance breakdown in the Calcs tab:
![crit](https://cloud.githubusercontent.com/assets/19189971/23510281/9af7eb04-ffa4-11e6-8daa-b129ab237ff0.png)
