### ISSUE TITLE
[Bug] Doryani's Invitation Heavy Belt ignite chance not working

### ISSUE THREAD

**Issue by sbfussy** [Openarl/PathOfBuilding#184]
EDIT: I am still figuring out exactly whats going on, but...

I am testing a build using Doryani's Invitation. Activating one flask increased my ignite chance by 9%, and activating additional flasks did not increase it further. I do not believe this is how the item works, but I am not certain.

**Comment by Openarl** [comment]
Items that grant stats while using a flask only give the stat once, even with multiple flasks active. I specifically tested Doryani's Invitation in-game and verified that it conforms to that.
