### ISSUE TITLE
[Feature request] Choose folder for storing builds

### ISSUE THREAD

**Issue by esge** [Openarl/PathOfBuilding#186]
Hi, so why i'm suggesting this is cos i want to have my builds stored in dropbox so i can check them from whatever pc i'm on

**Comment by dein0s** [comment]
How about just making a symlink to dropbox?
Like this
```
mklink /D "C:\PoB\Builds\" "D:\Dropbox\PoB_Builds\"
```
Few notes:
- before attempting to make a symlink - make a backup of your current 'Builds' folder
- ```mklink``` only available via cmd-shell
- administrator privileges are required to create symbolic links

**Comment by esge** [comment]
that is certainly an option i didn't know existed and i will use it, but not every user might be able/willing to do it..

**Comment by esge** [comment]
that is certainly an option i didn't know existed that i will use. But not every user might be able/willing to do something like this

**Comment by dein0s** [comment]
Well, if you fully use dropbox on everyday basis, at least you have to know about symlinks (if only you're not installing everything inside of your dropbox folder). I mean - skype/other im logs, configs, settings, backups, etc. Ofc this is only my point and it's subjective, but still.
Anyway, it's all up to @Openarl , I only gave you an advanced advice :)

**Comment by Openarl** [comment]
The next update adds an Options screen, and one of the options being added is to override the default build save location.
