### ISSUE TITLE
How to decode the PoB URL?

### ISSUE THREAD

**Issue by sjau** [Openarl/PathOfBuilding#1860]
Hi there

I've been wondering how you are decoding PoB URLs like the one in https://pastebin.com/UUz1EdjT to actual skills and items? I know it's not an issue with PoB itself but I couldn't find a better place to ask this.

**Comment by ppoelzl** [comment]
There are no "PoB URLs". The import code is not a resource locator, _but the resource itself_, even if it's MIME base64-encoded like it's common with URLs. First you have to decode the string, then decompress it using DEFLATE. It will yield a XML string exactly like your saved builds in `"%userprofile%\Documents\Path of Building\Builds\"` are. You can take a look at a decompression implementation using Python [here](https://github.com/ppoelzl/PathOfBuildingAPI/blob/master/pobapi/util.py#L53).

**Comment by sjau** [comment]
Perfect. That was the info I was looking for. Thank you.
