### ISSUE TITLE
[Bug] "Whitescreen" after short while

### ISSUE THREAD

**Issue by kerberk** [Openarl/PathOfBuilding#187]
After a short time (5-10 minutes) of running the program I get a "whitescreen". Basically the program freezes and is just a white screen. I can't close it without the task manager since it's unresponisve.  
The program worked for like a day after installing it and then it started.  
Is there some way to give you logs? I mean it could obviously also be a problem on my side, but I don't know how to figure that out?! I already tied to deinstall it and deleting the documents\path of building folder.  
I'm on Windows 10 btw.

**Comment by Openarl** [comment]
That's odd. Does the freeze happen while you're interacting with it, or can it happen while the program is in the background?

**Comment by kerberk** [comment]
Seems to only happen while I'm interacting with it.

**Comment by Openarl** [comment]
Interesting. Anything specific that seems to trigger it?

**Comment by kerberk** [comment]
I tried a few hours now and can't find an exact pattern. I think it happens primarily while playing with items. But I can't excluce, that the problem is on my side. I will try it on a VM tomorrow on the same PC and can try some more stuff then, to figure out what's triggering it. Short on time today, sorry.

**Comment by kerberk** [comment]
Well, the problem was on my side. I had some colliding graphic card drivers which flashed my screen and made PathOfBuilding to stop reacting. It still is odd that PoB just stopped working while the problem wasn't interacting with the program?!
Nevertheless, sorry for trouble - if somebody has similar problems (I switched from Nvidia to AMD), deinstalling the NVIDIA drivers cleanly and reinstalling the newest AMD drivers fixed my screen flashes and with that PathOfBuilding stopped with the odd behaviour.
