### ISSUE TITLE
I cant uptade my PoB

### ISSUE THREAD

**Issue by milk8888** [Openarl/PathOfBuilding#1871]
I tried deleting everything and re-download but everytime i open it starts an update wich never completes. Always stuck at some point. What can i do to fix it?

**Comment by silvajef** [comment]
Me too.

Update check Failed

SSL connect error

**Comment by 50934285342095** [comment]
Not a fix but an ugly workaround - disable SSL checks completely for PoB.
As PoB only pulls data, you _should_ be relatively safe

In file Launch.lua, between lines 237 and 238 

https://github.com/Openarl/PathOfBuilding/blob/47582672d5cba8eeb4f50477f8aecded9f973236/Launch.lua#L237-L238

add these two lines so it looks like the following instead:

```
 		easy:setopt(curl.OPT_ACCEPT_ENCODING, "") 
 		-- ugly workaround
 		easy:setopt(curl.OPT_SSL_VERIFYPEER, false)
 		easy:setopt(curl.OPT_SSL_VERIFYHOST, false) 
 		-- ugly workaround end
 		if cookies then 
```

Restart PoB. This will be overwritten if you update PoB.
