### ISSUE TITLE
I got this PoB error trying to import passive tree

### ISSUE THREAD

**Issue by Islam17-cm** [Openarl/PathOfBuilding#1876]
![image](https://user-images.githubusercontent.com/62155429/76650254-3e5abd80-6573-11ea-8387-12cdecc8f030.png)

**Comment by Byngalo** [comment]
+1

**Comment by The-Aurora** [comment]
+1

**Comment by OGvexy** [comment]
Also have the same problem whenever I try to import a toon from anyone accounts, mine or others :)

![image](https://user-images.githubusercontent.com/62165037/76674369-01acb780-65af-11ea-9410-12e60a862703.png)

**Comment by Hyhollow** [comment]
i have the same error too 
![image](https://user-images.githubusercontent.com/60813613/76675924-304b8200-65f1-11ea-8acf-b94666706da7.png)

**Comment by CButtars** [comment]
Same here.  Import Items and Skills works fine.  Just Import Passives and Jewels.
Happened even  if I rebooted (f5 from error or manual).  Tried with other toons and caused same error.
Using current version: 1.4.159
![image](https://user-images.githubusercontent.com/38955577/76676179-e6ca4b00-658e-11ea-89b3-79ce9be146aa.png)

**Comment by coder775** [comment]
+1

**Comment by nuenuewei** [comment]
+1, identical error message and conditions

**Comment by KobalDer** [comment]
+1

**Comment by midnightL** [comment]
+1, identical error and conditions.

**Comment by rcrowder** [comment]
+1 (for Classes/ImportTab.lua:454) when importing passive tree and jewels from account Zizaran, character ZizaranDeli (lvl86 necro in SSF standard, his league starter rip).

**Comment by thathobo** [comment]
+1, identical error message and conditions

**Comment by Openarl** [comment]
This is fixed in the latest update.
