### ISSUE TITLE
Cluster Jewel enchantments behaving incorrectly

### ISSUE THREAD

**Issue by Quotae** [Openarl/PathOfBuilding#1882]
Importing this jewel (Ctrl+C info from in-game):

```
Rarity: Rare
Phoenix Shard
Large Cluster Jewel
--------
Item Level: 63
--------
Adds 10 Passive Skills (enchant)
Added Small Passive Skills grant: 10% increased Spell Damage (enchant)
--------
1 Added Passive Skill is Practiced Caster
1 Added Passive Skill is Sap Psyche
1 Added Passive Skill is a Jewel Socket
--------
Place into an allocated Large Jewel Socket on the Passive Skill Tree. Added passives do not interact with jewel radiuses. Right click to remove from the Socket.
```

Shows this item card:
![image](https://user-images.githubusercontent.com/39030429/76688596-4ca0ec00-65fc-11ea-80c0-c30eae7fb2f4.png)

Then, once I hit "Add to Build", the enchantments switch to 12 Passive Skills and Attack Damage:
![image](https://user-images.githubusercontent.com/39030429/76688601-604c5280-65fc-11ea-8d44-5e0af21514db.png)

Then, even if I go to Edit the item and change the enchantments to the proper mods, my changes are ignored after hitting Save.

If I use Craft Item... to make my own jewel with these exact properties, the enchantments save properly.

Also, even the crafted jewel which says "Adds 10 Passive Skills" actually adds 12 skills when socketed, but that might just be a limit of the current implementation:
![image](https://user-images.githubusercontent.com/39030429/76688712-452e1280-65fd-11ea-89eb-713f2da506fd.png)

**Comment by Openarl** [comment]
This should be fixed in the next update.
