### ISSUE TITLE
Error when importing character tree and jewels

### ISSUE THREAD

**Issue by Cyanyx** [Openarl/PathOfBuilding#1884]
Greetings.

Long time usere of PoB, never had any problems but since the patch 3.10, or the latest PoB releases (starting from 1.4.160) i cannot import character tree using the character import window.
Items and skills seem to work fine though.

Error:
In download callback/ Classes/importtab.lua:550 : attempt to index fields "jewelsots" (a nil value)

https://imgur.com/hTn0bOS

**Comment by Openarl** [comment]
Are you trying to import to a build that is using an old version of the passive tree? That's the only way I can see that error occurring.

**Comment by Openarl** [comment]
This should be fixed in the next update.
