### ISSUE TITLE
Cluster Jewel "Added small passives have #% increased effect" does not show correct numbers on tree

### ISSUE THREAD

**Issue by MrCurlyFries** [Openarl/PathOfBuilding#1896]
Unfortunately I don't know if this is just visual or also applies to calculations.
Images for evidence

In Path Of Exile Client
![image](https://user-images.githubusercontent.com/62421959/77148963-b893c080-6ae4-11ea-8a5d-0d70e01c9112.png)

![image](https://user-images.githubusercontent.com/62421959/77149007-cc3f2700-6ae4-11ea-8c3e-60bc4005bcb4.png)

In POB Client
![image](https://user-images.githubusercontent.com/62421959/77149252-45d71500-6ae5-11ea-9906-1019e9996837.png)

~to show that the jewel is in the tree
![image](https://user-images.githubusercontent.com/62421959/77149309-62734d00-6ae5-11ea-9592-7e38dea32ba0.png)

**Comment by Openarl** [comment]
This is just a display issue; PoB doesn't have the ability to easily modify the description of passive skills (which is why radius jewels that modify nearby passives don't visually change them in PoB, but the modified stats do apply).
