### ISSUE TITLE
ring template and flat ele damage to attacks

### ISSUE THREAD

**Issue by mey1R** [Openarl/PathOfBuilding#19]
It's not possible to add "cold, fire or lightning to attacks" for any rare ring template.

**Comment by dein0s** [comment]
Yep, can confirm that this affixes are missing in ring templates.
Also some other affixes are missing too (checked '+ to Evasion', '% of Physical Attack Damage Leeched as Life/Mana'). Not counting new ones from essences, just default from http://poeaffix.net/
Hard to implement or just forgot to put them in templates?

**Comment by Openarl** [comment]
Affixes are added to templates manually; so it's almost always the case that I haven't bothered to include them. I've generally been added them as people request them, so I'll put these ones on (minus the leech one for now since PoB doesn't do leech calculations (yet!)).

**Comment by mey1R** [comment]
Much appreciated as always :)
