### ISSUE TITLE
[BUG] Poison Counted Incorrectly with The Consuming Dark

### ISSUE THREAD

**Issue by Veracior** [Openarl/PathOfBuilding#190]
It seems that _The Consuming Dark, Fiend Dagger_ counts all physical damage towards poison as well as chaos when the item states _Your Chaos Damage Poisons Enemies_ so I believe it should only be counting the chaos portion of the skills damage.

**Comment by Openarl** [comment]
The "chaos damage can poison" stat is currently implemented as a 100% poison chance. Factoring it in correctly is actually quite tricky to do; but since it's been brought up I will take a look at it.

**Comment by Openarl** [comment]
It took me longer than I would've liked to find a good solution for this, but this will finally be fixed in the next update.
