### ISSUE TITLE
LUA Error when try to set skills gems

### ISSUE THREAD

**Issue by bloddymane** [Openarl/PathOfBuilding#1906]
![image](https://user-images.githubusercontent.com/62486460/77237469-cf96e900-6b9e-11ea-9d26-1656effdf5c0.png)

![image](https://user-images.githubusercontent.com/62486460/77237489-f6551f80-6b9e-11ea-9b4a-3ef03b88a9bc.png)

**Comment by Openarl** [comment]
You're using the community fork; issues with that should be reported on their [GitHub site](https://github.com/PathOfBuildingCommunity/PathOfBuilding).
