### ISSUE TITLE
Question regarding "Total DPS inc. Poison" Calc

### ISSUE THREAD

**Issue by kyrious** [Openarl/PathOfBuilding#191]
Hey,

I am currently building a Tornado Shot Poison Build and the Calced Stats look like this:

Total DPS: 28k
Poison DPS: 11.4k
Total Damage per Poison: 55.1k
Total DPS inc. Poison: 202.8k
with an Attack Rate of 3.56 and a Hit Chance of 89%

How is the "Total DPS inc. Poison" calculated, because i can not seem to see through the code how such a high number is achieved.

**Comment by Openarl** [comment]
The simplified formula is:
Total DPS inc. Poison = <Total DPS> + <Total Damage per Poison> x <Poison Chance> x <Hit Chance> x <Attack Rate>
So it's your DPS from hits, plus the damage per poison stack multiplied by the number of poison stacks inflicted each second. It seems high, but it is a fairly accurate estimate of your peak DPS, which is what you'll be doing if you attack non-stop for long enough for poison stacks to start expiring.

**Comment by kyrious** [comment]
Ah ok.
I forgot the poison stacks already applied. Thanks for the clarification.
