### ISSUE TITLE
Large Cluster jewel not showing up

### ISSUE THREAD

**Issue by THSBDK** [Openarl/PathOfBuilding#1921]
Hello love your work.

This jewel does not show up:

Rapture Ruin
Large Cluster Jewel
Unique ID: fff31ae8b3e300b980d76b690b8660804fc95c94c9c6e7a686f368545197eaed
Item Level: 78
LevelReq: 60
Implicits: 3
{crafted}Adds 9 Passive Skills
{crafted}Added Small Passive Skills grant: Claw Attacks deal 12% increased Damage with Hits and Ailments Added Small Passive Skills grant: Dagger Attacks deal 12% increased Damage with Hits and Ailments
Corrupted Blood cannot be inflicted on you
Added Small Passive Skills have 25% increased Effect
1 Added Passive Skill is Wind-up
2 Added Passive Skills are Jewel Sockets
Corrupted

**Comment by Toverkol** [comment]
Same here but with a Sceptre/Staff cluster jewel giving fortify and explosions:

Rarity: Rare
Empyrean Essence
Large Cluster Jewel
--------
Requirements:
Level: 54
--------
Item Level: 79
--------
Adds 9 Passive Skills (enchant)
Added Small Passive Skills grant: Staff Attacks deal 12% increased Damage with Hits and Ailments
Added Small Passive Skills grant: Mace or Sceptre Attacks deal 12% increased Damage with Hits and Ailments (enchant)
--------
Added Small Passive Skills also grant: 2% increased Attack Speed
1 Added Passive Skill is Devastator
1 Added Passive Skill is Overlord
1 Added Passive Skill is a Jewel Socket
--------
Place into an allocated Large Jewel Socket on the Passive Skill Tree. Added passives do not interact with jewel radiuses. Right click to remove from the Socket.

**Comment by porcupince** [comment]
Same here, updated pob to 1.4.168

Rarity: Rare
Apocalypse Star
Large Cluster Jewel
--------
Item Level: 61
--------
Adds 8 Passive Skills (enchant)
Added Small Passive Skills grant: Claw Attacks deal 12% increased Damage with Hits and Ailments
Added Small Passive Skills grant: Dagger Attacks deal 12% increased Damage with Hits and Ailments (enchant)
--------
1 Added Passive Skill is Deep Cuts
1 Added Passive Skill is Drive the Destruction
1 Added Passive Skill is Martial Prowess
1 Added Passive Skill is a Jewel Socket
--------
Place into an allocated Large Jewel Socket on the Passive Skill Tree. Added passives do not interact with jewel radiuses. Right click to remove from the Socket.

**Comment by corosou** [comment]
Using 2 Nebulochs:
![image](https://user-images.githubusercontent.com/28074748/78096856-c41a9d80-73a8-11ea-9eba-03ebe63c66c7.png)

I have to manually edit the Jewel to say "Added Small Passive Skills grant: 10% increased Attack Damage" so it activates:
![image](https://user-images.githubusercontent.com/28074748/78097137-7488a180-73a9-11ea-89a2-a627259c9e63.png)

**Comment by Vayte** [comment]
Hi,

This is also affecting myself. I am running version 1.4.168 using the below large cluster jewel.

Sol Prism
Large Cluster Jewel
Unique ID: cebcee25815a1325baf6906b2b91e4535d1421c14ccb128e2b7f22b370adc603
Item Level: 64
Implicits: 2
{crafted}Adds 9 Passive Skills
{crafted}Added Small Passive Skills grant: Claw Attacks deal 12% increased Damage with Hits and Ailments Added Small Passive Skills grant: Dagger Attacks deal 12% increased Damage with Hits and Ailments
Added Small Passive Skills also grant: +2 to All Attributes
1 Added Passive Skill is Fan of Blades
1 Added Passive Skill is Martial Prowess

**Comment by Openarl** [comment]
This should be fixed in the next update.
