### ISSUE TITLE
[Bug] The Beast Fur Shawl and ES Regen via Zealot's Oath

### ISSUE THREAD

**Issue by MasterScooby** [Openarl/PathOfBuilding#193]
The Beast Fur Shawl's ES Recovery Rate (and also Trickster Patient Reaper) should be applied to ES Regen gained from Zealot's Oath.

**Comment by Openarl** [comment]
The stat from The Beast Fur Shawl seems to be working for me; although during testing I did discover that the ES regen percentage in the Calcs tab wasn't displaying the correct value when an ES Recovery modifier was present. The flat regen amount, as displayed there and in the sidebar, is correct, though.

As for Patient Reaper, I haven't added support for the Recovery portion of that passive yet. It should be easy though.

**Comment by MasterScooby** [comment]
Ah I didn't calculate the actual number just noticed the % didn't change when toggling Zealot's Oath on and off.  And that Beast was was not listed when hovering over the regen.  Calculating the % manually it does show the correct regen, so just a % display bug.  Thanks for the great tool!

**Comment by Openarl** [comment]
Patient Reaper will be properly supported as of the next update, so I think it's safe to close this.
