### ISSUE TITLE
Inevitable Judgement and Flammability

### ISSUE THREAD

**Issue by JYshadow** [Openarl/PathOfBuilding#195]
Hi, I've noticed that Flammability still applies to the ignite damage while Inevitable Judgement is enabled, but it shouldn't. I've also set the ignite calculation mode on 'crit only', so it should show the ignite damage when the resistances are ignored. Or maybe I'm missing something?

**Comment by Openarl** [comment]
Ignites are damage over time, they do not and cannot crit, therefore ignites cannot be affected by Inevitable Judgement, even if they are applied by a crit. This is working as intended.
