### ISSUE TITLE
[Bug] 2.6.0 Data Storm Weaver wheel rendering

### ISSUE THREAD

**Issue by krab** [Openarl/PathOfBuilding#197]
Very strange path rendering visual bug. Fresh portable copy full updated.

http://i.imgur.com/U0R2FZB.png
http://i.imgur.com/XJI01A5.png

**Comment by Openarl** [comment]
Yes, I've already been made aware of this. It seems the pathing for that cluster in the passive tree data is messed up; I can't fix the pathing but the next update will allow the current pathing to be correctly rendered.

**Comment by Openarl** [comment]
The rendering is fixed; the pathing is GGG's issue so I'll close this now.
