### ISSUE TITLE
Error when try to open build

### ISSUE THREAD

**Issue by Skelqua** [Openarl/PathOfBuilding#1972]
Hello,
When try to open the following pastbin https://pastebin.com/pQ0jZisb
I got an error and not able to open see attach file
![IgLXU9OiMPo](https://user-images.githubusercontent.com/67103251/85015698-17fb7e00-b171-11ea-877f-6628db3c590e.jpg)

**Comment by Kyuzik** [comment]
You have a pastebin for the community branch build

**Comment by Skelqua** [comment]
> You have a pastebin for the community branch build

Thanks for advice. Downloaded community version - issue resolved.
