### ISSUE TITLE
Thread of Hope Crimson Jewel

### ISSUE THREAD

**Issue by thisVioletHydra** [Openarl/PathOfBuilding#1985]
### How can I adjust the radius?

![image](https://user-images.githubusercontent.com/11839238/86002244-c37dbb80-ba18-11ea-9dd3-e2c1f180eb9e.png)

`Only affects Passives in Very Large Ring`

![image](https://user-images.githubusercontent.com/11839238/86002425-fcb62b80-ba18-11ea-9f1a-231566921d56.png)

**Comment by i3igpete** [comment]
You can either edit the text on an existing jewel, or use the unique item selector. The unique item selector will have a combo box with the radius options.

**Comment by thisVioletHydra** [comment]
> You can either edit the text on an existing jewel, or use the unique item selector. The unique item selector will have a combo box with the radius options.

![image](https://user-images.githubusercontent.com/11839238/86023915-0057ab80-ba35-11ea-91b7-ba8abacfce57.png)
What should i do now?

**Comment by thisVioletHydra** [comment]
⚰️ rip
