### ISSUE TITLE
How do I program using open source?

### ISSUE THREAD

**Issue by batebono** [Openarl/PathOfBuilding#1996]
am going to program using the open source of path of building.

How should I build the program?
Can I use the visual studio?

I'm sorry for the poor and sloppy question.

**Comment by Velzar** [comment]
you can use VS + Visual Studio Extension for Lua
https://marketplace.visualstudio.com/items?itemName=VisualCppDevLabs.VisualStudioExtensionforLua

**Comment by wellzar** [comment]
> am going to program using the open source of path of building.
> 
> How should I build the program?
> Can I use the visual studio?
> 
> I'm sorry for the poor and sloppy question.

please label this issue as question
