### ISSUE TITLE
[BUG] Cannot delete equipped item v 1.0.2

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#2]
First of all I want to thank you for your job and this amazing tool :) Was missing lots of your features in skill tree planner and forced to use online tools/own math spreadsheets. So, again - thanks a lot!

And now to the bug by steps:
- in 'Items' tab I've added Kintsugi to my build from bottom import list
![Import list](http://i.imgur.com/p6CQ62a.png) ![All items](http://i.imgur.com/rL5PKdV.png)
- equipped it

![Equipped items](http://i.imgur.com/K3zdRVt.png)
- after I realised that my current gear can be copy-pasted from ingame
- added another kintsugi

![All items again](http://i.imgur.com/ZGzBCe8.png)
- now without re-equipping I've tried to delete the first kintsugi in the list
![Delete this](http://i.imgur.com/gy91kOr.png)
- pressed 'Delete' button, but nothing happened, it's still in 'All items' list
![No magic](http://i.imgur.com/XVmlpC8.png)

That's all I have for now, will continue with exploring. And, btw, if there's any way to record logs - let me know, so next time I can provide them also.

**Comment by Openarl** [comment]
Thanks for the report! I've pushed an update that fixes this.
