### ISSUE TITLE
[BUG] Incorrect deletion of gem rows on 'Skills' tab in skill chain

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#20]
Steps:
1. Add new skill chain on 'Skills' tab
![Skill_chain](http://i.imgur.com/zO5g3YC.png)
2. Delete name, level and quality of some gem in the middle (Cont Destr here)
![Delete_name](http://i.imgur.com/ZTQGMxD.png)
3. After deletion of gem's level from p.2 row for gem 'Slower Proj' was also deleted
![Delete_level](http://i.imgur.com/fBBp0SL.png)

**Comment by Openarl** [comment]
Fixed. As it turns out it wasn't actually deleting the last gem but simply failing to update the controls properly. Thanks for the detailed report!
