### ISSUE TITLE
[Bug] Emberwake + The Taming

### ISSUE THREAD

**Issue by sbfussy** [Openarl/PathOfBuilding#200]
The Taming gives 10% increased damage per ignite on the enemy, however it does not seem to be factoring in correctly with the increased ignite count from Emberwake. If I understand the interaction correctly, each ignite stack should add 10% damage, not just the first.

**Comment by Openarl** [comment]
I haven't added support for the increase damage per ignite modifier yet. While it's possible for the program to calculate the maximum concurrent ignites, I'd be hesitant about piping that straight into that modifier, as the results are likely to be wildly optimistic in real-world conditions.

I might add an option to the Configuration tab to specify the number of ignites on the target, but until then, here's the silly workaround I used when I did an Emberwake/Taming build:
`Rarity: Unique
The Taming Hax
Prismatic Ring
League: Domination, Nemesis
Implicits: 1
{range:0.21}+(8 to 10)% to all Elemental Resistances
{range:0.13}(100-3000)% increased Damage against Ignited Enemies
15% increased Elemental Damage with Weapons
{range:0.5}+(10 to 15)% to all Elemental Resistances
15% increased Elemental Damage
5% chance to Freeze, Shock and Ignite`

**Comment by sbfussy** [comment]
It is understandable to not want to show optimistic approximations, such as the case with Firestorm. Thanks for the quick reply, the adhoc Taming Hax item, and even more for all your work with Path of Building. Cheers.

**Comment by Openarl** [comment]
The next update adds a "# of Freeze/Shock/Ignite on Enemy" option to the Configuration tab, so RIP Taming Hax :).
