### ISSUE TITLE
[Bug] Vaal Disc inocrrectly grants bonus ES

### ISSUE THREAD

**Issue by DanielLambert** [Openarl/PathOfBuilding#201]
In version 1.3.13, adding Vaal discipline to an skill group and marking it as "enabled" grants bonus ES proportional to the level of Vaal Discipline. According to the 2.6.0 patch notes, Vaal discipline no longer gives bonus energy shield.

**Comment by Openarl** [comment]
Most of the skill changes for 2.6 haven't been made yet; I need the exact numbers and stats, and the only way I'll get those is from the game data files once the patch is out. I will remove VDisc's energy shield now though, since it's a major change.
