### ISSUE TITLE
🐔[Release 1.4.170 BUG] Importing any builds not working! 

### ISSUE THREAD

**Issue by thisVioletHydra** [Openarl/PathOfBuilding#2025]
```log
dervish build
imports
Lovel 100 Ascendant
Lejel 91 Ascendant
Error:
In 'OnFrame': Modules/Bulld.lua:133: attempt to index field 'malnOutput' (a nil value)
stack traceback:
Modules/Build.lua:133: in function 'GetProperty
Classes/Control.lua:80: in function 'Getsize'
Modules/Build.lua: 124: In function 'GetProperty
Classes/Control.lua:57: In function 'GetPos'
Classes/Controllua:60: In function 'GetPos!
Classes/Edit Control.lua:186: in function 'Draw
Classes/ControlHost.lua:77: In function 'DrawControls'
Modules/Build.lua:807: In function 'Call Mode'
ModulesMain.lua:254: in function <Modules/Main.lua:233>
[C]: in function 'PCall'
tal Tools\POWER-Tools\Path of Building\Launch.lua:99: In function <...ync Sync Total Tools\POWER-Tools\Path of Building\Laun
Press Enter/Escape to Dismiss, or F5 to restart the application.
```

**Comment by Ghost1111onskates** [comment]
I'm having the same problem

**Comment by TwoPluzTwo** [comment]
That is happening to me as well. Tried updating/uninstalling and reinstalling. Still happening.

**Comment by Loppor** [comment]
Having the same problem here, this needs to be addressed ASAP! This is basic functionality and should be caught by automated tests (i'm a dev myself so I know what I'm talking about).... Added screenshot of the error as well
![image](https://user-images.githubusercontent.com/33860108/95673456-ea679400-0ba8-11eb-9fbc-083efb2b574b.png)

**Comment by insydeAFK** [comment]
> 
> 
> Having the same problem here, this needs to be addressed ASAP! This is basic functionality and should be caught by automated tests (i'm a dev myself so I know what I'm talking about).... Added screenshot of the error as well
> ![image](https://user-images.githubusercontent.com/33860108/95673456-ea679400-0ba8-11eb-9fbc-083efb2b574b.png)

same here

**Comment by slindagor** [comment]
The problem still exists, does anyone know sollution for this?

**Comment by thisVioletHydra** [comment]
> The problem still exists, does anyone know sollution for this?

https://pathofbuilding.community/
