### ISSUE TITLE
[Bug] Error when using brackets in Gem Text Field

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#203]
![image](https://cloud.githubusercontent.com/assets/510805/23498256/78e21e3a-feec-11e6-8d4d-1e7a31acd03b.png)

Accidentally hit left square bracket and got an error.

**Comment by aggixx** [comment]
Its a recoverable error but probably makes sense to not allow brackets in that field at all.

**Comment by Openarl** [comment]
This is already fixed in the next update. It actually shouldn't have been allowing brackets there, but they were being allowed owing to a fairly silly error on my part.
