### ISSUE TITLE
[Feature] Regex or custom tokens in node search

### ISSUE THREAD

**Issue by just-a-bird** [Openarl/PathOfBuilding#208]
By custom tokens I mean something like the ability to search "+x to maximum Life" and recognize that "x" is a numerical wildcard.

**Comment by Openarl** [comment]
Actually, this already exists, although undocumented. The passive tree search bar allows the use of [Lua patterns](http://www.lua.org/manual/5.1/manual.html#5.4.1), which are a limited form of regex. For your example, "+%d+ to maximum life" does the trick.

**Comment by just-a-bird** [comment]
Oh, nice!
