### ISSUE TITLE
Unique DB unrecognized item type of 'new';

### ISSUE THREAD

**Issue by NubScrub** [Openarl/PathOfBuilding#209]
![Screenshot](http://i.imgur.com/SsLBtqz.png)

Followed by a whitescreen and it hangs.

I seem to have the worst luck when the built-in updater tries to update, I always have to use the installer to fix.

Either way this doesn't look many people have this issue thought I might just post it anyway.

**Comment by Openarl** [comment]
That error message is actually perfectly harmless, and wouldn't have anything to do with the hang.

Someone reported the same issue in [the forum thread](https://www.pathofexile.com/forum/view-thread/1716360/page/77#p14238276); was that you? If not then you might have the same cause.

**Comment by NubScrub** [comment]
That was not me, I will PM Hyron and see how he managed to fix the issue as I'm running a Multi-Monitor setup also.

**Comment by Openarl** [comment]
Ah, interesting that you both have that in common. There might be an issue with the window handling code, then; I'll take a look at it when I can.  
Could you give more specifics about your setup? How many monitors, and what OS are you running? I know it's not a general conflict with multiple monitors as I used 4 myself, so there'll be something specific about your system that's triggering it.

**Comment by NubScrub** [comment]
2 monitors, 1 Asus VG278HE, 1 Samsung TV via HDMI.

Windows Home x64

Nvidia 1080 SLi

Would be happy do dump dxdiag and msinfo for you if it would provide any extra debugging information? 

On a side note, didn't see a crash log anywhere in the folders or have you not implemented it?

**Comment by Openarl** [comment]
I haven't implemented a crash log for the host application; I've had very few crash reports for it, as the vast majority of code is in Lua, and errors there are handled better.

I'm currently going over the window handling code again; the timing of the hang gives me some idea where the problem might lie. I'll let you know if I find anything.

**Comment by Openarl** [comment]
The "chosen" issue for this bug is #336, so I will close this as a duplicate. The bug itself should be fixed in the next update, though.
