### ISSUE TITLE
Fire Trap base fire damage per sec wrong calculations

### ISSUE THREAD

**Issue by AmarokWolfy** [Openarl/PathOfBuilding#2114]
I just checked on the Poedb and in game that the PoB number for Fire Trap base fire damage per sec is not corresponding to what the datas seem to indicate.

**Comment by QuickStick123** [comment]
This repo is older and not used for active development please repost on https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues if you still are having this problem.
