### ISSUE TITLE
[BUG] Poison Calculated Incorrectly

### ISSUE THREAD

**Issue by Toraeus** [Openarl/PathOfBuilding#214]
While using the Poison Support gem, sources of elemental damage (Taste of Hate, Added Lightning Support) also increase the Base Damage that Poison is calculated from.

Perhaps related to [#190: [BUG] Poison Counted Incorrectly with The Consuming Dark ](github.com/Openarl/PathOfBuilding/issues/190)

**Comment by Openarl** [comment]
With the way the program calculates poison base damage it's absolutely impossible for elemental damage to contribute directly. You must have some sort of elemental to chaos conversion present; Atziri's Promise, perhaps?

**Comment by Toraeus** [comment]
Well I feel like a dunce- it was Atziri's Promise (I completely forgot about the ele conversion!).

Thanks for all the great work!
