### ISSUE TITLE
[Bug] Stormweaver cluster

### ISSUE THREAD

**Issue by lutem** [Openarl/PathOfBuilding#215]
![image](https://cloud.githubusercontent.com/assets/15162911/23542111/553f1f64-ffb9-11e6-93f0-cbe9bffca751.png)

first node isn't supposed to be directly linked to the notable
v1.3.15

**Comment by Openarl** [comment]
I don't control what nodes are connected; that's all specified in the tree JSON that GGG provided. I don't know if the connections in that cluster are necessarily intended, as they are a bit odd, but I can't do anything about it.

**Comment by Openarl** [comment]
Ok, now that the patch is out I've acquired updated passive tree data, which fixes this cluster.
