### ISSUE TITLE
Official Request on behalf of those wanting to show some gratitude.

### ISSUE THREAD

**Issue by NubScrub** [Openarl/PathOfBuilding#217]
Where is your donate to coffee/beer fund button !?

Honestly you have been working damn hard, pumped out a bunch of commits and how is a man supposed to buy you a before & after work drink?

Don't think it being vain but you should put a donate link with a service of your choice on both your GitHub and Path of Exile forum thread.

**Comment by Openarl** [comment]
I've finally gotten around to creating a [Patreon page](https://www.patreon.com/openarl), so you can help support the development of the program (or just throw money at me because I'm awesome :P)
