### ISSUE TITLE
Flammability is stacking on skill

### ISSUE THREAD

**Issue by Gander7** [Openarl/PathOfBuilding#218]
I don't believe Flammability should stack on my orb of storms skill.
Build Code: http://pastebin.com/4ejbG4bP
With 1 Flammability enabled: 
![image](https://cloud.githubusercontent.com/assets/4229134/23559937/0e075f5c-000f-11e7-9940-e75e1cad822d.png)

With 2 Flammability enabled:
![image](https://cloud.githubusercontent.com/assets/4229134/23559964/207fb864-000f-11e7-824b-93fd983e420d.png)

Version: 1.3.16 on Windows 10

**Comment by Openarl** [comment]
It's a limitation of the calculation code's current design that it can't correctly handle duplicate curses/buffs/etc. It's also described in #171, so I'll close this one.
