### ISSUE TITLE
[bug] program freezes on import tree url 

### ISSUE THREAD

**Issue by krab** [Openarl/PathOfBuilding#219]
It happens when server down, for example poeurl.com servers down atm. So probably better to run all network stuff in different thread? It will prevent UI from freezes.

http://i.imgur.com/eg0bG8e.png
http://i.imgur.com/DPKjsrW.png

**Comment by Openarl** [comment]
The tree import dialog box is actually the only place in the entire program where a network request is made in the main thread; everywhere else (including the tree _export_ dialog) uses a central download manager that runs in a separate thread. I can't quite recall why I did it that way, but I'll take a look when I get time.

**Comment by Openarl** [comment]
I finally got around to creating a fix for this; as usual it's in the next update.
