### ISSUE TITLE
[BUG] Vaal Haste buff doesn't counts

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#22]
Attack/cast rate with active Vaal Haste
![active](http://i.imgur.com/denbPHH.png)
Attack/cast rate with inactive Vaal Haste
![inactive](http://i.imgur.com/et94ayz.png)

**Comment by Openarl** [comment]
Fixed. Turns out NONE of the Vaal auras were working correctly as I hadn't marked their effects as aura effects. Oops!
