### ISSUE TITLE
Cannot import foil uniques.

### ISSUE THREAD

**Issue by DeadLeaves** [Openarl/PathOfBuilding#225]
When trying to import foil uniques, the slot where the foil unique is remains empty or whatever was there before the import. The CTRL+C of a foil unique looks like this:

```
Rarity:

Normal
Goldwyrm
Nubuck Boots
--------
Quality: +20% (augmented)
Evasion Rating: 118 (augmented)
--------
Requirements:
Level: 68
Str: 71
Dex: 62
Int: 108
--------
Sockets: G-B-B-R 
--------
Item Level: 75
--------
60% increased Mana Regeneration Rate
20% increased Quantity of Items found
+48% to Fire Resistance
10% increased Movement Speed
--------
The wyrm draws warmth from the fires of desire.
--------
Relic Unique
--------
Has Legacy Boots
Has Legacy Footprints Effect

```

**Comment by PatrickGriffiths** [comment]
You shouldn't need to import these. 

You can set which version of the unique you'd like to use, inside of PoB. When you search and find the unique that you're looking for, in this case "Goldwyrm" in the top right you can see a drop down menu that is reading as "current" if you select that you can choose the variant that you wish to use. 

Here's an image.
http://i.imgur.com/WGDwFvV.png

**Comment by PatrickGriffiths** [comment]
I will include more information on this kind of thing in the documentation some time in the next 24hrs.

**Comment by Openarl** [comment]
An item failing to import is a perfectly valid issue; the fact that it can be replicated using the unique database is irrelevant.

I'll look into this once I can get my hands on a foil unique to test with.

**Comment by PatrickGriffiths** [comment]
@Openarl I can give you one on Legacy to test this with when I log in next.

**Comment by Openarl** [comment]
Fixed in the next update.
