### ISSUE TITLE
[Bug] "Extra Chaos Damage" being displayed as "Converted Chaos Damage"

### ISSUE THREAD

**Issue by DanielLambert** [Openarl/PathOfBuilding#227]
The `Gain #% of Physical Damage as Extra Chaos Damage` modifier is not displaying correctly on the "Calcs" screen. The actual damage calculation appears to be correct. The program appears to be incorrectly displaying `Gain #% of Physical Damage as Extra Chaos Damage` as `#% of Physical Damage Converted to Chaos Damage`.

Version: 1.3.18

Steps to reproduce:

1. Create a new build
2. Add `Ming's Heart, Amethyst Ring` as an equipped item
3. Add `Shockwave Totem` as an active skill

Observed behavior: 

When hovering over the "Skill Hit Damage" row in the "Chaos" column of the "Skill Hit Damage" table, the pop-up tool-tip incorrectly states that 20% of our physical damage is being converted to chaos damage.  However, the damage appears to be calculated correctly. This can be seen by observing only the physical damage (231-429) and removing all equipped items. The physical damage value will not change, but the total skill hit damage will change. 

This same behavior can be observed using any combination of `Ming's Heart, Amethyst Ring` and/or `Obliteration, Demon's Horn`.

**Comment by Openarl** [comment]
This is not a bug. "Gain as X" and "Convert to X" are both types of damage conversion; they use exactly the same mechanics and calculation code, except that "Convert to X" also reduces the final damage total of the source type. Consequently, they are combined together under the "Conversion" heading, and in fact it's not possible to list them separately, as they are combined long before the hit damage calculation occurs (which is when the table in the breakdown is populated).

I do agree that it can be misleading, but it merely reflects the underlying mechanics of the damage calculations, and some understanding of those mechanics will always be necessary if you are to correctly interpret the output of the hit damage calculations (especially when conversions are involved).

**Comment by DanielLambert** [comment]
After considering what you said and reading the wiki page carefully, I understand why you have chosen to represent the conversion in such a confusing manner. It is a shame that the terminology is so convoluted between "converted to" and "conversion to". Surely there must be a better way of representing the information! I mean, just look at this mess:

Initial physical damage (200)
-Converted to Chaos (50% of dmg)
-Added as Chaos (25% extra dmg)
-Total conversion to Chaos (75% of dmg)

Final Physical damage (100 dmg) 
**dispite "75%" conversion to chaos"**

Initial Chaos damage (0 dmg)

Final Chaos damage (150 dmg)
-Converted from physical (100% of dmg)
**dispite "75%" conversion to chaos.**
