### ISSUE TITLE
[Feature] Growing Agony

### ISSUE THREAD

**Issue by Crazy-KSK** [Openarl/PathOfBuilding#229]
Would be nice if you could add the "2% increased Attack Damage for each Poison" from Growing Agony.
Its kinda hard to calculate by hand. :sweat_smile:

**Comment by Openarl** [comment]
The next update adds a "# of Poison on Enemy" input to the Configuration tab; also, the Poison section of the Calcs tab will now display "Max Poison Stacks", which you can use to derive a reasonable input for the poison count.
