### ISSUE TITLE
[BUG] Error on copy-paste skill chain

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#23]
Step by step:
1. Copy existing chain
![copy](http://i.imgur.com/wiifIBm.png)
2. Paste it (guess it's because of 'Enabled' checkbox for the blank line)
![paste](http://i.imgur.com/lznEMJh.png)
3. Hit 'Escape' and try to unset 'Enabled' checkbox for the blank line - one more blank line added with 'Enabled' checkbox, error appear again
![error_again](http://i.imgur.com/NfB7bCt.png)

**Comment by Openarl** [comment]
Fixed. The error resulted from disabling the active gem within a skill, which was being triggered in this case because the gem enable/disable state wasn't being preserved when copying and pasting skills (which is also fixed!).
