### ISSUE TITLE
[Feature Modifier to see/hide node gains/losses

### ISSUE THREAD

**Issue by StingrayNine** [Openarl/PathOfBuilding#230]
Hi. As the title says I would like to suggest a modifier (toggle or hold) to show/hide the bonuses you gain/lose by allocating a node on the tree.
I find it can get in the way if you just want to read the node.
See [image](http://i.imgur.com/JjhvSEf.png) or [image2](http://i.imgur.com/0ZL7PEN.png) as an example. If you just want to quickly read the node you're assaulted with a screen-full of other text.

Any thoughts on the idea?

((Also, the deep blue colors of node power is hard to distinguish. Maybe a change of hue?))

**Comment by Openarl** [comment]
As of the next update, Ctrl+D will toggle the stat difference display.

Also, I've added an Options screen, and one of the options allows you to change the colour scheme of the node power display; you can choose from Red+Blue, Red+Green, Green+Blue.
