### ISSUE TITLE
Crit broken

### ISSUE THREAD

**Issue by rhazor** [Openarl/PathOfBuilding#231]
![123](https://cloud.githubusercontent.com/assets/22996586/23799643/ee7d0666-05b1-11e7-81b9-4de34c83b11d.gif)

Power charges, Assassins Mark, Crit nodes, etc on Hegemony's Staff doesn't got past 64% nor below as seen in .gif? E.g. the Serpent Stance noble when hovered it doesn't give any % crit in green text, only multiplier, etc.

**Comment by rhazor** [comment]
Edit: I think everything is broken, I don't know what I did, but half nodes don't calculate DPS or ticking/unticking dex/int nodes on Ranger's adjust % crit. Something is real broken.

**Comment by Openarl** [comment]
Your crit chance is capped; and because the program simulates the crit confirmation roll, your effective crit chance ends up being lower than 95% (much lower in your case). You _really_ need to get some more accuracy!

**Comment by rhazor** [comment]
OK I stacked flat accuracy on gear e.g. +900 total from gloves and rings and e.g. ticking/unticking Coungerweight does no affect to total % crit roll. Now it's just stuck at 81%. I don't understand, cap was always 95% no matter what. E.g. toggling Assassin's Mark affects DPS, but not % crit roll.

**Comment by Openarl** [comment]
With attacks, there is a second accuracy check that occurs after the crit roll succeeds that "confirms" the crit. If your actual crit chance is capped at 95%, but your hit chance is only 80%, then only 80% of crit rolls that succeed will actually be crits, making your effective crit chance 95% x 80% = 76%, and that is what is displayed by the program. This calculation is fully worked out in the breakdown for crit chance in the Calcs tab (which also shows how far over the cap you are).

**Comment by rhazor** [comment]
Which one shows over the cap crit?

**Comment by Openarl** [comment]
It's all under Crit Chance:
![foo](https://cloud.githubusercontent.com/assets/19189971/23801907/73be85f2-05fd-11e7-8645-a3e021d1aba6.png)

**Comment by rhazor** [comment]
I made it to chance to hit 95% so 95% (capped crit) x 0.95% (chance to hit) = 90.25% total crit.

So since it's not possible to go past 95% chance to hit no matter how much accuracy stacked then how do you get 95% crit capped?

I swear God I've played Hege's EQ a year ago and in-game stats (with power charges up) showed my crit capped at 95% and I cannot manage to recreate this on your program.

**Comment by Openarl** [comment]
The in-game crit chance does not factor in accuracy. I don't know why; perhaps because the chance to hit itself is only an estimate.

**Comment by rhazor** [comment]
Oh great in-game crap is yet again just misleading.
