### ISSUE TITLE
Ground Slam damage seems wrong

### ISSUE THREAD

**Issue by Zervox** [Openarl/PathOfBuilding#232]
Seeing the modifers on the ground slam gem source seems way off, ground slam level 15 has 110%+ something.

**Comment by Openarl** [comment]
The damage multipliers for attack skills are exported directly from the game data files; they shouldn't be wrong. I did check Ground Slam specifically, and everything looks correct. Note that the base damage multiplier is converted to a more/less modifier, so 90% of base damage becomes 10% less, and 115% of base damage becomes 15% more.

Where were you looking for the modifiers, by the way? By "gem source", are you referring to the gem data files (act_str.lua etc)? You shouldn't be reading those unless you know exactly how to interpret the data.

**Comment by Zervox** [comment]
Yeah sorry, I found the issue, it had unequiped one of the damage rings for some reason in path of building(maybe I changed it then deleted it).
