### ISSUE TITLE
ö causing issues in custom field

### ISSUE THREAD

**Issue by vegeto079** [Openarl/PathOfBuilding#233]
When creating a custom item, if the umlaut o "ö" is on any line, it behaves very strangely.
Copy this:
>Maelström Splitter Butcher Axe 3 days ago
>Level: 63 Strength: 149 Dexterity: 76 ilvl: 74 Max sockets: 3 (3)

And you can't edit the first line properly.
If you copy just this:
`Maelström Splitter Butcher Axe`
there's a huge space misplaced.

It's hard to explain, but easy to reproduce.

**Comment by dein0s** [comment]
Related to #55

**Comment by vegeto079** [comment]
Related in solution maybe, but these are names of items already in the English game, not to do with localization.

**Comment by dein0s** [comment]
I still don't see how "these are names of items already in the English game" is related to this issue. As been said - PoB doesn't support any unicode subsets apart from [basic latin](https://en.wikipedia.org/wiki/Basic_Latin_(Unicode_block)). And umlauts doesn't belong to this subset.

**Comment by vegeto079** [comment]
It is relevant because the urgency of the issue is a little different when it affects the "base game" and default supported language that is meant to work as-is.
It has been suggested, for example, to use poe.trade and copy the items over to add them, which is how I discovered this bug. It affects what I would call "normal procedure" and expected behavior.

**Comment by Openarl** [comment]
I'm aware of the urgency of this particular case, but that doesn't change the fact that adding full Unicode support will require a considerable investment of time. Anyway, the impact of it is fairly limited, as there's so few items with non-English letters, so I'm not too concerned about it.

**Comment by vegeto079** [comment]
Right, I didn't mean to make it sound mission critical, only comparing it to the posted relation. At the end of the day it's not a huge deal.
I think if it were possible, having question marks or another way of interpreting "unsupported" characters would be preferable to the current situation (especially in this editor since the name doesn't actually matter), as it's really confusing when it happens as the editor just gets...weird. I don't know the viability of that, though, just spitballing.

**Comment by Openarl** [comment]
Yeah, I know the current behaviour is a bit odd in this case; I haven't quite been able to figure out what's going on there, but I'm taking another look at it now.

**Comment by Openarl** [comment]
Oh.... So apparently. the Windows Clipboard API can pass "extended ASCII" characters when getting plain text from the clipboard, so certain non-ASCII characters (like ö) were sneaking across the border and causing havoc with the text renderer. I've added some code to the edit control to catch them, which should prevent the odd behaviour from occurring; there's an exception that turns ö into o, since it is used in English item names.
