### ISSUE TITLE
[Feature] Flask Charges Consumption

### ISSUE THREAD

**Issue by myrahz** [Openarl/PathOfBuilding#234]
Would be really nice to know the and flask charges consumed for each flask you have equipped based on Equipment and Passives.

**Comment by Openarl** [comment]
This already exists; the "Effective flask stats" section of the flask tooltip will show the charges used if you have any global "Flask Charges used" modifiers.
![used](https://cloud.githubusercontent.com/assets/19189971/23827986/4edb1388-070e-11e7-8ff2-c87e41ad1318.png)
