### ISSUE TITLE
[Feature] Custom item sets.

### ISSUE THREAD

**Issue by eskoONE** [Openarl/PathOfBuilding#235]
can we have the option to create sample sets for armoury? would be nice if we could create our own sets and just import em with a button click. going through creating every item again and again just to compare life totals endgame is kinda annoying.

otherwise great work. love this application, wasting several hours a day creating new builds.

**Comment by dein0s** [comment]
Related to #47

**Comment by Openarl** [comment]
1.4.12 added a new item list to the Items tab which is shared between all builds, so you can easily store entire gear sets in there if you want to.
