### ISSUE TITLE
Vulnerability Gem + Witchfire Brew double stacking aura

### ISSUE THREAD

**Issue by flynnzeke** [Openarl/PathOfBuilding#236]
Hi!

As you can see here, the blasphemy setup I have for Vulnerability seems to be stacking with the Vulnerability aura granted by Witchfire Brew?

![](https://cdn.discordapp.com/attachments/174994219390337024/290280803324395520/unknown.png)

**Comment by Openarl** [comment]
Duplicate of #171 
The program doesn't currently check for duplicate curses or buffs, but that'll be fixed eventually.
