### ISSUE TITLE
Necromantic Aegis

### ISSUE THREAD

**Issue by tkalucki** [Openarl/PathOfBuilding#237]
Necromantic Aegis does not remove the shield bonuses from the calculations, even though it should

**Comment by Openarl** [comment]
I haven't added support for Necromantic Aegis yet. It's not trivial to remove the shield bonuses, given the way the program's calculation code works; and fixing it is a low priority since you can just un-equip the shield.

**Comment by tkalucki** [comment]
Alright, just thought I'd post it up, in case it was an undocumented bug

**Comment by Openarl** [comment]
Fixed in 1.4.0.
