### ISSUE TITLE
Addition of a "CONTRIBUTING"-Guide

### ISSUE THREAD

**Issue by berserkingyadis** [Openarl/PathOfBuilding#239]
I think it would it be beneficial to add a guide for other developers to help contribute to the project.

Something like:
- Which Lua modules to install/use
- How to "compile"/make ready for use
- IDEs 
- Documentation about a development enviroment or the class/folder structure
- In general useful information for developers

A contribution guide would help for something like #28 or the other issues which pop up in here

**Comment by Openarl** [comment]
I suppose I should get around to making one, since it wouldn't take very long. There's really not much required to get set up though. I'm rubbish at making documentation though!

**Comment by berserkingyadis** [comment]
For now it would suffice to know how to get the development environment set up. Which programs/libraries to install to get started.

**Comment by Openarl** [comment]
As I said, there's really very little required:
1. Clone the dev branch (all changes are made there first)
2. Create a shortcut to Path of Building.exe in your installation of the program, and pass the path and filename of your local repository's Launch.lua as an argument

You can now use that shortcut to run the program from the repository. Any text editor can be used to edit the source files; I use VS 2015 with [NPLLuaLanguageService](https://marketplace.visualstudio.com/items?itemName=Xizhi.NPLLuaLanguageService) for syntax highlighting. Any changes take effect when the program is restarted (you can use F5 to restart the program in-place; this only works when run from the repository).

**Comment by Openarl** [comment]
Finally got around to adding a basic CONTRIBUTING,
