### ISSUE TITLE
[Feature Request] Add possibility to write and save text notes

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#24]
Would be great, if you can add such feature somewhere. 
It can be used to save forum link to the build guide, search filters on poe.trade and other useful information related to the current build.

**Comment by DanielGrobelny** [comment]
+1

I want to create a build-compendium for the next league.
Current plan is to write down the notes somewhere (google docs probably) and then add a download link to import the actual build with BiS items etc.

Would be neat to have it all in one place.

**Comment by Openarl** [comment]
I'll see what I can do. Need to find a place to put them though. Maybe a separate tab?

**Comment by DanielGrobelny** [comment]
Yes, just another button on the right side of the top bar or another button (in a new row?) on the left side would do.

Just a simple "full screen" text-area that's kind of always editable would do as a start.

Markdown with an "edit" button would be perfect for me.
A WYSIWYG editor would be preferable for "normal" users ... I guess

**Comment by Openarl** [comment]
I just released an update with the new Notes tab. It's just a simple text edit; if you want markdown you'll really have to beg because that'd be a major undertaking (the text edit control used by the program doesn't support any kind of advanced formatting).

**Comment by dein0s** [comment]
Enough for me :) Thanks a lot.
