### ISSUE TITLE
[Bug] Vaal Fireball isn't recognized as AoE spell

### ISSUE THREAD

**Issue by Virenta** [Openarl/PathOfBuilding#240]
Steps to reproduce:
1. Add a Vaal Fireball to your skills
2. On the passive tree navigate to "Amplify" templar node or "Blast radius" witch node
3. This nodes doesn't add any damage to Vaal Fireball

**Comment by Openarl** [comment]
This isn't technically a bug; as with Fireball, Vaal Fireball defaults to showing the projectile damage, which doesn't benefit from area damage modifiers (the in-game tooltip behaves the same way). I will add skill parts to Vaal Fireball in the next update to allow calculation of the explosion damage.
