### ISSUE TITLE
Instruments of virtue mjölner bug

### ISSUE THREAD

**Issue by Hapseleg** [Openarl/PathOfBuilding#242]
Hi, just wanted to let you know there's an oversight when it comes to instruments of virtue (inquitstor passive), if you cast a spell triggered gems will get the increased spell damage (triggered spells not procing instruments is however correct)

Keep up the great work :)

**Comment by Openarl** [comment]
I'm sorry, I don't quite understand the issue here. Could you clarify exactly what is happening currently, and what you're expecting to happen?

**Comment by Hapseleg** [comment]
Hmm it seems the spell damage part isnt working at all. When i put a checkmark in "Have you cast a spell recently" the dps of my spells dont go up but my attacks dps does.

**Comment by Openarl** [comment]
Setting that option won't have any effect for spells, because it will already be active if the main skill is a spell. I suppose it shouldn't do so if the main skill is triggered, though. I'll see if I can change that.

**Comment by Hapseleg** [comment]
Ah I see, yes I think that would be a good idea since for example when using mjolner triggered spells wont proc it but casting fx summon stone golem will so most of the time you wont have the increased spell damage.

**Comment by Openarl** [comment]
The next update adds support for Mjolner's trigger, which fixes this issue (only the trigger itself is supported, there's no proper DPS calculations for Mjolner yet).
