### ISSUE TITLE
righteous fire lvl has no effect

### ISSUE THREAD

**Issue by sparksenMarisol** [Openarl/PathOfBuilding#243]
in my build it has no effect when i lvl up my righteous fire(lvl1 =lvl20 damage) other gems work(elemental focus9

**Comment by Openarl** [comment]
Righteous Fire deals exactly the same damage at all levels; it's only the spell damage buff that scales up (and of course that has no effect on the DoT, since it's not spell damage). It is working as intended,

**Comment by sparksenMarisol** [comment]
wow thats so pointless.-.
