### ISSUE TITLE
Witchfire Brew, Blasphemy, and Curse Limits

### ISSUE THREAD

**Issue by Lothrik** [Openarl/PathOfBuilding#244]
According to: https://www.reddit.com/r/pathofexile/comments/58248i/does_witchfire_brew_override_blasphemy_curses/

If you're already at your Curse Limit via Blasphemy, the Level 21 Vulnerability Aura from Witchfire Brew does not apply.

I'm not sure whether Path of Building simply doesn't factor in the Level 21 Vulnerability, but if it does the behavior described above is not handled correctly, as adding (for example) Blasphemy Enfeeble to my skill setup with Witchfire Brew does not change my Poison or Bleed damage whatsoever.

The expected behavior would be one where my Poison and Bleed damage decrease drastically when I do this, as Vulnerability is no longer present.

**Comment by Openarl** [comment]
This isn't the same issue as #171; that's to do with multiple copies of the same buff/debuff stacking.
The program does the Vulnerability from Witchfire Brew (you can see it in the curse list on the Calcs tab); but it doesn't currently respect the curse limit, as it's not straightforward to handle. I'll likely be doing an overhaul of the buff/debuff code soon, which should allow me to fix both issues at once.

**Comment by Openarl** [comment]
The buff/debuff overhaul is coming in the next update, which will fix this issue (and #171).
