### ISSUE TITLE
Essentia Sanguis and additional block chance while dual wielding claws

### ISSUE THREAD

**Issue by c2ho2** [Openarl/PathOfBuilding#245]
Dual wielding Essentia Sanguis should result to 31% block chance.
Only shows 15%.

![image](https://cloud.githubusercontent.com/assets/16774450/23976918/dc895d7e-0a25-11e7-82d0-4c7c6f221df1.png)

**Comment by Openarl** [comment]
I haven't added support for the "dual wielding claws" condition yet; that's why the block chance modifier appears red. It's simple to handle though; it'll be in the next update.
