### ISSUE TITLE
[BUG] Wrong crit. chance for Imbued Wand

### ISSUE THREAD

**Issue by jobsonita** [Openarl/PathOfBuilding#247]
Imbued Wand has a base crit. chance of 7.00% instead of the 8.00% listed in PathOfBuilding.
Edit:
Nevermind, updated the program and got the correct values.

**Comment by Openarl** [comment]
I've just checked, and Imbued Wand definitely has 7%. 
Are you sure you're running the latest version? The wand bases were updated in 1.3.18, which was released 2 weeks ago.
