### ISSUE TITLE
Chance to Ignite Support is not added to global Ignite calculations

### ISSUE THREAD

**Issue by rhazor** [Openarl/PathOfBuilding#248]
Under Calcs tab under Ignite I have only 15% Ingite Chance from Chieftain's node, but no % from Chance to Ignite Support.

**Comment by Openarl** [comment]
Are you sure the Chance to Ignite is actually supporting the skill selected in the Calcs tab? The gem seems to be working fine for me.

**Comment by rhazor** [comment]
ur right
