### ISSUE TITLE
Where are the minimize/close buttons?

### ISSUE THREAD

**Issue by AngryRoleplayer** [Openarl/PathOfBuilding#249]
Must be dumb quesion but i have resolution of 1280x720 and the program is always in fullscreen with no buttons like minimize of close, i have to use alt-tab or windows button to get out of it. I cannot even close it properly so just alt+f4
![img_20170319_171727](https://cloud.githubusercontent.com/assets/22470478/24081613/5c763620-0cc8-11e7-8dcb-8a4ee3a68f2d.jpg)

**Comment by dein0s** [comment]
Dunno about hotkeys, but you can edit `Launch.cfg` to get out of fullscreen mode. There's an option for this, and also some more usefull things.

**Comment by Openarl** [comment]
I don't think it's actually in fullscreen mode; the window management code does have fullscreen support but there's no way for it to activate in this program. 
The program's window defaults to 1280x720, so if your screen resolution is set to that then the program may appear to be in fullscreen. If you use Windows+Up to maximise the window then it should fix it. I'll see if I can find a way to make the window maximised by default.

**Comment by AngryRoleplayer** [comment]
Tried windows+up and it does not help. Still no buttons. Will try editing cfg

**Comment by Openarl** [comment]
The 1.4.8 update should fix this.

**Comment by AngryRoleplayer** [comment]
Works now, thanx!
