### ISSUE TITLE
Location of Penetration % total?

### ISSUE THREAD

**Issue by rhazor** [Openarl/PathOfBuilding#251]
I can't find it anywhere in Calcs. I have like 20% fire pen from The Wise Oak flask, 8% from tree, 10% from Chieftain, can't see where's total.

Main hand skill Cyclone, but using Avatar of Fire.

**Comment by Openarl** [comment]
It's in the breakdown for the Effective DPS Modifier:
![pen](https://cloud.githubusercontent.com/assets/19189971/24087892/1e6739f8-0d70-11e7-8b6f-8d44a6213a95.png)
By the way, the penetration modifier from The Wise Oak isn't supported yet.
