### ISSUE TITLE
Chin Sol "More Bow Damage at Close Range" Not Applying

### ISSUE THREAD

**Issue by barbieqfreak** [Openarl/PathOfBuilding#252]
This doesn't seem to be applying Chin Sol's unique modifier to damage with bow skills.

I should add that this is with Projectile Travel distance set to 1. Changing the travel distance under Configuration has no effect on damage calculation.

**Comment by PatrickGriffiths** [comment]
You have to click on the "Configuration" tab at the top left and check the box "Is enemy at close range" as shown here:
http://i.imgur.com/PmV1wCo.png

**Comment by barbieqfreak** [comment]
Interesting. I have no such options there; my configuration tab is missing a lot of those options under Effective DPS. 

![Screen](https://cloud.githubusercontent.com/assets/26557117/24138011/b6c508ca-0dd3-11e7-937a-f7643e78d229.png)

I have been updating using the Check for Update button in the bottom left. Should I try a fresh install?

**Comment by Openarl** [comment]
Did you actually have Chil Sol equipped when you took that screenshot? Options in the Configuration tab only appear if they can have any effect, otherwise the tab would be far too cluttered to be usable.

**Comment by barbieqfreak** [comment]
That's it! I didn't realize it worked that way. Thanks for helping me better understand how it works :D

**Comment by Openarl** [comment]
All good. I could make the Close Range condition activate if the travel distance is <20, but I'm not sure that the 20 unit limit is actually measured by travel distance, as opposed to distance from the player.
