### ISSUE TITLE
Blood Rage + Enhance Attack Speed not Increased

### ISSUE THREAD

**Issue by peinanchen** [Openarl/PathOfBuilding#253]
After patch 1.3.21, it seems that when Blood Rage is socketed with Enhance, the increased attack speed is not applied. Before, disabling Enhance would decrease my DPS, while now, disabling it has no effect.

Furthermore, Blood Rage quality seems to have no effect

**Comment by Openarl** [comment]
This is an unforeseen side effect of the redesign of the buff handling code; the attack speed from Blood Rage's quality bonus is being overwritten by the base bonus of the skill. I'm not quite sure how to fix it, but I'll give it a go when I can spare the time.

**Comment by Openarl** [comment]
I've found a fix for this; it will be in the next update.
