### ISSUE TITLE
Feature Request- Minion Instability

### ISSUE THREAD

**Issue by youku11** [Openarl/PathOfBuilding#256]
I know it's unpopular to most of the players, but I realized that POB cannot calculate the damage from minion instability.

**Comment by dein0s** [comment]
As all of the rest minion-related things, this one is pretty hard to implement (I'd say - impossible at this stage).
Check https://github.com/Openarl/PathOfBuilding/issues/169 and https://github.com/Openarl/PathOfBuilding/issues/63 for more info.

**Comment by Openarl** [comment]
Quite impossible. Minion Instability acts like a skill that's being used by your minions, and is modified by minion damage and any applicable support skills; so I won't be able to handle it until I add full minion support.

**Comment by Openarl** [comment]
Added in 1.4.0.

**Comment by youku11** [comment]
you are my hero!
