### ISSUE TITLE
Can´t import Character Because they accept Letter "á"

### ISSUE THREAD

**Issue by money08** [Openarl/PathOfBuilding#258]
Thread say all i can´t import because my letter "á´" not accept

**Comment by Openarl** [comment]
Replace "á" with "%C3%A1" and it should work. It's a known limitation of the program; the text renderer doesn't support Unicode, so I can't allow non-ASCII characters to be input.

**Comment by money08** [comment]
Thanks work ;)

**Comment by dein0s** [comment]
Related to #55

**Comment by Openarl** [comment]
Huh, should have closed this ages ago, as the program now automatically converts such characters when input into the account name field.
