### ISSUE TITLE
Sin's Rebirth = No DPS change in chaos BF build

### ISSUE THREAD

**Issue by Murlocks** [Openarl/PathOfBuilding#259]
Hello, I was experimenting with my chaos BF build in PathOfBuilding and noticed that Sin's Rebirth offers no DPS increase. Fairly positive this is incorrect, but please let me know if there some sort of interaction that I overlooked.

**Comment by Openarl** [comment]
I can't see any issues with that flask; I also have a chaos BF build and it grants the expected DPS increase. Are you sure you haven't enabled Unholy Might in the Configuration tab?

**Comment by Murlocks** [comment]
Sorry, that was it... thanks for taking the time to figure out that I'm an idiot 😅
