### ISSUE TITLE
How do we implement Jewels to the tree (build?)

### ISSUE THREAD

**Issue by Romanticize** [Openarl/PathOfBuilding#26]
When going to the "Items tab" And we Import Rare Templates, how do I go about implementing a rare jewel, since there are no templates.
![screenshot 13](https://cloud.githubusercontent.com/assets/22439778/18823323/b2b95862-836d-11e6-9071-fe4d1215c8a1.png)

**Comment by dein0s** [comment]
There are [some reasons](https://www.pathofexile.com/forum/view-thread/1716360/page/3#p13613375) behind it. Right now you have to copy-paste new jewels.

**Comment by Openarl** [comment]
I've finally added some jewel templates. There's only a small subset of available mods on them, but you can always add your own using the item editor.

**Comment by Romanticize** [comment]
Hey, thanks a lot. Path of building is my abdolute favorite tool. And all
uts features are simply fabulous. Keep up the great work
