### ISSUE TITLE
Collateral Damage, Viridian Jewel DPS is not calculated for chance to deal double damage

### ISSUE THREAD

**Issue by Sammmmm** [Openarl/PathOfBuilding#262]
It does not appear that the DPS from "cone has 50% chance to deal double damage" is being added into shrapnel shot DPS calcs, only 15% increased physical damage.

Tested this by swapping out Collateral Damage for a jewel I created with only the increased physical damage component.

**Comment by Openarl** [comment]
"X% Chance to deal Double Damage" modifiers aren't supported yet; that's why that part of the jewel tooltip is red. I haven't quite figured out how I'm going to handle them, so I can't say when they're likely to be implemented.

**Comment by Openarl** [comment]
Support for Collateral Damage and other "X% chance to deal Double Damage" will be added in the next update.
