### ISSUE TITLE
[BUG] Modifiers to spell damage apply to poison

### ISSUE THREAD

**Issue by EvanRain** [Openarl/PathOfBuilding#263]
My account name is EvanTheGray, character Kora_The_Chaos_Herald. I'm playing ED with Consuming Dark.
With ED selected as main skill, in Calc -> Poison you can see that modifiers to spell damage apply also to poison, which [isn't supposed to happen](http://pathofexile.gamepedia.com/Poison#Damage).

**Comment by Openarl** [comment]
Working as intended; Essence Drain has the stat "Modifiers to Spell Damage apply to this skill's Damage Over Time", which applies to all DoTs created by the skill, including Poison.
