### ISSUE TITLE
[Request] Different sets of items

### ISSUE THREAD

**Issue by Rodrux25** [Openarl/PathOfBuilding#267]
Multiple times when planning a build, it has happened to me that I want to be able to quickly switch between two (or more) different sets of gear (for example, life and LL or CI gear). I think it'd be a great addition.

Thanks for the amazing tool anyways.

**Comment by dein0s** [comment]
Can be solved by #47

**Comment by Openarl** [comment]
Support for item sets is coming in the next update (along with a few other goodies).
