### ISSUE TITLE
Rapid decay with poison?

### ISSUE THREAD

**Issue by stania** [Openarl/PathOfBuilding#270]
I tried to calc my DPS with poison of Lacerate with Posion Support and Rapid Decay Support.
But latest version doesn't show any dps change when I enable Rapid Decay Support in Skill view.

Does Rapid Decay Support NOT affect skills with Poison support in GGG's game mechanics?
Or lack of support of path of buliding at the moment?

Thanks in advance.

**Comment by Openarl** [comment]
Poison Support doesn't add the Duration skill type, so unless the skill already has it then Rapid Decay will not apply to that skill. So Path of Building's behaviour in this case does match that of the game.
