### ISSUE TITLE
Minion Support

### ISSUE THREAD

**Issue by IGP** [Openarl/PathOfBuilding#271]
WIth the recent release of full minion data updated for 2.6 (located here: https://docs.google.com/spreadsheets/d/1LAi5g067lGa2XdHPpGa1ae8RKe-LBnwCjE-Z384fTV4/edit#gid=1197252210) can we get support added for them?

**Comment by dein0s** [comment]
Already discussed in https://github.com/Openarl/PathOfBuilding/issues/169#issuecomment-290687807

**Comment by Openarl** [comment]
Indeed.
