### ISSUE TITLE
hybrid evasion/armour nodes not added to displayed increase

### ISSUE THREAD

**Issue by McFrugal** [Openarl/PathOfBuilding#273]
The hybrid evasion/armour nodes near Duelist do not increase the "inc armour" or "inc evasion" tallies in the tree statistics for increased armour and evasion.  Your evasion and armour goes up as it should, it's just not reported fully in the statistics.

**Comment by Openarl** [comment]
The "%Inc X from Tree" stats in the sidebar are only intended to serve as a rough guide when building a tree; once gear and skills have been added you'll use the final computed Life/Evasion/etc values instead, so I haven't bothered making them count hybrid stats and such. I suppose I can fix that though, but I'll need to rework the code that sums those stats.

**Comment by Openarl** [comment]
This is fixed in the next update.
