### ISSUE TITLE
[Bug] Blade Flurry DPS not being shown

### ISSUE THREAD

**Issue by fikal** [Openarl/PathOfBuilding#274]
I am not sure if I am doing something wrong, but I am unable to get the DPS to display for Blade Flurry.

My account name is Fikal and this character is TwoDollarOrb

![image](https://cloud.githubusercontent.com/assets/4062745/24658195/9d4ce67e-190e-11e7-84df-8696c3e29249.png)

**Comment by Openarl** [comment]
Blade Flurry is being disabled because it doesn't have any compatible weapons to use. I'm not sure why that would be the case though, as the character imported just fine for me.
