### ISSUE TITLE
when I mouse over the area with my passive totals it shows my level but it is not correct

### ISSUE THREAD

**Issue by jesterx93** [Openarl/PathOfBuilding#281]
the area showing my passive totals in the top frame will show fir example 24 / 122 0 / 8  when i mouse over this it pops up required level 2.

this is of curse not possible to have 24  skill points allocated and only be level 2

is there something i am configuring wrong?

**Comment by dein0s** [comment]
Well, have you heard about passive points that you can get as a quest rewards?
They aren't tied to the character level.

**Comment by Openarl** [comment]
I already [replied](https://www.pathofexile.com/forum/view-thread/1716360/page/95#p14392632) to your forum post; I won't bother repeating it here.

I'll close this, since this can't really be fixed.
