### ISSUE TITLE
Rapid Decay does not affect damage on Lacerate

### ISSUE THREAD

**Issue by BorkaMatti** [Openarl/PathOfBuilding#282]
I am using skill Lacerate and linked it with Poison. Linking rapid decay does not increase poison damage.

![image](https://cloud.githubusercontent.com/assets/17543876/24922712/8900f412-1eef-11e7-8701-7e817a0fd124.png)

![image](https://cloud.githubusercontent.com/assets/17543876/24922738/9ccc859c-1eef-11e7-9bde-38632d2904c7.png)

**Comment by Openarl** [comment]
Lacerate is not a duration skill, and therefore cannot be supported by Rapid Decay. This is working as intended.
