### ISSUE TITLE
NaN Mana Leech/Gain per Hit with Shield Charge

### ISSUE THREAD

**Issue by MatthewClair** [Openarl/PathOfBuilding#283]
Steps to reproduce:
1. Equip an item that gives mana leech or mana gain on hit (Ex: Ephemeral Edge)
2. Equip a shield
3. Get the Blood Magic Keystone
4. The stat bar will show "Mana Leech/Gain per Hit: nan"

Expected result: Mana Leech/Gain per Hit shouldn't show if the Blood Magic Keystone is selected

Sample build: https://pastebin.com/LV0YhjhS

I tried a handful of different melee skills and the only one that I could get a repro on was shield charge.

**Comment by Openarl** [comment]
Thanks for the detailed report; this will be fixed in the next update.

Incidentally, this only occurred with Shield Charge because it required the skill to use Average Damage instead of DPS.
