### ISSUE TITLE
[Solved] Iron Ring missing

### ISSUE THREAD

**Issue by psyclown** [Openarl/PathOfBuilding#284]
I can't seem to find Iron Ring on the Rare items list, when I want to create a new item. Am I missing something here or is it a bug?

**Comment by psyclown** [comment]
![image](https://cloud.githubusercontent.com/assets/27353769/24958837/0bfecc3a-1f91-11e7-861e-c9e76e220e3d.png)

**Comment by dein0s** [comment]
Well, if you can't find a template, you can create an item from the scratch in 'Craft item...' menu.
![craft menu iron ring](http://i.imgur.com/HujZf4x.png)

**Comment by Openarl** [comment]
I haven't added every possible base to the item templates; only the useful ones. Iron Ring's implicit is quite weak compared to other rings, which is why I left it out. As dein0s said, if you really need it you can always create one from scratch, or edit an existing template.

**Comment by psyclown** [comment]
Oh cool, didn't know that. I know it's weak and probably useless, but I actually thought everything was there :)
Thanks for the answer.
