### ISSUE TITLE
Explosive Arrow

### ISSUE THREAD

**Issue by HatredC0pter** [Openarl/PathOfBuilding#288]
I was wondering if the explosion for explosive arrow is calculated with 1 charge on an enemy for 5. I don't see an option to change it or any info about it. I was also wondering if there is support for weapon swap yet. If there is, I'm just not seeing it anywhere.

Thanks!

**Comment by Openarl** [comment]
It's just one, at the moment. I could add a skill part for 5 charges, but it's a little tricky because of the skill mechanics. I'll look into it when I get the time.

**Comment by Openarl** [comment]
The next update adds a "5 fuse" skill part for EA.
