### ISSUE TITLE
Small glitch with support gems and quality

### ISSUE THREAD

**Issue by magus424** [Openarl/PathOfBuilding#289]
Version: 1.3.26 -- Couldn't find an existing issue matching this.

I was trying to compare added fire level 20 with added fire level 20 quality 20 on my build to see just how much it would raise my DPS, when I discovered that it was treating the quality 0 as quality 20.

I've been messing with it, and I can activate and deactivate the bug on command :)

I added both Added Fire 20/0 and Added Fire 20/20 to the skill link. Initially, it can tell them apart, and the tooltip on the enable checkbox, for example, shows different +dps values. It's not limited to just the tooltip though, as enabling/disabling either gem shows the same final DPS value in the sidebar.

If, however, I enable both at once, PoB now treats both gems as if they were quality 20, even though it shows 20/0 and 20/20 in the list.

If I bump the quality up to 1 and back down to 0 on the 20/0 gem, the bug is undone, and it starts counting them separately again. So long as I don't activate both at once, it'll work properly, but the moment I do, the bug is activated again.

Hm, there might be something else going on as well; while typing this up, I decided to see what happened if I added 20q versions of WED, Melee Phys, and Increased AoE as well, and now whichever gem I adjust the quality of last appears to "stick" for the tooltips.

If I +1/-1 of Increased AoE, all 3 20/20 tooltips show +1095 dps. If I +1/-1 melee phys, they all start showing +985 dps, and WED shows +1095 as well. However, it only starts reusing the tooltips after I mouseover the correct gem. So after +1/-1 on WED, mousing over melee phys or increased aoe shows nothing, but then once I mouseover WED, the other two start showing the 1095 number.

The character is [here](https://www.pathofexile.com/account/view-profile/magus424/characters?characterName=HappyFunBalls) if it helps at all for debugging.

**Comment by Openarl** [comment]
I've finally gotten around to taking a look at this; there were actually quite a few odd quirks with duplicate supports that I found, so I've reworked some of the related code, which will also fix #312. As usual it'll be in the next update.
