### ISSUE TITLE
AoE calculation and comparison

### ISSUE THREAD

**Issue by jcmoyer** [Openarl/PathOfBuilding#292]
With the new 2.6 AoE changes it would be cool if PoB could calculate and display the computed area for skills. Sometimes taking an increased area of effect node doesn't do anything at all for a skill. This would be incredibly useful for deciding whether or not a set of AoE nodes is worth taking.

Mainly I would love to see the percent change in area when hovering over inc. AoE nodes, but displaying the computed area in the skill statistics panel would be cool too.

**Comment by SRSFAN** [comment]
Would love to see this as well

**Comment by Openarl** [comment]
The 1.4.9 update adds radius calculations for most skills, as well as a visual display of the area size in the radius breakdown.
