### ISSUE TITLE
Incorporate shock chance and damage

### ISSUE THREAD

**Issue by Im2be** [Openarl/PathOfBuilding#295]
Allow the user to check a checkbox in Configuration that incorporates chance to shock and multiplies the average damage tooltip correctly.

**Comment by Openarl** [comment]
If I understand correctly, you want the program to use your shock chance to calculate the average shock uptime and modify your DPS accordingly? That's impossible to do, as the shock duration depends on the enemy's total life.

**Comment by Im2be** [comment]
I see. I didn't know that. My apologies.

Op 16 apr. 2017 13:21 schreef Openarl <notifications@github.com>:

If I understand correctly, you want the program to use your shock chance to calculate the average shock uptime and modify your DPS accordingly? That's impossible to do, as the shock duration depends on the enemy's total life.
