### ISSUE TITLE
Total Mana not accounting for Grand Spectrums

### ISSUE THREAD

**Issue by mireigi** [Openarl/PathOfBuilding#296]
Grand Spectrums seems to be properly calculated for the base mana, however, their addition to base mana isn't factored in when calculating the total mana.

![billede](https://cloud.githubusercontent.com/assets/27586367/25067172/8365fefe-223b-11e7-8732-0c7e95777f32.png)

**Comment by Openarl** [comment]
Oops, looks like I managed to break that one while restructuring the calculation code; it'll be fixed in the next update.
