### ISSUE TITLE
Error opening build in 1.4.2

### ISSUE THREAD

**Issue by fr3runn3r** [Openarl/PathOfBuilding#298]
Had this pop up when editing my skills, closed it and was able to save. It then popped up again and I chose to restart. Now unable to open my build, other builds open just fine.

![image](https://cloud.githubusercontent.com/assets/26168388/25071278/c8903548-22aa-11e7-87e7-19bf50d42dd6.png)

**Comment by Openarl** [comment]
Can you send me the build file? It'll be in your documents, under Path of Building\Builds.

It would have helped to see the original error that appeared while you were editing the skills; the error you posted tells me what happened, but not how it happened, which is much more important.

Anyway, I'll add code in the next update to allow you to load your build again; it'll be out shortly.

**Comment by fr3runn3r** [comment]
Here's the build file:

[Build File.zip](https://github.com/Openarl/PathOfBuilding/files/924283/Build.File.zip)

**Comment by Openarl** [comment]
Interesting. I'm not sure how you managed to trigger that, but the next update will prevent it from happening again (and allow your build to load). I should be releasing that update in the next 10 minutes if all goes well.
