### ISSUE TITLE
Arakaali's Fang broke application

### ISSUE THREAD

**Issue by elevan** [Openarl/PathOfBuilding#302]
To start off I have a melee summoner build I've been working on including Arakaali's Fang and the scourge, today when I opened up the build for it and went to the skill's window I got this error:

![image](https://cloud.githubusercontent.com/assets/9679061/25074617/3de77c92-22c5-11e7-98ab-74ebedcb3225.png)

After hitting F5 to refresh I could again use the other tabs as normal, as such thinking the build just got corrupted somehow I deleted it and made another.

During the process of making the other I suspected that it was one of the two weapons summon ability that caused as there was always a skill produced from one of them but since it didn't effect anything I just ignored it. As such I added Terror claw and checked the skills tab but nothing showed up. I then added Arakaali's Fang which did indeed add a skill to the window. Here's were it "broke application" comes into play. Noting that I could see the skill produced by the dagger in the skill window and not getting the above message I decided to see if I could reproduce the bug by saving and reopening the build. After saving the build and hitting back to my build list I got the above error again, hitting F5 just produced the same error as does restarting the application. In order to get Path of Building working again I had to manually go in and delete the build xml so it would launch again.

**Comment by elevan** [comment]
Just did some more testing, I couldn't get the entire application to break again but I was reliably able to reproduce the skill tab breaking issue. All I did was make a build with Arakaali's fang, saved it, and left. After re-entering the build the skill tab would be broken.

**Comment by Openarl** [comment]
It seems the program is processing the "Raise Spiders on Kill" modifier, but it's breaking the granted skill code because the Raise Spider skill isn't supported yet.

I'm going to fix this in two ways:
1. I'll add a check to the granted skill code to prevent this error from occurring again
2. I'll add support for Raise Spider :)
