### ISSUE TITLE
Scion-Chieftain's life regen is ignored

### ISSUE THREAD

**Issue by ItGacky** [Openarl/PathOfBuilding#304]
Even if "Do you have a Totem summoned?" is checked, "Regenerate 2% of your maximum Life per second while you have a Totem" from Scion-Chieftain is ignored in "Life Regen" value.
at Version 1.4.3

**Comment by Openarl** [comment]
The program wasn't recognising that modifier, which is why it appears red instead of blue. I've added support for it in the next update.
