### ISSUE TITLE
Application instantly crashes on Win10 Creators Update

### ISSUE THREAD

**Issue by willlowther** [Openarl/PathOfBuilding#305]
When using Windows 10 Home, Version 1703 OS Build 15063.138, the application crashes on startup.

After Loading Item Databases, the application moves to it's normal window size and then crashes with a standard Windows error. 

It appears to be related to the latest version of the Nvidia Graphics Drivers. I am running a 1080 GTX with Nvidia version 381.65

`Faulting application name: Path of Building.exe, version: 0.0.0.0, time stamp: 0x58a9a3a1
Faulting module name: nvoglv32.DLL, version: 22.21.13.8165, time stamp: 0x58deff5a
Exception code: 0xc0000005
Fault offset: 0x00acee5f
Faulting process id: 0x280c
Faulting application start time: 0x01d2b7b7be351e59
Faulting application path: C:\POE Tools\Path of Building\Path of Building.exe
Faulting module path: C:\WINDOWS\SYSTEM32\nvoglv32.DLL
Report Id: 15447947-b364-4f75-b3a9-df87869ccf21
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by Openarl** [comment]
I've had a few reports of this; it seems GeForce Experience is conflicting with the program in some way, as uninstalling it seems to fix the problem. I haven't been able to diagnose the precise cause of the conflict yet, unfortunately.

**Comment by willlowther** [comment]
Thanks, this solves the issue. I've seen it with a few other applications (like RenPy) so it's not PathOfBuilding specific. Might be worth leaving this issue here for anyone else having the same problem.

**Comment by PhilMonster** [comment]
I had the same Problem, the latest update for Nvidia GeForce Expirience fixed this Issue for me, try updating it :D

**Comment by Openarl** [comment]
Since this was caused by GeForce Experience, and the issue with that software appears to have been fixed, I'll assume this is fixed for everyone.
