### ISSUE TITLE
Ignite chance lowers ignite dps

### ISSUE THREAD

**Issue by Kessus** [Openarl/PathOfBuilding#307]
I couldn't help but notice that increasing ignite chance lowers ignite dps. In my opinion it's a miscalculation, that's why I'm reporting it here. If I don't understand something, please let me know why is it working that way :)

**Comment by Openarl** [comment]
It seems rather counter-intuitive, but this is intended behaviour. The ignite DPS shown by the program is the average DPS of each ignite instance, not the average DPS of ignite on the target over time (which is actually quite difficult to calculate).

I addressed the issue in depth in a [recent forum post](https://www.pathofexile.com/forum/view-thread/1716360/page/98#p14406887), if you want to know more.
