### ISSUE TITLE
Extend buildnames

### ISSUE THREAD

**Issue by JYshadow** [Openarl/PathOfBuilding#308]
I just have one simple request: could you perhaps increased the maximum amount of characters allowed in the buildname?. Currently it is 50 characters, but I usually like to put small descriptions in the name of the build, however most of the time doesn't provide enough space to do so. I would be nice if people could adjust the name-length to the size they'd like by dragging the edge.

**Comment by dein0s** [comment]
You can put whatever you want (like description, forum/reddit links, etc) in build notes :)
But I agree, that we need some QoL changes to the build list on the main window. Take a look at #275.

**Comment by Openarl** [comment]
The next update increases the build name limit to 100, and also widens the build list.
