### ISSUE TITLE
Cobalt jewel minion prefixes always shows

### ISSUE THREAD

**Issue by oskar94** [Openarl/PathOfBuilding#309]
As stated in title currently when creating a Cobalt Jewel it always shows the minion prefixes no matter what value they have. [Example](http://i.imgur.com/aNUgJAj.png) 

I found this bug while running version 1.4.4 however it still remains after I updated to version 1.4.5

Reproduction steps: 
1. Create a new build
2. Search for cobalt jewel in the premade items list and double click to enter edit mode
3. It should now have 2 minion prefixes that is both at 0%

I tested to see if this was a problem with the other 2 jewels but it only happens to the cobalt jewel.

**Comment by Openarl** [comment]
Thanks for the report; this is fixed in the next update.
