### ISSUE TITLE
[Feature Request] Allow keyboard navigation

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#31]
As subj says - allow users to use keyboard navigation and action in lists (like 'All items' on 'Items' page), dropdowns (like 'Main Skill' dropdown on the left bar), popups (delete confirmation window).

**Comment by Openarl** [comment]
Finally got around to working on this; the changes in 1.2.10 should be a major improvement.

**Comment by dein0s** [comment]
Thanks, will check it out!
Got distracteda a bit from poe by gwent :D

**Comment by dein0s** [comment]
This one can also be closed, current state looks fine for me.
