### ISSUE TITLE
Ignite Calculations

### ISSUE THREAD

**Issue by JoannaMeier** [Openarl/PathOfBuilding#310]
Fireball supported by Concentrated Effect does not gain a 'more' multiplier for Ignite damage (though Slower Projectiles works correctly).

Has this changed recently? Despite two year old Dev comments to the contrary, Area Modifiers had always applied to Fireball Ignites last time I checked.

**Comment by Openarl** [comment]
Are you looking at the 'Projectile' part or 'Explosion'? Only the latter is affected by area damage.

**Comment by JoannaMeier** [comment]
You are absolutely correct and I feel rather foolish, especially after making note of the same thing with an EQ character - It's been a very long time since I played Fireball with Pierce and I confess I completely forgot they were separate effects. This can be closed, and my thanks for your amazing tool - I spend about as much time tinkering in it than in game currently.

**Comment by Openarl** [comment]
Well, if it makes you feel any better you're far from being the first person to make that mistake :).
