### ISSUE TITLE
Question about Inevitable Judgement

### ISSUE THREAD

**Issue by chachazero** [Openarl/PathOfBuilding#311]
"Critical Strikes ignore Enemy Elemental Resistances"
Does the above part of Inevitable Judgement works as intended?

I tried to find related descriptions in Calcs page, and the only difference between allocating and unallocating the node is the "penetrate 10% resistances" part in Effective DPS Modifier. 
Is there any other modifier dealing with this part that I missed?

**Comment by Openarl** [comment]
Inevitable Judgement is fully supported, but since the "ignore resistances" part only applies to crits, and the Calcs tab only shows the workings of the non-crit calculations, you won't see it in action there; but believe me, it is working!

**Comment by chachazero** [comment]
So, the DPS

**Comment by Openarl** [comment]
Eh? I think you accidentally your post...

**Comment by chachazero** [comment]
Yeah I accidentally submitted. Now it's updated.

**Comment by Openarl** [comment]
Yeah, that's roughly correct. The crit damage is actually calculated in an entirely separate calculation pass, which allows modifiers like those on IJ to only apply to crits or non-crits; in theory I could display the workings for the crit pass as well as the non-crit pass, but normally the inputs are the same as for non-crit, with IJ being one of the few exceptions.

**Comment by chachazero** [comment]
Thanks for the explanation. :D

**Comment by i3igpete** [comment]
![image](https://user-images.githubusercontent.com/33877827/71189343-4ba02e80-2248-11ea-8500-b21844ab0065.png)

Quick example screenshot to show the crit damage increasing with Inevitable Judgement.
