### ISSUE TITLE
Heretic's Veil and Blasphemy level

### ISSUE THREAD

**Issue by Arturion23** [Openarl/PathOfBuilding#312]
When Heretic's Veil (or any other item that has a "gems are supported by" mod) is socketed with a matching support gem - in this case, Blasphemy - the real support gem normally does not take effect unless it is equal to or higher level than the support granted by the item. So in Heretic's Veil's case, your support gem would have to be level 22 for it to override the Blasphemy granted by the item. This overriding is useful to get a quality bonus on your Blasphemy curses.

However, Heretic's Veil gives +1 to level of socketed Curse gems, which applies to Blasphemy. This means that your Blasphemy gem should only need to be level 21, which gives it an effective level of 22, and thus overriding the Blasphemy granted by Heretic's Veil.

I have tested this in-game with a 20/20 Blasphemy (does not give +10% curse effectiveness, since Heretic's Veil overrides it with a 22/0) and a 21/20 Blasphemy (_does_ give +10% curse effectiveness, as it overrides Heretic's Veil's Blasphemy), but Path of Building does not let me override the helm's built-in Blasphemy unless I set the actual Blasphemy gem's level to 22 or higher.

I have both gems and can provide screenshots, etc. if needed to verify the mechanic. IGN: RadiantSolaris

**Comment by Openarl** [comment]
Currently the program collapses duplicate supports before handling +gem level modifiers, since normally it doesn't matter; but I never considered this particular edge case. I'd have to rework the code a bit to fix this, so I might not get around to it for a little while though.

**Comment by Openarl** [comment]
Said code rework is coming in the next update.
