### ISSUE TITLE
Unable to see all controls in item section with computer which has low screen resolution

### ISSUE THREAD

**Issue by arsirantala** [Openarl/PathOfBuilding#313]
The main window can be resized nicely, but the child window (like one used in items) does not have controls, which I as user could scroll horizontally and vertically.

The screen dimensions I am using in my laptop are 1366 x 768.

**Comment by Openarl** [comment]
The Items tab does have a horizontal scroll bar at the bottom; is it not appearing for you?

The program should function at resolutions as low as 1280x768, so I'm not sure why you're having problems.

**Comment by arsirantala** [comment]
Horizontal scroll bar can be seen but not a vertical one, here's a screenshot: [https://www.dropbox.com/s/viui29an1384ng9/Screenshot%202017-04-24%2008.42.43.png?dl=0](url)

**Comment by Openarl** [comment]
A vertical scroll bar isn't necessary though, since everything is visible.

I should point out though, that at lower resolutions the unique database and rare template database share the same space; there's a dropdown above it to switch between the two.

**Comment by arsirantala** [comment]
Ah I see now. I was assuming that the vertical bar was missing due a bug - as the listbox's border is so close to the window edge 😀

Fair enough - I just installed this program yesterday and I like it a lot. And you promptly reply to issues as well. Keep up the good work!
