### ISSUE TITLE
Collateral Damage support

### ISSUE THREAD

**Issue by widardd** [Openarl/PathOfBuilding#314]
Shrapnel Shot's threshold jewel isn't supported right now, is there an ETA or workaround for it?

Thanks!

**Comment by Openarl** [comment]
As per #262, Collateral Damage and other "X% Chance to deal Double Damage" modifiers aren't supported yet; I don't know when I'll be free to work on them, as I have a few other things to get out of the way first.

If you're looking for a workaround, adding "100% more Area Damage" to an item would have roughly the same effect (except for interaction with poison/ignite/bleed).

**Comment by widardd** [comment]
> If you're looking for a workaround, adding "100% more Area Damage" to an item would have roughly the same effect (except for interaction with poison/ignite/bleed).

Thanks!

Why wouldn't this work for poison and bleed? Shrapnel Shot is Projectile and AOE.

**Comment by Openarl** [comment]
What I mean is that that modifier will double-dip, whereas "X% chance to deal Double Damage" wouldn't.
