### ISSUE TITLE
Trap Cooldown Support & Enchant Not Included in Cooldown Calculation

### ISSUE THREAD

**Issue by Shaeltahl** [Openarl/PathOfBuilding#316]
PoB 1.4.7 is ignoring the Trap Cooldown Support gem when calculating Trap Cooldown in the Calcs page. In addition, helmet enchants that reduce trap cooldowns are not included either.

Can be replicated by creating a new socket group (or a new character) with a Trap skill, or any supportable skill supported by Trap Support, and then adding in Trap Cooldown support and/or the appropriate cooldown enchant. Calculations correctly take into account other trap cooldown related passives such as Hasty Reconstruction and Saboteur passives, as well as the Scion-Saboteur passive.

**Comment by Openarl** [comment]
Fixed in the next update.
