### ISSUE TITLE
hierophant mana problem

### ISSUE THREAD

**Issue by gaouri** [Openarl/PathOfBuilding#317]
herophant mana conversion to es is calculated from base mana pull insted of a total mana pool wich is incorect

**Comment by Openarl** [comment]
[It is](http://pathofexile.gamepedia.com/Sanctuary_of_Thought) [correct](https://www.pathofexile.com/forum/view-thread/1647563/page/1). Sanctuary of Thought is a conversion, so what you gain is 25% of your base mana, modified by increases to mana and energy shield.

Also, I have a Hierophant with Sanctuary of Thought, and the program calculates his maximum energy shield correctly, so I know the calculations are correct.
