### ISSUE TITLE
Berek's Respite "Adds X-Y Fire Damage to Spells and Attacks"

### ISSUE THREAD

**Issue by tuffff** [Openarl/PathOfBuilding#318]
This is somewhat connected to #246.

The 2.6 Berek's Respite has a mod "Adds X-Y Fire Damage to Spells and Attacks". This is inconsistent with the other Berek's items, those use "X to Y".

In the item database, Respite has the mod as "X to Y" and works fine, but when importing from a character "X-Y" is not recognised.

Example for an imported ring: https://pastebin.com/aSKXjjwy

Thanks for your work!

**Comment by Openarl** [comment]
Ah, interesting. And there I was thinking I'd never have to consider "X-Y"-style added damage again :/.

This will be fixed in the next update.
