### ISSUE TITLE
"Avatar of Fire" on Xoph's Blood isn't being recognized as the Keystone

### ISSUE THREAD

**Issue by widardd** [Openarl/PathOfBuilding#322]
Just started theorycrafting and noticed that I am still getting increases from Avatar of Fire although Xoph's Blood is slotted it.

**Comment by Openarl** [comment]
Are you absolutely sure? Because I can't reproduce it, and given how keystones are handled by the program it is quite impossible for this to happen.

**Comment by widardd** [comment]
Ok, that's weird. I can'reproduce it either now.

Sorry!
