### ISSUE TITLE
[Solved] Window Interface

### ISSUE THREAD

**Issue by Seystuff** [Openarl/PathOfBuilding#324]
It would be incredibly useful to have the option to drag, minimize, maximize and close the window in the same way one does with any explorer window.

**Comment by Openarl** [comment]
Eh? The program doesn't run in fullscreen mode; it's just a normal window. What screen resolution are you using?

**Comment by Seystuff** [comment]
1280x720.
I sincerely tried all I could to make it work in a standard window fashion, am I missing something? I did think it was weird...

**Comment by Openarl** [comment]
Yes, it's just a normal window. with all the usual adornments (minimise/maximise/close and resize border). The default window size is 1280x720, but it should be maximised by default. Have you tried doing Windows+Down, then Windows+Up to forcibly maximise it?

**Comment by Seystuff** [comment]
Tried both that and alt+enter. In one computer that makes it borderless with a lower resolution than the screen (basically picture a regular window without the top bar) and in the other it does nothing. I am using windows 10 on laptop on both cases. I feel like I'm missing something important here... I will remove the thread, though

**Comment by Openarl** [comment]
That's strange... I don't understand why maximising it doesn't work properly; I've tested the program at 1280x720 on my own PC and it works normally. I am using Windows 7 though, so maybe it's due to the OS.

There is one change I can make though which might fix the problem; I'll slip that in the next update.

**Comment by Seystuff** [comment]
Great! Thanks for the support as well as the software in the first place. Will delete this thread in a little bit

**Comment by Openarl** [comment]
Well, I poked around in the window handling code, and I've found the cause. Quite surprised I never spotted it before, since I've been over the code a few times when trying to solve this problem previously. It will be fixed in the next update.

**Comment by Seystuff** [comment]
Great! Thanks!
