### ISSUE TITLE
[Feature Request] Taking Notes

### ISSUE THREAD

**Issue by beginnerlein** [Openarl/PathOfBuilding#325]
Dear developers,

i've been playing POE for ~3k hours total (steam+nonsteam) now and your tool took loads (literally tens of MB of excel files) of my shoulders and i hope i won't ever have to plan a build without POB.
I just got one Request: As I'm a player who's throwing around many different builds for trying out stuff and finding ways that work without considering forums, i have ~30-40 builds floating around, ~10 of wich are actually in action. I still have a "notes" file for each one of these builds that contains stuff like "check out curses" or "try axes over swords" kinda stuff... ranging from 1 line to a few 100kb per build. (latest because i started a build idea but didn't have the time to bottle it up)

I could talk about dreams where this feature i request COULD go, but I'd humbly request a free, build specific, Textbox to just write stuff in :) (and save of course :P)

**Comment by dein0s** [comment]
Well... I'd guess that you didn't have enough time to discover at least the basic functionality of PoB (or search through already created issues) cos you was too much excited of this application :D
How about this? ![notes](http://i.imgur.com/ZHHXm51.png)

**Comment by beginnerlein** [comment]
tough i honestly don't really apreciate your smug phrasing, i am humbled and am ashamed for not noticing [please insert blushing smilie here]

**Comment by Openarl** [comment]
Oh, you'd be surprised how many people request features that already exist :).
