### ISSUE TITLE
Feature Request: GitHub integration

### ISSUE THREAD

**Issue by corosou** [Openarl/PathOfBuilding#326]
I've been doing a lot of theory crafting and posting and the forums and have gotten requests to share builds.

It's awesome to be able to share through pastebin, and it would be amazing (since you are already familiar with GitHub) if I could link PoB to GitHub and clone/commit/push,etc my builds here, and also share them with people this way.

It would allow me to keep track of changes, as I have often made a change I didn't notice that made a huge difference and relying on "undo" is pretty old school ;) it also would grant access to the latest revision of the build, as I am often making many changes throughout the day.

It would also allow for build links to not become stagnant and deprecated or lost. How long does the data in a pastebin post last?  Some builds are popular for years. What happens to the links in posts that used the pastebin url for others to import? 

Keep up the great work!

**Comment by dein0s** [comment]
Why can't you put your builds folder under git by yourself?

**Comment by Openarl** [comment]
I'm not really sold on this. I'd think anyone with the requisite knowledge of GitHub could easily manage this themselves; while there might be some benefit to having the program handle it, it would require quite a bit of work, and I don't see it being worthwhile for such a niche feature.

Incidentally, the program doesn't set an expiry date when creating PasteBin posts, so they should [last indefinitely](https://pastebin.com/faq#18) (and they certainly will if they are being accessed frequently).

**Comment by dein0s** [comment]
A simple recipe will look like this (all actions are performed in [git bash](https://git-scm.com/download/win)):
1. Create a new git repo (example https://github.com/dein0s/pob_builds.git)
2. Open `git bash` in your PoB root folder
```
cd Builds
git init
git add --all
git commit -m "init commit"
git remote add origin https://github.com/dein0s/pob_builds.git
git push -u origin master
```
Worth to mention, that you'll have to manually commit and push (via any git tool) all upcoming changes to you builds.

**Comment by corosou** [comment]
Ohh, to be honest, I hadn't taken a look at the actual app files. I didn't realize the builds were there. Perfect! Thanks :)
