### ISSUE TITLE
[Feature Request] Calculated Crit Damage

### ISSUE THREAD

**Issue by unsmith** [Openarl/PathOfBuilding#329]
In the damage calculations we have Total DPS, which takes your current crit chance and crit multiplier into account.  I'd like to see a calculation for how much damage is done on a crit, or basically a second damage calculation with crit chance being 100%.  Alternatively, a configuration option for shrine effects, so you can tick "Player is affected by a Diamond shrine."

It would be nice to know what your maximum possible damage output is.

**Comment by Openarl** [comment]
The crit damage is already displayed in the Calcs tab, although you have to dig around to find it; it's in the breakdown for Average Hit:
![critdamage](https://cloud.githubusercontent.com/assets/19189971/25618094/d9523116-2f88-11e7-90b9-e84a74dd95d7.png)

**Comment by unsmith** [comment]
Got it, thanks.  I didn't realize you could hover over things in those calc boxes to expose other data.
