### ISSUE TITLE
[Feature Request] Add support of Snakebite's poison

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#33]
I know that you are busy right now with the next major update (btw, how is it going?), but still.
Don't think it's gona be hard, just smth similar to the Consuming Dark effect or that one from Cospri's Will in combine with max frenzy charges turned on on 'Calc's tab.

**Comment by Openarl** [comment]
Fairly easy change. I just pushed it out in an update.

As for the major update, it's coming along nicely. I think I'm just about done with the changes to the backend systems. The bulk of the remaining work is for the new Calcs tab, which I'm super excited about by the way. It's way more powerful and streamlined than the current design. I think it'll be worth the wait :). I'm not sure how much longer it's going to take though; I haven't had much time to work on it lately, although there's not a huge amount of work left to do.
