### ISSUE TITLE
Doon Cuebiyari ele damage issue

### ISSUE THREAD

**Issue by ytzelf** [Openarl/PathOfBuilding#331]
Hello,

The soft is just great, I just have a minor issue with planning my RF char: Doon Cuebiyari (http://pathofexile.gamepedia.com/Doon_Cuebiyari) ele damage bonus with str doesnt seem to add up in my calculations.

Is that a known issue?

Thanks again for an outstanding tool

**Comment by Openarl** [comment]
I can't seem to find any issues with Doon Cuebiyari's bonuses. What is your exact setup?

**Comment by ytzelf** [comment]
https://pastebin.com/9YcjhH1P

Addl ele damage from strength doesnt show up in the calc damage detail

**Comment by Openarl** [comment]
Doon Cuebiyari provides a generic damage increase, not elemental damage, and it is appearing in the Calcs tab:
![doon](https://cloud.githubusercontent.com/assets/19189971/25613693/803826b4-2f72-11e7-93fc-20835c8bf94d.png)

**Comment by ytzelf** [comment]
sorry for being retarded then - closing this shameful issue.
