### ISSUE TITLE
[Request] Minion Charges

### ISSUE THREAD

**Issue by SRSFAN** [Openarl/PathOfBuilding#332]
Would really like to see an option somewhere to see what effect frenzy, power, and endurance charges have on all minion skills (Spectres, Golems, Zombies, Animate Weapon, Raging Spirit...).

Keystone passive "Necromantic Aegis" with Victario's Charity Shield gives minions full frenzy and power charges almost 100% of the time. Can't decide if I want to use a clay shaper over a shield or not due to the the power bonuses minions get from charges.

Would be much appreciated if you could implement! Thanks for all your hard work, this program is amazing!

**Comment by Openarl** [comment]
Minion charge options are already present; they're under the player charge options, but they only appear when you have a minion skill as your main skill.
