### ISSUE TITLE
Feature Request: Killed an enemy recently for effective dps

### ISSUE THREAD

**Issue by nxock** [Openarl/PathOfBuilding#333]
for passives like "Patient Reaper" which are only active if you have recently killed an enemy effected by your DoT, as well as lab enchants like "Adds 33 to 50 Fire Damage if you've Killed Recently" or "Damage Penetrates 10% of Enemy Elemental Resistances if you haven't Killed Recently"

basically just more conditions in the effective dps config page to get data for all situations

**Comment by Openarl** [comment]
This option already exists; it's in the "When in Combat" section, but like most options it doesn't appear unless you have stats that depend on it.

Patient Reaper would require a separate option; I'll add that in the next update.

**Comment by PelmusMarian** [comment]
for Death's Oath the life degen does not appear when is equipped
can this be fixed ?
