### ISSUE TITLE
Vulnerability damage calculation

### ISSUE THREAD

**Issue by CoderFX** [Openarl/PathOfBuilding#339]
Hi. I'm running righteous fire, can use 2 curses (Whispers of Doom), using Flammability and Vulnerability. Vulnerability has "Cursed enemies take 33% increased damage from Damage Over Time effects", but looks like this is not calculated - tried switching this gem on and off, still get same DoT DPS.
![git-issue-rf](https://cloud.githubusercontent.com/assets/4704376/25783741/fa3c51ba-3369-11e7-8fff-18976ee93072.png)

**Comment by Openarl** [comment]
Do you have Witchfire Brew active? It will take precedence over the CoH Vulnerability.

**Comment by CoderFX** [comment]
Oh right, my bad. Thank you for enlightening me :)
