### ISSUE TITLE
[Bug] Error when trying to add Lioneye's Fall

### ISSUE THREAD

**Issue by DanielGrobelny** [Openarl/PathOfBuilding#34]
Hey! Awesome update today!

I got following error today (not sure if it's new).
When hovering over Lioneye's Fall in the item tab I receive:
![pob_bug](https://cloud.githubusercontent.com/assets/7581754/19963494/f0fb4c94-a1bc-11e6-8054-1642c7509a65.png)

Thank you for your hard work!

**Comment by Openarl** [comment]
Yep, that's a new one. Looks like one of the later changes to the new calculation code had one side-effect that I failed to pick up. That'll be fixed shortly. 

Thanks for the report!
