### ISSUE TITLE
Elemental Equilibrium deducted resists twice?

### ISSUE THREAD

**Issue by tjk96** [Openarl/PathOfBuilding#343]
Once upon selection of skill node EE
another time upon selecting "hit by <element> skill recently" in configuration tab?

**Comment by Openarl** [comment]
That can't happen; only one set of resistance modifications can be active at any given point in the damage calculations.

**Comment by Openarl** [comment]
I can't find any evidence that EE is behaving incorrectly, so I'll close this.
