### ISSUE TITLE
Path of building is super slow after the update

### ISSUE THREAD

**Issue by itamarsher** [Openarl/PathOfBuilding#345]
Path of building used to work great up until the last update. The app itself uses 5% CPU and 87MB of RAM and I have a lot more available so I guess that's not the issue.
Tried re-installing and it's still very slow.
------------------
System Information
------------------
      Time of this report: 5/14/2017, 22:47:25
         Operating System: Windows 10 Pro 64-bit (10.0, Build 14393) (14393.rs1_release_sec.170427-1353)
                 Language: English (Regional Setting: English)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: To be filled by O.E.M.
                     BIOS: F8c
                Processor: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 CPUs), ~3.8GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16346MB RAM
                Page File: 10082MB used, 8694MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: Using System DPI
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.14393.0000 64bit Unicode

**Comment by Openarl** [comment]
Are you sure nothing else changed with your system? I haven't received any other reports of similar changes, and there aren't any recent changes that I can think of that might have caused this.

**Comment by itamarsher** [comment]
The only major thing that changed is that the windows malware detection service is disabled now. But I don't think it's relevant. 
Note: I just tested updating on my work computer and over there everything works fine.
I have no problem trying to debug the problem on my computer with a compiled source code instead of the release version if it'll help; but I'll appreciate a tip on where to begin looking.

**Comment by Openarl** [comment]
I'm not sure how much help that would be. The slowdown is most likely inside the renderer, which is part of the C++ host program, which in turn is part of a fairly complex solution, and isn't easily isolated. But if you're really keen on helping then I can try and get a standalone solution working for the host (SimpleGraphic.dll).

**Comment by itamarsher** [comment]
Well, after the following patches the lags disappeared. Closing the issue.

**Comment by Openarl** [comment]
That's good to hear, although I'll be damned if I know what fixed it, because I never identified the cause...
