### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by Demiurgi** [Openarl/PathOfBuilding#346]
Hey,
I downloaded the latest version and installed it successfully, but on startup I get this error.

SimpleGraphic v1.0 x86 Release, built Apr 28 2017

Executing SimpleGraphic/SimpleGraphic.cfg
Warning: config file not found
Executing SimpleGraphic/SimpleGraphicAuto.cfg
Warning: config file not found
Executing C:\ProgramData\Path of Building\Launch.cfg

--- Render Init ---
Pixel format: need 32,24,0
--- ERROR ---
Critical error at address 6211D604h:
Access violation: attempted to read from address 00000F83h

**Comment by Openarl** [comment]
Hmm. This is second report I've received of a crash occurring at that point; I'm still not sure exactly what's causing it, but I suspect the display driver is at fault, so you can try updating that. Also, what OS and graphics device are you using?

**Comment by Demiurgi** [comment]
OK, well if it because of my display driver then that's that for me. My graphic card is so old that it doesn't get updated drivers anymore. :D 
Anyway, the card is AMD Radeon HD 6800 and OS is Windows 10.

**Comment by Openarl** [comment]
The latest update (1.4.12) adds more error checking code around the part where this error is occurring; if you can try installing and running from the new installer versions then it may help track down the cause,

**Comment by Demiurgi** [comment]
I tried and no change.

SimpleGraphic v1.0 x86 Release, built May 18 2017

Executing SimpleGraphic/SimpleGraphic.cfg
Warning: config file not found
Executing SimpleGraphic/SimpleGraphicAuto.cfg
Warning: config file not found
Executing C:\ProgramData\Path of Building\Launch.cfg

--- Render Init ---
Pixel format: need 32,24,0
--- ERROR ---
Critical error at address 6211D604h:
Access violation: attempted to read from address 00000F83h

**Comment by Openarl** [comment]
... Ah. Well, that confirms that the crash is occurring outside the program's code; probably in the graphics driver. I can't figure out why it's occurring with this program in particular, as it doesn't do anything unusual in this part of the code; so I'm not sure I'll be able to fix this. Sorry :/

**Comment by Demiurgi** [comment]
I found out that the problem was with a particular AMD .dll file and complete removal & re-installation fixed the problem.

**Comment by Openarl** [comment]
Ok, glad to head it's sorted.
