### ISSUE TITLE
Reserved mana over 100% with Radiant Faith grants energy shield

### ISSUE THREAD

**Issue by srmark** [Openarl/PathOfBuilding#348]
I understand that showing reserved mana for combinations that use over 100% are useful in general, but granting energy shield should be be capped at 100%, as it shows misinformation at reduced mana passives, and possibly at other places too.

My case is where is use near 100% reserve, and I have reduced mana passives allocated, with aura effect nodes too, so if I hover a whole cluster's starting node to get the info of how much ES I gain from the whole cluster, the calculation includes removing reduced mana would grant me more reserved mana (over 100%, falsy) thus granting ES.

**Comment by Openarl** [comment]
Fair point. That's easily changed; it'll be in the next update.
