### ISSUE TITLE
[Bug] Serpent Stance not working with Lioneye's Fall and having a bow equipped

### ISSUE THREAD

**Issue by DanielGrobelny** [Openarl/PathOfBuilding#35]
Hey there! Thanks for the super fast Lioneye's Fall-fix!

I've got some more coming! ;)
Is this the best format for you for feature requests / bug reports here at github?

As mentioned in the title, Serpent Stance is not counted towards global values while having Lioneye's Fall in the jewel socket and having a bow equipped. Blunt Trauma and the other connector-nodes do work though.

**Comment by Openarl** [comment]
I do prefer GitHub, the issue-tracking system is very handy.

I would never have thought that Serpent Stance would work with Lioneye's Fall, but I verified it in-game. Interesting. This won't be quite as easy to fix, as I'll need to change how I've implemented the jewel.

**Comment by DanielGrobelny** [comment]
Alright. No hurry! ;)

It's awesome for CoC Bow characters as it's applied globally to the bow-attack and the triggered spells. I've used it quite a lot.

**Comment by DanielGrobelny** [comment]
Addition to the infos:
Apparently it's the stat category "increased Global XYZ while wielding a [melee weapon]" that's not working properly. Just in case you didn't notice already.

**Comment by Openarl** [comment]
It's fixed in the update I just put out. The solution's a bit of a hack, but it works. Actually that jewel in general is a pain. It's by far the most difficult conversion jewel to implement.

That'll be all for today, as I need to sleep :).
