### ISSUE TITLE
Items with partial quality show incorrect defense totals while importing

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#350]
If you import this item:

```
Rarity: Rare
Demon Hand
Sorcerer Gloves
--------
Quality: +5% (augmented)
Energy Shield: 165 (augmented)
--------
Requirements:
Level: 69
Int: 97
--------
Sockets: B-B B 
--------
Item Level: 83
--------
+35 to maximum Mana
118% increased Energy Shield
+13 to maximum Energy Shield
+32% to Lightning Resistance
```

The item pane looks like this:
![image](https://cloud.githubusercontent.com/assets/510805/26231902/d54908ce-3c17-11e7-844f-ed1c49d1dc94.png)

Notice how it says +20% quality, 165 ES, but the imported item has 165 ES with only 5 quality. Once you click Add to Build the resulting item shows the correct total.

**Comment by Openarl** [comment]
Fixed in the next update.
