### ISSUE TITLE
Error after updating to 1.4.12

### ISSUE THREAD

**Issue by Kindarya** [Openarl/PathOfBuilding#351]
After updating to 1.4.12 I get the error message in the image attached below.
The same thing happens after uninstalling PoB, installing an older version and letting it update from there.
Installing with the exe for 1.4.12 gives an error beforehand
![pob_error](https://cloud.githubusercontent.com/assets/28807335/26248343/47e064a6-3ca2-11e7-9c2d-5dc9aee6cd50.PNG)

Installed 1.4.12 again and on the 1st startup I get the error below, from then on I get the error above.
![pob_error_2](https://cloud.githubusercontent.com/assets/28807335/26248610/59c93d72-3ca3-11e7-8ecf-4477fdc29c51.PNG)

Removing 1.4.12 and reverting back to 1.4.8 works for me for the moment.

**Comment by Openarl** [comment]
This is an odd one; I did update lcurl.dll in 1.4.12, but I can't find anything wrong with the new version of the DLL. Does the program start in 1.4.12 if you copy lcurl.dll from 1.4.8 before running it?

**Comment by Openarl** [comment]
Try [installing this](https://www.microsoft.com/en-in/download/details.aspx?id=48145); I think I inadvertently compiled lcurl.dll against the wrong runtime version.

**Comment by Openarl** [comment]
I've released 1.4.13 with a correctly-compiled version of lcurl.dll, and uploaded new installers, which I'm told has fixed the issue, so I'll close this.
