### ISSUE TITLE
Ryslatha's Coil mods 

### ISSUE THREAD

**Issue by The-Hasanov** [Openarl/PathOfBuilding#352]
20% more Maximum Physical Attack Damage
20% less Minimum Physical Attack Damage
pob cant calculate this mods 
 i really wish see this mods work correctly on next patch

**Comment by Openarl** [comment]
Are they really that important? They only skew the DPS calculation by a few percent, which is barely more than the rounding error that typically occurs, so I'm not sure it's worth going to the trouble of adding the extra step to the damage calculation.
