### ISSUE TITLE
Blasphemy + Assassin's mark Lowering DPS

### ISSUE THREAD

**Issue by tynen** [Openarl/PathOfBuilding#355]
I'm trying to build a crit psn cyclone raider and when I added Blasphemy + Assassin's mark the Total DPS Inc. Poison goes down. Here's a paste bin to the build. I'm really confused why this would be happening.

https://pastebin.com/fpeerGA9

**Comment by Openarl** [comment]
You have Witchfire Brew active, and Blasphemy curses take priority over the flask's Vulnerability aura, so enabling Blasphemy on Assassin's Mark causes it to replace the Vulnerability, which results in a DPS loss.
