### ISSUE TITLE
Culling Strike implicit & effective damage multiplier overall

### ISSUE THREAD

**Issue by vitalif** [Openarl/PathOfBuilding#356]
Hi!
Path of Building doesn't parse Culling Strike on the following item:
```
Ngamahu's Flame
Abyssal Axe
Unique ID: 3837bdfc954c7bcc2d0a3ad215118861086fa40709c820c82d3c595338e28713
Item Level: 79
Quality: 20
Sockets: R R G R G B
Implicits: 1
Culling Strike
224% increased Physical Damage
11% increased Attack Speed
50% of Physical Damage Converted to Fire Damage
Damage Penetrates 20% Fire Resistance
20% chance to attack with Level 16 Molten Burst on Melee Hit
Corrupted
```
Also Culling Strike logical "11% more" damage multiplier isn't taken into account even if I add "Culling Strike" as 7th link.

**Comment by Openarl** [comment]
An "11% more Damage" multiplier might seem logical, but it doesn't really behave that way. Having that multiplier there would, for example, imply an increase to damage leeched, which of course doesn't actually happen. It would also affect the DoT calculations (particularly poison/bleed/ignite), even though DoTs cannot cull. And in some encounters, Culling Strike doesn't act like a constant damage multiplier at all: consider Izaro or The Shaper, where it has no effect in the earlier phases, and an inflated effect in the later phases.

So Culling Strike just isn't one of those things that can be simulated easily, and as such, it's likely to remain unsupported for the time being. I will make the item parser recognise it as a valid implicit, though.

**Comment by vitalif** [comment]
Yes, you're right... it's not "11% more damage" it's like "10% less monster health" :)
Maybe just show it somewhere in the offense calcs? I.e show that the skill has culling strike applied to it.

**Comment by Openarl** [comment]
Maybe, but I wouldn't think that having Culling Strike on a build is something you'd need a reminder of, or would have trouble figuring out, since there's few sources of it, and most of them are global.
