### ISSUE TITLE
Attack Rate of skill secondary effects

### ISSUE THREAD

**Issue by peonso** [Openarl/PathOfBuilding#357]
I'm playing with Molten Strike and Frost Blades, and a issue that bothers me is that their secondary effect (Magma Orbs and Icy Blades repectively) Attack Rate is calculated separately from the main skills, e.g. they don't get melee attack speed bonus. I'm nearby sure that not what actually happens, they should fetch attack rate from the main skill (melee portion).

**Comment by Openarl** [comment]
This is the same issues previously reported in #241, so I'll close this one. 

Ideally they would get the melee part's attack speed, but due to the way skill parts are handled it isn't currently possible to do.
