### ISSUE TITLE
[Feature Request] Let CoC-Support values just work like a normal support gem

### ISSUE THREAD

**Issue by DanielGrobelny** [Openarl/PathOfBuilding#36]
Hey,

I don't think this would be a lot of work, so I am reporting this idea here.
Just to get the damage calculations right, would it be possible to calculate DPS values with the more / increased multipliers from Cast On Critical Strikes? I don't think the calculator needs any fancy stuff for this gem and it could just be treated like Controlled Destruction for example.

Or is it the wording that's causing trouble?

Cheers!

**Comment by Openarl** [comment]
That's a reasonable request. I really should have added support for it when GGG added the spell damage multiplier... I'll sneak it into the next update.

**Comment by Openarl** [comment]
And it's out. Enjoy!
