### ISSUE TITLE
Setting gem level to 0 or 31+ crashing application

### ISSUE THREAD

**Issue by krab** [Openarl/PathOfBuilding#360]
Here screenshots: http://i.imgur.com/SRx7hRV.png http://i.imgur.com/WkCYrCK.png

Also can we remove gem from gem list? Like this http://i.imgur.com/b3gckcG.png

**Comment by Openarl** [comment]
The error is fixed in the next update.

You can remove gems from the gem list by deleting the gem name; if you've set the level or quality to something other than default, you have to delete those too.
