### ISSUE TITLE
Ignite chance gets somehow lost

### ISSUE THREAD

**Issue by Cerugon** [Openarl/PathOfBuilding#361]
![screenshot 14](https://cloud.githubusercontent.com/assets/13507318/26519537/150eb3b2-42c3-11e7-962b-d6854fc12518.png)
The picture should show it. 
Chance to Ignite shows: 5%
The different sources add up to: 81%
Don't know how this happens, but it does.

**Comment by Openarl** [comment]
Could you give me the build? I haven't been able to reproduce this.

**Comment by Cerugon** [comment]
eNrtWVtz4rgSfh5-hYqqOTVTOyS2wcbkkN3iHjKQECAhyUtKGBk7-BZL5pJT-99PS8YBBpjxbKbmafMQbKvV6uunbqn819J10JyE1Pa986x8ImUR8Qx_YnvT8-ztsJnTs3_9mSn3MLOuzWpkO3zkz8yHcg07BoWHD-W2F0QMedgl51nXpsbTODLNrj8hWURZKBg1ms1Gbdi-a2RP96bQme04T17kjkmYRfEvSLKmHBCDgWjI8B0HB5RMzrMmdijwtuFxwOcOiANEqegvbFbHLp6SVNR1Px3XQUDIJBVlLbRTC1qzsGeQ9GYYrgIyYJjRVFOqTlqZe75NfS8VaXvq2SylbYmBV6koO4QYVgvb6UToQgA2TBNo0tmhwiBExxEj6cg7tplOvy72cCrChkfC6Wpg2cRJ549K6PpRmI73HPO8TkXbJ9Sm6YIzTqEhnpH0PqkTE3BlbeXyaYIeZQEpyCFz4kDSSwA_hoMpvRLQMLKZYWURpgbxJrXN94ZDXOIx7HCJ0dwmCw43EH_d3nV_mEUuRMvAN2aEtUI_CjiaoDH2JjbrktCwHULpefYaz5KvV37oYlj_yvdI8q0WRiT5JGQWSRYjnnhEFNxg8FUZcc-Us6FF0MiyaUA45qG2Qb6gO1gLQVKaZixUBcw0J2K6sICQzMFjvhIHXjx2uO0YrA3g6fgMbEBwAJaV9xjwuVyaD-UWcd8smBWoCohkgGBgbwaq3Xr2S0SEGLKyt8xLBHZkq_OsFDtzh58ibTOE_6B3w7D8n-ciYL6HQ_aNkE1MGQlRDX7AbO-RruZ7LIQAJBNUB8XDSMTkuzgKCEbMR2tk-2Vatz0jJBgSBVWj0OPxst6X3qU_ZBLI2rTDH_Mpn4og2grn3xKf_8bTv_F0LJ7Sxs8xG1Rhgwgs4q5-YTA52HXx2Oazv8c1ZtC1PVFFDyLXhW1jwmeTlg-b1W-10Y4GPA_QwiLeOiBQvG3_lIXk4wYa4dDxw8l_AAPofynq4nD2E6GyfhKFwDAkBOFYNcE61qzMX2KJbvsd8fDBYiygZ6eni8XiJIDGxDfJEjbaE8N3TwMoEoBFTgicY8D0tAJ_1Uq3Vqm-Go2mPfbNJn1eBrT2NTfGrfu5eVVi1v08L6-c3rA9rzxS--mKjuaB8ngbXV7l1Ydhs5iLrI7aqS57D6X75f299VIwKzQcFqvPD5cd7aup4_tSW8tNg4i83txceLho0mbpZVQxXq7bpVZ_8diftHLEUkbz57v86r5YH7QHz9rCvHbdkU-0nDa8XEq3xfrzWJUel61W0Lq1Amp25tXl3eNz5_L11S10Li6uSb02Gbnspj8a1CRz2OnS-eswrz-8SPX2k3Y1ds3VU3s-7s-84jB8mD6ZN1K1eXPrdPXqnXFVn037Hbx6cIv3-rDaGimjltetzqJOMLjJsYp5cavjKf76XJTAdLSrrWbhrP0s9fq3ZqP5SJrXd1-9r4tedDHW7tq11iJYTF-txfm5cNBp4qFyXHzR2F3rN-RBjdaGqCiWNMgYgD-XvyUBt0eWV4paPgWdoheKaho6TS5pGzr16Lqali-kkS9f0ksbOv3ounJJT8OvoOm6kkqPoqKm0KMgK6nsl5c1PQ2dqsqlNH4r6EVNT6NHoSSnINPkglxKo0ahkEoNTcmnir68lpdTWFkFMxfTLCsV82oqdfVD0QdIuUkpeIlBsXzKUZM_XPnQwfIx_jF5EZh6B90RogSHhjVgId9SXn3ffQB8lUvqiVQoFBQ1r8sc4y1_cUEw6-LgrX3jtJ14FyjGFPyIoW5Dhx2Kfi4BeU54D04tySeaLBULuqbAX9w58QaJoogSaBN9bxJXjAPCklXiIyEgEt3iekfr4xA2jTMUNy8Z3l0NLb5H1EM89T2agY11AttaF9NZpk9eIqhSKBKyorz6BRUkqNqW4rftscwfnxQtl5c-f-QVDeZVZ9JDorjz5ZUZzTxATycKnmS7NLCHBhbYHo35iZXP1qVbTClKpC3KeOyNtAnyvhLkA6EF21E8p2NPLbZVoomJa8pkolhR-B0a2z72gCrk_yEgTtTs2kzrzZQbbmPBOZgNe2BaJSZTjlpzt1fNbFrVzF3M4wz1wA7KiXYibT7VohAcz_Ysnv-C1BLMD8Uvt3jbDRzbsBk9Q0rmf2u5zuS_ZeUj2hTCVYdr-jas_C3r-8N_yPw5Xsk3UZwKUOsOoiDwQ4agVoF4AAsxGtcsSEZJ84tEiZH5pOdkBbxvvxXKojISR3cZeft73JSsfQMGQrKIIPhoT3nIZz7JhZys7_DaGf-u2xIgOU5RPOxYPpQ_6MwGPzFdQFmX6UfjFeqDR791j6zxBJDeEkBE-CbuQSU1p6g7Km0lQeaTmpOlY8ZTPyLjm76GB7oIa9szIQYYigI-mJekNQFF0DLCeMODcn2dSqCTbUA6QgzZM6CY-CIVJgS-kSULcSKNLn1E_Ajnm1YnVbp8h0L5IUX-uGcKx0ELu9whvdCmLgYNY_90CJ5G5AzVfRjFvK_8gq4AkMAje6klge_02AHfxS5Z2vbQVgDH4PJljWPYmyQ45ScekNXtqRv2ayYLm1kohm0KwshSTlZ_KM13We5GzTEB3-vSwnGHqQcdVg0jMEvTD0Guge9E3DGZmj_GDkOXZEGcTB9P7AggrYND0AJsoeWUwmcR-tsYAEFMvClYzQx9F_XipoSCQVDMANkUDUFcagJEkcne_F8B_dphFTFHzir4hVkZAFoQqUoc9k9AX1HAAKWcIgn9Xby03chF8YE2ik-0DwYlN5vAmz21E5A6zm9rp1B2WB8mV3dodsYgWiECwYvgkveHWv49wVg86KkKBdDjWQOYcO2tlqjiRg7Z94K0Tkntc5KRm0sNDh0wJEmHxnIF1LNWVKDuOtMZPx2IgxYIsTGjvwhWD6mtH1S7SULGa5Gu7U3-Ue5B2ccIZ_mbkm_g-Mld5uYwNCngE_W3iGI3bkiK-yR8j0BbzWDhCMnWQvl9Ep7XGwJtffUiqnFxg-t7pj3du4-1BfTu3t_W-u3hgatbXs3bHCM7_kLcjKGx7zsEe-uuYH8GvxruEW8SOZF7iLp8mkhVPv32zvn_VZV6JQ==

**Comment by Cerugon** [comment]
https://pastebin.com/tK3K5NfX
sry about that.

**Comment by Openarl** [comment]
You have the "Ignite calculation mode" set to "Crit Damage", so the ignite calculations are ignoring non-crit ignites entirely.
