### ISSUE TITLE
Curse effectiveness calculation

### ISSUE THREAD

**Issue by OSwoboda** [Openarl/PathOfBuilding#371]
I use the following build: https://pastebin.com/aCqcERxY

In use are Soul Mantle and two Kikakazu, which give 80% reduced of effect of curses on me.

With the used setup I have 159% lightning res in hideout and with Lv20 Elemental Weakness and Lv20 Conductivity I have 144% lightning res in hideout.

However, the PoB shows that I should have 142% in hideout.

Seems like it is calculated this way:
44\*0.2 = 8.8 for Conductivity
39\*0.2 = 7.8 for Elemental Weakness

ingame it seems like its rounded down, PoB rounds up.

**Comment by Openarl** [comment]
Actually, PoB is rounding down in this case (towards negative infinity), but it is causing incorrect behaviour, as the resistance values from those curses are negative, and the game rounds them towards zero instead. I'll correct the rounding in the next update.
