### ISSUE TITLE
Warlord's Reach limit 1

### ISSUE THREAD

**Issue by tynen** [Openarl/PathOfBuilding#373]
I've got a Cyclone character using 2 warlord's reaches in the passive tree and both are effecting the radius, but it's a limit 1 jewel and shouldn't here's a pastebin of the tree: https://pastebin.com/JEwyrChd

**Comment by Openarl** [comment]
The program doesn't enforce the limits on unique jewels; it wouldn't really be a productive use of my time to develop a way of handling it, when the user should be aware of the limits anyway.
