### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by uzimex** [Openarl/PathOfBuilding#375]
I used "Craft item" to create a rare Cobalt Jewel. I gave it "Vivid" and "of Resistance" mods, then I wanted to give it Magic rarity via "Edit" and I got [this](https://puu.sh/wcDy8/ead035ebb2.png) error. I had to press F5 afterwards.

**Comment by Openarl** [comment]
I can't seem to load that image, but it should be the same error reported in #374, which is fixed in the next update.

**Comment by dein0s** [comment]
Re-uploaded this for you @Openarl 
![error](http://i.imgur.com/r2NuXHl.png)
