### ISSUE TITLE
Slow down and mini freezes on all versions of PoB

### ISSUE THREAD

**Issue by MalinirXaresson** [Openarl/PathOfBuilding#376]
Recently Path of building has been super slow. Whatever i do it takes up to 3 seconds to do it (even only hovering and higlighting a menu label) and inputs get sometimes lost if i click during this "mini freezes" that seem to occur costantly. I tried a couple of different versions of PoB and the problem is constant in all of them.

**Comment by LelandDantzler** [comment]
I can second this issue. Notably, closing and reopening will resolve it...this only seems to occur after the program has been open a while (maybe after a lock/sleep?).

**Comment by MalinirXaresson** [comment]
For me its stuck like that, closing and reopening it does not change the issue, nor does it change when i shutdown and restart the pc, honestly i have no clue what's going on

**Comment by MalinirXaresson** [comment]
Solved the issue by upgrading to the latest nvidia drivers, don't really know how this slipped my mind when i was trying to fix it XP

**Comment by Openarl** [comment]
Ah. I should have suggested it though; out-of-date drivers can cause all kinds of issues with this program.
