### ISSUE TITLE
Blade Vortex does not account for blade count

### ISSUE THREAD

**Issue by Tripwyr** [Openarl/PathOfBuilding#377]
I've never used Blade Vortex in pob before, so I can't say whether this is new in the update. Increasing the number of blades has no effect on the DPS dealt by the skill. On a quick test setup, I am dealing 4200 DPS with both 0 blades and 20 blades.

**Comment by tsandras** [comment]
I've used Blade Vortex in builds with PathOfBuilding and yes since 1.4.21 (or 1.4.20) the number of blades has no effect on the DPS.

**Comment by Openarl** [comment]
This is a known issue, and already fixed for the next update.
