### ISSUE TITLE
1.4.22 unique items filter is broken now

### ISSUE THREAD

**Issue by RinkataKimiku** [Openarl/PathOfBuilding#378]
Greetings!

Unique items filter is broken now if I select specified item type
http://dl4.joxi.net/drive/2017/06/08/0019/3848/1277704/04/8a801fada1.jpg

But it works if I select "any" item type
http://dl3.joxi.net/drive/2017/06/08/0019/3848/1277704/04/7c2c3eeec6.jpg

**Comment by Openarl** [comment]
Fixed in the next update.
