### ISSUE TITLE
[BUG] Attempt to compare number with nil

### ISSUE THREAD

**Issue by r0bo7** [Openarl/PathOfBuilding#38]
Stacktrace:

<img width="960" alt="stacktrace" src="https://cloud.githubusercontent.com/assets/23621201/20467098/f2a0ca9e-af66-11e6-9e50-916908e2a5d7.png">

This happens when I hover the mouse through the "Import from" list containing unique items for Weapon 2 slot

Edit: More specifically the `Kongming's Stratagem Ivory Spirit Shield`

**Comment by Openarl** [comment]
There was a bug with the No Block Chance modifier on that shield. That's fixed in the next update.

Thanks for the report!
