### ISSUE TITLE
Coated Shrapnel

### ISSUE THREAD

**Issue by sneffetsd** [Openarl/PathOfBuilding#380]
4 coated shrapnel gives 100% chance to poison, but doesn't show poison dps in calculations.

**Comment by Openarl** [comment]
I can't reproduce this; it seems to be working fine. Could you give me your build?

Also, just to make sure you know, that jewel only provides poison chance for trap and mine skills.

**Comment by sneffetsd** [comment]
I was trying with this build.

`eNrFWFtv4jgUfm5_hRVppdkHCgkhJCOYEbdSOkAZblP6gkzikEwTGxIDpb9-j51k2p3OxSOttFXV2sl3rj43p_HxKY7QkSRpyGhT068qGiLUZV5It01tMb8u2drHD5eNCebBnd8-hJF48-HyoiHXKCJHEjU1B8g4TraELwtW1TU822DqhXzMkhgDaswoKZ41tVYUJrjYjkjihhFJ0wLlRjhNxzgmTW0WYI-dNIRTl1Cv8-oF3jBODomGYhzSGXMfCe8n7LADQzR0DMlpxDzADUaTu-m8ENVJDqRQpiws6eDITWFx0RjQ3YEjKpmnj2EUrekh3hAQkP0XfMtvkHGYuuvNwfeFNA2lPJHO611f9zrzwbKXk8yIy8EzyGVRhHcp8ZoaDSMNhbCYCWEzEgFEAX0T8i6O8ZYoYLtMheNsR4ingOskoaKCnQBTl6iaPj_vyIxjnioQtCM1XScsTBlVAA62NORKviQuPivghoS4QR9CUgE7guDp-T4gVGxvcQiuzYETFfAw9FWsGmGKFWA9SpLteRaEJFLxfiuJGWSmAt8jFgVDATklaZiqhF-WHHP8SFRPoEt8qHq5VxvloiI0ZHBmtUEuZaFpAa8jkXsJlNUmwhtRVUT1xJtICOBQZ7TvCQRWsLto9ElcVE8DKqUsNwMg60fYDTFwTl0sysn-gKOQn5ta5Q1vUX4gc91vRKigKv9axuyw27GEtzyPeNdhQvJqoiZLUiFBhl5Xod9Km5IYqvUopKqCMgIkKdRECKgvA1RNwgtejf88wbsW9QTZH7lM0CFoPtKWP_PaJDinoYujORuG24BTaC2KQgtKxBl6oVWT2mGUJ5ArxOsS6GcHmT0_kevjKP2X4Bdi9Jo6y8SyTIPfZpTMTuWcEuhf23WDeUI8VQty9G99FceMQqNjaZ9FJM5fwRmDud-y_c3Dl5qhpkwmBkk56K2gAkC8V5ooaT6Fgek_VPz7-Mv1nnHQ7Zd6S8TP9NZrr_SG2Q8GkLOiAgX6fw28PKFAI5hyoJzFqt4TBCij-IFXXjcMEncJuBBnxTVVFFDQoIzoOyflK9kE5wkhCGdmS9KshTXEJtNsMR3KxUXA-S59Xy6fTqerHVwZmE-eYKy_cllc3sHcDixKUvESJBgpt-Cn3Vp1W-1n1_ON-yEePtSDxcBpVafn9rQz7J8Gx0_s7muA1-OHwWp5tCar_Wmg3931NoPnpL5vd0_ugtj92wnbjyxzetdduth8rLulORmldBwsdhHpPDlHulwcj5ZJ558fHvZfbw_YGFZv2_G4233cria9aGKv9qPx4_mZL75u7vfWc3vxCZuth-pAd-ytuThPH4wtuX84rrdsGiUVehcF66edsR_0rVo7XXu8-qVr1PyKa1R67acer0y-3EfzldNz1qfSfXuKH8efR8Puyr2-Dcyw4q8XLI6Wo6cbPd131suj3rudL3jL79tb577Sv_GTtmdHt_NPk_1yMKHs5E_O05WNg37JtrbNpnR8ufB8I7v9pNkx5DtE4UIiQqTuWBAKMOTGYlfJA-oNrGrUraoCzrDNek0FZ-mOpSLXsqrmC07_Ka7q2I6KXDgyUwFnWrZtKNlRN1TsrZm6UVfAWUa1omBuraY7Ksdm2nXLVjHDdHSV0zBNWyUKLN1WOjVLN3VH6XStqq7Cr1KvqpwGHIZSNFd160f2QgV8SSnYZMWuURbVUCzGUJrlO_Gw2MhauQzJCaUEJ24w44n4PiBG3mfG4hWYZVhXjqXXanZNr1kQfWnATjcE8xHe5d1HIId5K8nei6txN4RbYiJvKUUxF8D7plZyrKua4Th1U69Xq4aTXWIGYE-KDimBuw-j3heCd9DHCX9pWhIir0D5nWQq--V7tKDh_kAuOwzag4dmAUyvlESXcPmP4UaNbskJdmKmTb8NtSnyCIya76ql2t9i4HynV0o6LLHnhWL6g3ff5tFs_n3DIMBHaDPIqP2FXPnxQPDJLvEIfm9CLo9lxLwppluCEvEXzuvKcmo6pHz-R8styhuasFGem_SH_NzDqB9u33zFAU9N2IkkMEUlW9FFNwxGEkxzZ-cXw5y2Uf7-g9g_RNgEvw==`

**Comment by Openarl** [comment]
Your damage is 100% elemental, so you cannot poison.

**Comment by sneffetsd** [comment]
Oh...you can't poison with elemental now. I removed phystolighting and it show the poison, you are 100% right. I didn't know about that change. Thank you.

**Comment by Openarl** [comment]
Change? Elemental damage has never been able to poison.
