### ISSUE TITLE
The new Mind Over Matter does not include Damage over Time

### ISSUE THREAD

**Issue by rednax825** [Openarl/PathOfBuilding#381]
Mind Over Matter and related effects were updated. 

The wording changed from:
"When Hit, X% of Damage is taken from Mana before Life"
to:
"X% of Damage is taken from Mana before Life"

This update should cause damage from DoT to be affected by MoM. Currently this is not the case in PoB.

**Comment by dein0s** [comment]
Well, there's no complete patchnotes for the PTR realm yet. So, lots of things may be missing atm :)

**Comment by Openarl** [comment]
I'm aware of this change, but I haven't had time to figure out the best way to model it.

**Comment by Openarl** [comment]
The MoM/degen interaction has now been implemented in 1.4.30.
