### ISSUE TITLE
Melee Damage on Full Life 

### ISSUE THREAD

**Issue by devsej** [Openarl/PathOfBuilding#382]
MDOFL is giving less damage than fortify , whereas it gives somewhat equal to Melee Physical  Damage Support. I thought maybe active bloodrage is not counting my life as full , but that is not the issue.

**Comment by Openarl** [comment]
The program does not assume you'll always be on full life unless you have CI; so you need to enable the "Are you always on Full Life?" option in the Configuration tab if you want it to apply.

**Comment by devsej** [comment]
Thanks , was not aware of that, :)
