### ISSUE TITLE
Summon Skeleton Mages with Iron Will and The Baron

### ISSUE THREAD

**Issue by OSwoboda** [Openarl/PathOfBuilding#384]
I wanted to setup a build with Dead Reckoning Jewels and The Baron. Unfortunately Iron Will seems not to interact with summon skeletons in PoB. Are they for sure not using a spell (but spell echo and faster casting works) or is it just an oversight?

**Comment by Openarl** [comment]
Iron Will cannot support Summon Skeletons; whether that's intended by GGG or an oversight on their part I cannot say, but either way the fault is not with PoB as it uses the same data to determine support compatibility as the game does.
