### ISSUE TITLE
Blood Lust not updated to current version on Beta

### ISSUE THREAD

**Issue by nitroglisc** [Openarl/PathOfBuilding#389]

**Comment by Openarl** [comment]
Clarify? I'm not aware of any changes to that support. Perhaps you're referring to the absence of the "Cannot cause Bleeding" stat? That has been confirmed as being a display issue; the stat is still present on the skill, and indeed Path of Building still sees it and acts on it.

**Comment by Openarl** [comment]
I still can't see any inconsistencies, so I'll close this.
