### ISSUE TITLE
Decay DPS is not getting buffed by the 10 stacks Flameblast

### ISSUE THREAD

**Issue by myrahz** [Openarl/PathOfBuilding#390]
Pretty much what title says, Decay essence should benefit the more damage multiplier

**Comment by nitroglisc** [comment]
its more spell damage on flameblast, secondary DoT's dont benefit from spell damage

**Comment by Openarl** [comment]
Stats like the per-stage multiplier on Flameblast are changed to global damage modifiers in 3.0 so that they apply to ailments too. I was waiting for confirmation before allowing them to apply to Decay as well, but I've seen sufficient proof now that I'll make that happen in the next update.

**Comment by myrahz** [comment]
Oh well, nurfed :D

**Comment by Openarl** [comment]
Yeah, well the whole reason I didn't enable skill part modifiers for Decay was because I thought it'd be too broken for GGG to have allowed. Guess I was proven correct :P
