### ISSUE TITLE
Convenient 20% quality on gems

### ISSUE THREAD

**Issue by orlp** [Openarl/PathOfBuilding#391]
It would be nice to have a button on the skills section that puts all your gems to 20% quality, or some other method that makes it easy to put 20% quality gems in.

**Comment by aggixx** [comment]
Perhaps "Default gem quality" (and maybe even "Default gem level") could be added to the global options dialogue. I like to plan all my characters with the assumption of 20/20 gems, so that would save me a lot of time.

**Comment by Openarl** [comment]
I don't think I'd add something like that to the global options; there's valid reasons for wanting different defaults in different builds, so a global option won't do. It's also not the sort of thing I usually stick in the Configuration tab either. However, the Skills tab itself has plenty of spare room, so I could add those options there.

**Comment by Openarl** [comment]
The next update will add options in the Skills tab for default gem level and quality; these are saved per-build.
