### ISSUE TITLE
Righteous Fire, Scion Ascendant Trickster

### ISSUE THREAD

**Issue by ABCamper** [Openarl/PathOfBuilding#393]
Hi,

first of I have to say I am really impressed how well the tool ist working and even Righteous Fire calculations are correct which really surprised me. Great Job!

Now the minor error with Righteous Fire and the Scion.

If you choose Trickster at the Scion, one of its features is 20% increased damage while not on full Energy Shield.
This should be active for a life based RF build and implemented into the total damage calculations.

As said it is only a minor thing, just wanted to leave the message here so you know about it.

Good luck and take care

**Comment by Openarl** [comment]
It's not really an error as such, I just hadn't gotten around to adding support for the "full Energy Shield" condition; there's a LOT of odd conditions like that in Ascendancies, so I generally only add support for one if someone asks for it. It'll be in the next update, as usual.
