### ISSUE TITLE
Vile Toxins

### ISSUE THREAD

**Issue by Tarsonis42** [Openarl/PathOfBuilding#394]
Please add an option for the vile toxins more multiplier on hits:

> Skills deal 5 % more damage with hits for each poison on the enemy (up to 6-9).

This could be a part of the configuration panel, where we currently state weather the enemy is "chilled, ignited, covered in ash, ...". Could be an option like "Does the enemy have poison stacks" that lets us specify the number of poison stacks. I feel the gem will give a lot more damage to some builds, as soon as this is considered in the calculation.

Thanks!

**Comment by Openarl** [comment]
I do want to add support for this, but unfortunately the limit makes it a bit trickier to implement than would otherwise be the case. But I'll take another look at it now, since you asked nicely...

**Comment by Openarl** [comment]
Ok, I've found a reasonably elegant solution for this; it'll be in the next update.

**Comment by Tarsonis42** [comment]
Awesome. Many many thanks!
