### ISSUE TITLE
Corrupting item caused build to be unable to be opened

### ISSUE THREAD

**Issue by britishbubba** [Openarl/PathOfBuilding#395]
Added "1 extra curse" corruption to a carnage heart on a slayer build and I'm now getting the following error any time I attempt to open the build.

Error:

In 'OnFrame': Modules/Calcs.lua:256: bad arguement #1 to 'ipairs' (table expected, got nil)
stack traceback:
[C]: in fuction 'ipairs'
Modules/Calcs.lua:256: in fuction 'buildOutput'
Classes/CalcsTab.lua:378: in fuction <Classes/CalcsTab.lua:363>
Modules/Build.lua:484: in function 'CallMode'
Modules/Main.lua:248: in function <Modules/Main.lua:239>
[C]: in function 'Pcall'
C:\ProgramData\Path of Building\Launch.lua:98: in function <C:\ProgramData\Path of Building\Launch.lua:95>

Press enter/Escape to Dismiss, or F5 to restart Application.

Restarting or completely closing out the program and reopening does not chance this.

**Comment by Openarl** [comment]
Sorry about that; it seems I forgot to test Punishment against the modifications to the buff code that were in 1.4.31. That curse causes all kinds of problems, given its debuff/buff duality. Anyway, it will be fixed in the next update; I'll try and get that out soon.
