### ISSUE TITLE
Cannot see Helm Essence "More" modifier on Vortex spell gem. Same with Hierophant "More" ascendancy node.

### ISSUE THREAD

**Issue by charlarpoe1** [Openarl/PathOfBuilding#397]
https://pastebin.com/YGLY6Sqi

Hover More modifiers for Vortex effective DPS. only see gems do no see gear. However, toggling on/off the hat and ascendancy node changes side bar DPS calculation.

**Comment by Openarl** [comment]
Both are there, but I think you are looking in the wrong places, The Essence modifier is for elemental damage, so you will see it when you hover Cold in the Total More row. The Hierophant modifier is in the hover for Cold in the Effective DPS Mod row.
