### ISSUE TITLE
Chance to Bleed Support & Bleed Damage

### ISSUE THREAD

**Issue by joris-s-k** [Openarl/PathOfBuilding#399]
Currently the Chance to Bleed Support doesn't scale Bleed (which it does in-game).

**Comment by Openarl** [comment]
Hmm. This will be a bit tricky to fix; the base damage from that support is weapon-only, which can't possibly apply to the bleed given the current design of the ailment code. But there's also an issue with Drillneck's added damage to Bows, which isn't applying for the same reason, so I'll be able to solve two issues if I can find a fix...

**Comment by Openarl** [comment]
I've managed to implement a solution for this, which also has a side effect of making the calculation code faster, which is neat.
