### ISSUE TITLE
Crash on first run

### ISSUE THREAD

**Issue by VitusVarian** [Openarl/PathOfBuilding#4]
After the program installed, I tried to run it from the installer. A window popped up with the following:
Windows 7, used the installer exe

SimpleGraphic v1.0 x86 Release, built Aug 30 2016

Executing SimpleGraphic/SimpleGraphic.cfg
Warning: config file not found
Executing SimpleGraphic/SimpleGraphicAuto.cfg
Warning: config file not found
Executing C:\ProgramData\Path of Building\Launch.cfg

--- Render Init ---
Pixel format: need 32,24,0, using 32,24,8
Creating context...
Loading WGL extensions...
using WGL_EXT_swap_control
GL_MAX_TEXTURE_SIZE: 16384
Loading OpenGL extensions...
using GL_EXT_texture_compression_s3tc
using GL_ARB_texture_non_power_of_two
Loading resources...
Renderer initialised in 523 msec.

--- UI Init ---
Script: C:\ProgramData\Path of Building\Launch.lua
Script working directory: C:\ProgramData\Path of Building
Initialising Lua...
Running script...
Saving C:\ProgramData\Path of Building\Launch.cfg

--- Render Shutdown ---
Unloading resources...
Deleting context...
Renderer shutdown complete.
Engine shutdown complete.

--- SCRIPT ERROR ---
Runtime error in 'C:\ProgramData\Path of Building\Launch.lua':
[COULDNT_RESOLVE_HOST] Couldn't resolve host name (6)
stack traceback:
	[C]: in function 'perform'
	C:\ProgramData\Path of Building\Launch.lua:38: in main chunk

**Comment by Openarl** [comment]
The answer lies in the last part: [COULDNT_RESOLVE_HOST] Couldn't resolve host name (6)
The program needs to download a few files when it is first run, and it looks like there was a temporary problem with your internet connection when it attemtpted to do so. Just start it again and it should work.

**Comment by VitusVarian** [comment]
Hmm, I have had the problem non-stop (I've tried maybe 10 times?)
I will have to assume it is my work network. I'll try again from home later. 
Thanks for the reply.

**Comment by Openarl** [comment]
Ok sure; do let me know if the issue is resolved.

**Comment by VitusVarian** [comment]
Just following up - It does indeed work on my home computer.

**Comment by Openarl** [comment]
Ok, thanks!
