### ISSUE TITLE
beta 3.0 new cloak of defiance missing

### ISSUE THREAD

**Issue by mssimi** [Openarl/PathOfBuilding#400]

**Comment by Openarl** [comment]
The first batch of unique changes will be coming in the next update, including CoD.

**Comment by eps1lon** [comment]
I created a [js script that parses poedb's unique item list.](https://gist.github.com/eps1lon/0de26396f2f2751129f271ffac82be11) Usage is described in its description.

I already diffed it [with](https://www.diffchecker.com/zZ90a0ZF) and [without base items and implicits](https://www.diffchecker.com/OTyZd5yA)

**Comment by eps1lon** [comment]
Oh man you already closed it while i was writing :D Maybe this helps for future beta patches.

**Comment by Openarl** [comment]
Ooh. I'll take a look through that; there might be some changes I've missed.
