### ISSUE TITLE
Mana Regeneration is incorrectly increased in case of Trickster Degen Kill

### ISSUE THREAD

**Issue by hajdukd** [Openarl/PathOfBuilding#401]
It treats 70% increased recovery as addition to increased regeneration.

When it should be a multipler. At least in my understanding of the mechanic - (life regen is multipled)

**Comment by Openarl** [comment]
Ah, you're correct on this; I lumped recovery modifiers in with regeneration modifiers, when they do apply at different points. I'll fix this in the next update.
