### ISSUE TITLE
Jewel custom affixes only adding as suffix

### ISSUE THREAD

**Issue by sherlockmatt** [Openarl/PathOfBuilding#403]
In trying to add a jewel which has #% increased Maximum Mana on it, I noticed PoB tried to add it as a suffix even though it is a prefix, and it is listed under the prefixes section. Having tested several other custom affixes for jewels they all add as suffixes. I haven't tested other item types.

![Bug image](http://i.imgur.com/EaeYY6I.png)

PoB v1.4.33
Win10

Let me know if you need more info or there's anything else I can do to help :)

**Comment by Openarl** [comment]
That's not a bug; custom affixes always display at the end, after any other modifiers on the item, just as crafted affixes do in-game (that's why they use a different colour to normal modifiers).
