### ISSUE TITLE
Decay scaling with trap bonuses for some skills

### ISSUE THREAD

**Issue by Scol91** [Openarl/PathOfBuilding#405]
For some skills (like Vortex or Ethereal Knives) Decay scales with trap bonuses. For others (like Essence Drain or Blade Vortex) it doesn't.

tested with Trap and Mine Damage Support and Trap Support

**Comment by Openarl** [comment]
As far as I'm aware, modifiers to Trap, Mine, and Totem Damage are still able to affect Decay, so that's working as intended. The reason it doesn't work for Essence Drain and Blade Vortex is that neither of those skills can be turned into a Trap or Mine.
