### ISSUE TITLE
[Bug 3.0] LL RF w\ MoM

### ISSUE THREAD

**Issue by MasterScooby** [Openarl/PathOfBuilding#407]
When doing a LL RF build need a way to force degen to only ES as MoM does not kick in till after ES is depleted.  Maybe a Have ES? checkbox in Configuration?

**Comment by Openarl** [comment]
Why would you have MoM as LL RF? Or are you just going for the mana nodes? Anyway, I didn't anticipate that particular combination; I'll have to see if I can find a good solution.

**Comment by Openarl** [comment]
As of the next update, the split degen calculations will only activate when you have more Life regen than Energy Shield regen, which should exclude any kind of LL setup.

**Comment by MasterScooby** [comment]
Thanks!  And yes and it is just to get the mana nodes for Guardian/Hierophant Mana->ES.
