### ISSUE TITLE
New update turned tree into mush

### ISSUE THREAD

**Issue by Azmodael** [Openarl/PathOfBuilding#408]
Screenie

https://1drv.ms/i/s!AjprKol0kxJwhGWp4CL2W88W49Lg

Importing builds or using old saved builds produces this tree. Starting new builds works fine.

**Comment by Openarl** [comment]
I'm sorry, can you point out exactly what is wrong there? Because that looks perfectly normal to me.

**Comment by Azmodael** [comment]
I'm sorry. Apaarently the "Node power" checkbox was ticked in. Never used and never noticed it does that.

**Comment by Openarl** [comment]
Oh right. Fair enough.
