### ISSUE TITLE
[Feature Request] Show the calculated benefit of curses / buffs in the "Calcs" tab

### ISSUE THREAD

**Issue by DanielGrobelny** [Openarl/PathOfBuilding#41]
Hey again!

Just a low-prio feature, but I think this would be cool:
Hovering over the buffs at the top of the "calcs" tab could show the benefits of the eg. auras just like you do it in the skill-tree.

Here is some concept art with extensive use of Comic Sans to spice it up a little:
![aura_buffs](https://cloud.githubusercontent.com/assets/7581754/20499676/ce2693f2-b032-11e6-9be9-4f02ef34e4f4.png)

**Comment by Openarl** [comment]
That one's been on the TODO list for a while; showing the effects granted by an aura/buff/curse skill is easy but calculating the effect of enabling/disabling the skill is a bit trickier. I'll get around to it some day though.

**Comment by Openarl** [comment]
The modifiers granted by auras are now shown in the Calcs tab, and the effects of enabling/disabling a skill are shown in the Skills tab, so I'd consider this done.

No Comic Sans, though :P
