### ISSUE TITLE
Cannot find iron ring in items page except those Unique item

### ISSUE THREAD

**Issue by choiyuhin515** [Openarl/PathOfBuilding#410]
I am building a Ancestral Warchief build which my main DPS is from iron ring, but i cannot find iron ring in items page except those Unique item

**Comment by dein0s** [comment]
Craft it ?

**Comment by choiyuhin515** [comment]
That can be the temporary solution. Thx, i didn't think about that.

**Comment by Openarl** [comment]
The item templates are intended to provide only the commonly-used bases and modifiers; the item crafting system is intended to fill the gaps. Given how weak Iron Ring's implicit is, I don't think enough builds would bother with it to justify adding a template for it.
