### ISSUE TITLE
[Issue] Windows 10, app working space overlaps with window title bar

### ISSUE THREAD

**Issue by dsavvinov** [Openarl/PathOfBuilding#411]
It looks like something messes up Path of Building scale rendering, trying to fit it into smaller than intended viewport 
![example](https://user-images.githubusercontent.com/6999635/27427668-7427bc88-5748-11e7-8970-b17a68ae52a9.jpg)

Notably, this leads to issues with clicking buttons, as shown below:
![example2](https://user-images.githubusercontent.com/6999635/27427828-f9c76910-5748-11e7-8a65-0458e138a7a9.jpg)

It looks like app's working space is rendered starting staright from the top edge of the window, instead of bottom edge of title bar, while coordinates of mouse cursor are counted starting from the bottom edge of title bar (I assume this is correct). This results in shifting of targeting boxes from actual positions of corresponding buttons. Discrepancy is roughly equal to the height of title bar, which kinda proves this theory. 

I'm using Windows 10 for Education, ver. 1703, build 15063.413 / Intel HD Graphics 630 (updated to the latest drivers version). Display scaling set to 100%, and just in case Windows scaling turned off in Compatibility tab of Path of Building.exe  
I've checked exactly this version on my laptop, and it works fine. Laptop runs Windows 10 Home, ver. 1607, build 14393.1066 / NVIDIA GTX 860M. Notably, Windows scaling is set to 125%, and it is not turned off in Compatibilty tab of Path of Building.exe.

**Comment by Doomgull** [comment]
As another data point to attempt to assist tracking this down, I don't see this issue. Windows 10 Home, 10.0.14393 Build 14393. No window scaling.

Wonder if it's something with how win10e handles rendering?

**Comment by Openarl** [comment]
I've seen this a few times; it seems to mostly occur with Intel HD Graphics. It's definitely a display driver issue, and I'm fairly sure I know how the program manages to trigger it, but last time I attempted a workaround it caused major issues for some users, so I'm a little reluctant to go tampering with that part of the code again.

Anyway, the issue may not be around for too much longer, as I'll soon be embarking on a rewrite of the program host's engine, which should fix most outstanding technical issues such as this one. Of course, there'll no doubt be new ones...

**Comment by dsavvinov** [comment]
@Openarl is it possible to see a commit with workaround? Unfortunately, this issue isn't only about convenience - when I quit to the list of all builds, title bar hides menu buttons, and I can't even get back to the skill tree. I think, I could try to apply patch with workaround in a separate fork (I expect this will require some tinkering, but well, I wouldn't know if it will work if I won't try :) )

**Comment by Openarl** [comment]
The workaround is in the C++ host (SimpleGraphic.dll) and the code for that isn't hosted anywhere, but I can give you a version of that file with the fix in place: [SimpleGraphic.zip](https://github.com/Openarl/PathOfBuilding/files/1098099/SimpleGraphic.zip)
You'll need to close PoB, then overwrite SimpleGraphic.dll with the version provided (you'll find it in the PoB folder in Program Files if you used the installer). When you launch the program, it will detect the change and prompt you to update, so just ignore it.

**Comment by Openarl** [comment]
Oh boy. So you're having the problem, and are also one of the people for whom the fix causes issues. Well, on the plus side, if I can make a version that works for you, I'll be fixing two issues at once.
Could you try [this version](https://github.com/Openarl/PathOfBuilding/files/1098220/SimpleGraphic.zip)?

**Comment by dsavvinov** [comment]
Now PoB launches, but the issue is still here

**Comment by Openarl** [comment]
I must admit, that's not the outcome I expected; I thought it would either continue crashing, or work perfectly. I now suspect that the "fix" doesn't actually work, which implies that the problem is elsewhere. I'll be damned if I know where, though.

**Comment by Openarl** [comment]
I've had a report that the latest Intel graphics driver fixes this, so you should try updating.

**Comment by dsavvinov** [comment]
Updating worked indeed, so I close this one. Thanks for support :)
