### ISSUE TITLE
DPS calculation on Facebreaker version Ancestral Warchief

### ISSUE THREAD

**Issue by choiyuhin515** [Openarl/PathOfBuilding#413]
When i link [Ancestral Warchief - Faster Attacks - Melee Physical Damage - Melee Damage on Full Life - Increased Area of Effect - Added Fire Damage], Melee Damage on Full Life only contribute very low DPS (159.4 Total DPS), which may not be accurate. 

Here is my build for your reference: https://pastebin.com/zNAfRe6a

**Comment by Openarl** [comment]
The program doesn't assume you'll always be on Full Life; so if you want that support to apply fully, you'll need to set the "Are you always on Full Life?" option in the Configuration tab.
