### ISSUE TITLE
Raise Zombie Slam MH Total Increased 

### ISSUE THREAD

**Issue by cperche** [Openarl/PathOfBuilding#415]
With a Necromancer build, using Raise Zombie, looking at the Minions MH Total Increased stat in the Calc tab will trigger this error if Slam is selected as the minion skill:
![capture](https://user-images.githubusercontent.com/29665824/27499046-44e89a44-5862-11e7-8018-3366b72c9d07.PNG)

Here is my [build](https://pastebin.com/QewpJhVX)

**Comment by Openarl** [comment]
Fixed in the next update.
