### ISSUE TITLE
[BUG] Added base radius not working

### ISSUE THREAD

**Issue by didii** [Openarl/PathOfBuilding#417]
To emulate the unique jewel Rolling Flames, I added an item affix with the name

> +4 to Fireball Radius

which Path Of Building recognises (text is blue, not red). However, when looking at the _Calcs_ tab, the radius stays at its base value of 12 instead of 16. I tested this with both Fireball and Flameblast. Both have the same issue. Increased area of effect does increase the displayed radius on the _Calcs_ tab.

Minimal example: https://pastebin.com/vs7tvVVw.
* Weapon 1 has a Wand with _+4 to Fireball Radius_.
* Weapon 2 has _+4 to Flameblast Radius_.
* No area of effect modifiers are taken elsewhere.

**Comment by Openarl** [comment]
Ah. I'd never actually intended for the base radius to be modified that way; while the program does recognise the modifier and parse it correctly (which is mildly surprising), it doesn't do anything with the output, as only the base and added radius from the skill itself are counted. That is easily fixed, though.
