### ISSUE TITLE
Punishment Curse Calculation Issue

### ISSUE THREAD

**Issue by Veracior** [Openarl/PathOfBuilding#418]
Punishment's "Punisher" buff is effecting elemental damage when it shouldn't be.

_Cursed enemies grant (25-35)% more **Physical** Melee Damage on Melee hit_
Is incorrectly increasing average damage output by elemental sources such as Added Cold Damage Support.

Love your work on Path of Building @Openarl, I haven't used anything else in a long time!

**Comment by Lothrik** [comment]
I'm noticing this as well. Punishment definitely shouldn't be a 46.1% DPS increase for a build where 97% of the damage comes from Added Fire (with zero elemental conversion).

**Comment by Openarl** [comment]
Fixed in the next update. Oddly, the stat granted by the curse doesn't specify physical, and I never bothered to check if it was physical-only.
