### ISSUE TITLE
Necromantic Aegis Minion Block Chance

### ISSUE THREAD

**Issue by Lothrik** [Openarl/PathOfBuilding#419]
If Necromantic Aegis is enabled and you have a shield equipped, your minions still show 0% block chance under Calcs. Their block chance should (at a minimum) be equal to the block chance on the shield.

**Comment by Openarl** [comment]
This was an unforeseen side-effect of the changes to support Animate Guardian, since Animated Guardians can equip two shields at once. It will be fixed in the next update, as usual.
