### ISSUE TITLE
[Enhancement] Sort eligible support gems to top of list

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#420]
Most of the time when selecting a gem in the support dropdown, only a small selection of the full list of gems can actually support the active skill gem linked to it. It would be nice if these gems were sorted to the top of the list so the user doesn't have to scroll past tons of options that irrelevant in most cases.

**Comment by ltwiz** [comment]
a primary sort of colour and secondary sort of Total DPS (or user-defined sorting?) would be ideal. I was using the arrow keys to scroll through the (entire) list just yesterday to do just this.

**Comment by holwynn** [comment]
> A primary sort of colour and secondary sort of Total DPS (or user-defined sorting?) would be ideal. I was using the arrow keys to scroll through the (entire) list just yesterday to do just this.

So much this. I often want my 6th link to be just the most possible DPS increase, so this kind of sorting would be ideal.

**Comment by aggixx** [comment]
There are more ways to refine the sorting, total DPS is one way, but I think there might be some programming complications with that (I don't think PoB calculates that info if the skill in question isn't active?) so I figured I would start with much more simple suggestion that provides the biggest benefit.

But yes I agree, sorting by total DPS would be great as well. Even if the highest DPS option is not always the one you want to choose, most often it will be in the top 15 (which is how many the dropdown shows at a time).

**Comment by Openarl** [comment]
I suspect there'll be happier times ahead for all of you; I'm pretty much done with QoL improvements for the Items tab, so my attention will now be on the Skills tab...

**Comment by Openarl** [comment]
As of the next update, compatible support gems will be sorted to the top of the gem list, and gems will be sorted by DPS by default (this can be disabled on a per-build basis).
