### ISSUE TITLE
[Bug] Flasks in a new Item set do not grant their effects despite being checked

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#424]
When I select a flask in the flask dropdown in a new item set, the checkbox next to the flask defaults to checked but the flask does not grant any effects. Mousing over the flask shows the "Activating this flask will give you:" text that you would expect to see only when the flask is inactive. Unchecking and then rechecking the flask produces correct behavior from that point on.

How to replicate:

1. In "Items" click "Manage..."
2. Click "New", enter a name
3. Double click the new item set to activate it, click "Done". At this point, items look like this:
![image](https://user-images.githubusercontent.com/510805/27609777-95fb34a4-5b51-11e7-992d-0ef38603353a.png)

4. Select a flask in the flask dropdown, it then looks like this:
![image](https://user-images.githubusercontent.com/510805/27609805-b1d951ba-5b51-11e7-83a9-d53d63ea93cb.png)

The DPS has not gone up, and mousing over the flask looks like this:
![image](https://user-images.githubusercontent.com/510805/27609828-c7b2d33a-5b51-11e7-9f99-4f95bcd47b73.png)

**Comment by Openarl** [comment]
Fixed in the next update; the "activate" checkbox wasn't updating correctly when switching item sets.
