### ISSUE TITLE
Flasks not saving properly

### ISSUE THREAD

**Issue by JYshadow** [Openarl/PathOfBuilding#425]
When I disable my flasks and save it, it will show that I have my flasks enabled when I re-open it, even though I don't have them enabled.
A gif might explain the problem better:
https://gfycat.com/AngryMeagerBeauceron
I also have a build where it the other way around: the flasks are enabled, but it doesn't show on the calculation. It only applies it when I re-enable them. But when I save it and re-open, it doesn't show the flask are applied on the calculation again. I've tried to find the source of the issue, but I couldn't figure it out. It happens on 3.0 and 2.6 builds, on every one of them (new or few months old). 

Here's the build you see in the gif: https://pastebin.com/5AUCp4fq

**Comment by Openarl** [comment]
The update that I just released fixes this issue, amongst others.
