### ISSUE TITLE
[Bug] Essence Drain DoT(s) not calculating correctly

### ISSUE THREAD

**Issue by MrD3xter** [Openarl/PathOfBuilding#429]
From the Essence Drain wiki page:
"Damage over time: Modifiers to spell, projectile, chaos damage, and damage over time affect the damage over time component of this spell. Modifiers to Spell Damage apply to this skill's Damage Over Time modifier also affects other damage over time effects created by this skill, such as poison or ignite."

The issue has two facets, as far as I can tell.
1) Projectile damage does not affect the built-in DoT of Essence Drain nor any additional DoT effects, like poison or decay. Currently it only affects the initial hit damage.
2) Spell damage does affect the built-in DoT and the initial hit of Essence Drain as expected, but does not affect any additional DoT effects, like poison or decay.

I'm not sure if there are any cases other than Essence Drain where these interactions are not present.

**Comment by Openarl** [comment]
Just to get the obvious out the way, are you sure you're not on a 3.0 build? Because all of those behaviours are 100% intended in 3.0.

**Comment by MrD3xter** [comment]
My bad then, I wasn't aware that they changed essence drain in the beta. I'll close the issue.
