### ISSUE TITLE
[Feature Request] More Sort-Options for the build list

### ISSUE THREAD

**Issue by DanielGrobelny** [Openarl/PathOfBuilding#43]
Hey there!

Here's one for the long term to-do list if it's not on there already:
Make the initial build-list sortable by
- Name
- Class / Ascendancy
- Last edited

Especially "Last edited" would be super handy! ;)
Thank you again for your hard work!

**Comment by Openarl** [comment]
Hmm. This shouldn't be too difficult. I'm currently working on a few other features for the next update, but I'll see if I can get this in too.

**Comment by Openarl** [comment]
It'll be in the next update,

This turned out to be a little trickier than I'd thought, as the Lua code didn't have access to the "last modified" time of the build files. The update will contain a new runtime version to correct this.
