### ISSUE TITLE
path of building don't ignore equipaments that you cannot use

### ISSUE THREAD

**Issue by leoperes123** [Openarl/PathOfBuilding#430]
\/

**Comment by Openarl** [comment]
Could you give me your build? I can't seem to find any problems with that skill.

**Comment by leoperes123** [comment]
nvm .... the path of build don't ignore equipaments that you cannot use .. so the weapon i'm using it's include even if i don't have enough int to use.. this cause my path of build to not load the damage of ancestral warchief.. i'm using facebreaker

**Comment by Openarl** [comment]
There's a very good reason for that. When planning a build, attribute requirements is something that you generally sort out towards the end; so requiring the user to fulfil them even in the earliest stages is counter-productive, and would be horrible to work with.

Of course I could add the option to enable enforcement of requirements; it's not something I'm currently planning to do, but I will at least consider it.

**Comment by leoperes123** [comment]
don't worry :D.. but thx for the answer :D
