### ISSUE TITLE
[Bug] Physical Projectile Attack Damage Support incorrectly reduces the APS of melee projectile skills

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#437]
In PoB, if you support Frost Blades, Molten Strike, or Lightning Strike with Physical Projectile Attack Damage the APS of the attack is penalized only when viewing the projectile portion of the attack. This is incorrect, as fundamentally a skill can only attack at 1 rate, and I've verified that in-game if you support Frost Blades with PPAD the APS of the attack is not reduced.

Without PPAD:
![image](https://user-images.githubusercontent.com/510805/27806420-1b5c9ac2-6000-11e7-8257-b18a6d28c5de.png)

With PPAD:
![image](https://user-images.githubusercontent.com/510805/27806424-2323c226-6000-11e7-993f-f87dd98b9143.png)

**Comment by Openarl** [comment]
Duplicates #241.
