### ISSUE TITLE
New item crafting UI really confusing me.

### ISSUE THREAD

**Issue by krab** [Openarl/PathOfBuilding#441]
Here screenshot http://i.imgur.com/moMrvSA.png IMO it needs numbers like "T1 T2 T3" before mod name like: 

```
T1 Rapturous [+(110-119) to maximum Life"
T2 Vigorous [+(100-109) to maximum Life"
T3 Fecund [+(90-99) to maximum Life" ...
T1 Zaffre [+(59-73) to maximum Mana]
T2 Blue [+(65-68) to maximum Mana]
T3 Mazarine [+(60-64) to maximum Mana] ...
```
Or separate them somehow, don't know if it possible in UI framework you using.

Atm list looks like "messed up" when you first time open.

**Comment by krab** [comment]
It even worse if you open hybrid EV/ES gear: http://i.imgur.com/p0j86MG.png

**Comment by Openarl** [comment]
There will be some improvements coming for the item crafting system; now that it is becoming the dominant way of creating rare items, I'm looking to streamline it as much as possible.

**Comment by Openarl** [comment]
The latest update (1.4.44) brings some significant improvements to the crafting UI, which should address these concerns.
