### ISSUE TITLE
Adding +3 lightning bow increases Animate Weapon tooltip.

### ISSUE THREAD

**Issue by krab** [Openarl/PathOfBuilding#442]
Here elemental animate weapon build. https://pastebin.com/G7xJyqLw

Auras socketed into Victario's Charity. Try to remove/add bow from main hand and check tooltip. AW gem setup socketed into "None".

**Comment by Openarl** [comment]
You haven't set up an item set for Animate Weapon to use, so it's using the default item set with the +3 bow. 

You need to create a new item set in the Items tab (click "Manage" at the top, above the item slots), equip a weapon of some sort (you can use the "Craft Item..." option to create a white weapon), then select the new item set from the dropdown in the sidebar.

The result should be [something like this](https://pastebin.com/ZPsdW24H).
