### ISSUE TITLE
Brutality Support also causes supported ability to deal no chaos damage

### ISSUE THREAD

**Issue by RhymesWithEight** [Openarl/PathOfBuilding#443]
When supporting a skill with Brutality Support in a 3.0 build, chaos damage is removed with elemental. This problem is not present while using Starforge, even though they have a similar effect. Unless the gem has changed in the beta since it's been announced, this should not be the case.

**Comment by Openarl** [comment]
It has changed.
![brut](https://user-images.githubusercontent.com/19189971/27984120-8eb0fbd0-6410-11e7-8569-1144f28d7af6.png)

**Comment by RhymesWithEight** [comment]
Thanks, sorry for the confusion!
