### ISSUE TITLE
[Bug] Application crash after using any textbox

### ISSUE THREAD

**Issue by nskleckner** [Openarl/PathOfBuilding#448]
Any time I type characters into a text box (i.e. any of the search bars, the box for skill and character levels, etc) the application crashes with a "Path of Building.exe has stopped working" error message from Windows 10. This hasn't happened in the past, I believe it only started after I updated to a new version of Path of Building.

**Comment by Openarl** [comment]
That's definitely an odd one. There's no other reports of it, and I can't think of any recent changes that could account for it anyway; are you sure nothing else changed in your system, other than the update of the program?

**Comment by nskleckner** [comment]
I think this issue was related to drivers for my keyboard. Was happening with other applications as well.
