### ISSUE TITLE
[Feature Request] Ask user before closing application about saving build

### ISSUE THREAD

**Issue by krab** [Openarl/PathOfBuilding#45]
Closed without saving 2 times in a row, lost all changes.

**Comment by Openarl** [comment]
Known issue. It'll require a bit of technical tinkering to allow this to happen, due to the program's design. I'll see if I spare some time to work on this today.

**Comment by Openarl** [comment]
This will be in the next update.

It was a bit of a pain to implement. The query for "can the program exit yet?" that is now performed when you click the close button, has to pass through half a dozen different modules before it gets to the code that checks for unsaved changes. As I said, technical tinkering!
