### ISSUE TITLE
Penetration isn't working on fight for survival

### ISSUE THREAD

**Issue by boyangfu** [Openarl/PathOfBuilding#451]

**Comment by JYshadow** [comment]
Check if you have selected the 'melee hit' portion of the skill on the left sidebar, because Fight for Survival's Cold Penetration only applies to the melee part of Frost Blades.

**Comment by Openarl** [comment]
There is a typo present in the current version of the program that prevents that part of the jewel from being correctly recognised, but that's already fixed for the next version.
