### ISSUE TITLE
Scaeva bonus crit chance isn't working

### ISSUE THREAD

**Issue by boyangfu** [Openarl/PathOfBuilding#452]

**Comment by JYshadow** [comment]
Coincidentally I've been messing with the item too, but it works fine for me. Are you sure you have it equipped in your main hand? Or perhaps using the wrong weapon set?

**Comment by Openarl** [comment]
I can't find any problems with it either. I should note that the "increased Critical Strike Chance when in Main Hand" is global, so it doesn't alter the crit chance listed in the tooltip.

**Comment by boyangfu** [comment]
Sorry, now that I checked again - it is indeed working
