### ISSUE TITLE
temptuous steel hits can't be evaded isn't working when dual wielding and only attacking with mainhand (diff weapon)

### ISSUE THREAD

**Issue by boyangfu** [Openarl/PathOfBuilding#453]

**Comment by JYshadow** [comment]
The 'Hits can't be Evaded' from that weapon is Local, which means only attacks with The Temptuous Steel cannot be evaded, while attacks from your other weapon can still be evaded.

**Comment by Openarl** [comment]
JYshadow is correct; "Hits can't be Evaded" is always local.

**Comment by boyangfu** [comment]
Didn't know this, my bad
