### ISSUE TITLE
Jewel location picture is blocking the stats

### ISSUE THREAD

**Issue by JYshadow** [Openarl/PathOfBuilding#455]
![image](https://user-images.githubusercontent.com/25852794/28240009-3973cca6-6979-11e7-999e-1e0d8b7a2eb4.png)
I feel like this is a bit inconvenient.

**Comment by Openarl** [comment]
Hmm. It's supposed to be the other way around (tooltip covers the node location), but it seems one of the changes I made to tooltip handling in 1.4.44 had a side effect of changing that. It's fixed in the next update.
