### ISSUE TITLE
[Bug/Enhancement] Vaal double strike does not count as a totem

### ISSUE THREAD

**Issue by FruitcakeElemental** [Openarl/PathOfBuilding#457]
According to the poe wiki the [Vaal Double Strike](http://pathofexile.gamepedia.com/Vaal_Double_Strike) clone should be a totem and in theory would benefit from both character bonuses and penalties but also anything that effected a totem.

**Comment by Openarl** [comment]
The clone is conceptually similar to a Totem, but as far as I'm aware it isn't considered a Totem for mechanical purposes, and so totem modifiers wouldn't apply. Unless I get direct confirmation to the contrary, the program's behaviour will remain as it is.
