### ISSUE TITLE
[Bug] Main Skill Switch

### ISSUE THREAD

**Issue by yaaver2468** [Openarl/PathOfBuilding#458]
This was a bit of an odd and annoying find. Reproducible, probably not meant as a feature.
So, here's how this goes. You make a new character, any character, 2.6 or 3.0, put items in, don't put items in, doesn't matter, tree or no tree either. The real problem is that when you put your main skills in and try to view the main skill at the bottom, hovering over enabled and disabled will switch it to the main skill listed in the drop down of skills above it.
Example:
4 link > CwDT, Flame Golem, Arctic Breath, Immortal Call
(Input in that order of 1-4)
From the left side of main skills, select IC, and then on the right side with your skills tab active, hover over any of the checkboxes to enable/disable the skill, and it will jump up from IC to Arctic Breath. If you have any of the other main skills selected, nothing happens at all. It will always jump up to the one above if you've got the main skill selected on the left side is the last link. Change IC to any other active/main skill, it will always go to Arctic Breath or whichever skill was linked before the last. Number of links don't matter either, 2-3-4-5-6, it'll always jump to the one above.
Meaning if I add in Flame Dash after IC as the 5th link, when hovering over the buttons it will put me up to IC while Flame Dash was active on the left side. Guessing this could be some looping error but a very specific "if last skill" kinda case. Can provide video demonstration if explanation didn't make sense.

**Comment by Openarl** [comment]
Fixed in the next update. The main skill selection code in the Calcs module was validating the main skill index (which it is supposed to), but then changing the stored main skill index (which isn't supposed to happen during the special calculation pass performed when hovering over that checkbox).
