### ISSUE TITLE
[Feature Request] More Weapon types

### ISSUE THREAD

**Issue by Akhatalamablu** [Openarl/PathOfBuilding#46]
Can we get more top tier weapon types like Foils and Ambushers?

**Comment by krab** [comment]
👍 also we have only one quiver base "Spike-Point Arrow Quiver".

**Comment by Openarl** [comment]
If you can give me some specific base types that you think are useful, I can add them.

Incidentally, the next update adds a simple item editor that allows you to change literally anything about a given item, so you'll be able to change a template-derived item's base type yourself if needed.

**Comment by Akhatalamablu** [comment]
As the BF meta stands,
1. [Vaal Rapier](http://pathofexile.gamepedia.com/Vaal_Rapier)
2. [Harpy Rapier](http://pathofexile.gamepedia.com/Harpy_Rapier)
3. [Jewelled Foil](http://pathofexile.gamepedia.com/Jewelled_Foil)
4. [Ambusher](http://pathofexile.gamepedia.com/Ambusher)

You might want to post your next update on reddit or something, i don't know the usage numbers but it feels like this is too good a tool to fly under the radar. And it'd be perfect for the pre league build/gear planning hype.

**Comment by Openarl** [comment]
I'll change the attack daggers to the Ambusher base, and add Jewelled Foil templates. I dislike having multiples of the same weapon type though, since there isn't a huge difference in the stats.

**Comment by Akhatalamablu** [comment]
Jewelled foils are probably going to be the meta anyhow. Thanks for accommodating this request and thank you for all the good work so far!
