### ISSUE TITLE
Stale DPS calculation state with 2 instances open

### ISSUE THREAD

**Issue by tgavankar** [Openarl/PathOfBuilding#464]
First question:
Does PoB officially support having multiple instances open simultaneously?

If so, then I believe there may be some sort of latent bug where DPS calculations from one client are "leaking" into the other. Unfortunately, I don't have exact steps to reproduce yet, but I believe I created a build with high DPS (manually inputting Signalshot). I then opened a second instance of PoB and loaded an existing (similarly bow/barrage) build. The DPS calculations were similar, but different enough to make me believe that the loaded build was being calculated correctly. I then exported my custom build via pastebin sharing and loaded it on a different machine, and the DPS numbers were completely different (i.e. much lower, and most likely correct now on reload). I unfortunately closed the window with my original incorrect calculations and reopening on the first machine didn't reproduce the bug, but based on what I remember from the calc page, the damage discrepancy was due to skill tree points (Signalshot is mostly damage nodes while my build is mostly defense nodes).

If PoB is meant to work correctly with two instances running (and there isn't some weird saved), I can try more to get exact steps to reproduce the bug. If it's not, then I'll just not bother and never use two instances simultaneously.

**Comment by Openarl** [comment]
The program shouldn't have any issues running multiple instances; so long as you don't open the same build in both, there's no way they could interfere with each other, as they are entirely separate processes. So I'm not really sure what happened in your case, but you should try and reproduce it if you can.

**Comment by tgavankar** [comment]
I'm still trying to reproduce this. If I'm not able to in a reasonable amount of time, I'll just mark this as closed/not reproduceable.

**Comment by tgavankar** [comment]
I can't reproduce this.
