### ISSUE TITLE
[QoL Feature Suggestion] Show MoM threshold alongside Life/Mana Stats

### ISSUE THREAD

**Issue by LyskOnGithub** [Openarl/PathOfBuilding#465]
In the Stats Summary Box on the left, alongside the Life and Mana Paragraphs, if any % of damage is taken from Mana instead of Life (currently 30% with MoM alone and additional 10% with 3.0's Cloak of Defiance), Show the calculatedeffictive EHP values. 

---

**Example:**

Total Life: 5509
%inc Life from Tree: 166%
Life Regen: 35.9
_Effective Life with damage taken from Mana: 7161.7_

Total Mana: 3580
%inc Mana from Tree: 124%
Unreserved Mana: 1861.6
Unreserved Mana: 52%
Mana Regen: 84.0
_Damage taken from Mana before Life: 30%
Damage Threshold: 1652.7_ 

---

If Damage Threshold is greater than Unreserved Mana, add Unreserved Mana to Life for EHP instead of Damage Threshold

**Comment by Openarl** [comment]
This information is already displayed in the Calcs tab, in the Damage Taken section; you'll find the EHP calculations in the breakdown for Mind over Matter. I'd prefer to not add those to the sidebar, as there's already too many stats there.

**Comment by LyskOnGithub** [comment]
Thanks!
I missed that.
