### ISSUE TITLE
[Bug] "Thousand Ribbons" Wrong mods

### ISSUE THREAD

**Issue by LyskOnGithub** [Openarl/PathOfBuilding#466]
I just stumbled upon this by accident.

The Item "Thousand Ribbons" grants elemental damage to attacks only accoding to the wiki, not spells and attacks.

**Comment by Openarl** [comment]
Presumably you're in a 3.0 build, or looking at the 3.0 variant of that item; those modifiers have been changed in beta to apply to both spells and attacks.
