### ISSUE TITLE
[Bug] DPS Gain not being calculated properly

### ISSUE THREAD

**Issue by myrahz** [Openarl/PathOfBuilding#469]
Hello, I was testing out the new DPS Gem feature and I came up with this bug.

PoB Says that at this state:

![image](https://user-images.githubusercontent.com/13249929/28640569-034a5734-7244-11e7-83c7-4d3b025ab5e0.png)

Additional Accuracy is the best gem
Empower is the second best gem
Multistrike is the third best gem

Yet whenever I mouse hover these 3 gems it says:

![image](https://user-images.githubusercontent.com/13249929/28640128-a58d92c4-7242-11e7-87a6-a340be3c0d8f.png)
![image](https://user-images.githubusercontent.com/13249929/28640268-136dd22c-7243-11e7-9956-cdaed5ca3992.png)
![image](https://user-images.githubusercontent.com/13249929/28640282-1c2509a8-7243-11e7-88dc-bd595ab16354.png)

So it says that:
Empower is the best gem,
Multistrike is the second best,
Additional Accuracy is the third best.

Yet whenever I equip them the best order is the same as reported by the new feature:

![image](https://user-images.githubusercontent.com/13249929/28640381-6ba43b20-7243-11e7-8133-00a89d52596f.png)
![image](https://user-images.githubusercontent.com/13249929/28640388-71bc1d20-7243-11e7-8941-d11396dee417.png)
![image](https://user-images.githubusercontent.com/13249929/28640457-a3571592-7243-11e7-82d2-8e37956d7c33.png)

**Comment by Openarl** [comment]
This should be fixed in the next update; the comparison tooltip wasn't using the default gem level/quality specified in the Skills tab, but rather the old defaults of 20/0.
