### ISSUE TITLE
[Feature Request] Item Cabinet

### ISSUE THREAD

**Issue by Akhatalamablu** [Openarl/PathOfBuilding#47]
Would it be plausible to have an item stash/cabinet that you can share between builds? That way we don't have to recreate the same items each time we want to plan a build.

**Comment by DanielGrobelny** [comment]
+1

**Comment by Openarl** [comment]
It is something I'd like to add at some point, but there's a bit of work involved.

Until then, it's possible to copy and paste items between builds. Previously this didn't work properly for template-derived items (it would reset the modifiers), but the next update will fix that.

**Comment by Openarl** [comment]
This is finally coming in the next update. With the more critical features (minions etc) implemented, I'll have more time to work on QoL improvements like this, so there'll be plenty more to come!
