### ISSUE TITLE
Soul Raker life leech number doesn't work

### ISSUE THREAD

**Issue by mintjustin** [Openarl/PathOfBuilding#470]
The "Soul Raker" node only updates mana leech number and not life leech number. Is this a bug or am i missing something about this node?

**Comment by Openarl** [comment]
I suspect you're at the life leech cap, as there's no technical reason why the life leech wouldn't work. To check, go to the Calcs tab, select your main skill, then look at the Leech & Gain on Hit section.

**Comment by mintjustin** [comment]
Yes you are correct. It seems that I hit the life leech cap.
Thanks.
