### ISSUE TITLE
[Bug] Frost Blades projectile scaling with Ruthless support

### ISSUE THREAD

**Issue by sapper123** [Openarl/PathOfBuilding#474]
The Icy blades projectile damage portion of Frost Blades seems to be scaling with the Ruthless Support gem, even though Ruthless Support is tagged as "Melee, Attack" according to PoEDB data mined info. Contrast this to the Melee Physical Support gem which has the same tags as Ruthless Support but only scales the melee hit damage and not the projectile damage.

I'm using version 1.4.50 and game version 3.0.

Good job with PoB btw!

**Comment by Openarl** [comment]
The tags are 100% irrelevant in cases like this; they are merely suggestive of the gem's mechanics. But the Ruthless Blow damage modifier's description does specifically state Melee Damage, so I will change this in the next update.

**Comment by sapper123** [comment]
> The tags are 100% irrelevant in cases like this

Thanks for bringing that to my attention.
