### ISSUE TITLE
Carnage Heat life leech cap calculations

### ISSUE THREAD

**Issue by Nagapito** [Openarl/PathOfBuilding#475]
Hi, I might be reading this unique amulet wrong but, shouldnt the 50% inscreased life leech per second increase the life leech cap?  
  
Currently this seems to be ignored.

**Comment by Openarl** [comment]
Leech rate modifiers (X% increased Y Leeched per second) modify the rate at which each individual leech instance heals you, but they have no effect on the leech rate caps, which are increased by modifiers of the form "+X% of maximum Y per second to maximum Y Leech rate".
