### ISSUE TITLE
[Feature Request Kinda] Dark Pact Support

### ISSUE THREAD

**Issue by myrahz** [Openarl/PathOfBuilding#480]
Hey there, I've seen you recently added Dark Pact Support. Yesterday I manually added Dark Pact to my PoB  considering people would self cast it without skeletons, I wasn't able to get it working for all levels so I just ghettoed it with a lvl 20 gem and used the setup function on Vaal Righteous Fire to add 3% of life to the bottom end of its damage and 3% to the top end as the skill sacrifices 6% life to add extra damage along with the 152% more multiplier.

I was wondering if it was possible to add that, both the 152% multiplier and the 6% life added as chaos damage to the spell.

From the datamined values it says that the skill has a mana cost yet the skill showcase shows there is none, I also assume that it will have, based on the datamine, what do you think?

**Comment by myrahz** [comment]
Here's my snippet.

https://pastebin.com/aWM4TUS9

**Comment by Openarl** [comment]
The current support for Dark Pact is only preliminary, and support for the health scaling hasn't been added yet. It should be along in the next update or two, once I can sort out the technical issues with it.

**Comment by Openarl** [comment]
Support for the Life scaling has now been added.
