### ISSUE TITLE
[Feature Request] Include left panel totals in export XML

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#484]
I had an idea to write a reddit bot that would decode PoB import codes people posted in comments and then reply with a summary of the build, so I decoded an import string and found that (somewhat unsurprisingly) the stats that are usually of interest (DPS, life, es, etc) are not included in the import string; you'd have to calculate all that independently which is way outside the scope of what I want to do. Would it be possible to include all of the information in the left panel (just for the active skill would do, I think) in the import string?

**Comment by Openarl** [comment]
Ok, so I took a look at this, and:
1. It is damn easy to do
2. It doesn't increase the size of the XML file by much (about 3kB for a typical build)
3. There's a bit of demand for this, as a few others have asked for something similar

So you'll see it coming in the next update. As an advanced notice, I'm dumping every stat that's used in the sidebar into children of the Build section, [like this](https://gist.github.com/Openarl/e6e934a955592030556250f02c22cd8a).

**Comment by aggixx** [comment]
That's awesome, thanks adding it.

**Comment by aggixx** [comment]
Finished working on the bot, well as much as I can before I can see what it would do in the real environment. Once the update rolls out you should be seeing it on reddit pretty soon!
