### ISSUE TITLE
Bleed Configuration Flag

### ISSUE THREAD

**Issue by Saimeidae** [Openarl/PathOfBuilding#485]
As of right now, there is no configuration flag for Bleeding enemies, as it would be used for the Bloodlust support gem.

If this is incorrect and there is a way to properly calculate DPS from Bloodlust support I'd love to know how.

EDIT: Failed to consider if this were to be a feature or a bug. Whoops.

**Comment by dein0s** [comment]
It appears in Config tab only if you have any source that can inflict bleeding.
You can check this by taking/untaking gladiator's `Gratuitous Biolence` ascendancy node for example.
![node](http://i.imgur.com/S7W1C6G.png) ![tab](http://i.imgur.com/4oa0FNl.png)

**Comment by Saimeidae** [comment]
Ok, so it's then just not detecting Ancestral Protector Totem + Chance to Bleed as a viable method to cause bleed/Atziri's Disfavor.

**Comment by Lothrik** [comment]
"Ok, so it's then just not detecting Ancestral Protector Totem + Chance to Bleed as a viable method to cause bleed/Atziri's Disfavor."

It does, you just have to actually select the totem as your Main Skill before it will show up under Config.

**Comment by dein0s** [comment]
Well, looks like I was wrong about it also.
It seems that condition depends on "against bleeding enemies" mods regarding to this code:
`["against bleeding enemies"] = { tag = { type = "EnemyCondition", var = "Bleeding" }, flags = ModFlag.Hit },`
And according to my current investigation, `Bloodlust gem` has some issues with this mod.

**Comment by Openarl** [comment]
That option does already exist, but as with most options in the Configuration tab it isn't displayed unless it there's some modifier somewhere in your build that depends on it, so you need to actually have Bloodlust in your main skill and enabled for the option to appear; having a source of bleed makes no difference.

**Comment by dein0s** [comment]
@Openarl well, looks like either there's a bug with `Is the enemy Bleeding`/`Bloodlust gem` in Configuration tab or we don't understand smth correct.

Here's a simple profile with 3 skill groups: https://pastebin.com/braMVjZr
I've tried all of them as the main skill, but couldn't get `Is the enemy Bleeding` config tab.

Can you give a hint?
