### ISSUE TITLE
Elementalist Conflux Persists Forever

### ISSUE THREAD

**Issue by Lothrik** [Openarl/PathOfBuilding#486]
If you enable any conflux buff from Elementalist (Shaper of Desolation) and then later spec out of Shaper of Desolation, the conflux effect persists and cannot be toggled off.

This is extremely confusing as my chance to shock was stuck at 100% and all the calcs page said was "Condition: Combat, Source: Config" despite everything under Config being disabled.

I only figured out where the 100% chance to shock was coming from by digging around in the .xml file and finding:
`<Input name="buffConflux" string="ALL"/>`

**Comment by Openarl** [comment]
Fixed in the next update.
