### ISSUE TITLE
Error when displaying radius values higher than 92

### ISSUE THREAD

**Issue by MatthewClair** [Openarl/PathOfBuilding#488]
Repro:
1) Create a new 3.0 build
2) Select all aura radius nodes on tree.
3) Add Anger supported by Generosity
4) Set Anger to Q20, Generosity to Q18+
5) View Anger radius in Calcs tab
6) [Get this error](http://i.imgur.com/kZDv43y.png)

**Comment by Openarl** [comment]
Fixed in the next update.
