### ISSUE TITLE
Inquisitor "Instruments of Virtue" calculation bug

### ISSUE THREAD

**Issue by Bobblybook** [Openarl/PathOfBuilding#490]
The bonus attack/cast speed "if you've attacked recently" seems to be getting applied to my build by default. The tooltip in PoB says this will occur if my main skill is an attack (which it is), however my main skill (KB in this case) is on a ranged attack totem.

According to my googling, Instruments of Virtue will NOT grant you the bonuses unless you attack directly (eg. not via totem). I have tried toggling on and off "Have you attacked recently?" in the calcs sheet, and there is no difference in stats at all, which leads me to believe that PoB is incorrectly granting me the bonuses because it sees KB, and is not taking into account that it's linked to a totem.

Either the automatic calcs need to be fixed (check for totem link before adding bonus stats?), or give an option to force the bonus off. At the moment there is only unchecked (automatic) or checked (force-on).

If I am somehow misunderstanding how the mechanic works and I am wrong, please let me know. Thanks!

**Comment by Openarl** [comment]
You are correct; that condition shouldn't be activating automatically for non self-cast builds; I'll fix that in the next update.
