### ISSUE TITLE
PoB doesn't calculate double hit chance for crit

### ISSUE THREAD

**Issue by BioKalandra** [Openarl/PathOfBuilding#491]
I tried to calculate some attack builds and i realized that the program doesn't square the hit chance for crit. According to Mark from GGG there is another hit chance roll to confirm your crit. 

> Accuracy measures the chance for an attack to hit. Accuracy-dependent attacks make a second accuracy check to confirm the critical strike. If the check fails only a normal hit is dealt. Thus accuracy can play an important role in quantity of critical strikes.

Source: [https://pathofexile.gamepedia.com/Critical_strike#Accuracy](url)
GGG: [https://www.pathofexile.com/forum/view-thread/11707/filter-account-type/staff/page/10#p748465](url)

So if I do have a 50% crit and 50% hit chance, it's supposed to be calculated 0.5^2* 50% crit = 12.5% effective crit. PoB just calculates Hit*Crit.

**Comment by Openarl** [comment]
The program does account for the second accuracy check, but the Crit Chance shown by the program isn't the chance for any given attack to crit, but rather the chance that any given attack that hits to be a critical strike, so it doesn't need to factor in the first check, as the hit is assumed.
