### ISSUE TITLE
"Enabling this gem" tooltip incorrectly cached for inactive skills

### ISSUE THREAD

**Issue by tgavankar** [Openarl/PathOfBuilding#496]
v.1.4.52

STR:
1. Open PoB and import https://pastebin.com/cdWx8gk3
2. In Skills tab, go to first "No active skills" group.
3. Hover over Herald of Thunder "Enabled" check box. Note that it shows (+8.1%) for Total DPS. Do not enable the checkbox.
4. Go to second "No active skills" group.
5. Hover over Wrath "Enabled" check box. 

Expected:
Wrath has correct Expected tooltip.

Actual:
Tooltip shows the same tooltip as Herald of Thunder (shows (+8.1%) for Total DPS). Another confirmation that this is the incorrect tooltip is that it shows 25% mana reserved (same as Herald of Thunder), whereas Wrath actually reserves 50%.

If you check and uncheck the Wrath enable checkbox, the tooltip updates and is corrected.

**Comment by Openarl** [comment]
Thanks for the detailed report! It is fixed in the next update.
