### ISSUE TITLE
Error message on a rf totem build

### ISSUE THREAD

**Issue by RatDonkeyGoat** [Openarl/PathOfBuilding#497]
![desktop 08 03 2017 - 01 25 33 01](https://user-images.githubusercontent.com/30687395/28912913-ff3f0d5e-77ea-11e7-8582-9ecf504325ec.png)

**Comment by Openarl** [comment]
Whoops, sorry about that; check for update in a minute and you should get the fix.

**Comment by RatDonkeyGoat** [comment]
thanks for the quick fix <3
