### ISSUE TITLE
Dev mode crash bug in PassiveTree.lua

### ISSUE THREAD

**Issue by philroberts** [Openarl/PathOfBuilding#498]
As drawn to my attention by ccomly in the 'other platforms' issue, if you don't have a TreeData dir, the code in PassiveTree.lua will create one, but doesn't create the 2_6 and 3_0 subdirs, leading to a crash on line 61.

**Comment by Openarl** [comment]
Well, the code that builds the TreeData folder is fundamentally incapable of building it from scratch now there's multiple tree versions (as only the live version is available), so even if I fixed this issue, it wouldn't solve the problem entirely. If it is being run from the repo there is the tree.zip though; but adding code to look for and extract that seems a bit pointless when you can just copy the TreeData from a normal installation.
