### ISSUE TITLE
[Feature Request] Auto add all gem names from skill chain to it's label on 'Skills' tab

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#5]
Just a QoL improvement.  
So you don't have to click on skill chain in list just to watch what gems are inside and/or manually copy-paste them.
Smth like this: 'Frenzy - FA - CoH - Vuln'

**Comment by Openarl** [comment]
If you're not already aware, you can customize the label that is displayed in the skills list.
The full list of gems also shows when you mouse over a skill.
Presently the label defaults to the name of the first skill gem; adding abbreviations for all gems might be worth it but I'd need to make some sort of canonical abbreviation for each skill gem (consider Added Cold Damage vs Added Chaos Damage).

**Comment by dein0s** [comment]
Yeah, I'm aware of this customization.
I meant, that you can by default add names of all gems in order they are listed instead just of first gem.
And for now you can do it exactly with names that were written by user (so if my input was 'Added Chaos' and program already matched it to the right gem in base - keep it as is).

In any way that's not an urgent/must have feature and I can truly leave w/o it. It's all up to you. Just a little QoL that came up to my mind while I'm digging around (you can blame my qa specialization and exploration nature :D).

**Comment by dein0s** [comment]
And while I'm still here (just making a note, can create an issue for this later, gtg soon) - is it possible to list ALL active/support gems on mouse over, even if they are "ignored" or "unsupported"? Just with some grey background or mb that red icon (crossed circle)?

**Comment by Openarl** [comment]
Regarding the skill labeling, I'll consider it. In case of 5/6link setups the label could end up being too long though.
As for the second request, I might be able to do that; however the list that you see on mouseover is the output from the skill gem processing inside the calculations code, and that process strips out unsupported/ignored gems; so I'd need to add a way for it to pass those gems back to the skills tab. I won't have time to do that tonight (I'm in Australia and it's 1AM); maybe tomorrow if I can get the time.

Thanks for the feedback!

**Comment by Openarl** [comment]
Fair point.
