### ISSUE TITLE
Nodes becoming dark when loading a build

### ISSUE THREAD

**Issue by SaylorAldurren** [Openarl/PathOfBuilding#500]
Hi,

http://imgur.com/a/0DgKd

I have this issue everytime I try to load the tree. Any idea how to solve it?
 Here is the build shown previously : https://pastebin.com/cHcUpeqT

I tried while loading my own generated builds, but I don't have any bugs with these builds.

Thank you.

**Comment by Openarl** [comment]
You have "Show Node Power" enabled (the checkbox next to the tree search field).
