### ISSUE TITLE
Lioneye's Fall Ailment Damage Conversion

### ISSUE THREAD

**Issue by Tyrannical** [Openarl/PathOfBuilding#501]
Lioneye's Fall jewel does not appear to apply its conversion change to the new ailment damage increases. 

It works for the other portions of the damage nodes but not the ailment damage increase nodes.
Screenshot of DPS changes with one damage node: http://i.imgur.com/aqXnMHw.png
Bleed Damage Increase without that node: 660%
Bleed Damage Increase with that node: 660%

I have tested it with multiple other nodes and that have melee weapon type modifiers and no change.

Here is a pastebin of my build if that helps as well. https://pastebin.com/hb9e2a3j

**Comment by Openarl** [comment]
Fixed in the next update. I really, really hate that jewel! :(
