### ISSUE TITLE
Freeze also count as chilled

### ISSUE THREAD

**Issue by mikeboy91** [Openarl/PathOfBuilding#503]
According to the [Chill mechanics in the Wiki](https://pathofexile.gamepedia.com/Chill#Mechanics), a Freeze is also a Chill.
This seems not the case in PoB. Noticed it by adding Hypothermia. The damage goes up when i check 'Target is chilled' in the config tab but if i unselect it and select 'Target is frozen', Hypothermia does not have any effect.

**Comment by Openarl** [comment]
Ah, I wasn't aware of that. I'll fix that in the next update.
