### ISSUE TITLE
Faster Burn not calculated correctly

### ISSUE THREAD

**Issue by qikink** [Openarl/PathOfBuilding#506]
When using Dyadian Dawn and The Goddess Scorned, Ignite duration is not correctly calculated. It appears that the formula for ignite duration being used is (1- [total faster burning]) but 100% faster burning should only *halve* the duration.

The correct formula should be 1/(1+[Total Faster Burning]). This is reflected in the wiki:
Ignited enemies burn 50% faster with the Goddess Scorned, which means the fire damage per second is raised by 50% and the ignite duration is lowered by 33.3%.

**Comment by eskalimur** [comment]
Will it be solved soon , also if you combine Goddess with Dyadian a multiplier of 6,667 appears.

**Comment by Openarl** [comment]
I'll try and sort this out for the next update, but I'm having difficulty getting "Burn Faster" and "Burn Slower" modifiers to both calculate correctly (particularly when used together).

**Comment by eskalimur** [comment]
Pretty sure the act like increase/decrease  - more/less - faster/slower.
Together additive.
Goddess + Dyadian Dawn + Emberwake = 20% faster.

It always has a chain of calculations.

Ignite DPS * 4 = Ignite Total DMG
Ignite DPS * (1 + Burn Modifier) = NEW Ignite DPS

Ignite Total DMG / New Ignite DPS = New Ignite Duration
or
Ignite Duration / (1 + Burn Modifier) = New Ignite Duration




Your calculated way to.. difficult with changing it up to "decreased Burn Rate" in Percent.

Or maybe im wrong, or dont know the lilimations of pob, but my calculation seem to work

**Comment by Openarl** [comment]
As per [Mark's comment](https://www.reddit.com/r/pathofexile/comments/6r2pkk/clarification_on_new_emberwake/dl4vlys/), faster and slower are not additive, but rather function separately; so I suspect I'll need to break them into two separate stats )instead of both using IgniteBurnRate), then combine them somehow in the calculation code.

**Comment by eskalimur** [comment]
Oh, thats kinda stupid.

But why not make 6 variables, 4 private ones.


Ignite Duration Modifier Faster (Goddess & Dydadian)
Ignite Duration Modifier Slower (Emberwake)
Ignite Dps Modifier Faster (Goddess & Dydadian)
Ignite Dps Modifier Slower (Emberwake)
Ignite Duration Modifier
Ignite Dps Modifier


Ignite Dps Modifier Faster / Ignite  Dps Modifier Slower = Ignite Dps Modifier 
Ignite Duration Modifier Faster / Ignite Duration Modifier Slower= Ignite Duration Modifier
