### ISSUE TITLE
Intuitive Leap

### ISSUE THREAD

**Issue by rhazor** [Openarl/PathOfBuilding#51]
Adding Intuitive Leap into jewel socket should allow selecting nodes in the region without the links just like the jewel is designed.

**Comment by Openarl** [comment]
Easier said than done, unfortunately. Intuitive Leap is a real pain to implement as it allows violations of the basic rules of the passive tree. It's something I intend to add support for eventually, but I'm not looking forward to doing it.

**Comment by Openarl** [comment]
The next update will (finally) add support for Intuitive Leap.
