### ISSUE TITLE
Mirror arrow calcs are wrong

### ISSUE THREAD

**Issue by ifarmpandas** [Openarl/PathOfBuilding#512]
Missing damage range from bow.

Attack speed cap should also be implemented. (10/5.7 I believe)

**Comment by Spawnbroker** [comment]
I am unable to reproduce this issue.  Here are some screenshots of what I see.

I have a Physical Bow, Harbinger Bow equipped with a damage range of 164-380:
![image](https://user-images.githubusercontent.com/2287451/28979103-778904e6-7916-11e7-817a-fdd7761ad05b.png)

On the Calcs tab for Mirror Arrow, I have 164-380 damage range under MH Hit Damage:
![image](https://user-images.githubusercontent.com/2287451/28979228-01167fb8-7917-11e7-8d07-730d19740e40.png)

Also on the Calcs tab, I can see the minion stats by selecting "Show Minion Stats" above.  The tooltips look good to me, is there an issue you're seeing with a specific unique?

![image](https://user-images.githubusercontent.com/2287451/28979198-e58779e6-7916-11e7-83b5-9a4270d20223.png)

**Comment by ifarmpandas** [comment]
My bad, read the output wrong. That part's working fine. I'll close this.
