### ISSUE TITLE
Nodes like "Splitting Strikes" don't affect bleed DPS with Lioneye's Fall

### ISSUE THREAD

**Issue by izenja** [Openarl/PathOfBuilding#513]
I'm not entirely sure if this is a bug, but I think a mod like "% increased damage with ailments while wielding an Axe" on the tree should apply to bleed DPS when using a bow and Split Arrow with Lioneye's Fall socketed in range and applying bleed.

**Comment by Openarl** [comment]
Fixed in the next update.
