### ISSUE TITLE
Trickster Patient Reaper & Vaal Pact

### ISSUE THREAD

**Issue by salixa** [Openarl/PathOfBuilding#518]
Ticking "Killed Enemy affected by DoT Recently" with Vaal Pact allocated incorrectly increases "Life Leech/On Hit Rate" on the left pane, and "Life Leech Rate" in the skill calculator. Note that hovering over the "Life Leech Rate" box displays the correct amount of leech.

**Comment by Openarl** [comment]
Fixed in the next update.
