### ISSUE TITLE
Natural/logical sort order for build names

### ISSUE THREAD

**Issue by zao** [Openarl/PathOfBuilding#519]
As it currently stands, the build list will sort names in pure lexicographical order. This results in that names like `Smasher 116p` will be sorted before `Smasher 34p`.
Is it possible to use a natural/logical sort order in Lua, akin to the winapi `StrCmpLogicalW`?

It's of course always possible to work around this by gluing on leading zeroes on my numbers to make them the same length, but it'd be a nice QoL improvement.

**Comment by Openarl** [comment]
Sure, why not! I have a natural sort comparator for Lua lying around, so it's easy enough to do. It'll be in the next update.
