### ISSUE TITLE
[DEV Question] How is the Program UI done?

### ISSUE THREAD

**Issue by bschley** [Openarl/PathOfBuilding#521]
Hey Guys,

I love the UI of the program, is this a lib? It´s controlled through lua right?

Cheers

**Comment by Openarl** [comment]
The application code, including the UI framework, is written in Lua; the C++ host program just provides a simple rendering API (which really just amounts to "draw this text here" or "draw this coloured line there"). If you look through the [Classes](https://github.com/Openarl/PathOfBuilding/tree/master/Classes) folder, all the *Control.lua files define the various control types (many of them specific to Path of Building).
