### ISSUE TITLE
[Bug] Skeleton Life

### ISSUE THREAD

**Issue by OSwoboda** [Openarl/PathOfBuilding#522]
According to the [spreadsheet](https://docs.google.com/spreadsheets/d/1LAi5g067lGa2XdHPpGa1ae8RKe-LBnwCjE-Z384fTV4/edit#gid=306684935), skeletons should have 1897 life at gem lv20, but pob shows 
![image](https://user-images.githubusercontent.com/4248132/29015474-6f4766f8-7b4e-11e7-9a25-08bf2a9b425c.png)
It shows 1897 for gem lv21 tho.

**Comment by Openarl** [comment]
That spreadsheet isn't 100% reliable; there's multiple errors in it, one of which is the assumption that all of the minion skills have the same minion level at each level of the skill. In this case, a level 20 Summon Skeleton actually summons a level 68 minion, not level 70 as is the case for, say, Raise Zombie, so the life and damage numbers are all off.
