### ISSUE TITLE
Baron + Iron Will does not apply to Skeleton Mages

### ISSUE THREAD

**Issue by Smaptastic** [Openarl/PathOfBuilding#524]
The Baron + Iron Will should apply character strength to Skeleton Mage (granted through Dead Reckoning) spell damage, but it does not appear to do so right now.

**Comment by Openarl** [comment]
This in not a bug; Summon Skeleton cannot be supported by Iron Will (although it would work if it could).

**Comment by Smaptastic** [comment]
Yeah you're right. That seems like a bug on GGG's end, then. Apologies for wasting your time.
