### ISSUE TITLE
Charged Dash Average DPS calc incorrect  

### ISSUE THREAD

**Issue by acidreian666** [Openarl/PathOfBuilding#528]
Using this passive tree
[https://www.pathofexile.com/fullscreen-passive-skill-tree/3.0.0/AAAABAYBAQEJAhEFtQZwBx4HmQ5IES8RlhXtFf0WvyLqJogmlSoLKwowcTIBNj06QkX0SVFJsUsKSxxLeEyOUEJTNVS9VUtZ8FxAXfJh4mHrYqxkr2qMbIxtbG9XcFJ1_XgZelOEb4SiidOKOIw2jYGNv4_Bj_qSgJMnk5CVLpaLmhedqqEvotmmf6c0qTSw2LIZtMW1SLcwt9m42b6KwJzBoMLsyBTPetQj1ELVudYH18_dSN2o4tXjhOd06Fro1utj7UHviPDV9W_5Nw==](url)

The in game Tool tip dps is 308.1
Path of Building average dmg is 279.3
if i put more gear on and better weapons the damage changes what the tool tip reads is even further spread from what Path of building is stating.
I think something isn't being calc correctly.

```
1 weapon
Rarity: Normal
Throat Stabber
--------
Claw
Physical Damage: 21-73
Critical Strike Chance: 6.30%
Attacks per Second: 1.50
Weapon Range: 9
--------
Requirements:
Level: 60
Dex: 113
Int: 113
--------
Sockets: R-G-B 
--------
Item Level: 69
--------
+40 Life gained for each Enemy hit by Attacks
```
```
1 skill level 15
Rarity: Gem
Charged Dash
--------
Movement, AoE, Channelling, Attack, Lightning, Melee
Level: 15
Mana Cost: 4
Experience: 2,853,468/7,759,995
--------
Requirements:
Level: 60
Dex: 134
--------
Channel to project a mirage forward in the direction you're facing, based on your movement speed. Release to teleport to the mirage dealing area of effect damage multiple times along the way. Travelling further applies a bonus to the damage as well as dealing damage in larger areas. Faster attack speed and lower movement speed will both cause damage to be dealt more frequently along the path.
--------
Deals 99.6% of Base Damage
50% of Physical Damage Converted to Lightning Damage
40% more Attack Speed
100% more Damage with Hits at Maximum Dash Distance
--------
Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.
```

**Comment by Openarl** [comment]
As outlined in [this bug report](https://www.pathofexile.com/forum/view-thread/1933177), there are some errors in the game's data for Charged Dash, which at the very least cause the in-game tooltip to show more DPS than the skill should actually be doing, and may also cause the skill to actually deal more damage than intended. Path of Building uses what I believe should be the correct values for the skill, so until the skill's data is updated, the game will show a higher DPS than PoB.

**Comment by Openarl** [comment]
The errors in Charged Dash have been fixed, and the program's skill data updated to reflect that.
