### ISSUE TITLE
The Burn Rate Modifier in PoB is wrong

### ISSUE THREAD

**Issue by eskalimur** [Openarl/PathOfBuilding#529]
If you wear Dyadian Dawn for example (35% faster burn rate), PoB calculates

 

Ignite Duration (4s base) * 0,65 = 2,6s
and then calculates so the total damage from ignite which would have occurred over 4 seconds to fit into 4 seconds.
In this case it results in * 1,54

 

But the Wiki states it calculated the other way around.
Damage * 1,35 and the calculates how long it will need for the Damage to tick of.
For Example with 100 Damage it would be 3 seconds.

 

    Enemies ignited by an attack burn 35% faster with Dyadian Dawn equipped, which means the fire damage per second is increased by 35% and the ignite duration is decreased by 25%.[1]

        To illustrate this, assume an enemy would normally be inflicted with ignite for 100 damage per second over 4.0 seconds. With Dyadian Dawn, the damage per second is increased by 35%, which gives 100 × 1.35 = 135 damage per second. Because the total damage must remain the same, the new duration of 400 ÷ 135 = 3.0 seconds can be obtained. 3.0 seconds is 25% less than 4.0.

https://www.reddit.com/r/pathofexile/comments/6scdb4/psa_pob_ignite_calculation_wrong/

**Comment by Openarl** [comment]
Duplicates #506.
