### ISSUE TITLE
Southbound Gloves Not adding % increased life to the sidebar.

### ISSUE THREAD

**Issue by Leitnen** [Openarl/PathOfBuilding#530]

**Comment by Leitnen** [comment]
don't know if this is intended or not but I thought it might be helpful.

Thanks for the hard work!

**Comment by Openarl** [comment]
The % increased Life in the sidebar is from the passive tree only, and does not include modifiers from jewels or equipped items. If you want to see the total % increased Life from all sources, you can find it in the Life section of the Calcs tab ("Total Increased").

**Comment by Leitnen** [comment]
ok thank you!
