### ISSUE TITLE
Immolate bug

### ISSUE THREAD

**Issue by sankethcb** [Openarl/PathOfBuilding#532]
In the latest version which has burning and ignite under one check box, immolate never registers the target as burning hence does not add damage.

**Comment by wlfbck** [comment]
I think this is still bugged. Adding immolate in an Oro flicker build only changes dps by 2k (for comparison, ruthless adds ~60k) as the last support in a 6link. Unfortunately there is *no* config flag for "is always burning", which could in turn just let the calculation add the immolate damage.

**Comment by Openarl** [comment]
The "Is the enemy Burning?" option definitely does exist, but like most options it doesn't show unless it can have an effect, which in this case involves actually linking Immolate to your main skill.

**Comment by wlfbck** [comment]
Aaah okay. I think that is a bit counter intuitive, atleast i like to enable/disable gems pretty often when switching stuff around. I must've never gone to the configuration when Immolate was enabled. Just some food for thought, maybe that's something which can be changed around in the future.

Lastly, thanks for answering :)

**Comment by Openarl** [comment]
Perhaps it is a little counter-intuitive, but the alternative is trying to find the few working options amongst this:
![loloptions](https://user-images.githubusercontent.com/19189971/29275792-a830bc92-814f-11e7-86be-08ea8d6defb5.png)

**Comment by wlfbck** [comment]
:D good point. Mhm maybe making the option available when a skill gem with which it synergizes is listed (even if it's not enabled)? Or does that also lead to exploding lists like this in the typical scenarios?

**Comment by Openarl** [comment]
Hmm. It wouldn't exactly be an exploding list; I think there's only about half a dozen conditions that support gems use, and some of them display by default anyway. Detecting which conditions are used by compatible support gems would be tricky though, for various reasons; it may be easier just to have those options displayed permanently, which is something I've been considering anyway.
