### ISSUE TITLE
PoB freezes after initial installation and when trying to update - 1.4.53 to 1.4.58

### ISSUE THREAD

**Issue by Fressikus** [Openarl/PathOfBuilding#533]
This happens when I extract PoB from the standalone .zip or install it via the installer. After launching the program for the first time, it gets stuck on the initial updating process.
[https://www.dropbox.com/s/49cnh8tplqkcrx6/PoB_freeze.jpg?dl=0](https://www.dropbox.com/s/49cnh8tplqkcrx6/PoB_freeze.jpg?dl=0)

If you decide to kill the hanging process and start it again, you are greeted with the normal interface (Version 1.4.53). You are then reminded that there is an update available, Version 1.4.58. When trying to autoupdate, PoB freezes once again.
[https://www.dropbox.com/s/d55kbhjasams8iy/PoB_freeze2.jpg?dl=0](https://www.dropbox.com/s/d55kbhjasams8iy/PoB_freeze2.jpg?dl=0)

**Comment by DarkWiss** [comment]
I have the same issue when I try to update

**Comment by dein0s** [comment]
@Fressikus broken links. Can you rehost images somewhere else?

**Comment by Fressikus** [comment]
@dein0s Sorry, links are back up!

**Comment by Fressikus** [comment]
Any idea why this could be happening? Anything else I could add to help solve this? It's annoying since even a fresh install does not help.

**Comment by Openarl** [comment]
That's quite an unusual place for the program to be freezing; it seems to be unable to overwrite one of the files in its installation folder. I'm not sure what could be causing it; the only thing I can think of is to try disabling any antivirus programs you have installed.

**Comment by Openarl** [comment]
Hmm. It still doesn't make any sense; especially when it occurs after installation, as at that point those files shouldn't have been opened by _anything_. I can only presume that some other software on your system is interfering with the update process, but I have no idea what that could be.

Anyway, the latest update (1.4.64) comes with a new installer version, so for the time being at least you can be up to date.

**Comment by Fressikus** [comment]
I've come back to this and I think I have it figured out. I'm using Acronis True Image for backups, and the software comes with a "Active Protection" feature that's supposed to prevent malware from encrypting your harddrives. After turning this off, I was able to reinstall and do the inital update process without problems. I'll try to update after your next release.

**Comment by Fressikus** [comment]
Yeah, that was the problem. For anyone having a similar problem, you can whitelist your PoB directory in Acronis so it does not interfere with updating.
