### ISSUE TITLE
Import doesn't allow pasting of build links

### ISSUE THREAD

**Issue by DaySev** [Openarl/PathOfBuilding#534]
ctrl+v doesn't work in "To import a build, enter a code here" so there's no way to import a build
PoB version 1.4.58

**Comment by dein0s** [comment]
You're definitely doing something wrong, cos both imports (raw paste and pastebin link) works just fine.
![img](http://i.imgur.com/7CDebXE.png)

**Comment by dein0s** [comment]
Then you have and invalid link, obviously.
Here's my link for the build that I've crafted 2 days before FoO release (was sitting on version 1.4.50 or smth) and it's still working as intended: https://pastebin.com/SSnD9nbx

**Comment by DaySev** [comment]
I would agree with you but why does it work in poeplanner then? is there a format difference or something?

**Comment by dein0s** [comment]
Well, yes.
There are two different import features in PoB:
- import profile (means the whole profile with gear, flasks, tree, skills and other stuff)
- import tree (where you import only the tree from poeplanner, planner from the official site and others)
So, if you want to just import the tree - use 'Import Tree' button.
![tree_button](http://i.imgur.com/EAOudL9.png)

**Comment by DaySev** [comment]
I'll try that button on the bottom, because the one in the image up top (Your first one) is where it won't let me paste trees from anything

I can type in it, just not ctrl+v
It only happened after it patched yesterday; I was able to ctrl+v in that box two days ago no problem

**Comment by DaySev** [comment]
Ok, so the bottom worked for the tree so I'll deal with that
