### ISSUE TITLE
Win 10 error - prt scr

### ISSUE THREAD

**Issue by Korburathor** [Openarl/PathOfBuilding#541]
Laptop spec, Asus R556L:
Win 10 home 
i5-5200U
12 GB ram
GForce 920M
I have newest version Release 1.4.53
After green launch window that happends:

![image5](https://user-images.githubusercontent.com/30896903/29166705-d1492730-7dc7-11e7-8b20-2b46ecc80f4d.jpg)

Please help.
Regards

**Comment by Korburathor** [comment]
After another app reinstall it works !

**Comment by Korburathor** [comment]
It worket only once, problem has occured after another running attempt.

**Comment by Openarl** [comment]
That's odd; that line of code shouldn't even be running in the current version of the program. Go to `C:\ProgramData\Path of Building\Data\3_0\` and look for a file called "Passives.lua". If it is present, delete it; that should stop the error from occurring. Regardless, the next update will disable the offending code entirely, so if you reinstall using the 1.4.59 installer (once it is available) then it should work.

**Comment by Korburathor** [comment]
It worked, thank you !
