### ISSUE TITLE
Option to set player full life missing?

### ISSUE THREAD

**Issue by ghr74** [Openarl/PathOfBuilding#542]
I'm on Version 1.4.58 and trying to look at the Damage at Full Life gem, however I can't find the Player Full Life option in the configuration that's supposed to be there according to google. Here's a screenshot:

http://i.imgur.com/z5GHkre.png (please excuse the Afterburner overlay)

Am I just being stupid or is it actually missing?

**Comment by dein0s** [comment]
Appropriate skill (supported with `Damage on Full Life`) should be selected as Main skill on the left bar.
![skill_selected](http://i.imgur.com/5eB43Dz.png)

**Comment by ghr74** [comment]
Wow, I was sure I had it on frost blades when I checked but now it's working for me, thank you. Closed.
