### ISSUE TITLE
Option to specify if act 5/10 are finished

### ISSUE THREAD

**Issue by koryushin** [Openarl/PathOfBuilding#544]
Hello, i made a search and did not find it.
When importing a low character the tool automaticaly add my Resistance a -60%.
But i'm still leveling and act 5 not finished yet so i don't have resistances penality.
I post this cause i'd like to check if i can sustain Righteous Fire with my actual build, and if not what i have to do.

Thanks for your great tool ;)

**Comment by Openarl** [comment]
Added in the next update.
