### ISSUE TITLE
Error in DPS calculation: Phase run + Ancestral Warchief

### ISSUE THREAD

**Issue by corosou** [Openarl/PathOfBuilding#549]
Phase run is being added to Ancestral Warchief damage, even though the gem states that it does not support totem skills.

Or am I missing a crucial piece of information?

Thanks, and keep up the great work!

**Comment by hsjing** [comment]
Correct me if I'm wrong, but I thought Phase Run applies a buff onto you, and your totems basically copy your stats. Think Lion's Roar, any source of onslaught, etc.

**Comment by Openarl** [comment]
Fixed in the next update.
