### ISSUE TITLE
Error in DPS calculation: Bringer of Rain + Melee Physical Damage Support

### ISSUE THREAD

**Issue by corosou** [Openarl/PathOfBuilding#550]
It seems the DPS calculation is stacking the included MPDS in BoR + the gem. I have tested this in game and they do not stack.

Thanks!

**Comment by Yajirushi** [comment]
Path of Building is calculating the damage based on only a level 20 Melee Physical Damage Support if you include it in a setup with Bringer of Rain, which is how the game handles that situation, the higher level support applies and the lower level does nothing.

**Comment by corosou** [comment]
I see what my problem was. I had not correctly assigned "socketed in: helmet" for the Ancestral Warchief gem, so it was not taking into account to BoR bonuses.

This is a non-issue and I'm closing this.

Sorry to have wasted your time.
