### ISSUE TITLE
Doryani's Invitation Belt wrongly has Lightning damage on it instead of Cold damage. 

### ISSUE THREAD

**Issue by AngryRoleplayer** [Openarl/PathOfBuilding#551]
Doryani's Invitation Belt wrongly has Lightning damage on it instead of Cold damage.

**Comment by dein0s** [comment]
Well, it has multiple ingame versions.
Check wiki for mroe info: https://pathofexile.gamepedia.com/Doryani%27s_Invitation

**Comment by Yajirushi** [comment]
When you go to add Doryani's Invitation look up to the right of "Add to build" for the dropdown menu that starts as "Lightning", select one of the other three variants there.

**Comment by AngryRoleplayer** [comment]
Ooops sorry guys!! I didn't notice at first!
