### ISSUE TITLE
PoB only runs successfully one time

### ISSUE THREAD

**Issue by dprinslow** [Openarl/PathOfBuilding#552]
Everything runs fine the very first time i install and run it but if i close it and try to open it again to comes up as not responding immediately. Reinstalling makes it work 1 more time but basically every time i want to reopen it i have to reinstall it

**Comment by Openarl** [comment]
Are you by any chance using multiple monitors? If so, then you may be experiencing the issue described in #336.

**Comment by dprinslow** [comment]
Yes seems to be same issue. I'll close this one to avoid duplicates
