### ISSUE TITLE
Poison dps is not correctly calculated

### ISSUE THREAD

**Issue by twothe** [Openarl/PathOfBuilding#559]
With the 3.0 patch the way poison damage is scaled changed: many weapon nodes now add "increased damage with ailments" According to the [Wiki ](https://pathofexile.gamepedia.com/Ailment) ailments include poison, bleeding, ignite, chill, freeze and shock, however selecting those nodes incorrectly does not actually show an increase in bleeding, poison or burning dps. I assume it will also not be factored into freeze/shock calculations, if there are any.

It would also be great to see the total "+damage with ailments" in the menu on the left.

**Comment by Yajirushi** [comment]
I just tested with v1.4.59 and the Claw specific nodes near the shadow start at least work correctly, can you upload a pastebin for a build with non-working nodes?

**Comment by Openarl** [comment]
I can't reproduce this; all of the Damage with Ailments nodes seem to be applying correctly when using the appropriate weapon type. Could you give me your build, and also point out some specific nodes that don't appear to be applying?

**Comment by Yajirushi** [comment]
https://pastebin.com/vjcr1t2G is a build with a broken 100% to poison claw (for simplicity on comparing poison damage), the poison nodes near shadow are applying properly but the claw cluster just to the left of the poison cluster and the claw wheel are not applying to poison in anywhere near as meaningful of a way as the poison cluster.

**Comment by Openarl** [comment]
The modifiers to Damage with Ailments from those nodes are applying correctly; this is from the Total Increased under Poison in the Calcs tab:
![poisonailment](https://user-images.githubusercontent.com/19189971/29320896-12d74d6e-821c-11e7-926b-9caa162581cc.png)

**Comment by Yajirushi** [comment]
Then why does going from 0 to 100%+ increased damage not change the relationship between total damage per poison and average damage by more than 1%? Are those stats not included in the Poison DPS and Total Damage per Poison on the statbar on the left? The only nodes I've found that actually change those stats are the pure poison nodes.

**Comment by Yajirushi** [comment]
Ah, never mind, for a bit there I forgot GGG changed the way ailments work in 3.0...

**Comment by Openarl** [comment]
Fair enough then.

Incidentally, it is mechanically impossible for modifiers to be listed like that in the Calcs tab, but not apply to the numbers shown there or in the stats in the sidebar, as it all uses the same code to determine which modifiers apply.

**Comment by twothe** [comment]
![image](https://user-images.githubusercontent.com/1131621/29325434-eab8065e-81e7-11e7-8314-79e0a70cde68.png)

This is the snapshot of the poison damage. Ailment increase is in the list, but the damage is not calculated correctly.

MH + Chaos shows as 4802.6 (looks correct) * 0.20 = 960 dps. This value is shown in the poison dps section. This for once completely ignores the 670% increase and additionally does not include the 80% chance to poison, so it should actually be 960 * 7.7 * 0.8 = 5913.6 dps. Same goes for the bleed dps calculation.

The total dps including poison then however shows a 10k dps increase for no apparent reason.

**Comment by Openarl** [comment]
Actually, the 670% increase has already been factored into the calculation of the "4802.6" number. And the Poison DPS number is just the average DPS of each Poison stack; your Poison chance is factored in later, during the calculation of Total DPS inc. Poison, which is only shown in the sidebar.

**Comment by twothe** [comment]
With the base DPS of ~14k of mostly physical damage and a 20% * 80% poison dps of that dps it should be roughly around 2.2k dps without any modifiers, respectively around 17k dps with modifiers. The real number is of course lower, but 0.9k dps just cannot be correct given the numbers.

**Comment by twothe** [comment]
Doing the complete calculation:
MH + Chaos average hit: 2460
Including crit: 2619.9
At 4.12 attacks/s: 10793.988 dps

80% chance to poison for 20% of that damage: 1727,03808 poison dps
670% increased poison damage: 13298,193216 poison dps total.

There is either an error in my calculation or in the tool. ;)

**Comment by Openarl** [comment]
Oh boy. What you're doing is fundamentally incorrect, due to the Damage over Time changes made in 3.0. Poison's base damage is no longer based on the actual hit damage, but rather is derived using an entirely separate calculation. That's why the program now displays "MH Source Chaos" (and should also display "MH Source Physical", but that's bugged ATM), which is the output of that calculation; and that calculation already includes all modifiers that affect poison damage.

**Comment by twothe** [comment]
Tough to find some exact information on that. Closest I could find was this from Mark GGG:

> Poison deals 20% of the applicable (usually physical + chaos) base **and added damage** of the skill, per second

I can't however find any clarification what that added damage is.

**Comment by Openarl** [comment]
"Added damage" means modifiers like "Adds X to Y Physical Damage to Attacks".

**Comment by twothe** [comment]
Got a very detailed official explanation: https://www.pathofexile.com/forum/view-thread/1930909/page/4#p14741874

**Comment by twothe** [comment]
I removed some items from the build to make the calculation easier:

Bow damage: 79 - 294 physical
Physical added: 48 - 75 (support gem and gloves)
Applicable modifiers: 1.33 (Belt) * 1.94 (Maim + Physical Projectile Support) * 0.69 (Chain support) * 0.614 (Barrage base damage modifier) = 1.093 total modifier
Applicable MH base damage is: (79 + 294 + 48 + 75) / 2 * 1.093 = 271,064

This means poison base damage is: 27.8 - 80.7 damage
Damage modifier: 7.5 (poison/ailment passive skills) * 1.49 (physical projectile support) = 11.175
Crit effect mod: 1+ 13% * 50% = 1.065
Avg poison dps per poison: (27.8 + 80.7) / 2 *11.175 * 1.065 = 645.65 dps (Calcs shows 547.1 here)
Poison damage total per hit: 645.65 dps * 2.8s = 1807.82 damage (Calc shows 1531.9 here based the the different value above)
Max poison stacks: 3.97 (attacks) * 2.8s = 11.1 (Calc shows 8.9 here)
Maximum sustained poison dps: 11.1 * 645.65 = 7177.05 (Calc shows 4870.8 here, not sure if this includes the 1785,1 bleed dps already, calculating total dps incl poison - total dps)

The numbers differ, but I cannot tell why. If my calculation is correct, poison dps displayed in the tool would be off significantly.

**Comment by Openarl** [comment]
Could you give me the exact build? It'd be much easier for me to check the calculations if I had it.

**Comment by twothe** [comment]
[bow_debug.zip](https://github.com/Openarl/PathOfBuilding/files/1229160/bow_debug.zip)

**Comment by Openarl** [comment]
You don't need to upload the build .xml file to share builds; go to the Import/Export Build tab, then in the Build Sharing section you can generate a share code, which you can then turn into a pastebin.com link.

You've made two major errors in your calculations:
1. Damage modifiers (like PPAD and Chain) do not apply during the calculation of the base damage, and in fact Chain doesn't apply to Poison at all.
2. When modifying the base damage, you included modifiers for Chaos and Poison damage; but modifiers to Physical damage also apply to the Physical portion of the base damage (including the modifier from Maim).

So the correct calculations are:

Base weapon damage: (79 to 294) * 0.61 = 48.2 to 179.3
Base added damage: (48 to 75) * 0.61 = 29.3 to 45.8
Poison base damage: (48.2 + 179.3 + 29.3 + 45.8) / 2 * 0.2 = 30.2

Relevant modifiers:
650% increased Poison + Chaos Damage
121% increased Physical Damage
49% more Poison/Bleed Damage (from PPAD Support)
30% more Physical Damage (from Maim Support)
Crit effect modifier: 1.065

30.2 * (1 + 6.5 + 1.21) * 1.49 * 1.3 * 1.065 = 542.6 Poison DPS (off by ~1%, but that's rounding error)
Max stacks: 8.9 (you calculated that correctly)
542.6 * 8.9 = 4829.4

**Comment by twothe** [comment]
Thank you for the detailed explanation.

I am beginning to realize how difficult it is to get the correct formula with everything based on best guesses and occasional official explanations. Hopefully they fix the bug with the current display in the character sheet soon, so there is an officially correct base to check calculations.

It seems to me that I was wrong and the poison dps is correctly calculated (although displayed in a confusing way in the left summary window). Which also - sadly - means that poison dps is currently a worthless waste of skill points.
