### ISSUE TITLE
Life Calculations wrong

### ISSUE THREAD

**Issue by MaestroMaelstrom** [Openarl/PathOfBuilding#561]
Hello, just wanted to make a post letting you know there's an error in the life calculations. I have triple checked my gear. I have put the exact gear with proper stats into the builder to check some other things and it's telling me I should have way more life than I do. All other stats seem correct for me.

**Comment by Yajirushi** [comment]
Export your build to pastebin and post a link please.

**Comment by Openarl** [comment]
If something were indeed wrong with the life calculation then I think it'd be noticed by more than just one user out of a hundred thousand. It is far more likely that you've made some error in your build, but without seeing said build I can't possibly help.

**Comment by MaestroMaelstrom** [comment]
Here is the tree from PoB:
https://www.pathofexile.com/passive-skill-tree/3.0.0/AAAABAUBAFb6FHVPBAd1dKDUUuCf9zK18orkBiAFLWyMwKZ4eiFVJpWYb7c-wuy9Nhjb8B-Sfakn3D3EFaluxPYLYXTx2L3AGow2jb907WKsd-NRR2jy02_DOnKp2sG0xY9g6xQFZnrv6NYwfP4Kkm4CloTvh3aE2WegvqcuU5pqm-wWv6i551Qi6gxSKjg8LaIAVUt_KySL5c9h4kCgh2q8Vkd-AdwX3G8n0nx4Da9sJP1lTXfXBbUGouOfg8zGrjWSD6shYF4TqZRKfdwj

and I don't know how to export a character to pastebin but here's a link to the character profile: https://www.pathofexile.com/account/view-profile/Mastrchief1993/characters

the name is PyroMassachre. It should be wearing a kaoms but I currently have it on my other char.
