### ISSUE TITLE
Feature Request: Improve selecting "main skills" when there are multiples of the same skill

### ISSUE THREAD

**Issue by nevets1219** [Openarl/PathOfBuilding#562]
On the right-hand side where you can select your "main skill" - it's often not obvious what's the main skill is if you have multiples of the same skill - this also applies to the "Calcs" view when selecting "View Skill Details".

Like the "Items" view where you can easily choose "weapon set 1" or "weapon set 2", something similar for the "main skill" selection could make it easier than just guessing. Other options might be to sort it by DPS.

Currently on version 1.4.59

**Comment by Yajirushi** [comment]
Or, you can name your setup so you choose by name instead of by skills. Type in the "Label:" box above the skill/support gem chooser.

**Comment by nevets1219** [comment]
Good point, I had not thought about that.

However, in terms of usability and ease of use, I still think it would be an improvement to have some filter to make it obvious.

**Comment by Openarl** [comment]
Good suggestion. I've added the socket group tooltip to the main socket group dropdowns, which should suffice.
