### ISSUE TITLE
Necromantic Aegis Bug

### ISSUE THREAD

**Issue by RavaRosa** [Openarl/PathOfBuilding#563]
When you allocate a point into Necromantic Aegis, it ignores the resistances gained from "Elemental Resistances with Shields" and the "Sanctuary" notable.  In-game you still receive these bonuses.

**Comment by Openarl** [comment]
Ah, I never considered that interaction before. It seems that even "additional Chance to Block with Shields" apply with NA. I'll fix that in the next update.
