### ISSUE TITLE
Summon skeleton caster

### ISSUE THREAD

**Issue by ginolavagino** [Openarl/PathOfBuilding#567]
There is a bug in calcualting the skeleton caster damage (from summon skeleton threshold jewel), when you swtich from gem level 19 to 20 the dps triple

**Comment by Ndgc** [comment]
I have the same issue. Version 1.4.61.

Moreover, I'm not sure the calculated damage has any relation to what i can see in minion.lua

With only the level 20 gem, and no modifiers, Path of Building claims a range of 840-1309 for base damage on a fire caster.
Minion.lua seems to claim  47-221, unless I'm mis-reading.

Similarly at level 1, Path of Building seems to claim 7-10, where it reads 4-6 in minion.lua

**Comment by Openarl** [comment]
The damage for Skeleton Casters has not been updated for 3.0 for the same reasons outlined in #492; the short version being that I don't yet know how to calculate the base damage of any monster spells in 3.0. As this issue shares the same cause, I'll close this one as a duplicate.

Incidentally @Ndgc, you are indeed miss-reading that file; the level of the spell used by the minion is determined by the minion's level, not the gem level; so a level 20 Summon Skeleton summons a level 68 skeleton, which will use a level 28 Fire/Cold/Lightning Projectile spell (the highest it can use, given its level).
