### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Phlexx0** [Openarl/PathOfBuilding#57]
[BUG REPORT]
All imported items show up as +20% quality and as a result giving wrong Armor/Evasion/ES/DMG calculations, also i was unable to edit those items to remove quality or change it to any other value. It doesn't matter if items ingame have any quality on them, its always 20% after importing.

**Comment by Openarl** [comment]
The program automatically normalises quality on all non-corrupted items, as it assumes you'll always want everything at 20%. Although now that you've mentioned it, doing that for imported items may be counter-productive if you're deliberately keeping items at low/no quality. I'll see if I can add an exception for imported items.

**Comment by Openarl** [comment]
After the next update, the program will no longer normalise the quality on imported items.
