### ISSUE TITLE
pob white crash screen on booting up.

### ISSUE THREAD

**Issue by Novadesu** [Openarl/PathOfBuilding#570]
so when i updated pob to the latest version everything was fine until i rebooted my pc every time i open up  pob it will just be a big white screen and say that its not responding i tried opening pob as an admin but same problem...

every time i reinstall pob it work until i reboot my pc and then its the same problem please help.
i play poe alot and need pob to make my builds and try out stuff

**Comment by Openarl** [comment]
Am I to assume from your comment in #450 that you're having exactly the same issue (i.e it only occurs when opening on a non-primary monitor)? If so, then I'll close this.
