### ISSUE TITLE
Damage on Full Life does not show bonuses for ranged skills

### ISSUE THREAD

**Issue by djojd** [Openarl/PathOfBuilding#572]
In 3.0, it was changed from Melee Damage on Full Life, to just Damage on Full Life with attack skills.

However, bonuses still only show when using a melee skill.

**Comment by dein0s** [comment]
With what get this aint working for you?

**Comment by djojd** [comment]
Not that familiar with this website or what get is, but it's on the most recent update, afaik. Version 1.4.59

**Comment by Openarl** [comment]
Do you have the "Are you always on Full Life?" option set in the Configuration tab? It may not appear unless you have Damage on Full Life linked to your main skill.

**Comment by Ikaguia** [comment]
The "Are you always on Full Life?" option does not show up even if you link it to your main skill. it only works when you link it to a melee skill

**Comment by Openarl** [comment]
I can't manage to reproduce it. The option always appears when the support is linked to the main skill, even when it is a ranged skill; the only thing that can cause it not to appear is if the main skill is disabled (for example, if there's no compatible weapon equipped).

**Comment by Openarl** [comment]
I have still not seen any confirmed cases of that option failing to appear under the required conditions, and it shouldn't be mechanically possible anyway. Regardless, as of the next update all condition options upon which any support gems depend will always be shown, even if enabling them will have no effect; hopefully this change will dispel any remaining confusion regarding such options.
