### ISSUE TITLE
Hits can't be evaded not computed correctly

### ISSUE THREAD

**Issue by dIggl3r** [Openarl/PathOfBuilding#573]
I'm using The Temptestuous Steel sword, which has the implicit **Hit's can't be evaded**, yet in the dps window of PoB, Hit Chance isn't computing it.  Can we fix this please?

**Comment by dein0s** [comment]
Working as intended for me: https://pastebin.com/JdW3T95Q

**Comment by dIggl3r** [comment]
PoB shows mine having 89% hit chance, while in game it's 93%.  Bizarre?

**Comment by dein0s** [comment]
Can you provide your build at least so we can figure out whats going on?

**Comment by dIggl3r** [comment]
I switched builds and remapped my nodes... Next time *if* I see it, I'll come back and tell you.  :-/

**Comment by Openarl** [comment]
It does seem to be working as intended, so I'll close this.
