### ISSUE TITLE
Blight+temp chains

### ISSUE THREAD

**Issue by Hapseleg** [Openarl/PathOfBuilding#576]
Hi, it seems blight's skill duration isn't affected by temp chains (tested it in-game and it does prolong blight).

Also on a side note, it would be awesome if there was a way to see hinder's duration (the debuff from blight)

Keep up the great work :)

**Comment by Openarl** [comment]
The interaction with Temporal Chains was fixed in 1.4.60; and the next update (1.4.61) will add secondary duration calculations for various skills, including Blight.
