### ISSUE TITLE
Gruthkul's Pelt

### ISSUE THREAD

**Issue by livejamie** [Openarl/PathOfBuilding#577]
This item disables your spells, it would be nice if POB could recognize that and calculate knowing your spells would be disabled.

**Comment by Openarl** [comment]
Fortunately, one of the changes made recently (in 1.4.59) makes it fairly trivial to do this. It'll be in the next update.

**Comment by livejamie** [comment]
Thanks! If it's trivial would be nice to have the same thing for Brutality Support gem.

**Comment by Openarl** [comment]
What do you mean? Brutality doesn't disable any skills.

**Comment by livejamie** [comment]
It means your Heralds and stuff won't do any damage, correct?

**Comment by Openarl** [comment]
No. Brutality only prevents the linked skill(s) from dealing non-Physical damage; it has no effect on your other skills, and indeed support gems in general cannot affect other skills in any way.
