### ISSUE TITLE
"Chance to poison on hit" from weapons being added globally.

### ISSUE THREAD

**Issue by noremac13** [Openarl/PathOfBuilding#579]
When they did the poison and ailment rework they also changed weapons that poison on hit to only work with hits from that specific weapon.  You can easily test by equipping a weapon like Mortem Morsu in the calculator and use a spell linked with lesser poison.  The 60% on the weapon and 40% from the support gem are showing the spell has 100% chance to poison but if you go in game you will see you only have the 40% chance from the support gem only.

**Comment by Openarl** [comment]
Fixed in the next update.
