### ISSUE TITLE
[Request] Hypothermia

### ISSUE THREAD

**Issue by B14d3r11** [Openarl/PathOfBuilding#580]
PoB is unable to calculate Hypothermia in to damage calculations because there is no check box for "Is the enemy Chilled?"

Or is there some backhanded witchcraft behind Hypothermia which makes it hard to do?

**Comment by Openarl** [comment]
The option does exist, but you probably won't see it unless you actually have Hypothermia linked to your main skill, as like most options it doesn't appear unless it can have some effect.

**Comment by B14d3r11** [comment]
I do have hypothermia equipped to my frostblades skill and it doesn't show up...

**Comment by Openarl** [comment]
Are you sure it isn't there?
![hypo](https://user-images.githubusercontent.com/19189971/29557139-7648cfb8-876b-11e7-8a83-5d89f4ebbd7d.png)

Cold Penetration is additive with the target's resistance and any other source of penetration that you have, so it is only a straight "more" multiplier if those aren't present.

**Comment by B14d3r11** [comment]
I have found it after updating and can see it now.

I have around 49% Cold pen without Cold Pen support. A lvl 20 and 20% Cold pen support is like 47% more penetration or something. On an average mob that should be around 47% more damage compared to the hypothermia's 39% more on chilled targets. But Hypo is calculated as being a higher damage source than Cold pen...

Also why is it additive with the targets resistance? Resists are %less damage so if you have 75% res you take 75% less damage but if you cut through that 75% with 50% you are left with 25% resist so a 10000 dmg hit with 75% res does only 2500dmg but a 26% resist does 7500. That is basically tripling the damage you deal because the resist are less right?

**Comment by Openarl** [comment]
There is no "more" penetration; all sources of penetration are additive with each other and with the target's resistance. 

If the target has 0% resistance and you have 49% cold penetration without the support gem, then a hit that would do 10k without factoring in resistance would now do 10k * (1 + 0.49) = 14.9k. With the gem, (which gives 37% at level 20) it becomes 10k * (1 + 0.49 + 0.37) = 18.6k, and with Hypothermia instead it would be 10k * (1 + 0.49) * 1.39 = 20.7k.

If the target instead had 75% resistance, then with just the 49% cold penetration the hit would deal 10k * (1 - 0.75 + 0.49) = 7.4k. With the Cold Penetration gem, it becomes 10k * (1 - 0.75 + 0.49 + 0.37) = 11.1k, and with Hypothermia instead it is 10k * (1 - 0.75 + 0.49) * 1.39 = 10.3k.

**Comment by B14d3r11** [comment]
That is correct about the 37% i misread the 20% quality thing. Which means a lvl 20 hypothermia should be 2% more damage in comparison.

**Comment by Openarl** [comment]
1.5%, actually (1.39/1.37 = ~1.015), and only if the target has no resistance and you have no other sources of penetration.
