### ISSUE TITLE
POB stopped working

### ISSUE THREAD

**Issue by ZeroCool940711** [Openarl/PathOfBuilding#585]
Hi there, until yesterday I was using POB without a single problem, today when I tried to open it the interface just freezes and stop responding.Havent made any changes to my computer, any way I can provide you a log or something so you can help me figure out what went wrong?

**Comment by Openarl** [comment]
Are you using multiple monitors? There is a known issue that occurs in certain systems wherein the program freezes if launched on a non-primary monitor.

**Comment by ZeroCool940711** [comment]
Nope, I have only one monitor.

**Comment by ZeroCool940711** [comment]
BTW, I tried uninstalling POB and installing it back and also tried the portable version and none work. I managed to take this screen shot, when the app is loading the first window shows some kind of mini log and it says it cant find some config, not sure if thats what make it fail.
![untitled](https://user-images.githubusercontent.com/5977640/29554348-9e0ad610-86d3-11e7-9236-89cb8b3c11e8.jpg)

**Comment by ZeroCool940711** [comment]
Something that might be useful, or maybe not. I used Process Monitor to watch what POB was doing to see if I could find the problem and got [this](https://pastebin.com/z98jSZfg), its the log of things that were not marked as "Success" there and that were related to POB, I made some filters to get only things related to POB and reduce the log size, as you can see there are a lot of errors of files not on the POB directory and other things. Hope it helps a bit and hope its not a waste of time for you.

**Comment by ZeroCool940711** [comment]
@Openarl I tried some things to try to fix the problem with POB not working on my computer and so far I think that the problem is with POB SimpleGraphic.dll and not my computer or video card driver. I tried the next things to see if I could fix the problem but had no luck, maybe you can get something from this info and I hope you can fix the problem as I really need POB working ASAP, cant play without it, here's what I tried:
- Removed all my video cards but one as I though it might be a problem with having multiple cards.
- Reinstalled Windows 10 and all updates available from microsoft.
- Installed all .net framework and C++ redistributables.
- Installed every  single nvidia driver version and of course I restarted my computer every time to make the changes effective.
- Tried every single compatibility option windows 10 has and also tried every settings for the application on the nvidia panel.

Finally I uninstalled my nvidia driver and tried to open POB, it worked, everything was working without a problem, of course I can't play Path of exile without a driver for my video card so I had to install it back or there wouldn't be a reason to use POB if I can not play POE, after installing the driver and restarting again it stopped working. I think you could send me a few versions of the SimpleGraphic.dll to test it on my computer or you could give me some tool you use to debug POB and I can send you the logs back.  

Hope you read this text book I wrote and hope we can find a way to fix this problem, as last thing I will try to learn lua and see if I can make the code for POB work and fix things myself and help with the development as I have a lot of free time and some experience as a python developer and maybe I can do something with lua but learning a new programming language is not easy and could take me some time to learn enough to be able to help, have a good day and thanks for the time.

**Comment by ZeroCool940711** [comment]
Closing this shit as it seems like no one give a fuck about it and no one want to help me with this problem.
