### ISSUE TITLE
Crash on startup --SCRIPT ERROR--

### ISSUE THREAD

**Issue by Ruud88x** [Openarl/PathOfBuilding#588]
When I start the application the first time I get an error, and there is no way to use the program. Using windows 7.

Please wait while we complete installation...

Saving D:\Applications\PoB\Launch.cfg

--- Render Shutdown ---
Unloading resources...
Deleting context...
Renderer shutdown complete.
Engine shutdown complete.

--- SCRIPT ERROR ---
Runtime error in 'D:\Applications\PoB\Launch.lua':
UpdateCheck.lua:9: module 'xml' not found:
	no field package.preload['xml']
	no file 'C:\Program Files (x86)\LuaRocks\lua\xml.lua'
	no file 'C:\Program Files (x84)\LuaRocks\lua\xml\init.lua'
	no file '%APPDATA%\LuaRocks\share\lua\5.3\xml.lua'
	no file '%APPDATA%\LuaRocks\share\lua\5.3\xml\init.lua'
	no file 'c:\lua\systree\share\lua\5.3\xml.lua'
	no file 'c:\lua\systree\share\lua\5.3\xml\init.lua'
	no file '%APPDATA%\LuaRocks\lib\lua\5.3\xml.dll'
	no file 'c:\lua\systree\lib\lua\5.3\xml.dll'
stack traceback:
	[C]: in function 'require'
	UpdateCheck.lua:9: in main chunk
	[C]: in function 'LoadModule'
	D:\Applications\PoB\Launch.lua:30: in function <D:\Applications\PoB\Launch.lua:15>

**Comment by Openarl** [comment]
Your system's LUA_PATH is interfering with the program's ability to locate the libraries that are bundled with it; adding `!\lua\?.lua;` to it should fix it. You may also need to add `!\?.dll;` to your LUA_CPATH as well.

**Comment by Ruud88x** [comment]
That did the trick. User error I suppose! Cheers.
