### ISSUE TITLE
Need color selection for items like prismatic eclipse

### ISSUE THREAD

**Issue by Exportforce** [Openarl/PathOfBuilding#589]
Hello,

I am using "Prismatic Eclipse" ( https://pathofexile.gamepedia.com/Prismatic_Eclipse )
This item has different effects depending on the colors. It seems that PoB does not yet support this.

thanks

**Comment by dein0s** [comment]
Same as https://github.com/Openarl/PathOfBuilding/issues/388
As for now you can manually edit such items to provide stats that you're need.

**Comment by Exportforce** [comment]
Hello,

thanks for the reply. Would you mind telling me how to edit uniques that way, when they don't have any options for things like slot colors?

thanks

**Comment by dein0s** [comment]
Select unique, click `Edit` button, change desired stats.
![how_to_edit](https://i.imgur.com/UUFFx8M.png)

Let's say you have 3 green sockets in your sword (3*12=36%), then you have to edit the original value (change 12 for 36) and remove `per Green Socket` condition like this:
![three_green_eclipse](https://i.imgur.com/Ofjvwre.png)

And voila, the stat is taken into account now!
![magic](https://i.imgur.com/4TdMtlD.png)

**Comment by Openarl** [comment]
The next update finally adds support for viewing and editing item sockets, as well as adding support for item modifiers that interact with the item's sockets, such as those on The Pariah.
