### ISSUE TITLE
[Bug] Blade Flurry 

### ISSUE THREAD

**Issue by klipson3** [Openarl/PathOfBuilding#59]
Not work Curse and not correct show Average Hit and Skill hit damage.
Sry for my lng.
Build XML file:
[double_2.zip](https://github.com/Openarl/PathOfBuilding/files/623122/double_2.zip)

**Comment by dein0s** [comment]
![w/o vuln](http://i.imgur.com/9pTTOEF.png)
![w vuln](http://i.imgur.com/CvlIohp.png)
I don't see anyth wrong here, everything working as intended :|
