### ISSUE TITLE
Dark Pact Incorrect Functionality

### ISSUE THREAD

**Issue by SeventhSolar** [Openarl/PathOfBuilding#590]
PoB seems to assume Dark Pact calculates damage based on life, or probably life sacrificed.  It is not.  Dark Pact has a flat chaos damage base which increases as the skill gem levels. and is listed as a table on the wiki.

I could not see any way in which Dark Pact would otherwise be scaling off the life of my totems, but here's my pastebin just in case:
https://pastebin.com/92kZzJyJ

**Comment by Openarl** [comment]
Dark Pact removes up to 6% life from the target and deals base damage equal to the life removed, plus the flat damage listed in the gem tooltip. This is fundamentally how the skill works, and has been confirmed more times and in more ways than I care to list, but here's a few:

From [this reddit comment thread](https://www.reddit.com/r/pathofexile/comments/6r8xfg/here_is_the_skill_gem_information_for_the_new/dl38x29/):
> No, the base damage of the skill is what's listed on the gem, plus damage equal to the removed life of the skeleton.

> In this instance, self cast isn't relevant. It uses the life of a skeleton if one is in range of the targeted location, or your life instead if there are no skeletons in rage.

> If you link this with a totem and have no skeletons, does the totem use its own HP?
> Yes. So will a trap, but it only has 1, so it won't be able to sacrifice any.

From the skill reveal:
> Because the damage dealt by the skill is based on life, the skill has a unique build setup, involving specializing in minion life or player life and maximizing chaos and spell damage. The skill also works well with Minion Instability and the Necromancer's Beacon of Corruption, as you're able to forcibly cause your skeletons to reach low life.
