### ISSUE TITLE
Incorrect Life Calculation

### ISSUE THREAD

**Issue by XLordShadow45X** [Openarl/PathOfBuilding#593]
Hello there,
it seems that life is calculated wrong in the build I am currently using.

My life ingame is at around 3800. But Path of Building shows that my life should be at 4700.
I have entered all of my current ingame data. Equipment and Skilltree are identical. I have no auras or golems running.
I am quite confused and don't know where I might have made a mistake... Or where the calculation has gone wrong.

It would be nice to get an answer and maybe fix this issue.

https://pastebin.com/jHY2jkUr
https://www.pathofexile.com/account/view-profile/XLordShadowX/characters    X_TsarBomba_X

**Comment by Openarl** [comment]
You've set the character level in PoB to 99; correcting it resolves the difference.

**Comment by XLordShadow45X** [comment]
Damn I am an idiot...

Thank you.
