### ISSUE TITLE
The Unshattered Will increased damage not applying

### ISSUE THREAD

**Issue by kohelfs** [Openarl/PathOfBuilding#595]
The Unshattered Will (the new shield Harbinger shield) has a Increased Damage with Channelling Skills stat that does not applied, even though it reads in blue (thus, I thought it was being calculated).

I tried this with both Scorching Ray and Blight, and both skills do not receive the damage increase.

**Comment by Openarl** [comment]
The problem turned out to be specific to the Damage over Time portion of channelled skills; so it works fine with Flameblast and Charged Dash (which is what I tested it with when I first added support for it). It'll be fixed in the next update.
