### ISSUE TITLE
Innervate not accounted for with traps and mines

### ISSUE THREAD

**Issue by Firedrops** [Openarl/PathOfBuilding#599]
Seems to affect both spells and attacks, innervate's flat damage is not shown when added as support.

**Comment by dein0s** [comment]
Well, currently innervate doesn't work with lightning trap ingame either.
![l_trap](https://i.imgur.com/T53hBIx.png)

**Comment by Openarl** [comment]
Innervate Support cannot apply to trap, mine, or totem skills; so this is working as intended.

**Comment by Firedrops** [comment]
Sorry! Did not realise. Thanks for the quick response.
