### ISSUE TITLE
Guardian node "Radiant Faith" is not correctly adding ES or Armor

### ISSUE THREAD

**Issue by shoolayce** [Openarl/PathOfBuilding#6]
Understandably, it seems that the Radiant Faith node has been ignored or overlooked. Currently, allocating it does absolutely nothing. 

Here's an import code for a build that easily showcases said issue: https://gist.github.com/efd512b1ea0215f52d425fd1830a0064
Simply import and allocate the Radiant Faith node. Nothing changes.

This is pretty low priority (in my opinion) but if it's a quick fix I would appreciate seeing it dealt with. Thanks for making such a great utility.

**Comment by Openarl** [comment]
Radiant Faith is one of many ascendancy notables that require special-case code to get them working. I've added support for some such notables, but for many (including Radiant Faith) I simple haven't had the time. Naturally I'm prioritizing adding support for the ones people are asking for, so I will look into it, although this one is going to be particularly tricky to implement so no ETA or anything.

**Comment by Openarl** [comment]
Ok, Radiant Faith is supported now. Have fun!
