### ISSUE TITLE
add exclusion filtering in passive tree search

### ISSUE THREAD

**Issue by zmike** [Openarl/PathOfBuilding#602]
the most common search that I do is 'maximum life', but it would be nice if I could do something like "maximum life -minion" to exclude all the minion nodes

**Comment by dein0s** [comment]
Well, take a look at https://github.com/Openarl/PathOfBuilding/issues/208

In your case (to exclude all minion nodes) pattern will be the following:
`^%d*%% increased maximum life`

**Comment by zmike** [comment]
Oh, okay. In that case maybe there should be a tooltip for the search box which indicates regex searching is supported. Thanks!

**Comment by dein0s** [comment]
I definetly wouldn't call this a normal regex. It's too abnormal in lua (no support for alteration, no repetition operators for groups, it doesn't even support logical `OR`) :D

**Comment by zmike** [comment]
eh close enough for me
