### ISSUE TITLE
Chance to ignite support not counted in the Calcs window

### ISSUE THREAD

**Issue by VolG90** [Openarl/PathOfBuilding#603]
The bug was already reported but has been closed, the chance to ignite support doesn't seem to be shown in the Calcs window

Screenshots proof http://imgur.com/a/it93b

Pastebin of the build https://pastebin.com/k0YFHSS9

**Comment by Openarl** [comment]
You have Leap Slam selected as the main skill in the Calcs tab; you need to change it to Flicker Strike.
