### ISSUE TITLE
[Feature Request] Add configuration for "Used movement skill recently" for Walk The Aether

### ISSUE THREAD

**Issue by jrobinson3k1** [Openarl/PathOfBuilding#604]
Currently, Walk The Aether Trickster ascendancy node does not affect your DPS in Path of Building. The mechanics increase your cast and attack speed by 20% if you've used a movement skill recently. I would like to request a configuration option for having used a movement skill recently so that the output DPS can be affected by the benefits of this node.

**Comment by Openarl** [comment]
Fixed by #671; to be included in update 1.4.66.
