### ISSUE TITLE
Possible issue with "% Increased Life Leeched per second" mod

### ISSUE THREAD

**Issue by twiz-ahk** [Openarl/PathOfBuilding#605]
It seems the "% Increased Life Leeched per second" mod isn't being calculated into the "Life Leech/On Hit Rate" value.
Example: In the **Hematophagy** cluster taking the _Left_ node that gives "% of maximum Life per second to maximum Life Leech rate" will increase the value, but the _Right_ node gives no change.

Thank you to all contributors for your work on this amazing tool.

**Comment by dein0s** [comment]
Seems fine for me:
without 2 nodes in `Hematophagy` cluster
![no_2_nodes](https://i.imgur.com/Hr8ZSjB.png)
and with them
![yes_2_nodes](https://i.imgur.com/BwP3KXY.png)

**Comment by twiz-ahk** [comment]
http://i.imgur.com/eEYoaqW.png

**Comment by twiz-ahk** [comment]
http://i.imgur.com/eEYoaqW.png
http://i.imgur.com/7H6fYbj.png

**Comment by twiz-ahk** [comment]
http://i.imgur.com/Ji9tgdy.pnghttp://i.imgur.com/Ji9tgdy.png

**Comment by twiz-ahk** [comment]
Whoops, Seems I was hitting cap, so Rate doesn't help. Sorry for the confusion.
