### ISSUE TITLE
Installer for 1.4.59 triggers warning on VirusTotal

### ISSUE THREAD

**Issue by lunaryorn** [Openarl/PathOfBuilding#606]
See [report](https://www.virustotal.com/#/url/8b37a85c1351dfc5c0b1a87ccf173275be21483421b161fb4eeef6aad1689ea0/detection):

<img width="1105" alt="malwarepatrol warning on virustotal" src="https://user-images.githubusercontent.com/224922/29764972-9c9ae666-8bd9-11e7-9164-1c14d6f9b95a.PNG">

What's this?

**Comment by Openarl** [comment]
It's one out of 63, so it's a pretty clear false positive. They do happen from time to time; Baidu was flagging every version of the installer for ages (although that seems to have stopped now).

**Comment by lunaryorn** [comment]
Ah okay, thanks for the update.  I had Windows Defender complaining about that version as well a couple of days ago, and went with an older release which worked fine, so I checked Virus Total to see what's going on.

I'll try again with the next release and maybe wait for a signature update.


Thanks for the quick answer and also for this awesome tool 👍
