### ISSUE TITLE
Cospri's Will Assassins Garb error

### ISSUE THREAD

**Issue by Shiiike** [Openarl/PathOfBuilding#607]
Hi, love the program and fantastic job.

Cospri's Will Assassins Garb has poison cursed enemy on hit. I am carrying no other poison method and yet POB is saying 60% chance to poison. Shouldn't this either be no chance to poison or 100% chance to poison? The 60% chance doesn't make any sense to me. I've attached a capture of the poison box.

Cheers

![2017-08-28 18_22_01-path of buildingpoison](https://user-images.githubusercontent.com/31402686/29765281-e83a0a0e-8c1d-11e7-860e-1989ffcb1eb2.png)

**Comment by Openarl** [comment]
Cospri's Will was changed in 3.0 to only grant a 60% chance to poison against cursed enemies.

**Comment by Shiiike** [comment]
Okay, thank you.
Mine is pre 3.0 and still says poison on hit rather than the 60%. Does that mean mine is legacy and does poison 100% of the time or it does 60% but doesn't say it?

**Comment by Openarl** [comment]
Existing items from pre 3.0 will still grant 100% chance to poison, as the change was not retroactive.

**Comment by Shiiike** [comment]
Thanks so much; for speed of reply and info.
Cheers
