### ISSUE TITLE
Program not fitting window

### ISSUE THREAD

**Issue by C00P91** [Openarl/PathOfBuilding#608]
The top menu does not fit within the window. I have tried fixin it myself with resolution changes, but that did not work.
This causes the mouse to not fit in the screen aswell as it is off by the margin that the top of window that is missing.

Hope you can fix it.

Nice program!!

Best regards C00P91

**Comment by Openarl** [comment]
I suspect this is #527 again. If you're using Intel HD Graphics, make sure you're using version 15.46 of the driver, as older versions have a bug that causes this issue.

**Comment by C00P91** [comment]
I must say that i am amased at how much work you've put into this, and how fast you respond!!

Giant thumbs up man 👍 !!
I'll check out your surgestion and update if it does not fix.
