### ISSUE TITLE
Poison and weapon elemental damage with attacks seems wrong

### ISSUE THREAD

**Issue by Guillaume-Docquier** [Openarl/PathOfBuilding#612]
Hi guys,
I am fooling around to make a lightning poison build with the new gloves Volkuur's guidance (lightning damage can poison) and I found something wierd in the calculations.

Weapon elemental damage with weapons actually boost my poison damage. Here are some screenshots:  
## Calcs without WEDA
![without-wed](https://user-images.githubusercontent.com/16602209/29844282-bfdced3c-8cdc-11e7-8fda-e170830c5fac.png)
## Calcs with WEDA
![with-wed](https://user-images.githubusercontent.com/16602209/29844281-bfd7260e-8cdc-11e7-942c-37f50ff107e7.png)
## Gem setup
![weda](https://user-images.githubusercontent.com/16602209/29844283-bfdd79fa-8cdc-11e7-9e63-60d56dd34078.png)

I thought that in 3.0, only the base damage should affect the poison damage. However, as you can see in the last screenshot, WEDA does increase my poison damage. Is this a bug or my understading of poison is wrong?

**Comment by Openarl** [comment]
This is exactly how poison is supposed to work. 

The calculation for poison in 3.0 is very similar to the hit calculations, except that there are different modifiers applying; and as with the hit damage, the source damage for poison is affected not only by modifiers that apply to Poison or Chaos damage, but also by modifiers that affect the source damage type, and any other damage types that the source damage was converted from. This means that any portion of the Poison's base damage that is sourced from Elemental damage (Lightning in this case) will benefit from all modifiers to Elemental damage, such as Elemental Damage with Attacks.
