### ISSUE TITLE
Blasphemied curses aren't counted as reserved mana

### ISSUE THREAD

**Issue by gitdash** [Openarl/PathOfBuilding#62]

**Comment by Openarl** [comment]
I can't reproduce this. I have blasphemied curses in several builds and all are reserving mana correctly. Can you give any more details?

**Comment by gitdash** [comment]
Nevermind, it was a different issue.  Enlighten defaulted to level 10, which changed the mana reservation of a couple other auras. The resulting numbers just happened to be about the same as a missing curse aura.
