### ISSUE TITLE
Enfeeble + Blasphemy lowers damage

### ISSUE THREAD

**Issue by Fearwar123** [Openarl/PathOfBuilding#625]
Having Enfeeble enabled lowers the damage in the build.

![image](https://user-images.githubusercontent.com/31599053/30006594-fd733d90-90fb-11e7-8fe0-9869cbbc905f.png)

Build: **https://pastebin.com/LX07HiBC**

Cheers,
Fearwar

**Comment by Openarl** [comment]
You also have Projectile Weakness in the build, and you only have the ability to apply one curse to the enemy, so when Enfeeble is active it takes precedence (both by being a Blasphemy curse, and because it is before Projectile Weakness in the skill list).
