### ISSUE TITLE
Choir of the Storm amulet not applying crit damage buff

### ISSUE THREAD

**Issue by BlackAce21** [Openarl/PathOfBuilding#627]
Title basicly says it all, I was going through a build and noticed the crit multiplier wasn't changing for lightning damage in the calculations section when using this amulet. I don't know if it is being applied and just not being displayed as part of the calculation or not but I thought I would mention it.

::edit:: Also I am on version 1.4.62 for the sake of documenting xD

**Comment by Openarl** [comment]
The "Critical Strikes deal 50% increased Lightning Damage" modifier on legacy Choir of the Storm does not appear in the modifier lists in the Calcs tab, as those only show modifiers that apply to non-crits; but it does definitely apply.

On a side note, it seems I neglected to update that modifier on the 3.0 version of the item to remove the "Critical Strikes deal" qualifier. I'll fix that in the next update.
