### ISSUE TITLE
Serious graphical issues after latest Intel HD driver update

### ISSUE THREAD

**Issue by H4xoltl** [Openarl/PathOfBuilding#628]
Hi Openarl, 

I updated my Intel HD 620 driver on 05/09/17. Afterwords, PoB started having serious graphical issues
[Screenshot of the issue](https://imgur.com/Qwx38MO)

I am using Windows 10. Everything is up to date as possible. Could you look into it? I can't revert the driver update unfortunately :(

**Comment by locodicegr** [comment]
Run DDU and reinstall the latest driver by manual

**Comment by Openarl** [comment]
To what driver version did you update? That issue is only known to occur with older versions of the Intel HD Graphics driver, and is not known to occur with the [15.46](https://downloadcenter.intel.com/download/27058/Graphics-Intel-Graphics-Driver-for-Windows-15-46-) version.

**Comment by H4xoltl** [comment]
Intel High-Definition (HD) Graphics Driver | 21.20.16.4664 Rev.B | 247.3 MB | Jun 23, 2017

**Comment by H4xoltl** [comment]
I installed an older version of the driver (21.20.16.4590 Rev.B) and it fixed the problem

**Comment by Openarl** [comment]
I'm still not sure why the problem occurs; obviously it's a driver bug that's at fault, but I don't know how the program manages to trigger it, and I don't have access to any system on which the bug occurs, which makes it very difficult to attempt any fix. Anyway, this duplicates #527, so discussion should continue there.
