### ISSUE TITLE
Arohongui delivering wrong damage output

### ISSUE THREAD

**Issue by TheHaensel** [Openarl/PathOfBuilding#629]
Hey,
I just imported a pastebin RF-build and noticed some odd damage values on the ascendancy nodes for marauder.

When chosing a lower ascendancy point (like the one between Hinekora and Ngamahu) with **10% increased fire damage** the dot-damage output is raised by **+1.6%** with my build. (shown on the stat difference window)

When you chose Arohongui with **16% increased phys and fire damage**, the dot-damage output is raised by **+16%**. (also shown on the stat difference window)
The lower point before Aronhongui only gives regen and totem placement speed, so nothing that affects damage output.

Is this a mixup between "increased" and "more"?

**Comment by TheHaensel** [comment]
![pob inc damage 10](https://user-images.githubusercontent.com/31728719/30158403-732d2eda-93c5-11e7-90ea-6fca7c74c2a0.png)
![pob inc damage 16](https://user-images.githubusercontent.com/31728719/30158405-76a157b2-93c5-11e7-9bf5-280c2ffc58ad.png)

**Comment by Openarl** [comment]
Arohongui does not directly modify the damage that you deal, and is not additive with modifiers like "10% increased Fire Damage". It states "Enemies near your Totems take 16% increased Physical and Fire Damage", which instead modifies all incoming damage that those enemies take, and is only additive with other such modifiers (such as Intimidate, which causes enemies to take 10% increased Damage); so if there are no other modifiers present, then Arohongui will indeed cause you to deal 16% more Physical and Fire Damage.
