### ISSUE TITLE
SRS

### ISSUE THREAD

**Issue by MouldyTaco** [Openarl/PathOfBuilding#63]
SRS is not counted as an active skill by the tool.

Also, it will not allow any skill gem to support SRS.

**Comment by Openarl** [comment]
The program doesn't support minions yet (other than the buffs granted by golems). Minion stat calculations (particularly damage) are rather tricky to do, and I haven't had the time to add them yet.

**Comment by Openarl** [comment]
Oh, forgot to close this one. SRS support was of course added in 1.4.0.
