### ISSUE TITLE
any way for adding support gems to death's oath

### ISSUE THREAD

**Issue by ateam1122** [Openarl/PathOfBuilding#630]
first: thank you all for the great program 
today i wanted to do a build around death's oath body armor and when i tried to add any gem to link with death aura there is no way of doing it ( i just wanted to see the effect of the gems socked  in the body armor on the death aura but it is not working please do some thing about this

**Comment by Openarl** [comment]
Create a socket group, then select "Body Armour" from the "Socketed In" dropdown, then add the support gems to the group. All skills granted by items work the same way.
