### ISSUE TITLE
Mjolner / Mjölner Problems

### ISSUE THREAD

**Issue by livejamie** [Openarl/PathOfBuilding#631]
Trying to do some Calculations but when I'm importing Mjolners from poe.trade POB gets really confused

![image](https://user-images.githubusercontent.com/49513/30187440-34e2958c-93ef-11e7-9100-564987e6d891.png)
![image](https://user-images.githubusercontent.com/49513/30187441-3628120a-93ef-11e7-984b-65976dd251a4.png)

It doesn't think I have a weapon equipped. The Mjolner within POB seems different from the one in-game as well.

Build: https://pastebin.com/ZuV09TGJ

**Comment by Openarl** [comment]
Sorry for taking so long to get to this. This is mainly the fault of the script or extension you used to export the item from poe.trade, as it hasn't output the item in the correct format. That being said, one of the stats on Mjolner wasn't being recognised correctly, but that has already been fixed in a previous update.

**Comment by livejamie** [comment]
Is it something worth mentioning to @fikal to fix?

**Comment by Openarl** [comment]
Aye, if it is still occurring.

**Comment by fikal** [comment]
I'll look into this.

**Comment by fikal** [comment]
@livejamie I just tried this with the latest build of my tool on github and everything seems to be working.  This is what I am seeing when attempting to replicate your second image.

https://i.imgur.com/ZWklmdd.png

Check the latest version and use google chrome and let me know!

**Comment by livejamie** [comment]
Okay looks like we're good to go, boys.

Sorry for bugging you so much @fikal I hope I'm not the only one who uses your tool it's very helpful.

**Comment by fikal** [comment]
No problem @livejamie !  Spread the word about it ha.
