### ISSUE TITLE
Point blank node it not taken into consideration

### ISSUE THREAD

**Issue by ffogell** [Openarl/PathOfBuilding#633]
I'M doing a Chin Sol Shrapnel Trapper and the point blank node isnt not calculated into the dps.

When I equip the Chin Sol , I see the close range option in the configuration but selecting/unselecting point blank does not affect my dps at all.

**Comment by Mizzajl** [comment]
For Point Blank you have to set the "Projectile Travel Distance" in the configuration.
Point blank deals maximum damage at distance 10 or lower.
Chin Sol close range is 20 or lower.
and I think there are situations where the enemy is at close range but the projectile have travelled much further, like when using skills like tornado shot or with things like chaining/returning projectiles for example.

**Comment by ffogell** [comment]
Oh ok , I see I thought that close I selected close range I would include it in the dps, but youa re right setting distance to <10 worked.
