### ISSUE TITLE
Possible Skeleton Mage Inconsistancy

### ISSUE THREAD

**Issue by NigOlBigger** [Openarl/PathOfBuilding#637]
Was wondering if you could check Skeleton Mage damage, as there seems to possibly be an inconstancy in their DPS until they hit level 20. Depending on the element, their base damage from gem level 19-20 increases by about 3-5 times the amount. I don't know their actual damage numbers, but based on the pretty normal scaling that melee skeletons have, this doesn't seem right.
![inconsistancies ree](https://user-images.githubusercontent.com/31948946/30414911-00d8048c-9969-11e7-8460-e13edeba8552.png)

**Comment by Openarl** [comment]
Duplicates #567.
