### ISSUE TITLE
Fight for Survival limit not working correctly

### ISSUE THREAD

**Issue by TZer0** [Openarl/PathOfBuilding#639]
Using 1.4.62, I configured three Fight for Survival.

![Image of bug](https://i.imgur.com/cRKgowE.png)

You're only supposed to be able to use two.

**Comment by Openarl** [comment]
The program does not enforce limits on jewels; such things generally aren't enforced unless there's a practical benefit to doing so.

**Comment by TZer0** [comment]
Suggestion: could it be a toggle (that is by default on)?
Pratical use: you may forget that a given jewel has a limit while making a build and this would be a nice way to prevent someone from making a miscalculation.
