### ISSUE TITLE
[Feature Request] Minion and Totem Elemental Resistance with Spell Totem

### ISSUE THREAD

**Issue by OSwoboda** [Openarl/PathOfBuilding#64]
I wanted to add Minion and Totem Elemental Resistance Support to a Righteous Fire Totem build and the program says that the gem is unsupported.

**Comment by dein0s** [comment]
So, why do you consider this is a bug if it clearly says that "%gemname% is unsupported"?
Not implemented yet, TBD.

**Comment by Openarl** [comment]
The program doesn't generally support minion skills/supports, however since this one applies to totems too I'll see if I can enable support for it. The program doesn't yet calculate totem resistances, and won't do so if I enable it, but you'll at least get the mana cost multiplier.

**Comment by OSwoboda** [comment]
@dein0s I thought the gem has no skill to support, but now I know that minions in general are unsupported from the program, makes sense.

@Openarl The important part of this gem is the new multiplier it gets, for that it would be nice to support it.

**Comment by Openarl** [comment]
Yeah I'll try and put that in too, although until the patch is out I won't have the exact values of the multiplier for each gem level. I _think_ I know how it'll scale though (probably the same as the multiplier on Less Duration).

**Comment by Openarl** [comment]
It'll be enabled in the next update, including the new elemental damage multiplier.
