### ISSUE TITLE
Damage on full life support and ranged skills

### ISSUE THREAD

**Issue by mintjustin** [Openarl/PathOfBuilding#646]
Damage on full life support now works with ranged skills. It doesn't seem to work with the current PoB.

**Comment by Openarl** [comment]
It does work in PoB, but you need to enable the "Are you always on Full Life?" option in the Configuration tab for it to take effect. Note that like most options, it doesn't appear unless enabling it would have some effect, which in this case requires linking Damage on Full Life to your main skill.
