### ISSUE TITLE
[Improvement/Bug?] Configuration: "Do you have a Flask active?"

### ISSUE THREAD

**Issue by nevets1219** [Openarl/PathOfBuilding#649]
Using Scion with Raider ascendancy, you have the option to enable/disable flask in "Configuration". However, if you don't pick Raider ascendancy, you do not have this option.

For example, Dying Sun adds to your maximum fire resistances, it has non-DPS value as well.

Version: 1.4.63

**Comment by Openarl** [comment]
That option only exists to allow "while using a Flask" modifiers on non-flask items and passive skills to apply without having to actually activate a flask in the Items tab. If you're not seeing that option, then you have no such modifiers in your build, so enabling it would have no effect.

**Comment by nevets1219** [comment]
When you enable this, you can see the benefits of flask that has nothing to do with "while using flask" modifier (e.g. Dying Sun providing maximum resistances). For builds that don't contain "while using flask" modifier, you cannot see this which makes comparing builds non-obvious.

**Comment by Openarl** [comment]
I'll say again, that option has no effect whatsoever on your Flasks, as enabling a Flask in the Items tab automatically turns that option on. You do not need to see or use that option unless you have modifiers on other items or passive skills that depend on having a Flask active.

**Comment by nevets1219** [comment]
I see what you mean now, thanks for clarifying.
