### ISSUE TITLE
Barrage dps

### ISSUE THREAD

**Issue by Geekachuqt** [Openarl/PathOfBuilding#65]
This is more of a feature request, but barrage currently only displays the damage per hit, and not the damage per second. It would be nice if you could include a calculation that shows the dps, factoring in the amount of +additional arrows you have on your gear! Perhaps even a dropdown menu that shows dps depending on how many arrows hit the target.

**Comment by Openarl** [comment]
A bit delayed (!), but the next update will add a skill part to simulate all arrows hitting the target.
