### ISSUE TITLE
problem with noxious strike skill effect duration

### ISSUE THREAD

**Issue by hgfedcba** [Openarl/PathOfBuilding#650]
There are multiple problems with the skill effect duration you should get from killing a maimed enemy while having noxious strike.

Here is the build i noticed the problem:
https://pastebin.com/QApAF9yu
I have activated "is the enemy maimed" and "have you killed recently" and now it does calculate the increased skill effect duration for viper strike, but if you mouse over poison duration and look at "player modifiers" they sum up to 117%. Above that you see that the "duration modifier" correctly uses the factor 2.47, so the problem seems to be that the buff is not displayed.

However it is slightly more complicated as for example my immortal call does not benefit from the increased skill effect duration from noxious strike at all even though it should.

Summary:
Viper strike calculates correctly but doesn't show the modifier.
Other duration skills don't use the modifier at all.
Spectral throw correctly doesn't use it as. (I only mention this here to show I am aware of that, this does not(!) solve my problem)

**Comment by Openarl** [comment]
Modifiers to Skill Effect Duration cannot appear in the player modifiers list for Poison w/ Viper Strike, regardless of source; generic Skill Effect Duration modifiers such as Exceptional Performance will also not appear. This is a limitation of the breakdown modifier list code, as the list of stats to be shown in a given breakdown is fixed. As it is only a display issue, and as there are only a few edge cases like this where that limitation is problematic, it is unlikely to be fixed any time soon.

That duration modifier is definitely applying to Immortal Call though:
![noxious immortal](https://user-images.githubusercontent.com/19189971/30799737-38097c5e-a221-11e7-9cc7-bda51aef15c0.png)

**Comment by hgfedcba** [comment]
I just had a look and you are right. I am very sure it didn't show up yesterday, but today it does. Maybe I just had to reload the build...

It still does not show up for temporal chains, but neither does the increased duration support gem. Is that intended?

**Comment by Openarl** [comment]
Well, the duration for Temporal Chains wasn't showing at all, as it was missing the necessary flag. I've fixed that in 1.4.64 though, so it should work fine now.
