### ISSUE TITLE
Chieftain, Tukohama, War's Herald

### ISSUE THREAD

**Issue by Loukie** [Openarl/PathOfBuilding#656]
So this is more a question than an issue on Hinekora, Death's Fury is stats that 1% Fire Damage Leech as life right? So looking at Tukohama, War's Herald it stats that your totems Reflect 15% of their life as fire damage is the damage and leech calculated as part of DPS in POB and is it possible to see in POB how much life our totems have and how much damage they reflect, please.

Hopefully, you understand what I'm trying to say or ask? With that said thx for all the hard work.

**Comment by dein0s** [comment]
1. `Tukohama, War's Herald` is not yet supported (stats that are not currently supported by PoB are colored with red)
![hukohama](https://i.imgur.com/YTp0NSn.png)
2. You can check totem's life in cacls tab
![totem_life](https://i.imgur.com/fUrdtzV.png)

**Comment by Loukie** [comment]
Thank you so much for the reply and for showing me where totem life is ^^
