### ISSUE TITLE
[issue] poison & Increased Duration Support

### ISSUE THREAD

**Issue by 88Stach** [Openarl/PathOfBuilding#66]
Clean character.
P.Damage bow (in my case).
Barrage [enabled]
Poison support GEM [enabled]
###
case 1:
{
Increased Duration Support GEM [enabled]
poison DPS: 12
Total Damage per Poison: 24
}
case 2:
{
Increased Duration Support GEM [disabled]
poison DPS: 12
Total Damage per Poison: 24
}
[](http://pathofexile.gamepedia.com/Poison)

in other words.... calculation is not working

**Comment by Openarl** [comment]
Not a bug. Barrage doesn't have the duration tag, and therefore cannot be supported by Increased Duration; so there's no way it can affect the poison duration.

**Comment by 88Stach** [comment]
Well...
Im just pointing that **Increased Duration Support GEM** is not working on poison while
Increased duration nodes are working on poison calculations
 (i did not mean barrage)

**Comment by Openarl** [comment]
I've tested this, and the Increased Duration gem is definitely increasing the poison duration, provided that the skill is able to be supported by it. Is there a specific skill setup where you're experiencing otherwise?

**Comment by 88Stach** [comment]
There must be something wrong in my way of thinking then.
I always thought that poison support gem was adding duration to the skill.
Then My bad sorry :)

**Comment by Openarl** [comment]
It's fine! You've emerged enlightened, so it was hardly a waste :)
