### ISSUE TITLE
Access Violation on startup

### ISSUE THREAD

**Issue by Seriousnes** [Openarl/PathOfBuilding#660]
With the update to version 1.4.64, if PoB is closed while window is on the non-primary monitor, PoB crashes with an access violation (see attached image)
![crit error](https://user-images.githubusercontent.com/6109344/31103799-ba17c0bc-a824-11e7-9c2c-4bef99000443.jpg)

**Comment by Openarl** [comment]
Were you experiencing #336 before 1.4.64? If so, then we'll continue in there, as this is almost certainly related.

**Comment by ranky** [comment]
Nope, I have not experienced any of the issues outlined in #336.

I can provide more details of my pc setup tomorrow when I'm back at work, however iirc I have my main monitor using an ATI graphics card and second monitor using on-board intel graphics. PC is on Windows 10.

I have no issues moving or resizing PoB between monitors, the startup error only occurs if the application was closed on the second monitor.

Additionally removing the contents of Launch.cfg didn't help, but deleting Settings.xml did seem to fix the issue (e.g. close PoB > delete Settings.xml > open PoB > same AV > open PoB again > opens without any problems)

**Comment by Openarl** [comment]
That is quite unusual. As far as I can tell, the crash is occurring within your graphics driver during OpenGL initialisation; I have no idea why, though, and the only thing I can really suggest at the moment is updating your drivers.

**Comment by Jinnai** [comment]
I'm having exactly the same issue. I tried upgrade my drivers but it didn't solve it.
