### ISSUE TITLE
custom items from PoE with "c-C" copy always import +20% quality, ignoring the text

### ISSUE THREAD

**Issue by slippycheeze** [Openarl/PathOfBuilding#661]
I've found the "custom" item comparison invaluable to figuring out what difference an item will make compared to my current items.  The one pain point is that when I use the copied text from the game, the item quality is ignored.  

At max level this isn't a big deal, since I'll 20 percent anything I use, but at lower levels it's vaguely annoying because I'm going to likely replace it soon enough...

Example item that imports at +20 quality, instead of +11:

```
Rarity: Rare
Bramble Barrage
Long Bow
--------
Bow
Physical Damage: 6-25
Elemental Damage: 9-16 (augmented), 1-6 (augmented)
Critical Strike Chance: 6.00%
Attacks per Second: 1.37 (augmented)
--------
Requirements:
Level: 10
Dex: 38
--------
Sockets: B B 
--------
Item Level: 15
--------
Adds 9 to 16 Fire Damage
Adds 1 to 6 Lightning Damage
5% increased Attack Speed
+12% to Lightning Resistance
```

Example of item with no quality that also imports at +20:

```
Rarity: Rare
Blood Curtain
Buckskin Tunic
--------
Evasion Rating: 215 (augmented)
--------
Requirements:
Level: 22
Dex: 53
--------
Sockets: G-G-G 
--------
Item Level: 17
--------
+12 to Dexterity
22% increased Evasion Rating
+12 to maximum Life
1.6 Life Regenerated per second
+13% to Lightning Resistance
Reflects 2 Physical Damage to Melee Attackers
```

**Comment by Openarl** [comment]
That is intentional, as it can be quite useful when comparing items on high level characters. The program has limited support for low level characters as it is primarily designed for planning endgame builds; in the event that I get around to adding some sort of "low level" mode I will allow that feature to be disabled though.
