### ISSUE TITLE
wishlist: create custom item from clipboard

### ISSUE THREAD

**Issue by slippycheeze** [Openarl/PathOfBuilding#662]
It's super-easy to grab stats from an item in-game (or on poe.trade) to the clipboard.  It would be a convenience to have a "custom item from clipboard" button, or to have "custom item" default to pulling in the current clipboard content, and having it highlighted.  Not much, but it avoids an extra control-V to paste. :)

**Comment by Openarl** [comment]
Are you aware that you actually don't need to click "Create custom..." to import from the clipboard? Just pressing Ctrl+V while in the Items tab will work.

**Comment by slippycheeze** [comment]
I am, in fact, now aware of that fact, and came here to close the ticket.  :)
