### ISSUE TITLE
Blasphemy Problem

### ISSUE THREAD

**Issue by RussianSerbim** [Openarl/PathOfBuilding#665]
Hi Openarl Staff,

A problem that I noticed, what Blasphemy Gem not transform any CURSE in AURA in CALCS. But it continues as CURSE. If u can fix this, we would be grateful.
Thank you very much in advance!

**Comment by calmchaos** [comment]
This person is probably talking about how curses supported by Blasphemy still show duration stats and modifiers in the "Calcs" -> "Skill type-specific Stats" box.

**Comment by RussianSerbim** [comment]
@calmchaos 
is not this, look the images:
![curse](https://user-images.githubusercontent.com/32575914/31309287-3785cec6-ab5a-11e7-9742-fcd944eaae14.jpg)
![calcs](https://user-images.githubusercontent.com/32575914/31309291-44bd682e-ab5a-11e7-95f7-5170588591bb.jpg)
The Vulnerability only appears if I put a curse more, in tree passives or corrupted amulet

**Comment by Openarl** [comment]
Curses that are linked to Blasphemy are still Curses, and must obey the Curse limit. Path of Building's behaviour in this case is correct.
