### ISSUE TITLE
Larger than default window: when PoB starts, widgets don't resize correctl

### ISSUE THREAD

**Issue by slippycheeze** [Openarl/PathOfBuilding#667]
Windows 10, updated, latest PoB.

When I start up PoB it remembers the larger-than-default size that I have it at, but the entire widget set (left bar, central display, controls just below the title bar) all squish into the bottom left two thirds.

I'd guess that it resizes the window at some point during startup, but doesn't trigger a relayout.  Easily fixed by resizing the window a tiny bit.

**Comment by Openarl** [comment]
Fixed in the next update.
