### ISSUE TITLE
Dark Pact Totem DPS calculation 

### ISSUE THREAD

**Issue by Devilbane** [Openarl/PathOfBuilding#682]
Dark pact totem includes the "cast by  player" damage bonus, which is not correct as far as I know.

**Comment by Lothrik** [comment]
If a totem spends its own life on Dark Pact, it gets all the same benefits a player would for spending their own life on Dark Pact. You're just confused about how totems work.

**Comment by i3igpete** [comment]
Dark Pact totems receive the damage bonus.  Please see citation on the DP wiki page.

**Comment by Openarl** [comment]
As mentioned, Totem-case Dark Pact does indeed gain the damage bonus.
