### ISSUE TITLE
[Bug] Creating near infinite amounts of folders

### ISSUE THREAD

**Issue by Epsynus** [Openarl/PathOfBuilding#696]
PoB version: 1.4.64
OS: Windows 10 64-bit.

I was reorganizing my folders and I accidentally dropped the same folder on top of itself and I got the error: "Couldn't delete 'C:\Users\Epsynus\Documents/Path of Building/Builds 3.0 builds/HC Viable/Duelist' : Directory not empty"
When I hit Ok. It repeats the message but adds another Duelist:
"Couldn't delete 'C:\Users\Epsynus\Documents/Path of Building/Builds 3.0 builds/HC Viable/Duelist/Duelist' : Directory not empty"

The more I hit the more directories it create!
Going through File explorer my current Duelist folder looks like:
"C:\Users\Epsynus\Documents\path of building\Builds\3.0 builds\HC Viable\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist\Duelist"

I can repeat this as much as I want by just dropping another folder on top of itself and hitting the Ok button a ton.

It isn't that horrible of a bug since all you need to do is just force close the program and not drop a folder on itself in the first place. But thought I'd let you know.

**Comment by Openarl** [comment]
Fixed in the next update.
