### ISSUE TITLE
Trickster Shade Form attack/cast speed not supported

### ISSUE THREAD

**Issue by teuneboon** [Openarl/PathOfBuilding#698]
I'd love a checkbox for "Energy shield started regeneration recently" so I can see my attack/cast time with Shade Form's bonus. I also noticed that #671 for Walk the Aether support wasn't merged yet, which would solve the other issue I have with Trickster.

**Comment by eps1lon** [comment]
It might be better to add generic support for `if {condition} recently`. Hopefully it is humanyl readable if we just just display this condition next to the checkbox. 

That way we don't have to manage every new recently condition. Gonna track progress in eps1lon/PathOfBuilding#1

#671 is not the only PR not merged at the moment. @Openarl might be on a longer hiatus.

**Comment by Openarl** [comment]
Sorry about the delay on this; I was just reviewing the configuration options and realised that this one was still missing. It'll be coming in the next update.
