### ISSUE TITLE
Is this Project Still alive?

### ISSUE THREAD

**Issue by locodicegr** [Openarl/PathOfBuilding#699]
Just checking...3.1 Expansion Is coming.

**Comment by jaaqov** [comment]
Dude obv. it is, Openarl always updated as soon as he got the info/ data

**Comment by locodicegr** [comment]
We will see.

**Comment by Epsynus** [comment]
I doubt it sadly.

**Comment by Openarl** [comment]
I suppose this is a good place to pop in and say that yes, I am still around, and I am updating PoB (albeit slowly). I started a new job recently (~2 months ago) which has severely depleted my free time, and I haven't been able to dedicate much of what I have left to this project. 

However, with the new expansion coming I will be prioritising updates for the new changes. The next update will at minimum include the new passive tree changes, and maybe a few other goodies, and should be out sometime in the next few hours.

The cash I get from Patreon by the way is quite trivial compared to what I get paid for my job. It has only ever been intended as a way for users to show appreciation for the work I've done, as it is highly unlikely to ever grow to the point of becoming a meaningful income source.
