### ISSUE TITLE
Item Builder sizing issues

### ISSUE THREAD

**Issue by mattgilene** [Openarl/PathOfBuilding#7]
http://imgur.com/a/MnkWc

Sizing issue causing the user to not be able to slide the slider that modifies the value of the stat to its rightmost position. Only able to slide about 1/2-2/3 of the way.

**Comment by Openarl** [comment]
I am aware that the items tab is too wide for lower resolutions. There should be a fix coming very soon.
Sorry about that, and thanks for the report!

**Comment by Openarl** [comment]
Ok resolved this now. If the items tab won't fit on your screen there'll be a scroll bar shown.
