### ISSUE TITLE
[Feature Request] Multiple Traps Overlapping Damage Option

### ISSUE THREAD

**Issue by Belodri** [Openarl/PathOfBuilding#700]
As someone who's playing a lot of trappers a feature I'd really like to see would be adding an option to the Configuration tab where you can set a number for how many of the thrown traps hit the same enemy.
This option would only show up when a trap skill or a trap support is used.
This could be added for mines and totems as well.

Also a general overlap damage option would be nice but I'm not sure if this is possible.
Bladefall is a great example of a skill that could really use this feature as the average hit value shown is pretty useless when multiple waves of the same cast overlap.

Would be amazing if you could implement this!
Keep up the great work guys!

**Comment by eps1lon** [comment]
How would you know how many traps overlap a target? Is the spread radius of minefield or multiple traps known? Then I could see a radius tool being useful which displays overlapping areas. 

Otherwise it's just a simple `times x` calculation, isn't it?
