### ISSUE TITLE
Holding shift does not change tree stats

### ISSUE THREAD

**Issue by stevenolsen** [Openarl/PathOfBuilding#701]
If you manually path to part of the skill tree with shift, then let go of shift, if a shorter path exists the tooltip will not update with the new values. Furthermore, if you remove your mouse off of the node, you have to touch a different node before the node you wanted to see refreshes with proper values.

[Demonstration Video](https://streamable.com/lcyk6)

**Comment by Openarl** [comment]
Fixed in the next update.
