### ISSUE TITLE
[Minor] Issue with searching using "-" (hyphen)

### ISSUE THREAD

**Issue by twiz-ahk** [Openarl/PathOfBuilding#708]
Came across an odd issue while trying to search for "non-Curse Auras". Searching for "non-" highlights almost all nodes, while "non-c" highlights a few seemingly random ones including Chaos Inoculation.
![image](https://user-images.githubusercontent.com/2575677/33522188-f9ab0d2e-d7b3-11e7-8020-28de774e4e92.png)

However, searching for "-", "non--curse", and "non\\--curse" all yield proper results, which made me thing it was a parsing\escaping issue, but "non\\-curse" does not.
(Search strings above are all **visually** correct and take GitHub Markdown into consideration.)

**Comment by Openarl** [comment]
This is technically working as intended. The passive tree search field supports [Lua patterns](http://www.lua.org/manual/5.1/manual.html#5.4.1), which are a limited form of regex, in which "-" has a special meaning (match the shortest sequence of 0 or more of the preceding letter, in this case "n").

To be fair, that support isn't documented anywhere in the program or elsewhere, and you'd have a devil of a time figuring it out on your own. I do someday intend to add some kind of note in the program, and maybe offer a toggle and some basic instructions on using the patterns, but I don't really have time for that at the moment.

**Comment by twiz-ahk** [comment]
Thanks for the info!
The workaround for the issue posted here would be to search for "non%-curse", as % is the escape character in Lua.
