### ISSUE TITLE
Rename bug with capitalization

### ISSUE THREAD

**Issue by Niftator** [Openarl/PathOfBuilding#709]
In version 1.4.64, if you enter a name for your build without the intended capitalization, you cannot use the rename function inside PoB to change it.

To reproduce:
- save build with name starting with a lower-case letter
- back out to main menu
- click 'rename'
- attempt to capitalize the first character

Expected behavior: new name recognized as changed, allows saving
Actual behavior: checker doesn't recognize capitalization as a change and keeps save button disabled

workaround: manually rename xml file using a file manager

**Comment by eps1lon** [comment]
This is probably because the name of build is equal to the file name. Windows file system is case-insensitive and therefore does not recognize a change. But since the files are case-preserving this should be checked.

**Comment by Openarl** [comment]
Hmm. I deliberately made the save button ignore case differences for various reasons, but on reflection it probably is better to allow it for the occasional instance where it is useful. It'll be in the next update.
