### ISSUE TITLE
[Feature Request] Show Stat requirements for skill setup

### ISSUE THREAD

**Issue by zocke1r** [Openarl/PathOfBuilding#71]
Considering that it is possible to setup up your skill gems being able to see the stat requirements that those skill bring with them would be really helpful for planning the build, as you could see if you should get some more stat from the tree or how hard you have to invest into stats on gear

**Comment by Openarl** [comment]
It's on the TODO list. The program doesn't yet have the data for skill gem stat requirements, and it doesn't seem to be in the game files, so I have to figure that out first.

**Comment by Openarl** [comment]
It's been a long time coming, but the next update finally adds level and attribute requirement displays for gems and items.
