### ISSUE TITLE
Blade Flurry + Ruthless no longer works

### ISSUE THREAD

**Issue by corosou** [Openarl/PathOfBuilding#717]
Ruthless is still being shown as a valid link option for BF, which is a "Channeling" skill.

![image](https://user-images.githubusercontent.com/28074748/33728638-0c819df8-db49-11e7-988c-1a6c1bacb18e.png)
![image](https://user-images.githubusercontent.com/28074748/33728716-4d076e66-db49-11e7-815d-cf34fb1d9187.png)
![image](https://user-images.githubusercontent.com/28074748/33728793-9d860b54-db49-11e7-8a5f-3ebcf56e5d44.png)

**Comment by Openarl** [comment]
None of the skill gems have been updated yet; I need to get the patch data and re-export the skills in order to change anything.
