### ISSUE TITLE
Unable to import tree

### ISSUE THREAD

**Issue by sbfussy** [Openarl/PathOfBuilding#719]
I am unable to input any passive trees as of now. The error I get is:

Invalid tree link (unknown version number '2027597144')

I have tried multiple builds (all supplied by the same friend) and none of them work. We are both on the most recent version (1.4.65) and have been since starting these builds.

**Comment by Openarl** [comment]
That error results from attempting to input a build sharing code into the Import Tree dialog. That dialog only works for passive tree links (which start with "https://www.pathofexile.com/passive-skill-tree/"); build sharing codes (which usually start with "eNr") need to be input in the Build Sharing section of the Import/Export tab.
