### ISSUE TITLE
Issues Updating to new version(1.4.65)

### ISSUE THREAD

**Issue by Zack-J** [Openarl/PathOfBuilding#722]
here is the error on the launcher
https://imgur.com/gallery/pyXvoum
i don't know what happened but i don't have the 3.1 content.

**Comment by Zack-J** [comment]
also, i tried uninstalling/reinstalling, restarting POB and my pc. nothing fixed it

**Comment by Zack-J** [comment]
I actually have the new passives tree, but under the config tab, there are only the 3.0 and 2.6 versions, not 3,1

**Comment by eps1lon** [comment]
This is intentional as described in #712 

> This is intentional. The game version labels aren't intended to reflect the exact versions of the data used (otherwise it'd say 2.6.3 instead of 2.6), but rather serve to distinguish the... eras? of the game that the options represent. The changes with 3.1 weren't significant enough to justify adding a 3rd option, so 3.1 will fall under the "3.0" era.

But since this came up again it might be better to add a visible description of the purpose of this version string or use different version strings to avoid further confusion.

**Comment by Openarl** [comment]
Those error messages are fairly harmless, and will stop appearing once 3.1 goes live.

Anyway, regarding the game version number, even if I had changed it already it would just make people think that all the 3.1 content is present, when in fact I can't add half of it until I get the patch data. So it isn't a good indication of what version of data you have.
