### ISSUE TITLE
Huge spikes when trying to use PoB + picture with load screen

### ISSUE THREAD

**Issue by Dunkdk** [Openarl/PathOfBuilding#723]
Hello Openarl,

I really appreciate your work, and understand the amount of work you have atm. I want to address a bug I experience after installing the program. I get huge delay/spikes when trying to use the talent tree, like it's still loading. When hovering above a node it takes around 2-3 seconds to load the description.

I tried running it as w8(using w10 usually) and as admin, no changes.
Picture of loading screen: https://imgur.com/a/0GfG7

If you need any other information, that I can provide please let me know

**Comment by Openarl** [comment]
Those error messages in the loading screen regarding missing files are entirely unrelated.

Judging from the other messages there however, I must assume that your display driver is either absent, out of date, or corrupted, as the messages (particularly the maximum texture size of 1024x1024) indicate a total absence of any modern graphics capabilities on your system; in the absence of which the program cannot be expected to run correctly.

**Comment by Dunkdk** [comment]
Awesome! It works now, there was indeed a driver update laying. Still think it's wierd tho, updated my GPU last time 1 month ago o.O

Anyways it's smooth as it should be now and I will close the Topic!
