### ISSUE TITLE
PoB 1.4.65 import error

### ISSUE THREAD

**Issue by DaxxTrias** [Openarl/PathOfBuilding#724]
I'm unsure if this is related to the maintenance currently going on, but since the websites working I assume that isn't the case.

Upon trying to import a character its throwing an error. I can choose to ignore the error and it claims success, but nothing actually imports. Restarting app does not fix it.

Including screencap

![pob import bug](https://user-images.githubusercontent.com/1401032/33779860-3895fbc0-dc14-11e7-89dd-b38580d8be2b.png)

**Comment by Nunzaman** [comment]
I am having the same issue.

**Comment by aydjay** [comment]
Importing character with account name: d347hm4n

![image](https://user-images.githubusercontent.com/9460838/33787241-53bda5ec-dc64-11e7-9ac7-1ecc6384c7e5.png)

Same issue as above users. It happened when importing Items and skills

**Comment by Openarl** [comment]
Fixed in the next update.

**Comment by DaxxTrias** [comment]
Thank you for the fix

**Comment by aydjay** [comment]
Fixed for me thanks!
