### ISSUE TITLE
Incorrect Game version under Build configuration.

### ISSUE THREAD

**Issue by Hixxie** [Openarl/PathOfBuilding#726]
Needs to be updated for builds from 3.0 to 3.1
Would like separate version numbers.
This has some slight changes as Vaal Pact has moved and very few nodes removed.

**Comment by Openarl** [comment]
The changes in 3.1 aren't nearly significant enough to justify the effort required to set up a new game version, and as I've explained before, the game version number isn't intended to reflect the exact version of the data used, but merely serves to indicate the "era" for which the build is made (post vs pre 3,0).
