### ISSUE TITLE
Runtime error in Launch.lua

### ISSUE THREAD

**Issue by thehawkguy** [Openarl/PathOfBuilding#728]
Hey thank you for this great tool.

With the new league start I wanted to start using PoB again.

But when launching I get a runtime error.

> --- SCRIPT ERROR ---
> Runtime error in 'C:\Users\username\Documents\pob\Launch.lua':
> UpdateCheck.lua:9: module 'xml' not found:
> 	no field package.preload['xml']
> 	no file '.\xml.lua'
> 	no file '.\xml\init.lua'
> 	no file 'C:\Users\Public\Lua\LuaRocks\share\lua\5.1\xml.lua'
> 	no file 'C:\Users\Public\Lua\LuaRocks\share\lua\5.1\xml\init.lua'
> 	no file '.\xml.dll'
> 	no file 'C:\Users\Public\Lua\LuaRocks\lib\lua\5.1\xml.dll'
> stack traceback:
> 	[C]: in function 'require'
> 	UpdateCheck.lua:9: in main chunk
> 	[C]: in function 'LoadModule'
> 	C:\Users\username\Documents\pob\Launch.lua:30: in function <C:\Users\username\Documents\pob\Launch.lua:15>

A new installation doesn't help.

I suspect it might have something to do with me installing luarocks recently. But I am really not that much experienced in these sort of things.

Help would be appreciated.

**Comment by Openarl** [comment]
It is indeed your LuaRocks installation that is interfering. You need to add the following to your LUA_PATH environment variable:
`!\lua\?.lua;`

**Comment by thehawkguy** [comment]
Thank you very much for helping me out even though I caused this myself and wasn't an issue with your program
