### ISSUE TITLE
[Bug] v1.4.69 Passive stat gains not calculated with level change

### ISSUE THREAD

**Issue by TheVoiceofExile** [Openarl/PathOfBuilding#730]
I noticed that when changing your level that the passive stats (str, dex, int) gained per level are no longer added to the total. So a blank character of some class that is level 100 has the same str, dex, and int as another blank character of the same class that is level 1.

**Comment by Openarl** [comment]
Uhh... you don't gain stats per level in Path of Exile. So this is working as intended.

Plus I certainly wouldn't miss something so obvious :/
