### ISSUE TITLE
[Feature Request] Abyss Jewels

### ISSUE THREAD

**Issue by Chainezo** [Openarl/PathOfBuilding#731]
It would be nice to add abyss jewel support
sites like https://poecraft.com/jewels already have the mods, so it shouldn't be too hard to add them

**Comment by Openarl** [comment]
Please have patience. The league has been live for less than 2 days, and in between playing sessions I haven't had nearly enough time to implement all the new mechanics and content, of which there is a hell of a lot this time around.

**Comment by blake59** [comment]
Hi is there an ETA for when this feature will be available? Maybe even releasing it in pieces since there are a lot of changes.

**Comment by Neph0** [comment]
@blake59: in the meantime, you can just add the jewel's stats on random pieces of your gear.

**Comment by Chainezo** [comment]
You can make custom jewels with the stats. It's just a bit of work ATM and you need to look them up every time

**Comment by Openarl** [comment]
Full support for Abyss Jewels is coming in the next update, which should be out within the next day.
