### ISSUE TITLE
Inpulsa's Broken Hearth Sadist Garb

### ISSUE THREAD

**Issue by TutuRutuKibo** [Openarl/PathOfBuilding#732]
Hello m8, will u be soon adding this uniq chest ? I rly need it to finish building. Tnx

**Comment by Openarl** [comment]
It will be coming in the next update, along with quite a few other uniques. Please do have patience regarding the new content in 3.1; there was rather a lot added, and I simply haven't had time to get around to all of it.

**Comment by TutuRutuKibo** [comment]
Tnx for reply! I will, have a nice day! A.

On Dec 11, 2017 09:22, "Openarl" <notifications@github.com> wrote:

It will be coming in the next update, along with quite a few other uniques.
Please do have patience regarding the new content in 3.1; there was rather
a lot added, and I simply haven't had time to get around to all of it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Openarl/PathOfBuilding/issues/732#issuecomment-350652991>,
or mute the thread
