### ISSUE TITLE
Error opening path of building? Solved

### ISSUE THREAD

**Issue by bonzai169** [Openarl/PathOfBuilding#735]
When i open path of building if shows me this "--- ERROR ---
Critical error at address 73443AFFh:
Access violation: attempted to read from address 00000000h"

The only way i can get it to open is if i re install it everytime.

**Comment by bonzai169** [comment]
Found out 2 sec after i posted this that opening the app as an administrator solves it.

**Comment by Openarl** [comment]
Hmm, fair enough. It shouldn't be necessary to run it as administrator though...
