### ISSUE TITLE
[BUG] Adds X Damage to Attacks with Bows doesnt Calc

### ISSUE THREAD

**Issue by WamboOSX** [Openarl/PathOfBuilding#736]
Hi, 

i found the following issue at the Damage Calculation of Pob

Adds y to x Lightning Damage to Attacks <- Works
Adds y to x Lightning Damage to Bow Attacks <- doesn't work
Adds y to x Lightning Damage <- Works

Thx for your help and Pob

**Comment by Openarl** [comment]
Fixed in the next update.
