### ISSUE TITLE
[Bug] Detonate Dead does not account for 'spell' tags

### ISSUE THREAD

**Issue by MasonTallis** [Openarl/PathOfBuilding#739]
DD Is not accounting for spell damage or crit, which changed in 3.1.

**Comment by Openarl** [comment]
Unfortunately the change to DD isn't trivial to handle, as the flat fire damage is now affected by spell damage modifiers, but the percent-based portion is not. I will probably need to split the two into separate skill parts, as the program can't currently perform both calculations at once.

**Comment by MasonTallis** [comment]
IMO the stopgap is to factor in the spell/crit nodes as-is, and ignore the %hp portion completely (since this is likely used much less often, due to variability in mob hp), and then ultimately split the damage into parts the same way things like storm burst are. By far the most important calc is the main (flat fire) explosion damage though.

**Comment by Openarl** [comment]
Splitting it into two skill parts is actually quite trivial to do; it's just that all of the DD skills (new and old) need to have the same done for them. But it shouldn't be long before I get around to it...

**Comment by rudykocur** [comment]
+1 It would be awesome to be able to plan various DD builds given how buffed this skill was in 3.1

**Comment by Openarl** [comment]
The next update will split Detonate Dead into two skill parts: Spell, and Corpse Explosion.

I'm also adding Corpse Explosion skill parts to the other new corpse spells, because I can.
