### ISSUE TITLE
[Feature Request] Support for Horror rings/quivers mod (and Hopeshredder's similar mod)

### ISSUE THREAD

**Issue by Neph0** [Openarl/PathOfBuilding#744]
Hello!

I'm trying to plan a build around the new [Hopeshredder](http://poedb.tw/us/unique.php?n=Hopeshredder) unique bow. It features the "12 to 14 Cold Damage per Frenzy Charge" mod, which also exists for Essence of Horror-crafted rings and quivers ("4 to 7 Cold Damage per Frenzy Charge").

It seems that these are not supported by PoB. I've never looked at the source code but if someone points me in the right direction (main files to edit for this kind of things), I'd gladly put a pull request together.

Good luck out there and thanks for the great software.

**Comment by Openarl** [comment]
The next update will allow these stats to be correctly recognised.
