### ISSUE TITLE
3.0 Spectres missing

### ISSUE THREAD

**Issue by Megaddd** [Openarl/PathOfBuilding#747]
Frost Sentinels, Solar Guards, etc. are currently not present in the Spectre Library.

Is this something that can be manually band-aided as a user, until they are implemented?

**Comment by marat569** [comment]
Would love to see solar guards! (Take my energy)

**Comment by lyrjie** [comment]
Duplicate of #492

**Comment by Openarl** [comment]
Yeah, this is a duplicate.

I do really want to get these in, but unfortunately it isn't straightforward to do, as explained in the other issue.
