### ISSUE TITLE
Error: performing arithmetic on local 'value' (a nil value)

### ISSUE THREAD

**Issue by esge** [Openarl/PathOfBuilding#75]
got this error when when hovering over the "Total Increased" in Skill hit damage section of Calcs
http://prntscr.com/decrar

using 1.2.20 version

**Comment by Openarl** [comment]
Could you send me your build? Go to the Import/Export Build tab, and generate a sharing code; then paste it at http://pastebin.com and post the link.

**Comment by esge** [comment]
http://pastebin.com/kjM3RTNe

**Comment by Openarl** [comment]
Thanks! I'll get to work.
