### ISSUE TITLE
Rapid Decay missing

### ISSUE THREAD

**Issue by LyskOnGithub** [Openarl/PathOfBuilding#750]
Hi Openarl,

I've noticed that Rapid Decay is missing from the Skill Gem List.

Here's an archived Link of the Skill Gem on the Wiki, since the actual Wiki is currently broken:
http://web.archive.org/web/20170610213849/http://pathofexile.gamepedia.com/Rapid_Decay_Support

Sorry if this is a duplicate, I searched the open issues for "rapid" and "decay", and didn't find this yet.

Cheers

**Comment by Openarl** [comment]
Rapid Decay was renamed to Swift Affliction in 3.0.
