### ISSUE TITLE
Chin Sols new Wording change not factored in the Calculation

### ISSUE THREAD

**Issue by myklose** [Openarl/PathOfBuilding#751]
New Wording is "100% More Damage with Arrow Hits at Close Range" and is not beeing factored in calculations, as it's not "Bow Damange" anymore.

Old "100% More Bow Damage at Close Range " -> Works
New "100% More Damage with Arrow Hits at Close Range" -> Doesn't work

**Comment by Openarl** [comment]
Fixed in the next update.
