### ISSUE TITLE
Blank screen on launch [w/ solution]

### ISSUE THREAD

**Issue by jmwendt** [Openarl/PathOfBuilding#752]
PoB Version: 1.4.69
OS: Windows 10 x64
Video: Nvidia GTX 1060 Mobile / Intel HD Graphics 630

When launching application, the screen appears completely blank. This issue appears to only occur when the Intel HD graphics are used (which is default after installing the program).
Using the Nvidia Control panel, you can change the preferred graphics processor to the Nvidia processor:
![nvidiass](https://user-images.githubusercontent.com/603939/34056048-9a26451c-e19f-11e7-9e95-fd960b056e7e.jpg)
Once this is done the applications seems to work fine.

Noting this bug in hopes of including a way to default to high-performance graphics processor for dual graphics systems, and as a means of posting this solution for others with this issue. I could not find a troubleshooting forum for this tool, but if such a thing exists, let me know and I can post this fix there as well.

**Comment by Openarl** [comment]
I've already made a fix for this, which will be out in the next update (1.4.70).

**Comment by Openarl** [comment]
This has come up a few times; #672 describes the same general issue, so I will close this as a duplicate.
