### ISSUE TITLE
Minion Life Support doesn't affect golems

### ISSUE THREAD

**Issue by NJOYSoftware** [Openarl/PathOfBuilding#753]
In 1.4.69 version the %More life from Minion Life Support gem is not calculated.

In here I linked the golem with the gem:
![bug pob](https://user-images.githubusercontent.com/14941985/34069663-a7d1b384-e255-11e7-959f-c24753e4c83e.PNG)

Here I disabled it:
![bug pob disabled](https://user-images.githubusercontent.com/14941985/34069664-a7fc5b48-e255-11e7-9053-1b17e2a61761.PNG)

As you can see there is a difference in mana cost, but no difference in minion's life.
The minion statistic panel shows that the gem bonus is not accounted (it is linked and enabled, the mana cost shows that):
![bug pob minion stats](https://user-images.githubusercontent.com/14941985/34069677-f7ce33da-e255-11e7-953e-9c135eede6b1.PNG)

In-game stats:
Without the gem
![golem stats](https://user-images.githubusercontent.com/14941985/34069702-6b89a9d0-e256-11e7-839d-134bd1cc13b7.PNG)

With the gem
![golem more life](https://user-images.githubusercontent.com/14941985/34069703-6ba5e924-e256-11e7-9dce-c1673fb7621d.PNG)

**Comment by Openarl** [comment]
A fix for this issue has already been made, and is coming in the next update, 1.4.70.
