### ISSUE TITLE
Movement Speed

### ISSUE THREAD

**Issue by reticenti** [Openarl/PathOfBuilding#76]
I don't believe movement speed is shown anywhere. I would suggest [here](https://github.com/Openarl/PathOfBuilding/blob/master/Modules/CalcSections.lua#L299) using `MovementSpeed`?

**Comment by Openarl** [comment]
The program doesn't currently calculate your movement speed, mainly because it doesn't have the necessary data to determine the penalties from armour. It's something I intend to look at soon though.

**Comment by STiX360** [comment]
Penalties aside, it would be otherwise good to have.
Especially when trying to add up everything such as QotF bonuses.

Any ETA, by chance?

**Comment by Openarl** [comment]
Now that you've reminded me, I've finally gotten around to adding this. It'll be in the next update, penalties and all.
