### ISSUE TITLE
Void Gaze skill doesn't show duration

### ISSUE THREAD

**Issue by indirnys** [Openarl/PathOfBuilding#766]
In the Calcs tab, [Void Gaze](https://pathofexile.gamepedia.com/Void_Gaze) (granted by the [Eber's Unification](https://pathofexile.gamepedia.com/Eber%27s_Unification) helm) doesn't show a duration for its effect. Its base duration should be 2.5 seconds.

**Comment by Openarl** [comment]
Fixed in the next update.
