### ISSUE TITLE
Doryani's Invitation (Fire ver.) lowers fire damage

### ISSUE THREAD

**Issue by pincette** [Openarl/PathOfBuilding#767]
Doryani's Invitation (Fire version) **lowers** your hits and dps (burning damage is ok) while using it with Kaom's Heart (Flickerstrike Oro's Sacrifice build). Without Kaom's Heart it raises dps as supposed, as well as Kaom's Heart itself. The build link: [https://pastebin.com/yxREuLCu](url)

**Comment by Openarl** [comment]
With Doryani's Invitation equipped, your Fire Resistance is no longer your highest resistance, thus preventing The Wise Oak from boosting your DPS.
