### ISSUE TITLE
Sharing XML build files do not include the Skilltree

### ISSUE THREAD

**Issue by FWidm** [Openarl/PathOfBuilding#77]
Hi, a few friends and myself found out that when sharing the xml, the skilltree is not included, it'd be great if you could add the url of the tree to the xml file as well.

**Comment by Openarl** [comment]
The skill tree URL is in the XML file (in fact there's nowhere else it could be stored). I suspect that what's happening here is that some of you are using outdated versions of the program, as there was a recent change in the way the passive tree is stored in the XML file that isn't backwards compatible with older versions of the program (that change will eventually allow support for multiple passive trees in one build).

**Comment by FWidm** [comment]
Thanks that might be the case, i'll check that and report back. Thanks for the quick reply, i appreciate the effort you put in the tool.

**Comment by FWidm** [comment]
I can confirm, it works now both of us got the update information and swapping the XML works fine.
