### ISSUE TITLE
script error....i dont know what should i do

### ISSUE THREAD

**Issue by NechitaRobert** [Openarl/PathOfBuilding#770]
![capture](https://user-images.githubusercontent.com/29518282/34327257-fde82564-e8c7-11e7-9ee9-15b97d20b450.PNG)
i open pob and i stuck whit this...pls help :(

**Comment by Openarl** [comment]
It looks like your installation didn't update correctly at some point, as there's a mismatch between the versions of some of the files. You appear to be using the standalone version, so I'd recommend download the [most recent version](https://github.com/Openarl/PathOfBuilding/releases/download/v1.4.67/PathOfBuilding-1.4.67.zip) and re-extracting it over your existing installation; your builds and settings won't be affected.

**Comment by NechitaRobert** [comment]
thanks pal :)
