### ISSUE TITLE
Error on converting item to Shaper/Elder

### ISSUE THREAD

**Issue by JYshadow** [Openarl/PathOfBuilding#771]
![image](https://user-images.githubusercontent.com/25852794/34328590-0860d7f0-e8e3-11e7-9a8c-fe1c3caaa50a.png)

When I try to change an existing rare item to elder or shaper, it gives an error. Might be because I still use the old crafting method, like this: 

_Evasion Helmet (Innervate)
Lion Pelt
Quality: 20
Sockets: G-G-G-G
LevelReq: 70
Implicits: 0
Prefixes:
42% increased Evasion Rating
+52 to Evasion Rating
+90 to maximum Life
{range:0}+(0 to 2) to Level of Socketed Minion Gems
Suffixes:
{range:0}+(0 to 400) to Accuracy Rating
{range:0}+(0 to 55) to Dexterity
{range:0}+(0 to 55) to Intelligence
{range:0}+(0 to 48)% to Fire Resistance
{range:0}+(0 to 48)% to Cold Resistance
{range:0}+(0 to 48)% to Lightning Resistance
{range:0}+(0 to 35)% to Chaos Resistance
Socketed Gems are Supported by Level 16 Innervate_

**Comment by Openarl** [comment]
Fixed in the next update.
