### ISSUE TITLE
Is it this a issue?

### ISSUE THREAD

**Issue by hudsonphilipe** [Openarl/PathOfBuilding#775]
Just equip a weapon and than increase level, 
the average damage and total dps will decrease

example:
Xoph nurture at level 1 dmg: 222.7, total dps: 278
Xoph nurture at level 90 dmg: 103, total dps: 129

**Comment by master2080** [comment]
Your accuracy drops with level, pay attention to that.

**Comment by hudsonphilipe** [comment]
oh thanks.
