### ISSUE TITLE
Can't copy the new abyss jewels using fikals's PoeTradeItemCopy script

### ISSUE THREAD

**Issue by decayedCell** [Openarl/PathOfBuilding#776]
I am using:  https://github.com/fikal/PoeTradeItemCopy and when I try to copy a jewel into it I get this item is invalid https://i.imgur.com/fUrpnBA.png.

Is it something PathOfBuilding needs to fix or the copy script?

**Comment by master2080** [comment]
Try Removing the "Whispering Thresher" part.

**Comment by Openarl** [comment]
That's the copy script's fault; the item format it's providing is invalid, I suspect because it fails to recognise the item base type.
