### ISSUE TITLE
Equipping Opal Ring reduces total dps

### ISSUE THREAD

**Issue by Iammortal** [Openarl/PathOfBuilding#777]
Equipping Opal Ring with Elemental damage with attacks prefix into an empty ring slot reduces total dps.

Works fine in the craft item section, showing proper dps increase. When add to build, it starts showing as a decrease instead.

**Comment by Openarl** [comment]
Could you give me the build?

**Comment by Iammortal** [comment]
https://pastebin.com/w9MJfKdH

Removing ring 1 gives me a slight dps increase.

**Comment by Openarl** [comment]
You're using The Wise Oak, the Opal Ring gives Fire Resistance, and removing the ring causes your Cold Resistance to become your highest resistance, thereby increasing your DPS.
