### ISSUE TITLE
"Import from" dropdown menu for items disappears when maximizing.

### ISSUE THREAD

**Issue by Geekachuqt** [Openarl/PathOfBuilding#78]
As title says. It instead opens up a second search box, see image below:

http://imgur.com/Pns6DxM

**Comment by Openarl** [comment]
That second search box is the rare item template database! If there's enough room, rather than displaying either the unique DB or rare template DB and providing a dropdown to switch between them, the program will display both at once.

**Comment by Geekachuqt** [comment]
Oops! my bad. :<

**Comment by Openarl** [comment]
It's ok ;) We all have days like this.
