### ISSUE TITLE
Intimidate calculations

### ISSUE THREAD

**Issue by YurihOI** [Openarl/PathOfBuilding#781]
https://pathofexile.gamepedia.com/Intimidate

Intimidate doesn't proc on RF or Scorching Ray or any skill that doesn't "hit", but if you mark the Intimidate, it still adds +10% damage on the tooltip. This can cause confusion with some players who are planning new builds.

**Comment by master2080** [comment]
What's your point here? You can also mark shock and many other things, they are there in case you want the effect added, it doesn't have to be related to RF at all.

**Comment by YurihOI** [comment]
The DPS calculations using the Intimidate bonus even when it doesn't work is the same as if the "was hit by Lightning" added the 40% damage even when the build doesn't have EE. The Intimidate doesn't affect skills that don't "hit", so if a player has the Belt of the Deceiver, all skills should add the 10% bonus damage to the DPS tooltip, except the ones that doesn't hit.

The whole point of having a tool to plan a build and test different sets of equipment is not having to buy it in-game. If something is wrong in the calculations, it has to be fixed.

**Comment by Thirsk** [comment]
This is an issue, but not for the reason YurihOI seems to think it is. 
It has nothing to do with a skill's ability to proc Intimidate (if you manually set it as active, the program should consider it to be active regardless of your ability to proc it) and more to do with the fact that 3.1.0 changed it so Intimidate now causes enemies to take 10% increased _Attack_ Damage. 
Path of Building is still applying the increase to spell damage as well, which is simply an oversight.

**Comment by jtuc** [comment]
Is "Attack Damage" the same thing as damage from hits? If so, fixing this might be as simple as changing Intimidate from a DamageTaken mod to DamageTakenWhenHit, assuming we don't mind 2.6 calcs being inaccurate.

**Comment by YurihOI** [comment]
Thank you Thirsk, it's attack damage and not just damage from any hit. Just checked again on PoE Wiki

**Comment by Openarl** [comment]
This is finally fixed in the next update. Sorry for the delay!
