### ISSUE TITLE
Fresh install not showing 3.1 trees

### ISSUE THREAD

**Issue by Quantisaveri** [Openarl/PathOfBuilding#790]
I did a fresh install of PoB and it gives me tree options for 2.6 and 3.0, with 2.6 greyed out. Tried the update engine and it said I had the latest version. I then tried uninstalling and installing an earlier version just after the version that reddit said had the trees for 3.1. Did the same thing. 2.6, 3.0, no 3.1. Need help here. This happened regardless of source of install (zip or installer). Please help.

**Comment by Openarl** [comment]
If you have the latest version then you do have the 3.1 tree; the game version selector does say 3.0, but that isn't supposed to reflect the exact version of the game data used by the program, but merely differentiates the two game versions available.

**Comment by Quantisaveri** [comment]
except that I opened the build and the marauder tree is definitely 3.0 not 3.1

**Comment by Openarl** [comment]
Are you absolutely sure? Do you have the old version of Vaal Pact (instant leech)?
