### ISSUE TITLE
multistrike + frostblades icy blades option

### ISSUE THREAD

**Issue by Teriderol** [Openarl/PathOfBuilding#791]
I was trying to find why my build had so much lower dps for the icy blades option compared to the melee hit, when i noticed the MH More attack speed and OH More attack speed did not calculate multistrike into the equation, which leads to severely wrong numbers in the end. 

love the program, great work

**Comment by Openarl** [comment]
Refer to #241; basically, the attack speed calculation wouldn't be correct even if Multistrike was factored in, due to limitations of the program's skill part system.
