### ISSUE TITLE
Added Damage to Spells & Scorching Ray

### ISSUE THREAD

**Issue by snuze** [Openarl/PathOfBuilding#792]
Scorching Ray does not seem to be affected by added damage to spells modifiers.

The following jewel appears to have no effect with SR:
```
Hollow Glare
Hypnotic Eye Jewel
Unique ID: 74cad0b77e714bc780a841d6e455370e7bab248816d54166991c3ace72933b0a
Item Level: 71
LevelReq: 43
Implicits: 0
Adds 2 to 22 Lightning Damage to Spells
Adds 4 to 6 Cold Damage to Spells while holding a Shield
Adds 8 to 12 Physical Damage to Spells while holding a Shield
```

**Comment by Openarl** [comment]
That is working as intended; added damage modifiers cannot apply to Damage over Time.

**Comment by snuze** [comment]
Hi Openarl,

Thanks for the response! I am confused why the jewel affects ingame tooltip!?

**Comment by snuze** [comment]
I think you are confusing added damage modifiers with added damage support gems (these require spells to hit).

**Comment by Openarl** [comment]
What part of the in-game tooltip are you looking at? The "DPS" number shown at the top is meaningless for Scorching Ray, as that only shows the "hit" DPS, which Scorching Ray obviously does not. The value of the Damage over Time is shown further down.

Anyway, Damage over Time fundamentally cannot benefit from any form of added damage; this has always been the case.

**Comment by snuze** [comment]
Oy :( If that's the case, the ingame calculations are so deceitful! Note how all of the additional damage mods are listed ingame:
![image](https://user-images.githubusercontent.com/3533129/34501947-39a73a22-efdf-11e7-8156-c8556496364f.png)

>The value of the Damage over Time is shown further down.
I don't see damage over time shown anywhere ingame, I guess you are referring to it being listed in PoB?

**Comment by Openarl** [comment]
It isn't shown there; only in the tooltip that's shown when hovering over the skill in your action bar or in the skill list in the character tab.
