### ISSUE TITLE
[bug] Molten Strike Balls DPS has incorrect attack speed

### ISSUE THREAD

**Issue by dmitriy-kiriyenko** [Openarl/PathOfBuilding#793]
I understand that actual estimate of balls hitting target is inherently hard (but there is a calculator based on google spreadsheets), so you display projectile DPS based on one ball hitting the target. However, this calculation is still incorrect: it does not involve melee attack speed (because balls are projectiles), for instance, multistrike, which gives more melee attack speed.

But in this case melee attacks speed applies to number of balls proccing per second and should be included into calculations.

**Comment by Openarl** [comment]
Duplicates #241.
