### ISSUE TITLE
[bug] Oni-Goroshi's buff is included to another swords

### ISSUE THREAD

**Issue by dmitriy-kiriyenko** [Openarl/PathOfBuilding#794]
Make an Oni-Goroshi build. Click 'Are you in Her Embrace?'. Equip good 450+ PDPS sword. You see that it gives more damage. Check the configurations, see there is no checkbox 'Are you in Her Embrace?' at all.

You may think this sword is better than Oni. But it's wrong, 'Her Embrace' is still active, which you can see by either looking at calculations, or by equipping Oni, unchecking the checkbox and then equipping that sword.

Other weapon types do not have this effect, so obviously condition there is 'Sword' while it should be 'Oni-Goroshi'.

**Comment by Openarl** [comment]
Fixed in the next update.
