### ISSUE TITLE
[Feature Request] Sorting Uniques By DPS increase

### ISSUE THREAD

**Issue by wlfbck** [Openarl/PathOfBuilding#796]
This should be somewhat easy to implement but helpful: Currently [this search menu](https://i.imgur.com/I6IqRMP.png) is just sorted alphabetically. What would be great is if we had the option to sort it by DPS gain instead.

**Comment by Asymat** [comment]
A greed.

**Comment by tgavankar** [comment]
Looks like this was fixed/added in the latest version (1.4.87).

**Comment by Openarl** [comment]
Yup! (finally...)
