### ISSUE TITLE
pathofbuildingbuged

### ISSUE THREAD

**Issue by shockwave12128** [Openarl/PathOfBuilding#799]
![image](https://user-images.githubusercontent.com/35207925/34657461-232218ee-f3f4-11e7-83fa-c23f0610017d.png)
This is a bug on my laptop. I had been using pob for a while now, but then i accidentally might have messed with the green loading thing that happens when you open pob. Now i can see anything like the level of my character, i cant change which class my character is, the bandits, i cant even save builds or create new builds this sucks. Also the mouse curser is below quick recovery not one it yet is still highlighted, I tried uninstalling then reinstalling pob but that does not seem to fix the problem.

**Comment by moonlightdrive** [comment]
@shockwave12128 I think you're experiencing #527. Updating graphics drivers fixed this for me

**Comment by Openarl** [comment]
Yup, that's 527 again.
