### ISSUE TITLE
Buttons below skill tree do nothing at all

### ISSUE THREAD

**Issue by shoolayce** [Openarl/PathOfBuilding#8]
The panel of buttons below the skill tree (Reset, Import etc..) do nothing when pressed. The search field and "Show node power" checkbox are also not interactable.

 I am on version 1.0.15, using Windows 7. My screen resolution is 1920x1080, and this issue is present both in a maximized window and in a smaller window.

**Comment by Openarl** [comment]
Whoops! Sorry about that one; very silly mistake on my part. I've issued an update that will fix this.
