### ISSUE TITLE
Add Ring Prefix "(Global) Adds # minimum Chaos Damage to Attacks"

### ISSUE THREAD

**Issue by FWidm** [Openarl/PathOfBuilding#80]
Hi, i'd love to be able to plan using rings with the mentioned mods. According to exilemods.com the mod can roll the following values:

> (Global) Adds # minimum Chaos Damage to Attacks, Adds # maximum Chaos Damage to Attacks
30	8 to 11 / 18 to 23	Elreon lvl: 7

Thanks!

**Comment by Openarl** [comment]
It's always possible to add these yourself, by using the "Edit..." feature when viewing a template. I've had a few requests for this specific mod though, so I'll add it to the ring and amulet templates.

**Comment by FWidm** [comment]
Ah, thanks i tried adding it to the Rares.lua which for some reason did not work/did not show up in your planner.
