### ISSUE TITLE
[Feature Request] Split Leech and On Hit Rate

### ISSUE THREAD

**Issue by jasonrobinson-gpsw** [Openarl/PathOfBuilding#802]
I'd like to request that the leech rate and on hit rate be shown separately rather than bundled together on the Tree sidebar. Since "on hit" mechanics are instant, it's important for some builds to track it separately from leech.

**Comment by Openarl** [comment]
I combined those stats to save space, as the sidebar is already quite cluttered. If you need to see the separate values, you can find them in the "Leech & Gain on Hit" section of the Calcs tab.
