### ISSUE TITLE
"Hidden Potential" Jewel Not Supported

### ISSUE THREAD

**Issue by livejamie** [Openarl/PathOfBuilding#810]
Would be really nice to get this supported as it's complicated trying to figure out upgrades if you're using it.

https://pathofexile.gamepedia.com/Hidden_Potential

**Comment by eps1lon** [comment]
Could you provide a pastebin link to a build where it is not working?

It worked for me with a minimal example: https://pastebin.com/15CUbJeV

**Comment by livejamie** [comment]
Yeah it works when you do it that way, good debugging.

**Comment by Openarl** [comment]
As of the next update, the program will correctly parse both wordings of the modifier.
