### ISSUE TITLE
Item Editor Prefix/Suffix Errors

### ISSUE THREAD

**Issue by Lothrik** [Openarl/PathOfBuilding#811]
Importing this custom item into a blank profile:
Generic Gloves
Fingerless Silk Gloves
Elder Item
Crafted: true
Prefix: {range:1}LocalBaseEnergyShieldAndLife2
Prefix: {range:1}IncreasedLife8
Prefix: {range:1}IncreasedMana12
Suffix: None
Suffix: {range:1}Dexterity10
Suffix: {range:1}ChaosResist6
Quality: 20
Sockets: B-B-B-B
LevelReq: 70
Implicits: 1
{range:1}(12-16)% increased Spell Damage
+60 to Dexterity
+15 to maximum Energy Shield
+117 to maximum Life
+73 to maximum Mana
+35% to Chaos Resistance
{custom}14% increased Attack and Cast Speed

Throws the following errors: http://puu.sh/z4eB5/682e008509.png, http://puu.sh/z4eC1/d1320e6b93.png

The second error repeats forever, forcing you to reload Path of Building.

Attempting to edit the item in a build that already contains said item throws the following error: http://puu.sh/z4eDw/e21ab1b19d.png, and then repeats the same endless error from before.

If however, you attempt to edit a DIFFERENT item prior to editing this "bugged" item, it does not throw an error and instead pretends the first prefix does not exist. Double clicking the "bugged" item in this state will successfully load the item, but if you repeat the process the first prefix disappears again, and if you reload the build you can trigger all of the same errors mentioned before.

**Comment by Openarl** [comment]
Fixed in the next update.
