### ISSUE TITLE
Fertile Mind conversion not working

### ISSUE THREAD

**Issue by Woute** [Openarl/PathOfBuilding#812]
Using PoB 1.4.74, conversion jewels like Brute Force Solution or Fertile Mind don't seem to be working.
I have allocated all nodes I want to see converted, put the conversion jewel in the nearby socket and nothing changes. Neither on the tree nor in the global stats. Not sure why as people on discord assumed it should be working.
Here are some screenshots : https://media.discordapp.net/attachments/174994219390337024/403880644947476480/unknown.png?width=277&height=301
https://media.discordapp.net/attachments/174994219390337024/403880772580409344/unknown.png?width=338&height=300

Edit : After further investigation, it's when importing a build that the imported jewel will not work. If after importing everything I go and add Fertile Mind to the build and use this one, it will work as intended, the other one that was imported automatically from the string has no other effect than +24 Int though.

**Comment by Openarl** [comment]
Sorry for the late response; do you by any change still have the import string with the faulty Fertile Mind? I haven't been able to reproduce this.

**Comment by Woute** [comment]
Sure. I haven't been playing recently but I tried again today and it still seems to fail. Here is the import string (from poe-profile) : 
`eJzNW1tT28i2fvevUFE1dR4ohr6rNUWyyzYESLgF5zbzMtXqC1aQJUeSIeTU-e9ntWSwZBvjmbMz-4QkGGmt7l6X_ta3WuLgX98naXBnizLJs1c7-Fe086_XvYMrVY0v3WCWpCbJbl4f1J-C1N7Z9NVOxHeCShU3tvr0qEf_RDtBrDKTVBd5MVEgdZFn9vFa96dhMbNPAjpVZXmhJvbVzrkq1MzYYidQpbaZGS5uDWAiW9z6e80Y57bQSWrL8nGciUqyUa5vbXVc5LMpmLIT3CX2_jw3oD_snw1HO_uvD0a3SZqWgbFOzdLq2E7ez1SaVA-vdrIk3WldP2tsra-WeeEvlYOHw6vRq50K1r8zH6qet6-r5M7WPw9VqstaLd1Zvvd42WYqTq2ZDxSUaQ4O-mzVNM8CDAPDVI-uBiNKr3oK0m-Swg6smuwE3x7XjFYGy8Bdo6nVr3ZGOi_0GKIXXKsHb3prWEJb445m0ykYOFRl9XkMPh2OVZbZNAXVLafyqsG91w3ayktzojVz5hkEuipUZc2Rc1ZX287YUgzmmttMl5oPuffj1tNA1ld5UKu8PL4Xu7KZ9euCbbHlJF4raKttiNWWQ_oh9uuc-0lpSv6ZNF0Xw_9Imv7cvDlK7QSyWaVvcj0rt5zjSSlotP7f7bZ_3274Oal8YtOJrZ5P5Eevzeo0GVVFcrt1_BudYK60wVeXRXzpRhXUzG3jDhpB7oK5Tndosbr8fqFVZkczKNdbTtBoBI3KhqW_SUHlUJXjbSPr5YNa4afFdJCbh6BfTPJZ0Q0saUf2MCl1MoUIbeuSlsLLeT8AObPlwI3s_os5CMh1mR2qibqxH9St3XYzzRHPZkGjGzTK3flYa76BStOz5GZcZdvDqtcJFkpbMI0ZkLnL7CTZGn-8QnCZBV5lQwCOMmctDLEtgj6K_7R0PE7zO1suQcwzRe2nxReT1oSnkwnMp7xJ6ZaTPKoEtc7L-X-a6cKq0prD2V9C_ie94ElxgyGjGSwrgzqel8c5lMJt6UatFtR6QaP4E8Eor5aDH7VM-JTcJKnKqr9UWh6VnqktbfC4sPeA5VWi54C4NfyDyiOIblHmIQdt0a8qpW-3rQS1StDobGQuf4PvNt_L1wenFbRsgaqD5T-PbFWD66y0I6vzzDRctr7s2zxoe71YkBgv9rp3rQqY-Lfgun991Dse57M0GI1VYXrDPFZpFby19zbtnR7-FmBJscAxsRS4kWRWExoxF_NQGGtQTELGMLE6VlgKFDEd21BSJSIeKY6Msb3TCRQXnVTlbwHq7WLhueNpVnmCemOBe_Uw_yVInvZHzZGaHd_Don2nJp7zO7uRHwbSxGY31TiAtrk75sG-N_f1wmjSMvrjxen7j0e9N7aoPF8-hzK1ajeJYy0wQ9RpxJhiOBIqlMIpTQSJCWOMhIhaQ7hyVBotOQ5DZDSKI4N0SNt2497v-SwA5pHlVRADQ_eYb4L7BJY-giX4Fe8SsuKZQ_sdcgnWHLginwRXqiwh3iX4BBoKk8zgUxl8KFRWOiBM1qwMsOIGuuqGQTGrLPDsQgMvytOZB6dVdxjLQsQZjUJhqYX4s5jEBlPtlJHIOcRDbZnhMlY8BFehSFpBqYD_IkkUXkoDwlbW-hTMf5etbDnPobUqp-BPT159Se-dPEwhIgAIRw-2ZWskGHEMh9hFVEswNqI8jq0k1jAiuRUsZuADE2PKGdcm4kZoTpgmXDiOIfR-CfUhy2-BEF3T-8aUQRNrcEIr2-uEnoI9ZSODsb-CWTvvWzK7rN5JE_U9mcwmwVFmi5sH2MSJTc18AFoPEK2fZN4s3nt57xEVfLjPgxPYSeDbBj1WXcr_bvrEFmvFVKgUoAIy1jKFOI7iWEWYgTMloAclkZSGUqkcZ9IRjLiTXFqOrPsPpI9YTp-TPIOqEXyyZQlWrdkhYJRwJsTMxpAbRhvOLEVIYosRlTHnlIQShaE1UnLKQkUxQiGJsONEm66JXejrgCJ_DhQxad_pw_cnuMTIG7zAk5cBM1wN9WdV6bEt_qv0-6V3VSTlRPnds_ABd8p5FCA4UjrGKlZUMMWVltpZjFWouWISU0MUjVXMVQQ3wtBZQy3SDnV9wNrmrE_0tSJnibPr75yrTPUo6g4S3ADvASFIjMAqPfZ3Jw-ej8_3iKpPBUAifggW3VIPo198s3o1figTDRTycYd5mhqosrNvVwe6mtWBgAFO17lfLmcfdFMAWcEV0LrV3FM2sgyyDYoQcggTSg1sNsssDsH_DgKiKUztEMPaOBLDXy2U9z1ULSzoUu51MqyGi64dLdAYVWDUphKOX8jJv1DDo5ZPzvvHp8Pe0XeP5_6oqE7L6xk4Flrx8rY5RVCzrD5-q32kiTKWKCsjZZx0wlFjnHWhEgA4lHHiIhQ7RYDpxFriiGJsFREc6A5cw6iD6lj25ofrwBSW0hZ6ilnmYwvWDVJra0-ZWV13msXZOg9613biW6iFEJB3IHA9Kts-e2wYVv0B3dZSklzGaXIHshC0pFBp73IKeXn96AFinTAE9pkBEGKRERITv0W1VCyMCTYUWcx55LgzMopspImUMnJAbGLJRdzxgERdhkM6KbA4wHuMNpMrkEvZs_SOkueL2y7tVL56t_-3LpSDnfU_u4T-4u8-9ezBtS2TslJrMwrjVZT7MLZBiyn43fnJJ32T6TU_iAkPDQlphCOkNAJHWeNCrISVsM-ACkKpwyiUUkPeIGs5EGaLIssdpJ3uZlKIes2jHfDiYM9_XcPXoOtcDBnhj3W1bZIKFGD_1Hb6Uepsrwfx-7VpXQL_UKd3DBWvKudS2BtT-rO1oO4jep08q_tt2OzW9PCz-x-cEsC-7fL3zjCbtzBew8OHDzrNp1ZB55onae_MqgqqTDCwadUU1igEiiklZU6x2GGEqfRbVciQOgHth4wjuKSI89zMwH52EBAIDoqIMJp36ZjsenaXRivJtCvRyrUuwkF3VyQxEJ-yN3xi9W-K_Acgf-JadRZIxxgyEcypIHxd5yw0T28AL2DYxC3gcEnzaciW2mjsY16rtQdeVn0cshvWVkC5z58Hz23S_B4SZGHemgDSZcwB0geIn93Yolfj7wJuZBgB36PApGOA3AjqPhchhE4IygiLjdEaK2ABREbExhExzkkgR1rEQiO-FDe-HDf0y-NTiPYW3-V8BWd2Gd2AJmw12Ls-2nDRH_4tkGwxS9nGG_5X8Ib9HbyhOlRcC4AO8IugwjkduhBFLhaWUwltqIgji4iGxkR4wsmN9mVOhwDlZqlyhaSLN9cN5vwjeNMlA_8M4PAV0jAc2wlECPjCQJWeRz0xhhOAnoZPydggRTQxOOIiimnEHYsgmxFVSAsEjQtHOLJKEI1kBK1NGLGYGvjMvG7H4ww9zxUIlMDCmpn2_hj79w5KTwFMh0S8Kaz9YWuCNBz7Q7xNZGJFeE4qVj0jNnhmNEunYwCEJ9d8VoV53NjIAJXnsebYxTiUPAYQpsqE2gKjAOIUy4gSyEjITCD3yihioPnhGBtBHY7Cjncof847uDeEEAPGQl3ISqubR3T-DQiwDaz6CFYRssl_dfbWhy3lRp_NRZ71VLjiqT4s0wbvZ4m-LZP0zrY81TcAt6ruEOrOlzsqEGOOSSbiGDPiRGg5cE5psFNhqHUUOe2oi2IbUw0Xgb8rGTqgoYLLbio9n0mAWd7a8zmOzZ3R8zC52CvnYK5Hs2bbrfXJqvVyFbP6ZVUoP1BS9i6zh-9BfzJLbbN3nIxdDIRZhgqBzcpghcFAJo1jGIw3FjngThopCjAltHU6IpJyoOUKRch1DF7OiPn5oQfmVg3ejeSaq3vsmd6sPiGYH9CusXe1zdg-2hiMoYRK6MCEi6ijVKmIIQXxj6hEwuqYY43DCO4zoIMhFRx6EgREJaIsQttHO1oXbRL9X6NNVnqKN7DtfDEqeiezGHr-YJgU-jHYgHkOa600Nox53kUswyYENqYk17EwxkInSqD15EDLMKdIUuUP07im0JviZSrcNvipTB3XJWqw5AG2epK8G9VtQ19r6Jk0UBFonACzdsMN9V92mpAlbkD4Kjfw3ZmHFd-ubKr1ZOWcfWABX3Pgdu-snfY-qZpT3IDBqik6iCOhDGKAnTGKBBR1JDFUe44QlHrYL8oRgeFn6hR0bzqEZh46e2hFAHSNWi7za3052Duel_wVf4ar_pQbzhi7XWr33tIJQjXL6oJUEwmwWUNiFg899KuoT1C6pzHgEgsXarD31b-sn2csGFeIn593NQhkJQhFMgFOArXhSqWTXv1CAMQwaB5nNkktQu18W2Ewia2WwAPC0BmNRcx1GDMndRxi8D7GBEhXHGuGJGziOGIGIHylv1sbiOvVPg-CwOlqEKjc1Avz9TTYI8GaLF14kXa8eKf8u451kF7y6EoDsPDoca4MWFhoW_gGzj8ibByqQ-usETEBJhAD1NvQEiBNAP2IYGEACTgDjiC4kwLwAshtCICoNSAGgn9bZfY1ZPZxl8g-k9VsUzdAn_Fn-DzN31Rjn_X4Wi-PUujssvqt0Aam-U4AneHktD792u8I-D4rwIv7GC0JPL11uRDBSyK-x27dJuumIC0Bun6KtghbEmnsoC0JvlaCtSTEWom2IeGSRMM_WgJy7RDthS77c_7K1JMAWfZn-_2bhdSyS-evRSwElp3aPDlf3K99Wse_fH3wAdj7_LFu8_TXvzPrP70--Hh99npcVdPyt_39-_v7X6eqGufOfode8VedT_anzSOPvfr58h70_Ha_D38G_aNh__3hrL_Hjgb3WB7e3rz_PDiqjj71r9Pxx5vj-L2KB2V6cnFv3gzw1QngWz85fv_2UKdvH76Kdx_lt8vh9OLs7X05TR7-PLu8rU4eyOE50_j262d-UX6kNz_uq6sHMxijTyfX93-8eziazT6cXVy-SwfDj1-uP4_euLefRWRGn-jDFzJ16PiPj3_wqhweoz_ib9Pw68ndoZNqOGFnJzd47_DH6RUdf5kdl8ykybe984v8O_k6m1wd59Hx1z-_vR9O-9e3F-rDW_7xJlPCXr07ussTkeRC_TGdzbLhO11MCZldfdu7KPgMD86-PFQ_BLsNxbu7b_bP4flgcq-_DKRUMzT48z26-Dwhww-_35k0JnvOHNrD3_nwbNqf5e_FXlgeX96zcO_ue3I3dnv2697w5tWrg30fkIM5_Dx-CLLcWB_WMBJoEeQmlboSAkvaSvpwjQiRLOSbRwFCEImFCF8jQv15y0KErROhkYxemAhHkm0WYUJK8tJyQ_KCRdAkiBZcyHWuQyF9YRRoN6MXAsBkKORmEUrC9lrWhpHQF-bhYFH4wjxAnlvzkLUhErSFgHSdCBbtUcTapGO4FWi8LkQswkur3X_K8v0Gi_Y9Tr0-qN8egvsXOfRb-w16fUrsfQCkTRV6PKoK_5rLjzyf_P5qZy8EwidRiKAJiIBRNTe-wA0Ssl-pIAhHnFLk36ob5_f-MOZcTV_tOJWWthGe_-ICaSSgKakOE2hkCl_Xy_mrM7COYZ655MYvfOl3PXr_C35uMF0=`

**Comment by Openarl** [comment]
Oh, so it's from poe-profile... That website actually constructs the PoB build file manually using the imported character data, and what it generates is only barely accepted by the program. In this case, it is failing to include the jewel radius value on exported jewels, which is preventing conversion and threshold jewels from working. 

The bug appears to still be present in the website, as freshly exported profiles are also missing jewel radius values. I'd suggest notifying the site's developer, as I can't do anything about on my end.
