### ISSUE TITLE
Switching old Baron to new Baron doesn't change dps

### ISSUE THREAD

**Issue by OSwoboda** [Openarl/PathOfBuilding#818]
https://pastebin.com/hteEzWP6

I have 2 The Baron in there, one with 'Your Strength is added to your Minions' and the other one with 'Half of your Strength is added to your Minions'. If I switch between the two the srs dps doesn't change.

**Comment by Openarl** [comment]
This is intended; the change to The Baron affected existing copies of the item, but as Path of Building doesn't update the wording on items when such changes are made, both the new and old wording will have the same effect within the program (granting half strength).
