### ISSUE TITLE
Character import don't work

### ISSUE THREAD

**Issue by rhazor** [Openarl/PathOfBuilding#82]
E.g. it downloads the account info with the list of characters, then you select a character from the tree and try to import either setting and always end up with an error.

![asd](https://cloud.githubusercontent.com/assets/22996586/20867500/11251e64-ba4f-11e6-8f80-ee2890781741.gif)

version 1.2.22
it's not my firewall cuz update works.

**Comment by dein0s** [comment]
Account name field is case sensitive.
Input 'FleepQc' and you'll be fine with importing.
