### ISSUE TITLE
Error when trying to edit crafted Shaper/Elder Items

### ISSUE THREAD

**Issue by Gwahrdy** [Openarl/PathOfBuilding#827]
Hello,

when i try to change my crafted Elder/Shaper Items i get this error-message :
[https://imgur.com/a/WXxYC](https://imgur.com/a/WXxYC)
I have Version 1.4.74
I can craft a new item and use it, but can't edit it once it is saved.
It happens on all Shaper/Elder items.
Only pressing F5 helps.

**Comment by Openarl** [comment]
This should be fixed in the next update; sorry for the delay.
