### ISSUE TITLE
Assassin's Mark and Blasphemy+Quality

### ISSUE THREAD

**Issue by flynnzeke** [Openarl/PathOfBuilding#829]
Shouldn't quality on Blasphemy Support also increase the _Cursed enemies have an additional (5-9)% chance to receive a Critical Strike_ (and therefore the **Effective crit chance** stat) as it increases the _Cursed enemies take 20% increased Extra Damage from Critical Strikes_ part of the skill?

**Comment by Openarl** [comment]
Modifiers to curse effect are correctly applying to that stat; however, curse effect calculations always round towards zero, and the 10% effect from 20Q Blasphemy isn't enough to bump the 9% value up to 10 (as 9 * 1.1 = 9.9, which rounds back down to 9). If you get some curse effect from other sources however, you will see that Blasphemy's quality does in fact apply.
