### ISSUE TITLE
[BUG] Wrong spelling/parsing of Snakebite's "poison at max frenzy" affix

### ISSUE THREAD

**Issue by dein0s** [Openarl/PathOfBuilding#83]
Original string:
'**While** at maximum Frenzy Charges, Attacks Poison Enemies'
Template string:
'**When** at Maximum Frenzy Charges, Attacks Poison Enemies'
![affix ain't working](http://i.imgur.com/unnYp8y.png)

**Comment by Openarl** [comment]
GGG really loves to change the wording on item modifiers at random times... I'll fix it in the next update.
