### ISSUE TITLE
Import XML has Gem with blank nameSpec attribute

### ISSUE THREAD

**Issue by aggixx** [Openarl/PathOfBuilding#835]
I don't know how to reproduce this, and when I import it and immediately export the problem goes away, but [this person](https://www.reddit.com/r/pathofexile/comments/7xvo19/roast_my_spectral_shield_throw_build/dubiu8h/) posted an import string where the active skill's (Shield Charge) nameSpec attribute is an empty string.

https://pastebin.com/m1qZCdrb

**Comment by Openarl** [comment]
I managed to reproduce this; it occurs when blanking a gem slot without actually removing it. That instance is fixed, but note that the nameSpec attribute may be intentionally empty under rare conditions.
