### ISSUE TITLE
Unique item affix on Magna eclipse not calculated

### ISSUE THREAD

**Issue by Arcinsanity** [Openarl/PathOfBuilding#836]
**Magna Eclipse Tower Shield** has the following affix: _{range:0.5}+(80-100) to Evasion Rating and Energy Shield._
It is a tower shield with no base ES/Eva this affix is not calculated at all. 

how to repro: ceate a blank char add the shield, no increase to ES or Eva. not a big deal right now, but if there are issues with defense calculation from shields there will be issues whith dmg calculation when spectral shield throw comes out. 

Im gueesing it has something to do with the unique not having base ES/Eva, if other shields give defenses that are not on the base they may have similar problems calculating. 

**Chalice of Horrors War Buckler** has a similar affix (it is a pure evasion shield): _{variant:2,3}{range:0.5}+(50-70) to maximum Energy Shield._
This **is properly** calculated also the fated version is fine aswell.

Magna eclipse may be a unique case.

**Comment by Openarl** [comment]
Fixed in the next update; this would occur with any dual flat defence stats, but I believe this unique is the only item with such a stat on it.
