### ISSUE TITLE
[Bug] Traps+mines affect poison damage

### ISSUE THREAD

**Issue by eplgr** [Openarl/PathOfBuilding#840]
If I understood correctly, poison is calculated separately.

So let's say you have:
*Trap/remote mine support
*Bladefall
*4x unique jewels with 25% chance for traps/mines to poison on hit (coated sharpnel)

If you now add multiple traps support, cluster traps support, and so on, the poison damage will go down a lot. The "less damage" from these support gems shouldn't be affecting poison I believe.

**Comment by Openarl** [comment]
Sorry about the delay in replying!

This is in fact working as intended. Poison dealt by Traps or Mines is considered to be Trap/Mine Damage, and is affected by all modifiers to such damage, including the damage penalties on Multiple Traps and similar supports.
