### ISSUE TITLE
Jewel sockets with unallocated radius jewel causing errors

### ISSUE THREAD

**Issue by MatthewClair** [Openarl/PathOfBuilding#842]
#### Steps to reproduce the issue
1.  Allocate a jewel socket
2. Insert a jewel socket with a radius and a bonus per attribute allocated.  Ex: Static Electricity
3. Remove jewel socket and all other nodes in the jewel's radius.
4. Hover over unallocated jewel socket.
#### What's the expected result?
Act the same as any other unallocated jewel socket.
#### What's the actual result?
Error about performing math on nil.
#### Additional details / screenshot
The jewel must be one that gives a bonus per attribute in radius.  Normal threshold jewels and jewels that don't rely on attributes (Ex: The Blue Dream) don't have any issue.

Link to build: https://pastebin.com/K8hLTWsj
Hover over the jewel socket between Blood Drinker and Mind Drinker to repro.

**Comment by Openarl** [comment]
Thanks for the detailed bug report! This will be fixed in the next update.
