### ISSUE TITLE
Berserker: War Bringer does not activate Rage calculation

### ISSUE THREAD

**Issue by corosou** [Openarl/PathOfBuilding#851]
It seems selecting War Bringer alone does not activate the Rage calculation, even though it can generate them.

Can you please enable or allow a forced rage?

Thanks for the great work! Just became a Patreon supporter ;)

**Comment by Openarl** [comment]
Oh, looks like I missed that Rage source. I'll fix that in the next update.

**Comment by corosou** [comment]
Thank you! )
