### ISSUE TITLE
Trickster - Ghost Dance Node Doesn't Apply

### ISSUE THREAD

**Issue by junderwoodmGage** [Openarl/PathOfBuilding#852]
I noticed that 

1. there isn't an place to tick "energy shield recharge has started recently"

2. the wording on the node might have an unintentional return after "...Speed if Energy" therefore breaking the property into two lines, possibly the cause of the problem.

3. Mainly there isn't a combo of ticks in the settings (i.e. Full Energy Shield, Always Have Energy Shield) that results in this node increasing attack or cast speed.

Pastebin: https://pastebin.com/hbDH6qui

**Comment by Openarl** [comment]
I finally remembered to add the option for this one; it is coming in the next update.

Incidentally, the return had nothing to do with the issue, as the stat parser is smart enough to read stats that are split over multiple lines.
