### ISSUE TITLE
[Bug] Hidden Potential not working

### ISSUE THREAD

**Issue by Zuum** [Openarl/PathOfBuilding#857]
Title is self-explanatory.
No copies of this issue if found. Not sure if it works on 1.4.75 - 2018/02/22 as it was stated.
Reproduceble for me on any class. Running version 1.4.79.
Some Screenshots:
![image](https://user-images.githubusercontent.com/12525365/36857937-d5c9a8ee-1d8a-11e8-8dd1-b2351b2d16bf.png)
![image](https://user-images.githubusercontent.com/12525365/36857956-e4de11bc-1d8a-11e8-89d3-281ec0d189c0.png)
![image](https://user-images.githubusercontent.com/12525365/36857965-e96c35d8-1d8a-11e8-9221-c83eb03a82bf.png)
![image](https://user-images.githubusercontent.com/12525365/36858136-66684b3a-1d8b-11e8-8bb1-69eecaf0d95c.png)

**Comment by eps1lon** [comment]
This should've been fixed as mentioned by @Openarl  in #810.

Is this with the Hidden Potential used from the dropdown menu or an imported version?

**Comment by Zuum** [comment]
Fixed with editing ffect description with answer from [#810](https://github.com/Openarl/PathOfBuilding/issues/810)

Hidden Potential
Viridian Jewel
Limited to: 1
Implicits: 0
{range:0.5}(20-25)% increased Damage for each Magic Item you have equipped

**Comment by Openarl** [comment]
Ok, this will definitely absolutely be fixed in the next update.
