### ISSUE TITLE
Windows Defender detecting a Trojan

### ISSUE THREAD

**Issue by Saragnon** [Openarl/PathOfBuilding#86]
This program was working great for me until today when I hit the update button in the lower left. Not sure how long it was down there but I started using the program about a week ago. Anyway after trying to update Windows Defender freaked out saying it was detecting a Trojan. I tried uninstalling and reinstalling but now it detects it even when I just download the installer. The detected item comes up as:

Trojan:WIn32/Peals.A!cl

Is there anyway to stop this from happening without just turning off windows defender? I love your program for planning builds!

**Comment by Openarl** [comment]
I have no idea why that's happening. I'm using MSE on my PC and it doesn't detect anything when I install, run or update the program. I'm not sure what I can do to help.

**Comment by dein0s** [comment]
Here are virustotal reports for:
[Path of Building.exe](https://www.virustotal.com/en/file/bcea0a55af001e41f1ef81b8e9da194cdd4d62781c51f470ccb64d5cb95c7e12/analysis/) and [Update.exe](https://www.virustotal.com/en/file/0fe4d727b187285fa808713d83dd480afe8bd80f14690abfe36f5ad3132b0123/analysis/)

Only one false positive occurrence for PoB.exe itself, I don't see anything criminal.

**Comment by Openarl** [comment]
I'm actually surprised that there's a false positive for Path of Building.exe, as there's virtually no code in it (it just loads SimpleGraphic.dll, which [is likewise clean](https://www.virustotal.com/en/file/a16ff8ea6fbd38cb2dcf077e9cddeb529fe3ac8be4e3164dab53e79a47d32f66/analysis/1481201756/).

**Comment by Saragnon** [comment]
Maybe I got the trojan somewhere else and it was just infecting all the files I downloaded. I'm going to try doing a clean sweep of my computer with a couple other programs and try again to see if it still occurs.

**Comment by Saragnon** [comment]
Okay it looks like the trojan came from somewhere else and was infecting all my downloads. Did a couple scans on my computer and deleted some threats and now I can download Path of Building without any issues. Sorry for the false alarm and my thanks for your amazing character builder!

**Comment by Openarl** [comment]
Ok, good to hear that's sorted.
