### ISSUE TITLE
Might of the Meek Jewel problem

### ISSUE THREAD

**Issue by B14d3r11** [Openarl/PathOfBuilding#864]
I have Might of the meek in two seperate locations and instead of calculating the 50% additional twice on the overlapping nodes its subtracting? Specifically the Ele Resist nodes under Scion, it starts at 0% res, i put one jewel in and it bumps to 9% (which is 50% of the 18% they give) then i put the other jewel in and they drop to 8%?? They're supposed to go up another 9% because two of the jewels adding 50% additional, is the same as 100% additional? Cause its working that way with the scion life bubble.

https://imgur.com/a/e1drz

**Comment by Openarl** [comment]
The jewel is actually working just fine, but socketing the jewel below Scion disables the Sentinel notable, which cause you to lose 10% resistances; since each Might of the Meek gives an extra 9% from the Scion resistance nodes, that means you lose 1% resistances when socketing the second jewel.
