### ISSUE TITLE
Gems missing?

### ISSUE THREAD

**Issue by AngryRoleplayer** [Openarl/PathOfBuilding#867]
Maim and Swift Affliction missing after recent update...
maybe i broke something? Removed them and cannot put em back cause they do not exist
![2018-3-2_16-52-12 611](https://user-images.githubusercontent.com/22470478/36902039-34ef46da-1e3a-11e8-88ec-5fc4c3575f1c.jpg)
At the same Elemental Focus shows up and adds damage to Earthquake, even though Earthquake is not an elemental skill at all. It's pure physical. 
![2018-3-2_16-55-9 580](https://user-images.githubusercontent.com/22470478/36902144-82f67470-1e3a-11e8-9dee-b461ffc74b30.jpg)

**Comment by Openarl** [comment]
Your build is set to use the 2.6 game version; those gems didn't exist back then. And you have Hatred and Herald of Ash in your build, so your Earthquake will be doing some Elemental Damage; so Elemental Focus will have some effect.
