### ISSUE TITLE
Summon Skeletons might be missing a mod.

### ISSUE THREAD

**Issue by Embers-Coffee** [Openarl/PathOfBuilding#869]
I think summon skeletons is missing the 50% more added damage mod. I have skeletons and added cold damage and it doesn't show any modifies for the cold damage. Thanks for POB, I have more time spent on it than POE.

**Comment by Openarl** [comment]
It is definitely present and functioning; it is modelled as damage effectiveness, so it appears in the breakdowns for hit damage

**Comment by Embers-Coffee** [comment]
ah ok i see it now thanks.
