### ISSUE TITLE
Gloomfang only calculates one chain? 

### ISSUE THREAD

**Issue by AngryRoleplayer** [Openarl/PathOfBuilding#872]
I have a feeling Gloomfang ignores amount of chains and only uses 1 chain for DPS calculation,
https://pastebin.com/2FJSPLF2
3 chains here. But damage only increaes by 8%.

**Comment by Openarl** [comment]
By default, the program shows the damage dealt by the first hit of the projectile, before any chains have occurred, and since Gloomfang grants 18% Chaos for each time the projectile has chained, it won't be granting any. To see the damage after each chain, you need to set the "# of times Skill has Chained" option in the "For Effective DPS" section of the Configuration tab.

**Comment by AngryRoleplayer** [comment]
You also mentioned in PoB update that it now interacts with Richochet, but how? Richocet increases damage per REMAINING chain, how PoB calculates how many chains remain? I can understand that PoB just increases damage per chain for Gloomfang, but i wonder if Richochet is properly calculated as well.

**Comment by Openarl** [comment]
PoB knows what your maximum chain count is, so, given that you're telling it how many have been used, working out how many remain is quite trivial.

**Comment by AngryRoleplayer** [comment]
Please confirm if i do inderstand correctly:
if i have 3 chains in total (skills+gear).
If i have 2 skills have chained in PoB then i get 18+18 chaos damage through Gloomfang and also 10% more damage from Richochet Passive?
If i have 1 skills have chanined then i have 18% chaos damage through Gloomfang but 10+10=20% more damage with Richochet?

**Comment by Openarl** [comment]
That's correct.

**Comment by AngryRoleplayer** [comment]
I see, but 10% more damage should give more DPS than 18% extra chaos damage AFAIK (maybe i am wrong). Can you please check internally , because i have a feeling PoB does not calculate remaining chains for Richochet properly. Whenever i decrease a chain from 2 to 1 (with max 2 chain in total) my DPS goes down by 2% while i believe it must go up by an amount (because i gain 10% MORE damage and losing 18% extra chaos damage on top of the rest).

**Comment by Openarl** [comment]
Believe me, the program is handling it correctly; it really isn't difficult to implement, and I did test it quite thoroughly (including combining it with Gloomfang).

You are actually wrong about 10% more Damage being better; owing to the large amount of Elemental Damage gained from Physical Damage (which benefits twice from the extra Chaos Damage), the extra Chaos Damages gives about 15% more DPS per Chain.

**Comment by AngryRoleplayer** [comment]
Thanx! I just wanted to confirm it. Thank you very much for all your work!
