### ISSUE TITLE
Add an 'Are you Ignited?' option to the in combat configuration options

### ISSUE THREAD

**Issue by Ahumm** [Openarl/PathOfBuilding#873]
Currently there doesn't appear an option to toggle whether or not the player is currently ignited in the configuration options. This appears to prevent the inclusion of any unique item bonuses which have the 'while ignited' condition in calculations. This most notably affects uniques which provide some direct DPS or survivability bonus such as [Mokou's Embrace](https://pathofexile.gamepedia.com/Mokou%27s_Embrace), [Berek's Pass](https://pathofexile.gamepedia.com/Berek%27s_Pass), [Eye of Innocence](https://pathofexile.gamepedia.com/Eye_of_Innocence), and the new [Sunspite](https://pathofexile.gamepedia.com/Sunspite) as well as a handful of others with only provide additional movement speed while ignited.

**Comment by Openarl** [comment]
That option most certainly does exist; it's in the "When in Combat" section.
