### ISSUE TITLE
Celestial Punishment node not working

### ISSUE THREAD

**Issue by Schmidter** [Openarl/PathOfBuilding#874]
Celestial punishment writes "25% increased damage against Frozen, Shocked or Ignited enemies" Yet when I write enemy is burning or one of the others. The DPS does not increase. 
   
Elemental Focus is of course not used. It say Ignite DPS etc on skill, it CAN ignite. But Path of Building des not calculate it from that node. :(

**Comment by Openarl** [comment]
Could you give me your build? As far as I can tell, that node is working perfectly.

**Comment by Schmidter** [comment]
https://pastebin.com/cBfpKqe1   

Removing the node does not give more damage on the hit. Doesn't change it. I have "Is The Enemy Burning" on.

**Comment by Openarl** [comment]
"Burning" is not the same thing as "Ignited"; "Ignited" specifically refers to the Ignite ailment, whereas Burning refers to all Fire Damage over Time effects (Righteous Fire and Burning Ground being other examples). So to enable the damage bonus from that node, you have to enable "Is the enemy Ignited", "Is the enemy Frozen", or "Is the enemy Shocked"; and that does work for your build specifically.
