### ISSUE TITLE
The Wasp Nest

### ISSUE THREAD

**Issue by Atros81** [Openarl/PathOfBuilding#876]
There was an old ticket (#535) about support for The Wasp nests modifier of 'Attacks with this weapon deal 80-120 added Chaos Damage against enemies affected by at least 5 poisons', where it was claimed that there was support added, but in the program the expected jump in damage after 5 poisons isn't there.

**Comment by Openarl** [comment]
It looks like GGG changed the wording of that modifier at some point, which prevented the program from recognising it. That'll be fixed in the next update.
