### ISSUE TITLE
Frost Blades - Multistrike interaction

### ISSUE THREAD

**Issue by Nagshell** [Openarl/PathOfBuilding#878]
Calculations for Melee hit part of the skills seem alright, but calculations for icy projectiles are flawed:
PoB doesn't count in more atk speed for the projectile part of the skill, 
which results in massively reduced effective dps calculated compared to real value. 

I'm not sure if any additional info is required.

**Comment by Openarl** [comment]
As per #241, the attack speed (and therefore DPS) of non-melee skill parts isn't currently accurate; only the average damage is reliable.

The program's skill part system is due for an overhaul in the reasonably near future, which will fix this issue.
