### ISSUE TITLE
[Missing] Attribute Affixes for Jewels

### ISSUE THREAD

**Issue by Ikbosh** [Openarl/PathOfBuilding#88]
These are important for Whispering Ice, and the new multitude of X/% Based on Stat type Uniques.

**Comment by Openarl** [comment]
I generally only add essential modifiers to the templates, mainly to avoid cluttering the UI with modifiers that hardly anyone uses. It's always possible to add them manually using the edit function. I'll consider adding the attributes though, since you asked nicely :).

**Comment by Openarl** [comment]
The next update will add attributes to the jewel templates.
