### ISSUE TITLE
Death's Harp/Death's Opus Additional Arrows not Calculated

### ISSUE THREAD

**Issue by worldofmiao** [Openarl/PathOfBuilding#882]
Version: 1.4.83
The additional arrows from death's harp/opus are not calculated in barrage damage calculation. 
This issue only happens when you import a real character that equips this bow to POB because it seems ggg changed the tooltip of additional arrows on this bow

**Comment by worldofmiao** [comment]
made a pull request for a fix for this: https://github.com/Openarl/PathOfBuilding/pull/883, thanks.

**Comment by Openarl** [comment]
Fixed in the next update.
