### ISSUE TITLE
Doomfletch prism and additional arrow

### ISSUE THREAD

**Issue by phx7** [Openarl/PathOfBuilding#884]
Path of Building version 1.4.83

1) Imported Doomfletch's Prism from my character (acc name "phx", character name "EKS__DEE") gets its passive like this "**Gain 100% of Weapon Physical Damage as Extra Damage of each Element**", but it doesn't work, passive line stays red and doesn't affect numbers. Fixing it to "**Gain 100% of Bow Physical Damage as Extra Damage of each Element**" fixes it. Looks like PoE now has second variant and returns it via API.

2) When I corrupt quiver in Path of Building (tested on Drillneck), added line is "**Bow Attacks fire an additional Arrow**", but it should be "**Adds an additional Arrow**" to work properly.

**Comment by Openarl** [comment]
Both are fixed in the next update.

**Comment by phx7** [comment]
Addition to [2] - Drillneck passive updated too. Imported string "**Arrows deal 50% increased Damage with Hits and Ailments to Targets they Pierce**", PoB string "**Arrows deal 50% increased Damage against Pierced Targets**".

**Comment by Openarl** [comment]
That too. There was a major pass on projectile-related stats in 3.2 that clarified or altered their wording, preventing PoB from recognising them.
