### ISSUE TITLE
the "life recovery rate" of Watcher's eye increased maximum life leech rate

### ISSUE THREAD

**Issue by benqy** [Openarl/PathOfBuilding#886]
watcher eye
![wacthereye](https://user-images.githubusercontent.com/611055/37082759-5734d18c-2228-11e8-90b9-eb09541424dd.png)

no jewel
![nojew](https://user-images.githubusercontent.com/611055/37082749-4fe4f1b4-2228-11e8-834f-59ee29f32ec2.png)

with  jewel
![withjew](https://user-images.githubusercontent.com/611055/37082768-5973e758-2228-11e8-8fa0-e0fe7256c4ec.png)

**Comment by Openarl** [comment]
Yes, that is supposed to happen; modifiers to Life Recovery Rate affect all sources of life recovery over time, and apply after any applicable caps.

**Comment by mactane** [comment]
No, Life Recovery Rate do affect leech, but wont boost leech if you are already leeching at cap. The little gain of 24.9 hp to leech cap is due to your total life going from 6431 to 6539 from the 5% increased from jewel, assuming a life leech cap of 20% + 3 % ( probably from vitality void )
