### ISSUE TITLE
[PostInstallation/FirstRun Error] MSVCR100.dll not found even though existing in system32

### ISSUE THREAD

**Issue by LyskOnGithub** [Openarl/PathOfBuilding#89]
I downloaded and installed the PathOfBuilding-Setup-1.2.0.exe, the installation completed successfully. When trying to run "Path of Building.exe" (with or without admin privileges) I get the Error

"Program could not be startet because MSVCR100.dll is missing on the system. Reinstall the program to fix this error" (rough translation from German)

My C:\Windows\System32 Directory contains the MSVCR.dll, Version [10.0.40219.325](https://www.dll-files.com/download/0e37fbfa79d349d672456923ec5fbbe3/msvcr100.dll.html?c=Vk0xNjlyaXFpZnhMMm5ZWUpWVmx4dz09), but the Error persists.

**The Error was fixed when I copied the dll into the Program Directory (C:\Program Files (x86)\Path of Building)**

Maybe include the dll in the installer package?

**Comment by Openarl** [comment]
That file should be present on every system, as it's from a relatively old C runtime version. I'm not sure why it wasn't using the one in your System32 directory though; did you put the file there yourself, or did you use the Visual C++ Runtime installer?

**Comment by LyskOnGithub** [comment]
I put it there myself, maybe I missed a registration step.
My OS is a freshly installed Windows 10 Pro 64bit

**Comment by Openarl** [comment]
Yep, that'd be the reason. You can't install CRTs manually these days, you need to use the installer. This is the second or third report I've had about that version being missing in Win10; I think I'll have to start including the redist installer for it.

**Comment by Openarl** [comment]
The new installer versions that I'll be releasing shortly will contain the CRT installer, which should stop this from ever occurring.

**Comment by FaLLeNaNg3L82** [comment]
> **The Error was fixed when I copied the dll into the Program Directory (C:\Program Files (x86)\Path of Building)**

doint this caused a 0xc000007b ERROR for me
