### ISSUE TITLE
Are you Ignited + Eye of Inocence

### ISSUE THREAD

**Issue by Ruddplays** [Openarl/PathOfBuilding#893]
Hello, I was making a build with Eye of Inocence, Mokou Embrace and Dreadsurge, but when I tick the box "are you ignited" in configurations, my damage drops instead of increasing. Am I missing something or is this a bug? Thanks for any help!

**Comment by Openarl** [comment]
Dreadsurge's "Hits ignore Enemy Monster Fire Resistance" modifier works exactly the same way as Inquisitor's Inevitable Judgement, in that it causes the relevant damage type(s) to be dealt as if the enemy had 0 resistance. This means that ALL modifiers to resistance are ignored, whether they are inherit resistances, or penalties from curses, or penetration. So if you were reducing the enemy's effective Fire Resistance to below 0, then enabling that modifier will reduce your damage.

**Comment by Ruddplays** [comment]
AH, Thank you so much. I just tested by changing to is the enemy a boss and now the damage output goes up. Thank you for the help!
