### ISSUE TITLE
Oni-Goroshi degen + Barbarism

### ISSUE THREAD

**Issue by olabrosse** [Openarl/PathOfBuilding#899]
Without Barbarism and at capped 75% fire res, I see proper calculation of Total Degen with a 0.25 multiplier and correct total.

With Barbarism and still capped 76% fire res, the multiplier goes up to 0.26 instead of going down to 0.24, and the total is as if the multiplier was actually 0.264.

Build used: https://pastebin.com/zNxcsHii

**Comment by Openarl** [comment]
Without Barbarism, your resistances are all equal (108%) total, and so The Wise Oak reduces your Fire Damage taken by 10%, cancelling out the penalty from Aspect of Carnage. This leaves only your Fire Resistance in play, giving you a 0.25 multiplier.

With Barbarism, which grants +8% to Fire Resistance, you lose the reduced Fire Damage taken from The Wise Oak; so the multiplier now becomes 0.24 (resistance) x 1.1 (Aspect of Carnage) = 0.264.

**Comment by olabrosse** [comment]
Good catch, I'm sorry I missed it and wasted your time.

Would be useful to list multiplier mods in the Total Degen tooltip, though.

**Comment by Openarl** [comment]
That would be redundant, as they are already listed in the breakdowns for the Hit/DoT multipliers themselves.
