### ISSUE TITLE
Jewel "Lioneye's Fall" does not correctly convert passives on the tree.

### ISSUE THREAD

**Issue by shoolayce** [Openarl/PathOfBuilding#9]
Although the item's mod text is highlighted as blue, (which I believe is supposed to indicate that the planner knows how to use the mod?) Lioneye's Fall's "Melee and Melee weapon Type Modifiers are Transformed to Bow Modifiers" does nothing.

Here is an example of a build that showcases this effect: https://gist.github.com/78ac225562d0b0bb564c00371d7fc48d
Removing/replacing the Lioneye's Jewel in Socket #1 does nothing.

**Comment by Openarl** [comment]
The jewel is supported (and yes, that's what the blue text means) but it seems I neglected to add One Handed Melee Weapon and Two Handed Melee Weapon to list of converted modifiers. I've fixed that now; the update containing the fix will be out shortly. Sorry about that one, and thanks for the report!
