### ISSUE TITLE
[Feature Request] Diamond Flask 

### ISSUE THREAD

**Issue by bdg0** [Openarl/PathOfBuilding#90]
I know flask slots are an upcoming feature, but I feel like a boolean "is Diamond Flask active" would be useful in the meantime, and a lot faster to implement.

**Comment by Openarl** [comment]
Hmm. I'll consider it.

**Comment by Openarl** [comment]
The next update will add a "Is your Crit Chance Lucky?" option to the Configuration tab, in the Effective DPS section.
