### ISSUE TITLE
Juggernaut "Unyielding" not calculating?

### ISSUE THREAD

**Issue by Kobelayton** [Openarl/PathOfBuilding#906]
Tried it with multiple skills and no change

**Comment by Openarl** [comment]
Obvious question, do you have Endurance Charges enabled in the Configuration tab?

**Comment by Kobelayton** [comment]
Yes sir.

**Comment by Kobelayton** [comment]
Disregard... it's working for me now.  I'm 100% certain I had End Charges enabled and it wasn't showing for any skills, neither with "show node power" color or any change in numbers when allocated.

Sorry.
