### ISSUE TITLE
flameblast totem cast speed

### ISSUE THREAD

**Issue by mikebtw** [Openarl/PathOfBuilding#909]
when loading my character into PoB, and also when using a pastebin from the forum, the cast speed is listed incorrectly in PoB.

Account name     RatchetmyPlank
character             BigFireBang

in game, sitting in my hideout with no buffs, my cast speed is listed as 9.90, but in PoB it's listed as 7.95.

This is a pastebin from the forum guide (not my character) which also shows lower cast speed in PoB than that player has in game.
pastebin from forum  :  https://pastebin.com/jm9NBFJ4

**Comment by Openarl** [comment]
The cast speed calculation shown in-game does not factor in the cast speed penalty from Spell Totem Support; this is a known issue, and it has been around for as long as the penalty itself has existed.

PoB does not have the same issue, and so the cast speed that it calculates will be more accurate, and higher.

**Comment by mikebtw** [comment]
Thanks for clearing that up :)  We all appreciate the work your team does !
