### ISSUE TITLE
[Bug] Blade Flurry offhand Dmg Calculation wrong

### ISSUE THREAD

**Issue by zocke1r** [Openarl/PathOfBuilding#91]
for whatever reason a 56dps dagger is supposed to give me higher avg dmg per hit compared to a 150dps dagger according to PoB, according to the game it is the other way around

**Comment by Openarl** [comment]
Path of Building doesn't currently have proper support for dual wielding; only the main hand is used in calculations. It's something I'd like to fix one day, but it's a bit of a pain to do.

**Comment by zocke1r** [comment]
oh, okay that should most likely be on a known issue list, considering that people use this to also calculate their dps and that issue makes that pretty much unreliable and as such almost useless for dual wield builds,

And concerning things people should know, it would really help people looking at this repo if you would label the issues so they can easily be filtered for e.g. known bugs

**Comment by Openarl** [comment]
The next update (1.2.39) will add full support for dual wielding.
