### ISSUE TITLE
Self-Flagellation jewel with any number of curses on you does not increase DPS

### ISSUE THREAD

**Issue by systemdown** [Openarl/PathOfBuilding#916]
The Total DPS calculation does not change when setting any number of curses ("Player is cursed by") in Configuration, for example setting any number of curses to level 20 does not change the DPS value.

The Calcs section shows no mention of damage increase due to Self-Flagellation and/or curses on you.

Did I miss a simple option elsewhere to set number of curses on you? I assumed that setting the level of curses that are on you would enable them for calculation purposes as I could not find any similar options.

Things I checked:
- Self-Flagellation is definitely equipped in a jewel slot
- The main skill group (glacial cascade, spell totem) is active and socketed in equipped gear

**Comment by Openarl** [comment]
Could you give me your build? I am unable to reproduce this.

**Comment by systemdown** [comment]
Yes sorry I should have provided that originally, thanks for having a look!
https://pastebin.com/gqSjwUkH

**Comment by Openarl** [comment]
You have a Warding flask active, which is making you Immune to Curses.

**Comment by systemdown** [comment]
*facepalm* really sorry to waste your time like that, I thought I looked over everything so carefully. Thanks for an amazing PoE tool.
