### ISSUE TITLE
[Bug] Attribute conversion jewels stack

### ISSUE THREAD

**Issue by Cholerix** [Openarl/PathOfBuilding#918]
Jewels like Fertile Mind, Inertia or Brute Force Solution will apply twice if their radius overlap. They will convert attribute points to another even if it is already covered by another jewel.

Version is 1.4.83

<details>
  <summary>Example Build</summary>
  eNrdWVt32jgQfk5-hQ9Pu2dPAF8wkAPdA-RSupBSIO32KUeYAbSRJWrJEPbX78g2wWkCiOw-bR-oLb75NDfNjEjj96eQWSuIJBW8WbCL5YIFPBBTyufNwv345qJW-P3DeWNA1OLzrB1Tpr_5cH7WSJ4tBitgKFewFInmoL5umdwHZJoQPqXqTkQhQdCd4LBde_nWhyigDKTcLgeMSHlHQmgWvlEVLAoWkQHwaWe3ngJDQvlIBI-gbiMRLxNNVhTWfTFFTLc_-Dwcb3fpRDFs1UALzhoDRjYQjRRRlsSPZqGFjiBzuCIhfiIRYTGyOMWyWyi9LTFaAkyfkXbR-dfAQQTXsxkEiq6gE6HWC8KDnTLlfXKnYvsxU3TJKEQ5rSr7JD6-Iq_U9mHHQhF2NRjlHOi5_mG0UMe1xkxYDASVghuT9wknHSENyEcq5wdvH2oIP_LAvWxX8PQMOkSWx-0l6_Kd_o7nHKDLI_fS9egsF8XqgYQNLjW2ywMz0nsegYRolcvz_fQvBQZYACCnvF0-uNMQ5sDNlOoBBItbrBJDogxOhk6YnRa-fdA7GmzkHQ18wzsH-F9KnOAeLfjSPe7-U63BJzromkM034wWFNjOEOewn_IyRv7KCxjGOi9yqkkronuW6ZnI4GaBBwaAAlP4qXq6zn8oMojEX7phsBPlWlEoYoNqlpidgo2sHiw2kgZY1ZM-OoRpjMoJkyBuG19frCDEjE-6JvbyXebvE20znAJM-x_SMnaSREspEjxeiekcTtrkJIkbGqG3JM31qwt_fxMX-nCYont0vlAcZ7cTNlgQIc3hO-0_4xjVIUuDOeTZBGORn-ww32pnzNsyjVIy0eqnDmGBTGi6fBkriycDp3ykjD3wOJzokSn9f5eQeWRIZfAwiWczPYUWUIEomaavb26uO-Pu1-tMZATJsbACwRhZSpg2C5yygkXxYaQ3G2EpCJQBGqezbGY9jtWjlsH-ybh6HKcnSTMFs0NgaPp4swQdPWkg0GZmuqazowGwO-dUGfkSArIxwD03JANsH5MnrYMmtmNdiugkVmACTiY_Aw30DHQc9mISMNA0bTYGvFk7Po7MapNBnJLDMSaPYBqBK5jhNTjzaqO0rQiNJDmlNYUZwfvTLYRfYsKo2mTiu_VeejFOVqWI9JJsb_Di0iwovIemvOMIwCJJx9M9VleTVDt80Q9njfthL3k4Wyi1lJel0nq9Li7xMi5m8IQNvxiIsLTESzFSXCQV6kIhaamF_9qtfqvV78na90jeXge3t8IZf_Ie_NmDkp27iz9mtcmX8t2Ktydf76NofNNdDevlcN37tpm0n740m4kCpa0GjfSaLVN1sjeLY4Xros-qdWwMFp6aUL9lVfg1zHWqvrvD2ftwTs2rVgz4HN-u-yb7-r7rmeA8r-aa7GvXayZ8nl-rOQY43_bsugGu4tlO1YSvXHVN_Fep2HWTuHm1ql8z8YtXt03Uc9yykVdq-ag5e7WzHd8kaq7ru7YRrl6rG2Vf1THxsmv7b2VVo5Q7UviSHvpGSVcF_XAnsKzr7_Ti9iWpGV8prC0JJAoWI4VDSMH6W4jwO2pUcYpureyWvZrjlFE3uRDrj0BUnyyzYqSRWXHy0u91n72i2HKipORlBSoB_okTX6VsF6t2rexXq65XSX8Ja3TRFpmVLv08ApX89hZLwNIq-PQbkKXgybLeNp2REJhU2LTMnQ0JTg-bS-ue0x8xnN9ApO8wVp_y6XlHTAhT1idYAzsfkimN5aXV078xnv_2i-1fON6vlhJWlyucsulca35-BU8KNKU1i0RoDdKyKC3KrZTBotIaR4TLmYhCmL4i0EHBmW1I-BysSH9itIqVQqZ02jpK2oyX9jj_H3swYnuDmI9dY8TEdt69ZXhdk28keA6TUln2YdQNI_LxGKgN6MjWZCMlYVZ21BwTXvcIr5hurHRMOZG-FcYM1OlaG3njyN4fgYVwqj-yaDjGDjlum4kplcOgIV6TjusklDzR2jQ_35Uy3nuY7fdEzH53ctpmJ88arfWl96hzDWJktqNjsGPqi3eE_LUKaSHDYpU00aRBJZd5wWd0johG6ec_Yv0DGWhHoA==
</details>

**Comment by Openarl** [comment]
This is working as intended; if you try it in-game you will find that conversion jewels do actually work this way.
