### ISSUE TITLE
[Bug] Added Damage to Spells should not be added to Herald of Thunder/Ice

### ISSUE THREAD

**Issue by StephenHopkins** [Openarl/PathOfBuilding#920]
Added Damage to Spells should not be added to Herald of Thunder/Ice. Only global flat damage can be added to heralds, e.g. Impresence amulet, 'Adds X to X cold damage'. Flat added damage to spells does not work with herald secondary damage from Herald of Thunder or Herald of Ice.

![image](https://user-images.githubusercontent.com/902108/37574433-19afffc6-2ade-11e8-9aed-bbf7f5d660b1.png)

**Comment by StephenHopkins** [comment]
Looks like the added damage from the skill it self, is also being applied to the secondary damage hit.

**Comment by Openarl** [comment]
Fixed in the next update; the change in 3.2 that removed the concept of "cast" skills is responsible.
