### ISSUE TITLE
Bear Trap not counted as spell

### ISSUE THREAD

**Issue by melching** [Openarl/PathOfBuilding#922]
Hello,

it seems that the skill Bear Trap is currently not counted as a spell (version 1.4.83), in contrary to the [wiki](https://pathofexile.gamepedia.com/Bear_Trap).

An example is given here: https://imgur.com/a/ENJOP

**Comment by Openarl** [comment]
Bear Trap is considered to be a Spell (it used to be a Cast before that concept was removed in 3.2); however it deals (and has always dealt) Secondary Damage (not Spell Damage), and does not benefit from any modifiers to Spells or Spell Damage. 

I did verify this in-game with the specific node you highlighted, and Doom Cast does indeed have no effect on Bear Trap.
