### ISSUE TITLE
Crash whilte trying to make a jewel

### ISSUE THREAD

**Issue by Crazy-KSK** [Openarl/PathOfBuilding#923]
https://i.imgur.com/AmDjsO9.png

**Comment by Openarl** [comment]
How exactly did you trigger that? I can't figure out how to reproduce it, nor how the error could occur.

**Comment by Crazy-KSK** [comment]
I believe it happened when I clicked 'create' on a custom jewel creation, but I think it might just have coincided or triggered the crash I keep having that I've put off to be nvidia driver crashing, could it be that PoB is crashing the nvidia driver? maybe because I'm running windowed gsync on a 240hz screen?
Maybe I should just update the driver, even though I head that it doesn't perform well with POE.

**Comment by Openarl** [comment]
This was fixed by the latest update.
