### ISSUE TITLE
Power charge count doesn't consider snapshotted charges

### ISSUE THREAD

**Issue by geneccx** [Openarl/PathOfBuilding#924]
Currently using Brinerot Flag + Storm Prison in the offhand. 

Since Storm Prison adds +1 to max power charges, if you warcry twice and swap back to main, it's possible to have 4 power charges without picking up any power charge nodes. Unfortunately, the calcs tab doesn't allow you to change the power charge count in the combat buffs, so it's a bit difficult to get accurate DPS numbers.

Right now, the only way I can find to work around this is to pick up a nearby additional power charge node, but this isn't always possible.

**Comment by Openarl** [comment]
Luckily for you, in the process of adding support for Crab Barriers I've needed to add number inputs for each type of charge (Crab Barriers are handled like charges, and having a non-maximum number of those is quite likely). These inputs are not restricted to the maximum, so it will cover your use case as well.

The update with these new inputs should be out in the next 24 hours, if all goes well.
