### ISSUE TITLE
Wither only displaying/calculating max stacks of 1

### ISSUE THREAD

**Issue by Wriann** [Openarl/PathOfBuilding#932]
It's only showing Wither (1 stack) in the curses and debuffs section. When I select the active skill section for wither it shows 15 stacks, but when I select my main skill, Blade Flurry, It only shows 1 stack. Here's a screenshot of it two days ago. 
![image](https://user-images.githubusercontent.com/37647937/37751604-582b4460-2d61-11e8-95c5-04e1edc040c6.png)

Here's a screenshot of it today. 
![image](https://user-images.githubusercontent.com/37647937/37751598-4dab4f26-2d61-11e8-98d9-a6f40143071e.png)

I was confused because I got an additional jewel socket, upgraded my weapon, and my dps went down 150k.

**Comment by Openarl** [comment]
What is Wither's stack count set to in the sidebar? The Calcs tab uses that setting if you don't have Wither selected there.
