### ISSUE TITLE
need help for mobile app version 

### ISSUE THREAD

**Issue by woqufelix** [Openarl/PathOfBuilding#933]
Hi Openarl, 
I'm a big fan of POE and I planned to build mobile app version of your project. The biggest problem are the formulas of calculations like total damage, resistances etc. Are there any guides or handbooks u can offer me or I have to find these formulas from you code out by myself ?

**Comment by Openarl** [comment]
Honestly, if you're wanting to produce a mobile version, and you think the biggest problem is finding the formulas (which are on the wiki, by the way), then you'll be in for a big shock. The program's offence/defence calculation code is dwarfed by the setup and infrastructure code required, and *that* code involves dealing with a ton of obscure mechanics that are even harder to learn about (if they're even publicised anywhere, which many aren't).

If you're determined to do this, then I wish you good luck, but I can't afford to help you to any real degree.
