### ISSUE TITLE
Sceptres (Doryani's Catalyst) listed as one-hand mace

### ISSUE THREAD

**Issue by zechs1460** [Openarl/PathOfBuilding#936]
Not a big deal, just thought i'd let you know if you didn't already. Ty for the awesome program!
![image](https://user-images.githubusercontent.com/15159661/37857194-987c2af6-2ecf-11e8-8554-c5e307d41730.png)

**Comment by Openarl** [comment]
You could've at least checked this in game...
![sceptre](https://user-images.githubusercontent.com/19189971/37859888-e669ab7a-2f66-11e8-83a0-f649b48334b3.png)

**Comment by zechs1460** [comment]
I'm sorry :(
