### ISSUE TITLE
Calcs Tab does not take account of the 100% more burning damage by Dyadus

### ISSUE THREAD

**Issue by LordRegulus** [Openarl/PathOfBuilding#937]
Title. I have dyadus in the offhand, i checked the enemy being ignite, burning and chilled.

However there is no 100% more added to my ignite damage.

**Comment by Wires77** [comment]
I made a new character with flameblast and Dyadus, and the ignite damage exactly doubles when checking if they're chilled.  Can you provide a pastebin link?

**Comment by LordRegulus** [comment]
Oh it does increase the damage, it just does not indicate it under the ignite table on the calcs tab. Mb

**Comment by Openarl** [comment]
It does actually indicate it there, but you're looking in the wrong place. Dyadus applies a "Damage taken" modifier, not "more Damage", and so it appears in the breakdown for the Effective DPS Modifier.
