### ISSUE TITLE
Scourge + Ghastly Jewels

### ISSUE THREAD

**Issue by B14d3r11** [Openarl/PathOfBuilding#939]
Ghastly jewels can roll the property
"15-20% increased minion damage if you've used a Minion skill recently"

There needs to be a tick or some check to "Have used a minion skill recently" so that the 20% per jewel is applied through the Scourge's "Increases and Reductions to Minion Damage also affect you"

Also idk if the ability is working or not in PoB cause it doesn't seem that damage goes up that much, the minion damage % is treated as a global damage increase right?

**Comment by Thirsk** [comment]
But there is already a "Have you used a Minion Skill Recently?" tick. 
![capture](https://user-images.githubusercontent.com/16472201/37982228-e4812294-31a4-11e8-9f96-65eb48126f3c.PNG)

And you might just already have a ton of increased damage on your tree/gear, so an additional 20% isn't _that_ significant of an increase.

**Comment by B14d3r11** [comment]
I have around 335% increased minion damage with the build in PoB, with another 10 Abyss jewels setup with 20% minion damage.

Also with a "extra damage as ___" stat stick just for the highest possible damage this could pull off. And full build its saying like 100k dps

**Comment by Exportforce** [comment]
You do realize that extra damage as ELEMENT does NOT count for your minions and only counts from phys damage you (or your totems) inflict?

**Comment by B14d3r11** [comment]
I am not using minions really at all, I am using the Scourge claw which changes Minion Damage increases and reductions into a Global Damage modifier for the player.

**Comment by Exportforce** [comment]
Then with what minion skill to you trigger the "blah blah minion skill recently"?

**Comment by B14d3r11** [comment]
Summon Ice Golem

**Comment by Exportforce** [comment]
You might wanna choose something else. As "recently" refers to the last 4 seconds. So you can't keep that buff up. But for your problem. Can you please post a pastebin with your build where this won't work?

**Comment by B14d3r11** [comment]
https://pastebin.com/4DmEyKtb

**Comment by Exportforce** [comment]
http://prntscr.com/ix8o4q

As you can see the function for the "minion skill recently" is in the config tab and activated.
If you really don't see it your PoB has to be outdated.

btw. ticking that off will cost you 9k dps... so you can ignore that completely

**Comment by Openarl** [comment]
Everything seems to be working correctly here; the Minion Skill used Recently option is present and functioning, and all the calculations appear to be correct.
