### ISSUE TITLE
Anyone can help me make a build to support MAC OS

### ISSUE THREAD

**Issue by tamdao** [Openarl/PathOfBuilding#94]
Hi there,

I have two machine:

1. Run Window OS
2. Run MAC OS

I think we can make a version to support MAC OS. Anyone can help me do that or suggest a artical to do that. I can try because I'm a developer

Thanks

**Comment by dein0s** [comment]
Duplicates https://github.com/Openarl/PathOfBuilding/issues/28
Check it out.
