### ISSUE TITLE
First Snow Cobalt Jewel and Frozen Trail Cobalt Jewel issues.

### ISSUE THREAD

**Issue by Junkernaut** [Openarl/PathOfBuilding#943]
First Snow Jewel not give 25% inc. FP dmg because Configuration not have check-box: "Shattered an Enemy Recently".
Can you add new check-box? Thank you.

**Comment by Junkernaut** [comment]
I tested Frozen Trail Cobalt Jewel with Frostbolt. Second mod (With at least 40 Intelligence in Radius, Frostbolt Projectiles gain 40% increased Projectile Speed per second) in this jewel not working too. Projectile speed not changed, but count of projectile is correct. I think issue is not with check-box.

**Comment by Wires77** [comment]
The first issue with "First Snow" is a feature request, as any mods colored red in PoB are currently unsupported.  The second issue is not working for a similar reason, and probably won't be added because then you'd also have to have a configuration option for projectile lifetime.
