### ISSUE TITLE
Notable "Gemini" does not grant accuracy when using two Piscator's Vigil Wands

### ISSUE THREAD

**Issue by N1gh7h4wk** [Openarl/PathOfBuilding#948]
When using a different Wand + Piscator's Vigil it works, dualwielding two makes the node not work.

**Comment by Openarl** [comment]
Could you give me your build? I can't manage to reproduce this; the node is correctly granting the bonus accuracy with two Piscator's equipped, and couldn't possibly fail to do so simply because of the specific wand you're using.

**Comment by N1gh7h4wk** [comment]
Since i changed the build in the meantime, i tried to reproduce the issue but i did not succeed in doing so.

**Comment by Openarl** [comment]
In that case I'll close this, as I cannot see how the described behaviour is possible.
