### ISSUE TITLE
Scaling Summon Phantasm on Kill

### ISSUE THREAD

**Issue by andya34** [Openarl/PathOfBuilding#949]
POB scaling phantasm minion wrong. It count phantasm as melee physical attacker. And according to wiki phantasm use ranged physical projectile spell. Im trying a build and noticed this now. When I use spell echo with phantasm it attacks second time meanwhile multistrike has no effect on phantasm. but according to pob multistrike increases attack rate of phantasms...

**Comment by Openarl** [comment]
Duplicates #908.
