### ISSUE TITLE
Wrong Resistancecalculation

### ISSUE THREAD

**Issue by Exportforce** [Openarl/PathOfBuilding#953]
Pastebin: https://pastebin.com/4eK1aBuW
Screen from my defense tab: http://prntscr.com/izu7o1

The Pastebin is without endurance charges, as I am sitting in my hideout. I have no res auras etc. Yet I am ingame with 87% cold res but on PoB it's only 72%.

**Comment by chollinger** [comment]
Did you take Alira for the bandit? If so, your pastebin doesn't reflect that.

**Comment by Exportforce** [comment]
Oh crap. I totally forgot about her. Thanks! I wondered for at least 8 hours today.
