### ISSUE TITLE
Attack Speed by Multistrike

### ISSUE THREAD

**Issue by Lhansk** [Openarl/PathOfBuilding#958]
Hey, 

Multistrike doesn't modify attack speed, so dps with Multistrike never show true numbers.

**Comment by Openarl** [comment]
Did you look at #241? It applies to Lightning Strike, and all other Melee skills that have Projectile skill parts. The gist of it is that the Attack Speed for those Projectile parts isn't accurate due to technical limitations; one of the effects is that Multistrike won't apply.
