### ISSUE TITLE
Unique item to be added

### ISSUE THREAD

**Issue by Dargather4** [Openarl/PathOfBuilding#972]
I was unable to find Eyes of the Greatwolf 
https://pathofexile.gamepedia.com/Eyes_of_the_Greatwolf
and the following Greatwolf talisman do not have the proper Talisman Implicits.

**Comment by Openarl** [comment]
Eyes of the Greatwolf hadn't been added previous as I didn't have support for selecting the two implicits. However, I had to add the necessary tech for Watcher's Eye, so it's pretty simple to do EotG too. It'll be in the next update.

Crafting Greatwolf Talismans still won't work though, as the aforementioned tech won't work in that case; I don't think I have any real hope of handling that without an excessive amount of work.
