### ISSUE TITLE
Voll's Vision bonus not applied

### ISSUE THREAD

**Issue by tstivers1990** [Openarl/PathOfBuilding#976]
It seems Voll's Vision's life and regen bonus aren't being applied when no corrupted items are equipped. I've checked, double checked, and triple checked to make sure no items in PoB are accidentally corrupted, etc. I've looked for a checkbox for this as well, and can't seem to find one.

I'm not sure how difficult this would be to implement the ideal way, in that PoB would automatically detect whether or not an equipped item is corrupted. But if it's not feasible in the normal way, a checkbox to manually select whether or not an equipped item is corrupted would suffice in my opinion.

**Comment by Openarl** [comment]
They should already be working, but it seems a recent wording change to the relevant modifiers was preventing the program from recognising them on imported items. That's fixed in the next update.
