### ISSUE TITLE
Issue with multiple monitors

### ISSUE THREAD

**Issue by kiukkukisu** [Openarl/PathOfBuilding#977]
Sorry I should have checked first, this problem is already open on #336 

If I close PoB on my secondary monitor it will never start again: just black screen and endless loading. 
I have to force shutdown from Task Manager. 
When I disable my second monitor PoB starts normally and is usable again. 

Win 8.1 Pro 64-bit

**Comment by Jascheminant** [comment]
This shit is still happening? Why is this still happening 2 years later?
