### ISSUE TITLE
Lua Error's ( 355,330,199,191)

### ISSUE THREAD

**Issue by CascadingMotion** [Openarl/PathOfBuilding#985]
Problem: Getting error when using the "Import: Passive Tree and Jewels"
Frequency: Permanent
Priority: Critical

Extra's: Tried the usual basic troubleshooting - restarting pc, updating pob, running as admin, etc etc.
Also I am able to import items, just not import passive tree and jewels. Screen shot of what it looks like provided.

![screenshot 36](https://user-images.githubusercontent.com/39077389/39739007-99ea4f0c-525c-11e8-9bca-9a050519c363.png)

**Comment by Openarl** [comment]
Hrmph. It seems GGG decided to make a change to the data format returned by the get-passive-skills API, which broke the program's import code. I'll be releasing an update soon to fix it.
