### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by terbenstaar** [Openarl/PathOfBuilding#986]
Getting this error when trying to import character tree and jewels. Have the latest build 1.4.85.

![](https://i.imgur.com/yrFjsrZ.png)

Edit: Also, it worked fine 3hours ago.

**Comment by jwile14** [comment]
Can confirm issue, happens when importing Passive Tree + Jewels, 100% reproduction.

![image](https://user-images.githubusercontent.com/9904655/39740600-65996e6a-5264-11e8-9d45-ac081ed6dd76.png)

**Comment by Openarl** [comment]
Duplicates #985; a fix is set to be released soon.
