### ISSUE TITLE
Raging spirit not affected by added damage to spells

### ISSUE THREAD

**Issue by Kagerfef** [Openarl/PathOfBuilding#989]
I am not certain which is incorrect, but Path of Building does not account for added spell damage from
Hrimsorrow, Herald's or Dusktoe boots (active potion), even though in game tooltip shows DPS increase for all 3.

Anger aura still shows dps increase in both, most likely because of allies tag.

**Comment by Openarl** [comment]
The in-game tooltip DPS for minion skills has no relation whatsoever to the minion's actual DPS, and should be always be ignored. What it shows is the damage that the minion summoning spell would hypothetically deal, but of course it cannot actually deal damage, so the number shown is meaningless.

That aside, any modifiers on your passive tree or equipment that aren't minion-specific have absolutely no effect on your minions, with few exceptions (e.g increased effect of your Auras). So your minions cannot benefit in any way from added damage to spells (or attacks) on items like Hrimsorrow.

Finally, Raging Spirits use a Melee Attack, and will not benefit from added damage to spells, even if such modifiers are applied to the minion.
