### ISSUE TITLE
Window too big

### ISSUE THREAD

**Issue by TianRB** [Openarl/PathOfBuilding#997]
Can't find anything in the Issues section, I hope this is not a duplicate. The window is way to big on my computer, I'm not able to see about 3-4 inches of the right side. Changing OS resolution had no effect on it.
This is especially notisable on the calcs tab, where I'm unable to see any of the rightmost calculations.

<img width="840" alt="capture" src="https://user-images.githubusercontent.com/5522022/40139700-61095abe-5916-11e8-83bc-425caeab5e78.PNG">

**Comment by FranciumGoesBoom** [comment]
Similar issue.  There is an offset between the window and content displayed.  The second image shows the Bandit drop down highlighted but the mouse is below the field. 
![image](https://user-images.githubusercontent.com/39768171/40721993-b90731a8-63e0-11e8-8fdd-af3d7b957a9c.png)
![image](https://user-images.githubusercontent.com/39768171/40722041-dab785be-63e0-11e8-8ab0-ccc35fc630e5.png)

**Comment by TianRB** [comment]
In case anyone encounters this problem, my solution was to change Windows font scaling to 100%, I had them al 150% which caused the size issues.
