### ISSUE TITLE
AoE nodes don't increase Minion Instability damage

### ISSUE THREAD

**Issue by Larius** [Openarl/PathOfBuilding#998]
As in title, AoE nodes (like Amplify or Blast Radius) seem to have no impact on Minion Instability damage while support gems, like Concentrated Effect, do.

**Comment by Exportforce** [comment]
Nodes on the tree are for you, not for your minions or allies except they explicitly say so.

Support gems are for the gems they support.

**Comment by Larius** [comment]
You are probably right, my bad, closing.
